### ISSUE TITLE
Simulate OS hang

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#100]
https://github.com/openbmc/openbmc/issues/278

Probe checkstop sensor which is implemented using the above story. And if it is found hang, Using BMC resets the system/CEC.

**Comment by sivassrr** [comment]
This is from Barreleye
root@barreleye:~# ps | grep host
  991 root     24240 S    /usr/sbin/control_host.exe
  993 root     24236 S    /usr/sbin/host_checkstop.exe   <======= This should be running and will take care when OS hangs. 
 1015 root     24228 S    /usr/sbin/host_watchdog.exe
 1078 root      2976 S    grep host

**Comment by sivassrr** [comment]
So our automation code simulate OS hang and BMC with the help of host_checkstop.exe will reset the system.

**Comment by sivassrr** [comment]
@SrideviRamesh could you please update your progress on how you are making it. 
Last time, when I checked with her, She mentioned she could able to do OS hang but has to do manually restart.  But expect host_checkstop.exe to do the host reset the partition.

**Comment by SrideviRamesh** [comment]
@sivassrr We are able to observe OS hang after the checkstop through OS.. OS is rebooting after checkstop if auto_reboot s enabled else we have to manually power off and on BMC to boot OS.
I would request you to close the issue and we can open a new issue for enabling RAS testcase in automation

**Comment by sivassrr** [comment]
Now we will track it in #413
