### ISSUE TITLE
Factory Reset: Create user defined files in read-write file system and check that those files get erased after factory reset

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1006]
Create files in pnor and bmc read-write volumes and check those get deleted after host and BMC factory reset.

**Comment by ssombar** [comment]
Can we also check if the Energy Scale settings reset back to defaults after factory reset?
Resource          ../lib/energy_scale_utils.robot
  # enable energy scale settings
  Activate DCMI Power And Verify
  Set DCMI Power Limit And Verify  500
  # do factory reset
 Do Factory Reset
  # Energy scale should go back to defaults:  deactivated and power limit = 0
   Fail If DCMI Power Is Not Deactivated
   ${power}=  Get DCMI Power Limit
   Should Be True  ${power} == ${0}

**Comment by gkeishin** [comment]
That's a fair point @ssombar

**Comment by gkeishin** [comment]
@prkatti1 any update ?
