### ISSUE TITLE
Code Update: Check for deformed software objects

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc-test-automation#1009]
Check that software objects have the following properties:

- [ ] The generated hash ID has 8 hex digits
- [ ] Have Activation, Path, Purpose, RequestedActivation, and Version properties
- [ ] Properties are set to legal values

**Comment by gkeishin** [comment]
One use case reported in lab for BMC
```
/xyz/openbmc_project/software/3ab50d91
{
    "Path": "/tmp/images/3ab50d91",
    "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC",
    "Version": "ibm-v1.99.10-0-r7-0-gcce0f1b"
}

```

**Comment by charleshofer** [comment]
https://gerrit.openbmc-project.xyz/#/c/7119
