### ISSUE TITLE
Code update : Reboot BMC during PNOR activation in progress

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1010]
- [x] Upload PNOR
- [x] Start activation and reset BMC
- [x] Verify the PNOR failed

**Comment by charleshofer** [comment]
How is this story any different than https://github.com/openbmc/openbmc-test-automation/issues/993? Activation is the code update for PNOR.

**Comment by gkeishin** [comment]
oops my bad.. I was breaking down the task
