### ISSUE TITLE
Energy Scale (power):  upload of occtoolp9 tool

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#1014]
We currently run the wget command on the SUT to get the occtoolp9 energy reporting tool from github.com.   However if the SUT has no network connectivity to github, the energy scale test may fail.

It perhaps would be more robust to upload the occtoolp9 directly to the system running robot framework, then upload it to the SUT from there.

**Comment by ssombar** [comment]
Perhaps the best solution is to use a git submodule to pull  openbmc-test-automation  in to openbmc-test-automation

**Comment by gkeishin** [comment]
Task completed
