### ISSUE TITLE
RAS test cases are failing as error is not getting created.

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1018]
Below RAS test cases are failing as expected error is not getting created during the test case.

Verify Recoverable Callout Handling For MCA With Threshold 32
Verify Recoverable Callout Handling For NXDMAENG With Threshold 32
Verify Recoverable Callout Handling For CXA With Threshold 5
Verify Recoverable Callout Handling For CXA With Threshold 32
Verify Recoverable Callout Handling For NPU0 With Threshold 32

```
URI:https://wsbmc014:443/xyz/openbmc_project/logging/entry//list, method:Get, args:{}
Response code:404, Content:{
  "data": {
    "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /xyz/openbmc_project/logging/entry"
  }, 
  "message": "404 Not Found", 
  "status": "error"

```

**Comment by gkeishin** [comment]
@SrideviRamesh  Please use this to push the changes.. Thanks
