### ISSUE TITLE
[Automation] Update all existing data model from skeleton

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#102]
There are pretty new delta changes which came up https://github.com/openbmc/skeleton/tree/master/configs
Barreleye.py
Firestone.py
Garrison.py
Palmetto.py
Witherspoon.py

However, so just to avoid breaking all together if there is a mismatch.. will start with Barreleye/Palmetto and witherspoon..   Firestone and Garrison post these

Will validate through running the test.. and then update it..

**Comment by gkeishin** [comment]
Validating the models vs the what setup we have in automation... Initial run doesn't seems to cause problem on barreleye..  However need to check the FRU lookup ID's so that the inventories are intact

**Comment by gkeishin** [comment]
Right now the drivers are still not very to good to validate the model.. so will keep watch when things are stable and validate..

**Comment by sivassrr** [comment]
Shall we try to minimize referring to skeleton and try to use enumerate and other commands of bmc

**Comment by gkeishin** [comment]
Lets close this.. since we are most probably doing away using the MRW and other enumeration mechanism.. If needed we will re-open this and work on it but for now we seems to have all set so far.
