### ISSUE TITLE
BMC and PNOR power off before update

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1026]
- [x] Poweroff system before update BMC / PNOR
- [x] Ignore if failed to power off since we wanted the system to update if the system was not in good state.

**Comment by charleshofer** [comment]
We already power off the host before a PNOR code update [here](https://github.com/openbmc/openbmc-test-automation/blob/master/extended/code_update/host_code_update.robot#L181). I have a change out there to turn off the host with BMC code updates https://gerrit.openbmc-project.xyz/#/c/7017/.
