### ISSUE TITLE
Automation:IPMI: Verify enable / disable auto reboot

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1029]
New Requirement from Dean seems. 
- [ ] Enable / Disable Auto reboot via IPMI

Development story
https://github.com/openbmc/openbmc/issues/2398

**Comment by gkeishin** [comment]
CI test code does this https://github.com/openbmc/openbmc-test-automation/blob/master/tests/test_basic_poweron.robot#L123

**Comment by gkeishin** [comment]
Ooops my bad.. not done via IPMI

**Comment by sivassrr** [comment]
This is needed, So keeping it.

**Comment by gkeishin** [comment]
This feature should be there in latest
