### ISSUE TITLE
To verify GPUs in inventory list during BMC Standby / Runtime.

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1030]
- [ ] GPUs should be checked in inventory list via REST / OS 

Equivalent development stories:
https://github.com/openbmc/openbmc/issues/1725

**Comment by ssombar** [comment]
see related OpenBMC issue   openbmc/openbmc/issues/1725

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/8444

**Comment by ssombar** [comment]
for the BMC to see the GPUs. hostboot must run once.
