### ISSUE TITLE
FieldMode test cases

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc-test-automation#1032]
- [ ] Check that /usr/local is mounted and field mode is off
- [ ] Put the BMC in field mode
- [ ] Check that /usr/local is not mounted
- [ ] Check that usr-local.mount is masked
- [ ] Check that the user can't deactivate field mode through REST
- [ ] Disable field mode through the BMC command line
- [ ] Check that /usr/local is mounted

**Comment by charleshofer** [comment]
Relevant https://github.com/openbmc/openbmc/issues/2428

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/7192/
