### ISSUE TITLE
Check for Zombie process at Suite Start and teardown

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#104]
Need to check Zombie process at BMC ready and Host run time as given below. 
Basically we should not have zombie process
ps | grep -i 'z'
PID USER VSZ STAT COMMAND
1059 root 0 Z [flasher.exe]
1064 root 0 Z [flasher.exe]
1094 root 0 Z [python]
1101 root 0 Z [pcie_slot_prese]
1133 root 2972 S grep -i z

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc/issues/206  - Existing issues.

**Comment by gkeishin** [comment]
@SrideviRamesh  The above command is not the correct way to find zombie process.. The Zombie generally will have a status either as defunct or Z in the PS stat

PID USER       VSZ  STAT COMMAND

A simple grep is not going to reliably tell if a process is a Zombie or not... Take a look around how to accurately find out from the list.. a simple grep will result in wrong listing of non defunct process

**Comment by SrideviRamesh** [comment]
okay .. I will try it

**Comment by sivassrr** [comment]
Looks like base ps command output format had changed (I checked it in VERSION_ID="v1.99.0-131-ga81f31c-dirty"). And I am not seeing no zombie as of now. To check zombie, we need to use "ps -o stat" command to automate.

**Comment by sivassrr** [comment]
ps -o stat | grep -i Z , we can use it. Then if Z stat is available, then we can display corresponding process details using ps -o stat,user,comm,ppid etc..

**Comment by mdmillerii** [comment]
Why the  `-i` flag to `grep` ? you are looking for a `Z` only, not also a `z`.  Although `-w` (whole words) might sense.

**Comment by sivassrr** [comment]
@mdmillerii yup, -i not needed

**Comment by SrideviRamesh** [comment]
Infra support for check Zombie process is added using https://github.com/openbmc/openbmc-test-automation/issues/236

**Comment by gkeishin** [comment]
@SrideviRamesh  Whats remaining here.. the utility are in.. now do the remaining needed..

**Comment by gkeishin** [comment]
Closing .. Open new one if there is needed
