### ISSUE TITLE
Timestamps for OS console log

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc-test-automation#1049]
Put timestamps in the name of OS console logs.

**Comment by gkeishin** [comment]
@charleshofer any plan here of you can give input what is expected so that someone can take this one up..

**Comment by charleshofer** [comment]
When running a test, the OS console is written to a file called os_console.txt. Sometimes, a console from an old test run would make its way into a test that had just been run. The real fix was to clear out the old console, but it was suggested that we also put a timestamp in the name of the os_console.txt file, maybe like os_console_23-01-2018.txt, so that developers are absolutely sure that they have the correct console log.

**Comment by gkeishin** [comment]
good point there for now the current format is  `xx.xx.xx.xx_os_console.txt` but yeah having a date timestamp would make more sense.

**Comment by gkeishin** [comment]
I looked at the code and the code is designed in such a way that the os_console is looked upon stop and created on starting. So irrespective of which order it may be called it still finds the pattern to create or kill the pid for SOL.
If we add time stamp that order is no longer valid and seems to have and overhead of passing and setting the timestamp for the same suite or across. So `xxx.xx.xx.xx_os_console.txt` is generic enough per system in this case.. 

We will need to look another aspect where the timestamp is needed.

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/11124/
