### ISSUE TITLE
Fix signature description parameter in lib/ras/variables.py

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#1051]

**Comment by gkeishin** [comment]
Comments to address for https://gerrit.openbmc-project.xyz/#/c/7188/ chanes

**Comment by SrideviRamesh** [comment]
Will be using the same issue to verify scom operations on host os after error injection

**Comment by lkammath** [comment]
Also fix some of the comments made in https://gerrit.openbmc-project.xyz/#/c/6811/

1) Check for the stderr always 
2) Verify the scom output to make sure the scom failures are captured

**Comment by gkeishin** [comment]
@lkammath If there are logs for scoms on the OS to be collected, please advice so that @SrideviRamesh can add those in FFDC collection. Thanks
