### ISSUE TITLE
Deprecate / remove old code update test cases ONLY ( Not code update Portion )

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1054]
Placeholder to delete the old code update

Test cases to remove from files:
- [x] extended/code_update/code_update_utils.robot
- [x] extended/code_update/update_bmc.robot
- [x] extended/test_bios_update.robot

**Comment by gkeishin** [comment]
DON"T remove this for now. Keeping as a place holder. Since Non Witherspoon still uses this one.

**Comment by gkeishin** [comment]
To delete post Dev removal https://github.com/openbmc/openbmc/issues/2480

**Comment by mdmillerii** [comment]
That story says from witherspoon, other systems will still use it.

**Comment by gkeishin** [comment]
@mdmillerii  got it... I ll ask my folk to remove ONLY other extra test code from those suites but not the code update part..

**Comment by swe12345** [comment]
Code in Review
https://gerrit.openbmc-project.xyz/#/c/7467/
