### ISSUE TITLE
Change the core dump path checking in BMC dump

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1055]

**Comment by sivassrr** [comment]
@gkeishin There is already issue opened and  had assigned that to me. https://github.com/openbmc/openbmc-test-automation/issues/1052

This issue intention was to remove core dump "Post Dump Core Dump Check" because development code is getting enabled. Once it is done, as discussed, we will remove.

**Comment by gkeishin** [comment]
Now the application core dumps are collected as part of the BMC dump so we won't need this.
