### ISSUE TITLE
Code Update Tests: Automate tests for checkstop errors during code update

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc-test-automation#1059]
With PNOR we can do a code update when Host is Powered on and it can happen that a checkstop comes in when the PNOR update is in progress. Once that happens it would ReIPL the box while the PNOR update is going on.This could have two places where we could possibly be worry about..
 - [ ] When Activation is in progress and the checkstop happens
 - [ ] When the Activation is completed and Checkstops happens
The latter is a good kind of use case where it will try to come up with new loaded PNOR, but 1) is something which we possibly need to worry about.

**Comment by gkeishin** [comment]
Pre-req for this task https://github.com/openbmc/openbmc-test-automation/issues/1100

**Comment by gkeishin** [comment]
We have code which does the disruptive to achieve this.. So this is more of a error case which doesn't impact the update process.
