### ISSUE TITLE
Test OCC sensor old code cleanup / fix

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1071]
Please refer this code we have currently, identify, fix if needed else remove the use case from the code

https://github.com/openbmc/openbmc-test-automation/blob/master/tests/test_sensors.robot

@ssombar

**Comment by ssombar** [comment]
Discussed this with Marissa and we think nothing additional needs to be done here.  Agreed?

**Comment by gkeishin** [comment]
Lets use this defect to clean up the tests which are invalid @ssombar

**Comment by gkeishin** [comment]
In review https://gerrit.openbmc-project.xyz/#/c/7627/
