### ISSUE TITLE
Remove Journald test code 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1074]
This is no longer use cases. Remove them from the code as a functionality we are not going to test the journald logging in our bucket.. 

https://github.com/openbmc/openbmc-test-automation/blob/master/extended/test_journal.robot

**Comment by swe12345** [comment]
Code in Review
https://gerrit.openbmc-project.xyz/#/c/7559

**Comment by sivassrr** [comment]
Our intention is not to remove only to skip the journal test code. We need to use the same (re-use when new feature introduces in journalctl).

**Comment by gkeishin** [comment]
@sivassrr We won't be able to use it since the REST don't log the REST footprint anymore there and top of that this code is using old codes. We don't want to keep something not used. If needed we can always rewrite this piece of code. 

@swe12345  please rebase the code and we will remove it. Thanks
