### ISSUE TITLE
PreTag Set IP address on valid Interface - FAILED

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#11]
Set IP address on valid Interface Failure.. This needs to be fix asap.. because of these 2 more test cases are failing .... ( "Persistency check for ip address" / Revert the last ip address change )

Full Name: Tests.Test Networkd.Set IP address on valid Interface
Documentation: This test case sets the ip on the interface and validates that ip address has been set or not. Expectation is the ip address should get added.
Tags: network_test
Start / End / Elapsed: 20160530 23:16:18.693 / 20160530 23:16:18.705 / 00:00:00.012
Status: FAIL (critical)
Message: Environment variable 'NEW_BMC_IP' does not exist.

As per README.md ..
Use Following Variables for networking test cases

$export NEW_BMC_IP=<openbmc machine ip address>
$export NEW_SUBNET_MASK=<openbmc new subnet mask>
$export NEW_GATEWAY=<openbmc new gateway>

But I don't see it exported any where in the setup.. So either this has to be automated or to be removed from the test case in full run... since it needs the setup prior to running the test,..

So this code tests/test_networkd.robot: ${NEW_IP}= Get Environment Variable NEW_BMC_IP

is bound to fail...

+++++++++++++++++++++++++

Since the above test case ""Set IP address on valid Interface" Failed.. this also failed...

And same with test case "Persistency check for ip address"

Revert the last ip address change

Full Name: Tests.Test Networkd.Revert the last ip address change
Documentation:

This test case sets the ip on the interface and validates that ip address has been set or not. Expectation is the ip address should get added.
Tags: network_test
Start / End / Elapsed: 20160530 23:16:18.706 / 20160530 23:16:18.717 / 00:00:00.011
Status: FAIL (critical)
Message: Variable '${OLD_IP}' not found.

**Comment by gkeishin** [comment]
Since the PDU and Network are needed to be set before running the test.. I would vouch for moving the PDU and network test code for setting with new IP out of test folder and create new one test_pdu_network/  directory and run separately..

This will help in two aspects
1. The CI/FVT jenkins runs to pass.
2. The automation test code such as PDU/IP changes which are not really testing the code stack directly can be run separately

**Comment by gkeishin** [comment]
From the README if the user sets this every run then it wold work but it may not be necessarily keep doing this in all the test run for CI's.

Use Following Variables for networking test cases
===========================================================    
    $export NEW_BMC_IP=<openbmc machine ip address>
    $export NEW_SUBNET_MASK=<openbmc new subnet mask>
    $export NEW_GATEWAY=<openbmc new gateway>    
==========================================================

    Use following parameters for PDU:
    $ export PDU_IP=<PDU IP address>
    $ export PDU_USERNAME=<PDU username>
    $ export PDU_PASSWORD=<PDU password>
    $ export PDU_TYPE=<PDU type>
    $ export PDU_SLOT_NO=<SLOT number>

    for PDU_TYPE we support only synaccess at the moment

**Comment by sivassrr** [comment]
Please close, we can track it under https://github.com/openbmc/openbmc-test-automation/issues/3
