### ISSUE TITLE
[Automation] Test non-SSL Connection to port 443 Error

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#110]
**Test case expectation**
This testcase is for test to check OpenBMC machine will not accepts the non-secure connection that is with http to port 443 and expect 400 in response

**In actual Test result**

Send a GET request on the session object found using the
Start / End / Elapsed:  20160913 22:22:25.494 / 20160913 22:22:29.659 / 00:00:04.165
22:22:29.658    FAIL    ConnectionError: HTTPConnectionPool(host='9.3.29.119', port=443): Max retries exceeded with url: //list (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))
# Tests.Security.Test Ssl :: This testsuite is for testing SSL connection to ...
## Test non-SSL Connection to port 80 :: This testcase is for test to... | PASS |

Test non-SSL Connection to port 443 :: This testcase is for test t...
FFDC Collection Started         : 20160913225946561517
FFDC Collection Completed       : 20160913225958445798
| FAIL |
## ConnectionError: HTTPConnectionPool(host='barp01.aus.stglabs.ibm.com', port=443): Max retries exceeded with url: //list (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))

Tests.Security.Test Ssl :: This testsuite is for testing SSL conne... | FAIL |
3 critical tests, 2 passed, 1 failed
#3 tests total, 2 passed, 1 failed

**Comment by gkeishin** [comment]
I think we need to fix the automation code and we need to key this off from this is a valid errors.

**Comment by gkeishin** [comment]
Earlier : We use to get HTTP_BAD_REQUEST for non-SSL Connection to port 443

url=http://9.3.29.119:443/

Start / End / Elapsed: 	20160901 10:02:48.461 / 20160901 10:02:48.842 / 00:00:00.381
10:02:48.841 	INFO 	Get Request using : alias=openbmc, uri=/list, headers=None 	
10:02:48.842 	INFO 	${resp} = <Response [400]>


Now : With the new REST server, we get ConnectionError: straight away

Send a GET request on the session object found using the
Start / End / Elapsed: 	20160913 22:22:25.494 / 20160913 22:22:29.659 / 00:00:04.165
22:22:29.658 	FAIL 	ConnectionError: HTTPConnectionPool(host='9.3.29.119', port=443): Max retries exceeded with url: //list (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))


Is this expected to work like this Error ? 

@bradbishop

**Comment by gkeishin** [comment]
Had a word with Brad, he is looking into it...

**Comment by rahulmah** [comment]
Just for more info. Tested with latest openbmc build (v1.99.0-85-g0d2bd6a). Found that this issue is seen on both Palmetto and Barreleye systems.

**Comment by rahulmah** [comment]
@gkeishin : This does not seem to be a bug in automation. Can you please move this issue to openbmc repo.

**Comment by sivassrr** [comment]
May be need to reassign based on the latest check.

**Comment by gkeishin** [comment]
Closing this as counterpart is opened  for openbmc https://github.com/openbmc/openbmc/issues/829

**Comment by gkeishin** [comment]
As per @ratagupt  
From the openbmc/openbmc#829  comment
I think that HTTP ERROR 4xx is for (request data is not valid).Now as in this scenario we are sending the http request to port 443,as the ssl connection would not be established so server doesn't get a chance to look at the request.so you should get error 104. which is connection reset by peer.
