### ISSUE TITLE
[Automation] FFDC needs to be collected if Setup The Suite fails

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#113]
In recent run, it is seen that "Setup The Suite" fails for Test Inventory. But openbmc automation, does not collect FFDC for this failure. 

Test automation need to be modified to collect FFDC in such case.

SETUP Setup The Suite
Start / End / Elapsed:	20160916 09:33:19.931 / 20160916 09:33:40.107 / 00:00:20.176
00:00:10.657KEYWORD powerons . BMC Power On
00:00:00.007KEYWORD @{ret} = utilities . Get Inventory List ${OPENBMC_MODEL}
00:00:00.003KEYWORD BuiltIn . Set Suite Variable @{sys_inv}, @{ret}
00:00:09.507KEYWORD ${resp} = rest_client . Read Properties /org/openbmc/inventory/enumerate
Start / End / Elapsed:	20160916 09:33:30.600 / 20160916 09:33:40.107 / 00:00:09.507
00:00:09.505KEYWORD ${resp} = rest_client . OpenBMC Get Request ${uri}, timeout=10
00:00:00.002KEYWORD BuiltIn . Should Be Equal As Strings ${resp.status_code}, ${HTTP_OK}
Documentation:	
Fails if objects are unequal after converting them to strings.
Start / End / Elapsed:	20160916 09:33:40.105 / 20160916 09:33:40.107 / 00:00:00.002
09:33:40.106	INFO	Argument types are:
<type 'int'>
<type 'unicode'>	
09:33:40.106	FAIL	404 != 200 

System fw info: 
root@palmetto:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-85"
VERSION_ID="v1.99.0-85-g0d2bd6a-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-85"
BUILD_ID="v1.99.0"
root@palmetto:~#

**Comment by gkeishin** [comment]
If its a Suite setup, it didnt won't even start the test.. so it wont collect the FFDC..  

This was also earlier thought off if Suite setup failed shouldn't we collect FFDC ?... 
the answer is no at this point.. 

 The FFDC is designed to captured data at the test case level failure not at the Suite Level.

**Comment by gkeishin** [comment]
This we are not going to support for now. Here are the reason

Sample                                                                        
==============================================================================
Test cases 1                                                          
Hello
Test cases 1                                                          | PASS |
------------------------------------------------------------------------------
Test cases 2                                                          | FAIL |
testing != oops
------------------------------------------------------------------------------
Test cases 3                                                          
Hello
Test cases 3                                                          | PASS |
------------------------------------------------------------------------------
**Suite Status: FAIL**
Sample                                                                | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================


You can see if the Test case fails, the Suite Status is marked failed. So its a double collection.

Now next use case like the one u have here where the suite failed

==============================================================================
Sample                                                                        
==============================================================================
Test cases 1                                                          | FAIL |
Parent suite setup failed:
initialization != oops
------------------------------------------------------------------------------
Test cases 2                                                          | FAIL |
Parent suite setup failed:
initialization != oops
------------------------------------------------------------------------------
Test cases 3                                                          | FAIL |
Parent suite setup failed:
initialization != oops
------------------------------------------------------------------------------
**Suite Status: FAIL**
Sample                                                                | FAIL |
Suite setup failed:
initialization != oops

3 critical tests, 0 passed, 3 failed
3 tests total, 0 passed, 3 failed
==============================================================================

Now if you look at the both ways example, you can't really differentiate the suite failure vs a test case failure exiting from the suite.

**Comment by gkeishin** [comment]
This is still  a debatable idea to have for test suite setup failure.. open for discussions...

**Comment by causten** [comment]
system is not in a valid state if the suite setup fails. No need for FFDC since another test previous to it caused the system to get in to a bad state.  More important things to worry about like adding test cases for what is in the current sprint.  suite setup failures will not get the system to GA faster

**Comment by gkeishin** [comment]
Closing this..

**Comment by rahulmah** [comment]
@causten : I completely agree with your point. I was seeing a case (https://github.com/openbmc/openbmc/issues/580) where one suit was completely failing and no FFDC was getting captured for it. So I just logged it as a future enhancement item.
