### ISSUE TITLE
Error capping Test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1154]
New error logging capping test needed

- [x] Information Capping test - Max 10 logs and then rotates
- [x] High severity capping test - Max 100 and then rotates

Developer @ngorugan if you have question on the use cases.

**Comment by swe12345** [comment]
Code in Review:
https://gerrit.openbmc-project.xyz/#/c/8437

**Comment by gkeishin** [comment]
- [x] Information changes is not done with this. Since the logging binary doesn't support to create one at the moment.
