### ISSUE TITLE
Need to add IPMI sensor ID related test case for OCC/ Boot progress/ OperatingSystemStatus

### ISSUE THREAD

**Issue by swe12345** [openbmc/openbmc-test-automation#1159]
Need to add IPMI sensor ID related test case for OCC/ Boot progress/ OperatingSystemStatus.

**Comment by swe12345** [comment]
Code in review
https://gerrit.openbmc-project.xyz/#/c/8208/

**Comment by gkeishin** [comment]
New comments in review.. fix it up @swe12345
