### ISSUE TITLE
Walk through inventory object paths and verify

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1164]
- [x] /xyz/openbmc_project/ and its child
```
/xyz/openbmc_project/
[
    "/xyz/openbmc_project/dump",
    "/xyz/openbmc_project/software",
    "/xyz/openbmc_project/control",
    "/xyz/openbmc_project/network",
    "/xyz/openbmc_project/logging",
    "/xyz/openbmc_project/sensors",
    "/xyz/openbmc_project/inventory",
    "/xyz/openbmc_project/user",
    "/xyz/openbmc_project/time",
    "/xyz/openbmc_project/led",
    "/xyz/openbmc_project/watchdog",
    "/xyz/openbmc_project/state"
]
```
Next
/xyz/openbmc_project/inventory
{}

/xyz/openbmc_project/inventory/
[
    "/xyz/openbmc_project/inventory/system"
]

and so on.

**Comment by gkeishin** [comment]
Task for Manash to implement
- [x] Keyword library to accept the path and create a tree
- [x] Keyword to walk through the paths object and query sub objects

**Comment by gkeishin** [comment]
@manashsarma

**Comment by manashsarma** [comment]
It is in progress. I am to use:

1. list to take all URI one after another
2. get each uri from the REST server with status
3. Able to put each uri and status to a list.
4. Also able to selectively (if not 200) put uri and resposne status in a list

**Comment by manashsarma** [comment]
In my  code , not committed / checked  into git yet,  I am able to do all above 4 points

**Comment by gkeishin** [comment]
Good work.. @manashsarma Let get the code in
