### ISSUE TITLE
IBM Milestone 2: Fan Control  Test / Automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1174]
Here is equivalent of development IBM Milestone 2 - Fan control story
https://github.com/openbmc/openbmc/issues/2605

**Comment by sivassrr** [comment]
Based on discussion with Tan, Assigning this to Steven Sombar.

**Comment by ssombar** [comment]
see related issue phosphor-fan: support fan pwm openbmc/openbmc#2808

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/8889 Add fan tests
