### ISSUE TITLE
IBM Milestone 2: IPMI 2.0 Test and Automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1182]
Development epic: https://github.com/openbmc/openbmc/issues/2616

- [ ] IPMI 2.0 - Test plan 

- [ ] IPMI 2.0   Automation 

- [ ] IPMI 2.0   Testing

**Comment by rahulmah** [comment]
IPMI DCMI : Get System GUID - https://github.com/openbmc/openbmc-test-automation/issues/1191

**Comment by rahulmah** [comment]
```DCMI commands```

DCMI Capabilities& Discovery Configuration Commands:
Get DCMI Capabilities Info - Need to be implemented.
Set DCMI Configuration Parameters - Need to be implemented.
Get DCMI Configuration Parameters - Need to be implemented.
Get Management Controller Identifier String - Already implemented by community
Set Management Controller Identifier String - Already implemented by community


Platform & Asset Identification Commands:
Get Asset Tag - Already implemented. 
Set Asset Tag - Already implemented. 
Get Device ID - Defect. Fix needs to ne integrated.
Get System GUID - Need to be implemented.


Chassis Commands:
Get Chassis Capabilities - Already implemented. Need to test.
Get Chassis Status - Already implemented.
Chassis Control - Already implemented.
Chassis Identify - Already implemented. Need to test.
Get ACPI Power State Already implemented. Need to test.

Boot Control Command:
Set System Boot Options - Already implemented.
Get System Boot Options - Already implemented.

LoggingCommands:
Get SEL Info - Already implemented. 
Reserve SEL - Already implemented. 
Get SEL Entry - Already implemented. 
Clear SEL - Already implemented.

Sensor & SDR Commands:
Get DCMI Sensor Info - Need to be implemented.
Get SDR Repository Info - Need to be implemented.
Reserve SDR Repository - Need to be implemented.
Get SDR - Need to be implemented.
Get Sensor Threshold - Need to be implemented.
Get Sensor Reading - Need to be implemented.
Set Sensor Event Enable - Optional command. Need to be implemented.
Get Sensor Event Enable - Optional command. Need to be implemented.


Power Management:
Get Power Reading - Already implemented.
Get Power Limit - Already implemented.
Set Power Limit - Already implemented.
Activate/Deactivate Power Limit - Already implemented.

ThermalManagement:
Set Thermal Limit - Optional command.
Get Thermal Limit - Optional command.
Get Temperature Readings - Need to be implemented

Watchdog Timer
Reset Watchdog Timer - Already implemented. Need to test.
Set Watchdog Timer - Already implemented. Need to test.
Get Watchdog Timer - Already implemented. Need to test.

Remote and Serial Over LAN SessionEstablishment
Get Channel Authentication Capabilities - Already implemented.
Set Session Privilege Level - Already implemented.
Close Session - Already implemented.
Get Session Info - Already implemented.
Get Payload Activation Status - Already implemented.
Get Payload Instance Info - Already implemented.
Get Channel Payload Support - Optional
Activate Payload - Already implemented.
Deactivate Payload - Already implemented.
Get Channel Cipher Suites - Already implemented.
SOL Activating - Already implemented.


RemoteAccess Configuration:
Set LAN Configuration Parameters - Already implemented.
Get LAN Configuration Parameters - Already implemented.
Set Channel Access - Not implemented. Intel may do as part of user management.
Get Channel Access - Not implemented. 
Get Channel Info - Not implemented. 
Set User Access - Not implemented. 
Get User Access - Not implemented. 
Set User Name - Not implemented.
Get User Name - Not implemented.
Set User Password - Not implemented.
Set User Payload Access - Not implemented.
Get User Payload Access - Not implemented.

Serial Over LANConfiguration:
Set SOL Configuration Parameters - Already implemented.
Get SOL Configuration Parameters - Already implemented.

System (local) InterfaceAccess:
Set BMC Global Enables - Optional command.
Get BMC Global Enables - Optional command.
Clear Message Flags - Optional command.
Get Message Flags - Optional command.

Messaging Commands:
Get Message - Optional command.
Send Message - Optional command.

**Comment by sivassrr** [comment]
Done. So closing it. Thank you @rahulmah
