### ISSUE TITLE
IBM Milestone 2: Power Supply Automation and test

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1187]
Development Equivalent Epic: https://github.com/openbmc/openbmc/issues/2596

- [ ]  Manual testing with latest Power supply code - Need to check LED, Errorlogs associate with that.
- [ ]  Automation - Already code is there, if there is any changes needed then need to be done.

**Comment by sivassrr** [comment]
For some reason, Not able to assign it to Tan / Marissa Id.

**Comment by sivassrr** [comment]
So assigning to Steve as on now.

**Comment by ssombar** [comment]
Jan 11:
    Marissa GARZA:
    Here's the link for the 7 Fan tests for Witherspoon:
     https://jazz01.rchland.ibm.com:13443/jazz/web/console/Power System Enablement FTC and ITC#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestPlan&id=2965

    And you might want to take a look at the Witherspoon FAN Manual Regression Test Plan:
  https://jazz01.rchland.ibm.com:13443/jazz/web/console/Power System Enablement FTC and ITC#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestPlan&id=3091

**Comment by ssombar** [comment]
Sivas, I think we can close this issue (number 1187)

**Comment by ssombar** [comment]
opembmc-test-automation power supply test file names:
lib/open_power_utils.robot:    ${power_supply_avg_list}=  Create List
lib/open_power_utils.robot:    ${power_supply_max_list}=  Create List
lib/open_power_utils.robot:    ...    Append To List  ${power_supply_max_list}  ${entry}
lib/open_power_utils.robot:    ...    Append To List  ${power_supply_avg_list}  ${entry}
lib/open_power_utils.robot:    [Return]  ${power_supply_avg_list}  ${power_supply_max_list}
mnfg/pgood.robot:    [Documentation]  Verify pgood state on good power supply.
mnfg/pgood.robot:    [Documentation]  Verify pgood state on bad power supply.
tests/test_ledgroup.robot:Verify Power Supply Fault LEDs Group
tests/test_ledgroup.robot:    [Documentation]  Verify power supply's fault LEDs.
tests/test_ledgroup.robot:    [Tags]  Verify_Power_Supply_Fault_LEDs_Group
tests/test_ledgroup.robot:    Verify LED Group  powersupply  fault
tests/test_hardware_sensors.robot:   # /xyz/openbmc_project/sensors/chassis/PowerSupplyRedundancy
tests/test_hardware_sensors.robot:   # /xyz/openbmc_project/sensors/chassis/PowerSupplyRedundancy
tests/test_hardware_sensors.robot:    ...  raw ${IPMI_RAW_CMD['power_supply_redundancy']['Disabled'][0]}
tests/test_hardware_sensors.robot:    ...  raw ${IPMI_RAW_CMD['power_supply_redundancy']['Get'][0]}

**Comment by sivassrr** [comment]
Thank you @ssombar for the update. Closing this. As it is done.
