### ISSUE TITLE
[Automation] ConnectionError while doing GET operation on inventory url

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#119]
ConnectionError seen on Palmetto with latest openbmc build v1.99.0-108-g5d5f8df-dirty. These errors are seen with inventory related test cases. This seem to be happening as Palmetto's inventory url is changed recently in openbmc fw. Changes need to be taken care in automation framework.

**CPU Present**                                                           URI:https://9.3.164.153/org/openbmc/inventory/system/chassis/motherboard/cpu0/attr/present, method:Get, args:{}

FFDC Collection Started 	: 2016-09-20 07:21:13,870742
FFDC Collection Completed 	: 2016-09-20 07:21:57,393340
| FAIL |
ConnectionError: HTTPSConnectionPool(host='9.3.164.153', port=443): Max retries exceeded with url: /org/openbmc/inventory/system/chassis/motherboard/cpu0/attr/present (Caused by ReadTimeoutError("HTTPSConnectionPool(host='9.3.164.153', port=443): Read timed out. (read timeout=5.0)",))

Tried running manually GET operation and found that path is not found.

rahulmah@rackspace:~$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET -d "{\"data\":[]}" https://9.3.164.153/org/openbmc/inventory/system/chassis/motherboard/cpu0/attr/present
{
  "data": {
    "description": "org.openbmc.ObjectMapper.Error.NotFound: path or object not found: /org/openbmc/inventory/system/chassis/motherboard/cpu0"
  },
  "message": "404 Not Found",
  "status": "error"

**Comment by gkeishin** [comment]
@rahulmah  Check once you get hands on a system booting to HOST_BOOTED state.. I suspect 404 may be due to pre condition state requirement.

**Comment by rahulmah** [comment]
@gkeishin : This has nothing to do with system state. System inventory should url which I have tried should work on host power off state (I cross checked it). Anyway my system was booting to HOST_BOOTED state while doing testing.

**Comment by rahulmah** [comment]
Code checked for review.
