### ISSUE TITLE
[Automation] - IPMI DCMI : Get sensor threshold

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1194]
Development story - https://github.com/openbmc/openbmc/issues/2624

**Comment by sivassrr** [comment]
Dbus: Critical & Warninghigh, unrecoverable, Recoverable, Non-critical - Warning
IPMI: 

Basically currently comparison between Dbus and IPMI ,  decided to have Critical and Warning as per today's meeting. @swe12345 FYI.

**Comment by rahulmah** [comment]
Merged - https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/33481/
