### ISSUE TITLE
[Automation] IPMI DCMI : Get power reading

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1195]
Development story - https://github.com/openbmc/openbmc/issues/2625

**Comment by sivassrr** [comment]
Hi @ssombar Pls check on this from DCMI perspective, your recent automation code check-in, I saw you are addressing some of this. Pls check and close accordingly. If not we need to add it.

**Comment by ssombar** [comment]
yes, we do this in tests/test_escale_base.robot and systest/test_power_capping.robot  which are in the GH source tree and in

**Comment by sivassrr** [comment]
Thank you @ssombar based on your input and discussion with @rahulmah , Assigned to @rahulmah
