### ISSUE TITLE
[Automation] - IPMI DCMI : Get temperature readings

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1196]
Development story - https://github.com/openbmc/openbmc/issues/2626

**Comment by sivassrr** [comment]
Hi @ssombar Pls check on this , your recent automation code check-in, I saw you are addressing some of this. Pls check and close accordingly. If not we need to add it.

**Comment by ssombar** [comment]
We don't use the interface of openbmc/openbmc#2626 yet so this would need to be coded in Robot Framework.
