### ISSUE TITLE
Align with merged code

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1204]
Sathya to align with merged code for his commit https://gerrit.openbmc-project.xyz/#/c/7127/

As @samahaba wants to have a separate commit to merge, As per request from him, have created this issue.

**Comment by samahaba** [comment]
This issue resolved only when after my latest checkin code merge happen, because as I repeatedly mention that base framework has to finalized first.

**Comment by sivassrr** [comment]
Taken care in my current commit. We can close it.
