### ISSUE TITLE
[Automation] IPMI - Get dcmi get and set power limit

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1205]
IPMI - Get dcmi get and set power limit

**Comment by sivassrr** [comment]
Hi @ssombar Pls check , I believe you had already automated this. So accordingly we can close it.

**Comment by ssombar** [comment]
yes, we do this in tests/test_escale_base.robot  which is in the GH source tree

**Comment by ssombar** [comment]
I think we can close this

**Comment by sivassrr** [comment]
Thank you @ssombar for your confirmation. Closing it accordingly
