### ISSUE TITLE
GUI- Template implementation

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1211]
Need to look at the existing GUI test code and implement template where ever required.

Will address Mike Walsh comment using this commit. Thanks

**Comment by gkeishin** [comment]
This was one of the @micwalsh comment for GUI earlier to templatize in GUI.

**Comment by sivassrr** [comment]
I am seeing opportunity using template in Health status. Will use template there.

**Comment by sivassrr** [comment]
Existing code, Will take it as less priority. New code will grab the opportunity.

**Comment by sivassrr** [comment]
Not working on this.
