### ISSUE TITLE
Move tests/security/test_user_management.robot to the extended bucket.

### ISSUE THREAD

**Issue by swe12345** [openbmc/openbmc-test-automation#1218]
Moving the test suite tests/security/test_user_management.robot to the extended bucket.

**Comment by gkeishin** [comment]
We see its safe to move out from main `tests` since if this one fails it would mess up the whole test depending on user default root password. So to contain this moving to `extended`

**Comment by swe12345** [comment]
Code in Review
https://gerrit.openbmc-project.xyz/#/c/8753/
