### ISSUE TITLE
use web sockets

### ISSUE THREAD

**Issue by mdmillerii** [openbmc/openbmc-test-automation#1219]
Issue openbmc/openbmc#2858 shows that CI passed without flagging web sockets were broken.

https://lists.ozlabs.org/pipermail/openbmc/2018-January/010289.html describes a use case for web sockets.

**Comment by gkeishin** [comment]
Thanks @mdmillerii Will look into it.

**Comment by gkeishin** [comment]
@ratagupt Could u help us here in this context what nature of the test we could enable in CI to catch such bug ahead..

**Comment by ssombar** [comment]
If this issue is not being worked on yet,  I have test code working (unashamedly mostly Justin Thaler's code) which I would be happy to put into a robot framework test case.

**Comment by gkeishin** [comment]
You could do this in a couple of ways:

1. Add delta to the script and submit for community usage.

2. As for the test, if there is no simpler way to achieve this, we can discuss use the tool in our code to call it or implement the similar to support it. 

Just take a look and weight it out.

**Comment by ssombar** [comment]
with python2.7 get fatal error "SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. **You can upgrade to a newer version of Python to solve this**.".
However, it works fine on python version 3.

**Comment by gkeishin** [comment]
We have one task pending to be python3.x compliance. So the best strategy to do is

- [x] Go ahead and implement in python 3.x level 
- [x] Create a new test dir opebmctool_test and drop the changes.

**Comment by gkeishin** [comment]
@ssombar scheduling for next sprint.. Thanks

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/23226
