### ISSUE TITLE
Enhance existing Read Attribute base keyword

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1221]
@micwalsh suggestion

Either 'Read Attribute' should be updated to accept a "expected_value" argument or a 'Check Attribute' (or 'Verify Attribute') keyword should be added to lib/rest_client.robot.

Then you could call it directly up above like this:

    Wait Until Keyword Succeeds  10 sec  5 sec
    ...  Read Attribute  ${SOFTWARE_VERSION_URI}${image_object}  ${sw_attribute}  expected_value=Priority

**Comment by manashsarma** [comment]
What is the exact intent of adding this attribute 'expected_value' ?

**Comment by gkeishin** [comment]
This enhances the Read Attribute keyword so that it can be used to just read or read and compare..
