### ISSUE TITLE
[ Automation ] ipmi BT capabilities command  Failure

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#123]
The DBUS command doesn't return data for the test resulting in failure..

14:32:42.545    INFO    Executing command 'dbus-send --system /org/openbmc/HostIpmi/1 org.openbmc.HostIpmi.ReceivedMessage byte:0x00 byte:0x06 byte:0x00 byte:0x36'.  
14:32:42.726    INFO    Command exited with return code 0.  
14:32:42.726    INFO    ${output} =  
14:32:42.726    INFO    ${stderr} =

**Comment by rahulmah** [comment]
@gkeishin : Any update on this issue? It is failing on Palmetto system also.

**Comment by gkeishin** [comment]
Probably @sivassrr can help explain what was the problem we had with the DBUS . I think there are couple more failing because of DBUS related issues..

**Comment by sivassrr** [comment]
@SrideviRamesh As per today's discussion, Assign this issue to you. Please use external IPMI to fix this.

**Comment by gkeishin** [comment]
@swe12345  Please verify if this is working now

**Comment by gkeishin** [comment]
Closing as tracked by https://github.com/openbmc/openbmc-test-automation/issues/926
