### ISSUE TITLE
To make use of recently checkin keywords

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1230]
Purpose of this issue is to adopt recently checkin keywords

- [ ] Explore the new keywords what was merged

- [ ] Adopt into the GUI Header, Where it is applicable.

**Comment by mdmillerii** [comment]
This issue is for all keywords?  Or was this supposed to be keywords in some specific file(s)?

**Comment by sivassrr** [comment]
I think it is done.
