### ISSUE TITLE
[Barreleye VERSION_ID="v1.99.0-123-gfc7788a-dirty"] obmc-console-client: obmc console client failed to start

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#124]
Explanation of the issue:

obmc-console-client: Can't connect to console server: Connection refused

1. Start manually : login to BMC and run obmc-console-client

2. Start connect using SOL port :    ssh -p 2200 root@xx.xx.xx

Expected Behavior:

Expected to get console logs when powered off and on the BMC system

Actual Behavior:

obmc-console-client command execution failed

obmc-console-client: Can't connect to console server: Connection refused

Recreation Steps:

 1. Log in to BMC and execute "obmc-console-client"

 2. power off and on BMC System and observe  the logs generated from "obmc-console-client"

Specifications:

BMC Version

root@barreleye:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-123"
VERSION_ID="v1.99.0-123-gfc7788a-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-123"
BUILD_ID="v1.99.0"

System Type: Barreleye

Operating System Details:

Linux beye5 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:40:06 UTC 2016 ppc64le ppc64le ppc64le GNU/Linux

**Comment by gkeishin** [comment]
@anoo1 @jk-ozlabs  anything you are aware of SOL failure recently ?

**Comment by gkeishin** [comment]
There is already opened defect one for this... so this is pretty known issue now.. closing here

Refer  
https://github.com/openbmc/openbmc/issues/585
https://github.com/openbmc/obmc-console/issues/7
