### ISSUE TITLE
[Automation] Tag test cases by its name

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#126]
To address this for upcoming sprint

1 Create all test case and tag by the test name itself.
2 Create a master file for skip list 
3. --argumentfile  skip_list   

For maintainability and for cleaner approached.

example 

 "clearing logs results in no logs"   --> clearinglogsresultsinnologs

 clearing logs results in no logs

```
  [ Tags ] clearinglogsresultsinnologs
```

**Comment by sivassrr** [comment]
gkeishin Partially we are done, right. Shall we focus on test content and take it in the next sprint?

**Comment by gkeishin** [comment]
Let keep this.. If we will try to add tags in our others changes.. If most of them are done, then we will use this to complete the remaining pending few ones and close it..

right now we are done only 10-20 % of the tagging..

**Comment by gkeishin** [comment]
Closing this as we are done tagging all  test.. if there are missing , it will be part of the other work items
