### ISSUE TITLE
IPMI in-band network configuration test

### ISSUE THREAD

**Issue by swe12345** [openbmc/openbmc-test-automation#1260]
BMC Setup using in-band network setup via IPMI.

**Comment by gkeishin** [comment]
https://github.com/openbmc/phosphor-host-ipmid/blob/1500a64704cf558a1d08d1cf0db7a4a3d550989a/docs/ipmitool-commands-cheatsheet.md

- [ ] Test to set the static IP via in band

```
Set the interface mode

ipmitool lan set <channel> ipsrc static
Set the IP Address

ipmitool lan set <channel> ipaddr <x.x.x.x>
Set the network mask

ipmitool lan set <channel> netmask <x.x.x.x>
Set the default gateway

ipmitool lan set <channel> defgw ipaddr <x.x.
```

**Comment by gkeishin** [comment]
Fancy taking this one up @ssombar

**Comment by gkeishin** [comment]
U can use the https://github.com/openbmc/openbmc-test-automation/blob/master/lib/ipmi_client.robot#L296 code to do the trick for u.

So create a test case to set the IP and call this with the parameters

**Comment by ssombar** [comment]
is this still needed?

**Comment by gkeishin** [comment]
Yup @ssombar we will need this one.

**Comment by NamanNH** [comment]
Review completed:
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/24340/
