### ISSUE TITLE
standardize_mac

### ISSUE THREAD

**Issue by micwalsh** [openbmc/openbmc-test-automation#1264]
We found at least one case where we get a mac address that looks like this: 70:e2:84:14:2a:8.  Notice the "8" at the end vs the more standard "08".  It can be argued that that address is legitimate but that it is difficult to compare mac addresses when they are not in a standard format:

Proposal:  Create a python function 'standardize_mac':
def standardize_mac(mac_addr):

    r"""
    Return standardized mac as defined below:

    All hex letters will be lower case, colon-separated octets, each containing 2 digits.
    """

After this we can probably re-evaluate the need for the compare_mac_address function in lib/utils.py.

**Comment by gkeishin** [comment]
Sounds good.. Thank you @matthewfischer  Closing the ticket.
