### ISSUE TITLE
Suite Setup failure: Associate TC suite failure

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1276]

**Comment by sivassrr** [comment]
@gkeishin Feel free to assign to either Sridevi and Swetha as per our scrum discussion today. We can assign them based on the work priority.

**Comment by sivassrr** [comment]
Pls refer saturday's driver of GHE CT execution.

**Comment by gkeishin** [comment]
Most of the suite failure are now fixed via few smaller other commits for different module suite fixes.. closing this one.
