### ISSUE TITLE
Watchdog: Verify watchdog enabled failing

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1283]
![image](https://user-images.githubusercontent.com/19144129/36796386-7436a2c2-1ccb-11e8-98d6-d1aedc624c5f.png)

**Comment by sivassrr** [comment]
Have shared the output to @SrideviRamesh . Please investigate.

**Comment by gkeishin** [comment]
Closing this as we have code in review using this https://github.com/openbmc/openbmc-test-automation/issues/1299
