### ISSUE TITLE
GUI: Automation: Automation should run header less  browser mode (Non-headerless) on Mac OS

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc-test-automation#1288]

**Comment by sivassrr** [comment]
First higher priority is to run with header browser support only for system like Mac. 
 Headerless not much of higher priority. And it is not exact replica of customer environment. 

We are working on headerless / Headerway for Jenkin environment. Jenkin environment are all individual company environment. Heardway is the actual customer environment.

**Comment by samahaba** [comment]
So now only the priority comes in picture, but in reality and as per our discussion there is no priority level taking about and also the discussion mentioned that our GUI automation has to run in such a way that first it should run header browser as default irrespective of the (customer laptop - OS Windows/Linux/Readhat linux/Mac OS)  and automation should automatically detect if the customer (on customer laptop) not able to do/run launch header browser then it should have a capable of automatically switch to launch headless browser (Virtual browser). But am just getting wonder that requirement and discussion says one thing for me and now closing the issues irreverently under the name of priority.

**Comment by samahaba** [comment]
I think for a customer Window OS is also important it should also have high priority. because more over Microsoft is also one of our customer as you mentioned in one of our meting discussion.

Please correct me if am wrong.

**Comment by sivassrr** [comment]
Yes, Windows OS also an important and my point is to give higher priority to head way then headerless. @samahaba . As you know, we give importance to Windows, Linux and Mac OS. But there are other OS also there.. We will try to give support to main OS.
