### ISSUE TITLE
GUI Automation - Duplicate functions are exist in resource.robot

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc-test-automation#1289]
After merging of fix issue #1246 the function key word "Expected Initial Test State" is a replica of the function key word "Test Setup Execution" both the function are does the same thing but here the function key word "Test Setup Execution" has a advantage/feature  that if the system is already in expected state it simply return from the key word. So here code merger has to take the proper/correct decision before accepting and merging the code

**Comment by sivassrr** [comment]
@samahaba As you point out there are subtle difference between those two functions. Test Setup Execution provides rprint output and also if system is already in expected state it return from the keyword.  If needed people can use either one of them. And also if not required , we can remove the keyword "Expected Initial Test State" down the line. And consider as less priority as of now.

**Comment by samahaba** [comment]
See here the point is why we do have two same function if one function has to do all the capabilities and requirement. rprint is just print the line that what currently automation is doing at back ground, so I think it is not a good idea to have two function and it will confuse to the customer bit more. Any why it is up to you as per the priority do what ever you want. And also if the code like duplicate it will hamper the company name form the customer (customer like Dell, Intel, MicroSoft, Google) perspective.

**Comment by sivassrr** [comment]
I think it is resolved. If it is exist, we can reopen it.
