### ISSUE TITLE
Feature: system model files for test need to be generated from MRW /OpenBMC

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#129]
@spinler is going to generate system model from MRW and will populate the same in OpenBMC. 
Once system model file update, Test need to use it for test automation / test purposes. 
https://github.com/openbmc/openbmc/issues/599

Currently it is a place holder.

**Comment by spinler** [comment]
You can find the file the MRW parser generates at tmp/work/all-openbmc-linux/obmc-inventory/1.0-r1/image/usr/share/inventory/inventory.json.  So far this is just for Palmetto.

**Comment by rahulmah** [comment]
@spinler : I am unable to find this file in Palmetto. Do I need to perform any operation to see this file?

**Comment by spinler** [comment]
It gets generated in the build tree.  It isn't in source.

**Comment by sivassrr** [comment]
@rahulmah Currently we are moving towards enumerate, right. Do we still need to have system model updated , right. Shall we use the build tree ?

**Comment by rahulmah** [comment]
@sivassrr : We still depend on sensor id in model file for some sensor related test case. We need to find ways to read this data directly from the system to complete come out of dependency.

**Comment by sivassrr** [comment]
Thought of closing it.. But Previous comment from @rahulmah make sense. Need to revisit it.

**Comment by sivassrr** [comment]
@rahulmah do we still need this?
