### ISSUE TITLE
IPMI Test use cases for Basic IPL

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1292]
IPMI Power ON,
Power OFF,
Power Cycle
Power Soft,
Power Reset,
BMC Reset
BMC Reboot

IPMI Warm/Cold MC Reset  <-- This is in review

**Comment by gkeishin** [comment]
@manashsarma Once you are done with other. Here is next stuff you can pick up.

**Comment by rahulmah** [comment]
@manashsarma : We have below IPMI commands related to power functions. Out of which "status, on, off" is already done. So you can automate "cycle, reset, diag and soft".

chassis power Commands: status, on, off, cycle, reset, diag, soft

You can start automation in below order.
1. Soft - Host OS should shutdown softly.
2. Reset - BMC should reset with this command.
3. Cycle
4. Diag

**Comment by gkeishin** [comment]
Good input @rahulmah 

@manashsarma try to use minimum REST code as much as possible. 80% of the code is REST based. We want this to be logistically IPMI only codes related

**Comment by manashsarma** [comment]
'Diag' test case not added as development team replied that 'Diag' is not supported on my query to them.

**Comment by gkeishin** [comment]
So it's not supported or going to be supported? If it's going to be supported, go ahead and open one task for it.
