### ISSUE TITLE
Detecting the system automatically and kick off tests related to that model of the system only

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#13]
Based on the https://github.com/mkumatag/openbmc-automation recommended way of running entire test suite is as follows. .

No preset environment variables, the entire test suite for a barreleye system
$ OPENBMC_HOST=x.x.x.x tox -e barreleye -- tests

One Method which I can think off, BMC Prompt is set based on the system type. We should login using the given BMC IP address and check the prompt, Based on the trigger the test suite of corresponding systems.
# Then our method of invoking test will be simplified further.

Exploring the other better method.

**Comment by gkeishin** [comment]
This is already in our internal jenkins setup .. using AES.. so its done by HW CI as well.. We could use that model if needed to do our run separately ahead
