### ISSUE TITLE
[Automation]  REST restart test cases 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#130]
This needs to be revisited after discussion.

tests/test_openbmc_service_restart_policy.robot
Disabling Test OpenBMC Services Autorestart Policy 

The REST services here are hardcoded and will continue to change either in the service name or the policy as per the development perspective untill things are sorted out in REST. On the other hand, we shouldn't be really hardcode this anyway. We don't want to delete, neither add in known issue list. This surely fails each test run, so disabling this test case

Right now this test case is skipped

**Comment by sivassrr** [comment]
It can fall between unit test / Functional test.  But user can play with rest service start etc.

**Comment by gkeishin** [comment]
Services identified which are mission critical for functioning of the REST and error. 

```
    @{services}=
    ...  Create List  xyz.openbmc_project.Logging.service
    ...               xyz.openbmc_project.ObjectMapper.service
    ...               xyz.openbmc_project.State.BMC.service
    ...               xyz.openbmc_project.State.Chassis.service
    ...               xyz.openbmc_project.State.Host.service
```

**Comment by gkeishin** [comment]
This estimation will need correction is the current review goes through.. Currently put effort of 1 point identifying the changes, coding, testing and re structuring the code..
