### ISSUE TITLE
Open BMC tool test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1303]
We've got more and more people starting to use the tool from Justin, openbmctool.py (https://github.com/openbmc/openbmc-tools/blob/master/thalerj/openbmctool.py)
 
Probably a good idea to get some testing of this tool into our automated test suite if we don't already have it.
Feedback from @geissonator

**Comment by manashsarma** [comment]
I  downloaded ../thalerj/openbmctool.py from openbmc project


1. 
Manashs-MacBook-Pro:thalerj manash$ ./openbmctool.py -U root -P 0penBmc -H  9.41.166.234 collect_service_data
-bash: ./openbmctool.py: /usr/bin/python3: bad interpreter: No such file or directory

My Observation: 

Noticed “#!/usr/bin/python3” as the first line / shebang.
Needs to b removed

2.

Manashs-MacBook-Pro:thalerj manash$ python openbmctool.py -U root -P 0penBmc -H  9.41.166.234 collect_service_data
Attempting login...
Inventory collected and stored in /tmp/9.41.166.234--2018-03-16_13.34.45/inventory.txt
Key Error: /xyz/openbmc_project/sensors/chassis/PowerSupplyRedundancy
Failed to collect sensor readings
System LED status collected and stored in /tmp/9.41.166.234--2018-03-16_13.34.45/ledStatus.txt
sel short list collected and stored in /tmp/9.41.166.234--2018-03-16_13.34.45/SELshortlist.txt
fully parsed sels collected and stored in /tmp/9.41.166.234--2018-03-16_13.34.45/parsedSELs.txt
Attempting to get a full BMC enumeration
RAW BMC data collected and saved into /tmp/9.41.166.234--2018-03-16_13.34.45/bmcFullRaw.txt
Collecting bmc dump files
retrieving dump file 21
data collection complete
Manashs-MacBook-Pro:thalerj manash$ ls /tmp/9.41.166.234--2018-03-16_13.34.45/bmcFullRaw.txt
/tmp/9.41.166.234--2018-03-16_13.34.45/bmcFullRaw.txt

Manashs-MacBook-Pro:thalerj manash$ ls /tmp/9.41.166.234--2018-03-16_13.34.45
9.41.166.234--2018-03-16_13.34.45.zip	SELshortlist.txt			inventory.txt				parsedSELs.txt
9.41.166.234-dump21.tar.xz		bmcFullRaw.txt				ledStatus.txt

**Comment by manashsarma** [comment]
I modified shebang and now it can be easily  run from any folder:
Manashs-MacBook-Pro:tools manash$ ./openbmctool.py -U root -P 0penBmc -H  9.41.166.234 collect_service_data
Attempting login...
Inventory collected and stored in /tmp/9.41.166.234--2018-03-16_14.42.08/inventory.txt
Key Error: /xyz/openbmc_project/sensors/chassis/PowerSupplyRedundancy
Failed to collect sensor readings
System LED status collected and stored in /tmp/9.41.166.234--2018-03-16_14.42.08/ledStatus.txt
sel short list collected and stored in /tmp/9.41.166.234--2018-03-16_14.42.08/SELshortlist.txt
fully parsed sels collected and stored in /tmp/9.41.166.234--2018-03-16_14.42.08/parsedSELs.txt
Attempting to get a full BMC enumeration
RAW BMC data collected and saved into /tmp/9.41.166.234--2018-03-16_14.42.08/bmcFullRaw.txt
Collecting bmc dump files
retrieving dump file 24
retrieving dump file 25
retrieving dump file 22
retrieving dump file 23
retrieving dump file 21
data collection complete

**Comment by manashsarma** [comment]
I have incorporated the OpenBMC tool after some test. At this moment I have opened it for review without working on format, coding guide line.

Manashs-MacBook-Pro:tools manash$ ./openbmctool.py -U root -P 0penBmc -H xx.xx.xx.xx collect_service_data
Attempting login...
Inventory collected and stored in /tmp/xx.xx.xx.xx--2018-03-16_14.42.08/inventory.txt
Key Error: /xyz/openbmc_project/sensors/chassis/PowerSupplyRedundancy
Failed to collect sensor readings
System LED status collected and stored in /tmp/xx.xx.xx.xx--2018-03-16_14.42.08/ledStatus.txt
sel short list collected and stored in /tmp/xx.xx.xx.xx--2018-03-16_14.42.08/SELshortlist.txt
fully parsed sels collected and stored in /tmp/xx.xx.xx.xx--2018-03-16_14.42.08/parsedSELs.txt
Attempting to get a full BMC enumeration
RAW BMC data collected and saved into /tmp/xx.xx.xx.xx--2018-03-16_14.42.08/bmcFullRaw.txt
Collecting bmc dump files
retrieving dump file 24
retrieving dump file 25
retrieving dump file 22
retrieving dump file 23
retrieving dump file 21
data collection complete

**Comment by gkeishin** [comment]
@manashsarma  please go through the code a bit and the supported options. 
We can take input from @geissonator the type of test we want to plan for it.

**Comment by gkeishin** [comment]
@ssombar and I can take this one up and see how much we can do

**Comment by gkeishin** [comment]
@ssombar can u list out the possible test we plan to do. Just a brief here

**Comment by gkeishin** [comment]
```
OpenBMC Tool.

Development will provide updates to the tool to support the new RestAPIs.
- [ ] Configuring LDAP server
- [ ] Configuring the Logging server
- [ ] Uploading certificates
```

**Comment by ssombar** [comment]
```
Initial test plan:

openbmctool.py requires python 3. 
We can use existing TCs to create ESELs,  dumps,  and other functions.

FRU:
    Print out all FRUs.
    Print status of all FRUs.
    Print details of all FRUs.
    Print details of a single FRU. <--- TBD
Sensors:
    Print list of all sensors.
    Display details of a specific sensor.  <--- TBD
SEL (alerts):  
    print out a list of all sels condensed form.
    list all SELs.
    List specific SEL.  <---  TBD
    Get the verbose details of a specified SEL entry <-- TBD
    Clear all entries from the SEL.
    Set a specific sel entry to resolved.
    
    TBD becasue displaying a single SEL(alert),  single Sensor, 
    or Single FRU not working satisfactorily yet.
    
Service data:
    Verify collect service data function.
Health Check:
    Verify health check function.
Chassis:
    Verify chasis power on, softoff, hardoff.     
    Verify can control the chasis identity LED.
    Verify status of identity LED and Power Status.
Dump:
    List dumps.
    Create dump.
    Delete dump.
    Delete all dumps.
    Retrieve dump.
BMC:
    Verify bmc reset function thru menu option "bmc". 
MC: 
    Verify bmc reset funciton thru menu option "mc". 
Gard:
    Verify clear gard function.
Firmware:
    Verify can flash system BMC.
    Verify can flash system PNOR.
    Activate bmc image.
    Check status of firmware activation: 
      Running, Available, Needs Activation.
   
-end-

**Comment by gkeishin** [comment]
```
Justin Thaler [22:23]
@gkeishin This looks complete to me
```
@dkodihal if we miss anything there in the above list planned.

**Comment by dkodihal** [comment]
@gkeishin there's an API @tomjoseph83 has proposed for specifying privileges for LDAP groups. That will get into openbmctool as well.

**Comment by gkeishin** [comment]
Added in the plan above list. So we are looking ok there @dkodihal right?
 If further changes added, we can always update the plan and prioritize for more, as we go.

**Comment by dkodihal** [comment]
@gkeishin @ssombar we know that several customers are running this tool on Windows machines, and that updates had to made in the tool to be able to run with Windows Python. So it would be good to be able to test any updates we're adding to the tool from a windows system as well.

**Comment by ssombar** [comment]
Do we have a Jenks that runs on windows?

**Comment by gkeishin** [comment]
@ssombar well you can download and configure one.. but what are u looking here to execute ?

**Comment by gkeishin** [comment]
New changes from @dkodihal 
- [x] Configure logging server on BMC
```
python openbmctool.py -H xx.xx.xx.xx -U root -P 0penBmc logging remote_logging_config  -p 514 -a yy.yy.yy.yy
```
this is to set address and port in one shot - both have to be provided to this command

- [x] Disable logging forwarding to remote rsyslog server
```
python openbmctool.py -H xx.xx.xx.xx -U root -P 0penBmc logging remote_logging disable
```
this is to disable remote logging

- [x] View the remote logging configured on the BMC
``` 
python openbmctool.py -H xx.xx.xx.xx -U root -P 0penBmc logging remote_logging view
```
this is to view current config (ip address and port)

**Comment by gkeishin** [comment]
Changes https://github.com/openbmc/openbmc-tools/pull/30  for your reference @ssombar

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/13062

**Comment by gkeishin** [comment]
`MERGED`
- [x] Initial base setup codes drops from @micwalsh 
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/12989/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/12990/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/13025/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/13078/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/13080/

**Comment by ssombar** [comment]
`not merged`
` [ ]`  Enable local users
     https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-tools/+/13163/
 `[ ]` Add LDAP commands:
    https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-tools/+/13416/
 `[ ]` Add LDAP group privilege commands
    https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-tools/+/14271/
  `[ ]` Add certificate management commands
    https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-tools/+/13457/

**Comment by ssombar** [comment]
see related issues  https://github.com/openbmc/openbmc-tools/issues

**Comment by gkeishin** [comment]
Closing this task.. as its completed
