### ISSUE TITLE
openbmc-test-automation should follow PEP 8 Python code standards 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc-test-automation#1308]
https://github.com/openbmc/docs/blob/master/cpp-style-and-conventions.md#python-formatting

Add a `setup.cfg` and enable CI for openbmc-test-automation to enforce the standards. The code base needs to be fixed up first. 

```
bash-4.1$ pycodestyle   /esw/san5/gmills/obmc/openbmc-test-automation/ | wc -l 
10832
```

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/9725/
https://gerrit.openbmc-project.xyz/#/c/9724/
In review.

**Comment by micwalsh** [comment]
https://github.com/openbmc/docs/blob/master/contributing.md#python-formatting contains the directions for doing this.
