### ISSUE TITLE
Witherspoon LED state check at standby

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1314]
Feedback from @spinler  something we could do in our CI to check at standby

/xyz/openbmc_project/led/physical/front_id
{
    "Color": "xyz.openbmc_project.Led.Physical.Palette.Unknown",
    "DutyOn": 50,
    "Period": 1000,
    "State": "xyz.openbmc_project.Led.Physical.Action.Off"
}

/xyz/openbmc_project/led/physical/rear_id
{
    "Color": "xyz.openbmc_project.Led.Physical.Palette.Unknown",
    "DutyOn": 50,
    "Period": 1000,
    "State": "xyz.openbmc_project.Led.Physical.Action.Off"
}

**Comment by gkeishin** [comment]
Export the keyword from tests/ipmi/test_general_ipmi.robot to utils  "Verify Identify LED State" and then write TC to check for CI

**Comment by gkeishin** [comment]
Looks like for whatever reason the LED seems to turn on automatically. so something we need to check on,

**Comment by spinler** [comment]
People have been seeing systems with the front ID LED on solid by itself, so hopefully this should help catch that.

**Comment by gkeishin** [comment]
In review https://gerrit.openbmc-project.xyz/#/c/9848/
