### ISSUE TITLE
Code Update Improvements

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#132]
We continue to hit intermittent issues with our code update test.

First one we hit is this:

> Power State: 0
> URI:https://xxx.xxx.xxx.xxx/org/openbmc/sensors/host/BootProgress/attr/value, method:Get, args:{}
> Response code:200, Content:{
>  "data": "POST Error, unknown", 
>  "message": "200 OK", 
>  "status": "ok"
> }

The issue appears to be that this sensor is only valid after the system has booted.  Instead of looking at this, we should look at the BMC state (obmcutil state).  

The second issue is that we're not following the code update process.  We occasionally hit this error:

[32m.[0m[32m.[0mURI:https://xxx.xxx.xxx.xxx/org/openbmc/control/flash/bmc/action/update, method:Post, args:{u'data': {u'data': [u'/tmp/flashimg']}, u'headers': {u'Content-Type': u'application/json'}}
[31mF[0m
                                                                             
Initiate Code update BMC :: BMC code update process initiation        | [31mFAIL[0m |

I see this in the OpenBMC logs:

> Sep 17 05:06:15 barreleye bmc_update.py[753]: Preserving network settings
> Sep 17 05:06:15 barreleye bmc_update.py[753]: update: --no-flash --no-save-files --no-restore-files --no-clean-saved-files
> Sep 17 05:06:16 barreleye bmc_update.py[753]: /dev/mtdblock5 /run/initramfs/ro squashfs ro,relatime 0 0
> Sep 17 05:06:16 barreleye bmc_update.py[753]: ERROR: Device mtd5 is mounted, image-bmc is busy.
> Sep 17 05:06:16 barreleye phosphor-gevent[854]: ::c053:a2b6:8e91:f402%1188661576 - - [2016-09-17 05:06:16] "POST /org/openbmc/control/flash/bmc/action/update HTTP/1.1" 200 169 5.046002
> 

Per a recent email of mine, I believe we must first do this during the code update process:
- Perform a POST to invoke the PrepareForUpdate method of the /flash/bmc object:

**Comment by mdmillerii** [comment]
@geissonator You are correct to do the update online the `PrepareForUpdate` needs to be invoked.   To avoid the update being attempted on the way down at reboot when `PrepareForUpdate` is invoked, call the `Abort` method to remove the pending update.

**Comment by gkeishin** [comment]
@geissonator  The sensor boot method is called because of the BMC poweroff , this can be avoided using the existing keyword "Initiate Power Off" in utils  which issues poweroff and checks the power /org/openbmc/control/chassis0/  if its off or on.. this should be the right choice in this case

As for the PrepareForUpdate, is this need to be done prior to activating the update ? and this would change the Update status from Idle to progress
Response code:200, Content:{
  "data": {
    "auto_apply": 0,
    "clear_persistent_files": 0,
    "filename": "/tmp/flashimg",
    "preserve_network_settings": 1,
    "restore_application_defaults": 0,
    "status": "Switch to update mode in progress",
    "update_kernel_and_apps": 0
  },
  "message": "200 OK",
  "status": "ok"
}
