### ISSUE TITLE
CT failing due to ssh issue

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1320]
CT failing due to SSH issue. 

May be CI putting system in bad state, I guess.
To make CT run, We have to do BMC reboot. 

Kindly investigate with the data what I had slacked you.

**Comment by sivassrr** [comment]
CT failing due to "**ERROR** The prior SSH command returned a non-zero return code:"

**Comment by gkeishin** [comment]
Please re-open if we see this ahead.
