### ISSUE TITLE
[Barreleye VERSION_ID="v1.99.0-131-ga81f31c-dirty"] BMC did not reset when HOST OS is hung after performing checkstop sensor operation on HOST OS

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#133]
Explanation of the issue:
BMC did not reset when HOST OS is hung after performing checkstop sensor operation on HOST OS

Expected Behavior:

BMC resets the system if the OS is hung.

root@barreleye:~#  ps | grep host
  687 root       0:01 /usr/sbin/host_checkstop.exe
  691 root       0:05 /usr/sbin/host_watchdog.exe
  787 root       0:04 /usr/sbin/control_host.exe
 1781 root       0:02 /usr/sbin/dropbear -i -r /etc/dropbear/dropbear_rsa_host_key -B
 2037 root       0:04 /usr/sbin/dropbear -i -r /etc/dropbear/dropbear_rsa_host_key -B
 2045 root       0:04 /usr/sbin/dropbear -i -r /etc/dropbear/dropbear_rsa_host_key -B
 2159 root       0:00 grep host

Actual Behavior:

1. BMC HOST OS did not ping even after 5 minutes

2. To Bring HOST OS up i tried to power off and on the system through BMC openbmutil commands

   and then the HOST OS started running

Recreations Steps:

1. At BMC HOST_BOOTED state. Inject an unrecoverable error to the processor core from the HOST OS

sudo /home/ibm/skiboot/external/xscom-utils/putscom -c 0x0 0x1d01080D 0x0A00000000000000

2. HOS OS goes down

3. Through BMC obmc-console-client observe that BMC resets and HOST OS comes to operating

Specifications:

root@barreleye:~# cat /etc/version
20160926091605
root@barreleye:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-131"
VERSION_ID="v1.99.0-131-ga81f31c-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-131"
BUILD_ID="v1.99.0"

FFDC attached
[client_console_logs.txt](https://github.com/openbmc/openbmc-test-automation/files/496391/client_console_logs.txt)

**Comment by sivassrr** [comment]
Issue moved to [openbmc/openbmc #603](https://github.com/openbmc/openbmc/issues/603) via [**ZenHub**](https://www.zenhub.com/)
