### ISSUE TITLE
FFDC for network testing on Host OS

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1332]
- [x] Collect FFDC needed for failure

Needed for https://gerrit.openbmc-project.xyz/#/c/10086/

@onye1 Take a look what data it needs like dmesg or host journald on link failure..

**Comment by gkeishin** [comment]
Probably u can use this existing keyword for it 

```
FFDC On Test Case Fail
```

**Comment by onye1** [comment]
@gkeishin I'll add error collection in the next commit.

**Comment by onye1** [comment]
I'm not sure the would show up there but I was looking at collect BMC logs.

**Comment by gkeishin** [comment]
Current FFDC infrastructure does the collection. if needed use case latter we can enhance
