### ISSUE TITLE
Run script using python -m robot option

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1337]
Thinking https://github.com/openbmc/openbmc-build-scripts/blob/master/scripts/run-robot.sh#L23
ROBOT_TEST_CMD=${ROBOT_TEST_CMD:-"tox -e ${MACHINE} -- --argumentfile test_lists/QEMU_CI tests"}

to
ROBOT_TEST_CMD=${ROBOT_TEST_CMD:-"python -m robot  --argumentfile test_lists/QEMU_CI tests"}
Strictly speaking since we don't use the Model data anymore.. we can leave the MACHINE type there..
scripts/run-robot.sh:23
```ROBOT_TEST_CMD=${ROBOT_TEST_CMD:-"tox -e ${MACHINE} -- --argumentfile test_lists/QEMU_CI tests"}```
openbmc/openbmc-build-scriptsAdded by GitHub

so that once installed, it doesn't need to update those packages again and again via tox

**Comment by sivassrr** [comment]
This will help us to see the progress in our CT environment.
