### ISSUE TITLE
Enhancement:FFDC log collection for manual test

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#134]
Predominantly we will be running automated test cases and we collect FFDC automatically on failure. 
But sometime we do manual test as well. For eg. Pre-automation, When we execute manually some of the TCs and we found functionality is failing.  

In recent scenario of checkstop handling, We have to do manually and found it failing. That time we found that FFDC collection for manual will be helpful. Hence opening it.

**Comment by gkeishin** [comment]
This in fact a good idea to do so. Make a whole lot of sense as well.

**Comment by gkeishin** [comment]
add a code.. there in gerrit.. take a look @sivassrr
