### ISSUE TITLE
[Barreleye VERSION_ID="v1.99.0-131-ga81f31c-dirty"] Unknown Gard records on OS are created repeatedly even after clearing gards and boot to OS

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#135]
Explanation of the issue:

Unknown Gard records on OS are created repeatedly even after clearing gards and boot to OS
Expected Behavior:

Gard records should not be created after clearing gard records on HOST OS and reboot to OS
Actual Behavior:

Unknown Gard records on OS are created repeatedly even after clearing gards and boot to OS

Recreations Steps:

1. When BMC is in HOST_BOOTED state. clear gard records and reboot the OS
2. when the HOST OS is running . Then check gard records
3. Make sure no gard records are created

Log Info:

1. Gard records initially seen and clearing gard records at BMC runtime state

ibm@beye5:~$  sudo /home/ibm/skiboot/external/gard/gard list
[sudo] password for ibm:
|    ID    |   Error  | Type            |
+---------------------------------------+
| 00000001 | 9000029b | physical        |
| 00000002 | 9000029b | physical        |
+=======================================+

ibm@beye5:~$ sudo /home/ibm/skiboot/external/gard/gard clear all
Clearing the entire gard partition...done

2. Gard records observed when HOST OS is booted again

ibm@beye5:~$ sudo /home/ibm/skiboot/external/gard/gard list
[sudo] password for ibm:
|    ID    |   Error  | Type            |
+---------------------------------------+
| 00000001 | 900003a5 | physical        |
| 00000002 | 900003a5 | physical        |
+=======================================+
ibm@beye5:~$

Specifications:

root@barreleye:~# cat /etc/version
20160926091605
root@barreleye:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-131"
VERSION_ID="v1.99.0-131-ga81f31c-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-131"
BUILD_ID="v1.99.0

FFDC attached
[OBM_HOST_GARD_ISSUE.zip](https://github.com/openbmc/openbmc-test-automation/files/497206/OBM_HOST_GARD_ISSUE.zip)
[barraleye_client_console_logs.txt](https://github.com/openbmc/openbmc-test-automation/files/497208/barraleye_client_console_logs.txt)

**Comment by sivassrr** [comment]
Issue moved to [openbmc/openbmc #602](https://github.com/openbmc/openbmc/issues/602) via [**ZenHub**](https://www.zenhub.com/)
