### ISSUE TITLE
Do not run test cases that modify mac address

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#136]
We've been dealing with intermittent network issues for months now on our systems.  When the network expert got on our system last night to debug, he noticed 2 systems had the same mac address!  This can wreck havoc on the network.

I see tests out in tests/test_networkd.robot that modify the mac address.  These should probably just be deleted, but at least moved to extended.

In fact, until we get some network stability, I think we should move the entire network test bucket out to extended.  I think some of the error paths with gateway's and such could be causing other issue we're seeing.

**Comment by gkeishin** [comment]
I'm on it..
