### ISSUE TITLE
CI smoke test for STC test 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1360]
- [x] A small test bucket to run for newer changes under systest
- [x] A 15-30 minutes run
- [x] Run on every commits pushed

**Comment by gkeishin** [comment]
```
$ cat test_lists/SYSTEST_CI
-i Hard_Bootme_Test
-i Processor_Speed_Check
-i Test_IO_Adapters_EEH
-i Test_EEH_Operation
-i Reboot_OS_And_Verify_uCode_Update
```
Propose list

**Comment by ssombar** [comment]
similar to issue 1287 I think.   We can cancel that one

**Comment by gkeishin** [comment]
We will still need #1287 for the job to run. This is more of a grouping for the 1287 to run on it..

**Comment by gkeishin** [comment]
Maybe @onye1 you can use this as a placeholder  to start with on the CI and CT runs
