### ISSUE TITLE
[ Automation ] Fix Network MAC address test case

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#137]
Right now the MAC address use case is moved to extended however those test case are static and needs to be fix.

Place holder for next sprint to fix those use cases..

reference : https://github.com/openbmc/openbmc-test-automation/issues/136

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc/issues/622

**Comment by sivassrr** [comment]
Please revisit this TCs as discussed. Run with latest official release driver and verify we need to fix it.

**Comment by gkeishin** [comment]
Fixing new xyz codes.. so this no longer valid for org
