### ISSUE TITLE
Create generalized variables for the various OSes 

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#1377]
Need a set of generic variables (or keywords) which would facilitate usage of OS-specific commands without regard to a particular OS.   This could perhaps be a collection of  keyname-command pairs,  which map a keyname to an OS-specific command.     Use a different collection set for each OS.

**Comment by ssombar** [comment]
From George Keishing:
There are two ways we can implement the variables
1. Class variable and load them when called
2.  The above example just a normal py variables which we can use to indexThe class way are good if there are methods and classes across needs it.. but not in this context we simply need a table type variable flat file for test to use..
So we dont want the instances in this context of the flow .. so 2) is the better option here

**Comment by gkeishin** [comment]
@ssombar any better method to do so here..

**Comment by ssombar** [comment]
hmmm do we still need this?

**Comment by gkeishin** [comment]
Yeah for Ubuntu and RHEL those commands we execute. If you feel it's not needed, we can close this one up.

**Comment by gkeishin** [comment]
Discussed with @ssombar and we feel we no longer need this now. We may address it in different method ahead.
