### ISSUE TITLE
io_board inventory url related test case are failing for Palmetto as the url now does not exist

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#138]
io_board inventory url(/org/openbmc/inventory/system/chassis/io_board) seem to be removed from Palmetto. If we tried to do enumerate also we dont see. 

rahulmah@rackspace:~$ curl -c cjar -b cjar -k https://Palmetto_BMC_IP/org/openbmc/inventory/system/chassis/io_board
{
  "data": {
    "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /org/openbmc/inventory/system/chassis/io_board"
  },
  "message": "404 Not Found",
  "status": "error"
}rahulmah@rackspace:~$

Same problem is not seen with Barreleye as same url is still accesible in Barreleye. 

rahulmah@rackspace:~$ curl -c cjar -b cjar -k https://Barreleye_IP/org/openbmc/inventory/system/chassis/io_board
{
  "data": {
    "Custom Field 1": "Rackspace US, Inc.",
    "Custom Field 2": "00016C800278",
    "Custom Field 3": "",
    "Custom Field 4": "",
    "Custom Field 5": "",
    "Custom Field 6": "",
    "Custom Field 7": "",
    "Custom Field 8": "",
    "FRU File ID": "FRU Ver 0.01",
    "Manufacturer": "INGRASYS",
    "Name": "BARRELEYE IO Board",
    "Part Number": "10010VU00-600-G",
    "Serial Number": "10010VU00X1571001",
    "fault": "False",
    "fru_type": "DAUGHTER_CARD",
    "is_fru": 1,
    "present": "True",
    "version": ""
  },
  "message": "200 OK",
  "status": "ok"

Due to this below two test cases are failing in automation run for Palmetto. 

io_board Present                                                      URI:https://xx.xx.xx.xx/org/openbmc/inventory/system/chassis/io_board/attr/present, method:Get, args:{}
Response code:404, Content:{
  "data": {
    "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /org/openbmc/inventory/system/chassis/io_board"
  },
  "message": "404 Not Found",
  "status": "error"
}
.F
FFDC Collection Started         : 20160929064025010563
FFDC Collection Completed       : 20160929064041651994
io_board Present                                                      | FAIL |
{u'description': u'org.freedesktop.DBus.Error.FileNotFound: path or object not found: /org/openbmc/inventory/system/chassis/io_board'} != True
------------------------------------------------------------------------------
io_board Fault                                                        URI:https://xx.xx.xx.xx/org/openbmc/inventory/system/chassis/io_board/attr/fault, method:Get, args:{}
Response code:404, Content:{
  "data": {
    "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /org/openbmc/inventory/system/chassis/io_board"
  },
  "message": "404 Not Found",
  "status": "error"
}
.F
FFDC Collection Started         : 20160929064042160513
FFDC Collection Completed       : 20160929064059081686

**Comment by spinler** [comment]
Palmetto doesn't have an IO Board.  Neither does Firestone/Witherspoon/Garrison/Habanero.

**Comment by rahulmah** [comment]
Okay then we have to skip this test case in our framework. I will close this once we drop code to skip this test in our automation.

**Comment by rahulmah** [comment]
Skipped IO board related test case in our framework for palmetto. Code integrated.
