### ISSUE TITLE
PreTag 0.8 Testing failure for 'user/group authentication'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#14]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/290)

6 failures, I am using one issue to resolve all

Create and delete user with user group name
Full Name: 	Tests.Test User.Create and delete user with user group name
Documentation: 	

**GOOD PATH** This testcase is for testing user creation with user name, password, comment and group name(user group) in open bmc.
Start / End / Elapsed: 	20160519 15:28:31.740 / 20160519 15:28:40.484 / 00:00:08.744
Status: 	FAIL (critical)
Message: 	Authentication failed for user 'HuHkThIS'.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Create multiple users
Full Name: 	Tests.Test User.Create multiple users
Documentation: 	

**GOOD PATH** This testcase is to verify that multiple users creation in open bmc.
Start / End / Elapsed: 	20160519 15:28:40.484 / 20160519 15:28:48.145 / 00:00:07.661
Status: 	FAIL (critical)
Message: 	Authentication failed for user 'mrnviL4h'.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Create and delete user without password
Full Name: 	Tests.Test User.Create and delete user without password
Documentation: 	

**GOOD PATH** This testcase is to create and delete a user without password in open bmc.
Start / End / Elapsed: 	20160519 15:28:48.146 / 20160519 15:28:57.151 / 00:00:09.005
Status: 	FAIL (critical)
Message: 	Authentication failed for user 'nxeznfvp'.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Set password for existing user
Full Name: 	Tests.Test User.Set password for existing user
Documentation: 	

**GOOD PATH** This testcase is for testing password set for user in open bmc.
Start / End / Elapsed: 	20160519 15:28:57.152 / 20160519 15:29:04.658 / 00:00:07.506
Status: 	FAIL (critical)
Message: 	Authentication failed for user 'BaToCj2H'.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Set password with empty password for existing
Full Name: 	Tests.Test User.Set password with empty password for existing
Documentation: 	

**GOOD PATH** This testcase is to verify that empty password can be set for a existing user.
Start / End / Elapsed: 	20160519 15:29:04.658 / 20160519 15:29:12.031 / 00:00:07.373
Status: 	FAIL (critical)
Message: 	Authentication failed for user '6mm7Lxrk'.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


---

@rahulmah commented on [Tue Jun 14 2016](https://github.com/openbmc/openbmc/issues/290#issuecomment-225869533)

@hramasub : Please provide update on this issue.

**Comment by gkeishin** [comment]
This I took a look at it..  the mailing list documentation of how the user are added seems to be correct however when talked to the owner, looks like we need to revisit the implementation test cases... Will update post discussion tomorrow..

**Comment by gkeishin** [comment]
All of the test are failing here in user create/delete 

Here is a debug example:

Create and delete user without groupname :: ***GOOD PATH*** 

Username: KIGKGJ7Y
Password: qtc1mRwD
comment: BMzxRXk8

Authentication failed for user 'KIGKGJ7Y'.

 SSHLibrary . Login ${username}, ${password}
Documentation: 	

Logs into the SSH server with the given `username` and `password`.
Start / End / Elapsed: 	20160915 22:23:32.349 / 20160915 22:23:36.259 / 00:00:03.910
22:23:32.349 	INFO 	Logging into '9.3.29.119:22' as 'KIGKGJ7Y'. 	
22:23:36.258 	FAIL 	Authentication failed for user 'KIGKGJ7Y'.



ON BMC

root@barreleye:~# cat /etc/passwd | tail -1
KIGKGJ7Y: x:1041:1041:BMzxRXk8:/home/KIGKGJ7Y:NB
root@barreleye:~#

root@barreleye:~# cat /etc/shadow | tail -1
KIGKGJ7Y:$6$Bh0moQyeU$BLhfn7Zof1yReY166Wfn6I0Ukg.gG2cE4s74GcteknnFQvrsmHz2eV1e84L78haV4mxWq/6F4W6wk8EgR3wkM0:17053:0:99999:7:::
root@barreleye:~#
 
 root@barreleye:~# cat /etc/gshadow | tail -1
KIGKGJ7Y:!::
root@barreleye:~#

**Comment by gkeishin** [comment]
Discussing with @hramasub  to figure out the issue.. This is becoming a problem for the test run.. Will need to address this base functionality supported..

**Comment by gkeishin** [comment]
@rahulmah This is a code bug .. please refer to https://github.com/openbmc/openbmc/issues/581

You can close this...

**Comment by gkeishin** [comment]
Made the code change in obmc-phosphor-userd for user add and change pasword and patched onto the BMC .. and it working good..

------------------------------------------------------------------------------
Test User :: This suite is for testing Open BMC user account manag... | PASS |
12 critical tests, 12 passed, 0 failed
12 tests total, 12 passed, 0 failed

**Comment by rahulmah** [comment]
@williamspatrick : Please close this issue. It seem to be fixed. I can not close this issue from my side.
