### ISSUE TITLE
OpenBMC:Witherspoon:SNMP- Multiple SNMP manager

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1409]
Configure multiple SNMP managers using list

**Comment by kantvijay** [comment]
@prkatti1 :  Please provide more info and set the clear expectation

**Comment by prkatti1** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/11142/9/snmp/test_bmc_snmp_config.robot
Line# 81

**Comment by kantvijay** [comment]
@rahulmah :  Please explain your comments in https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/11142/9/snmp/test_bmc_snmp_config.robot
