### ISSUE TITLE
Host Time REST update failure

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1413]
To JSON using : content={ "data": { "description": "Failed to convert 1487304700000000 to type t" }, "message": "403 Forbidden", "status": "error" } 

@rahulmah  if you manually try also it will throw the same error.. Please check on the Host setting policy for time. Thanks

**Comment by gkeishin** [comment]
Thanks @mine260309 https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-rest-server/+/11462/ is merged.. @rahulmah can we fix this one up.. since we are seeing those in the tests for time. Thanks

**Comment by mine260309** [comment]
@gkeishin This is part of the change.
Eventually time manager will throw more proper errors (https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/11479/) which is not merged yet.

I would suggest wait for that changes and then update the tests.

**Comment by gkeishin** [comment]
Sure then @mine260309

**Comment by rahulmah** [comment]
Fix checked in - https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/12514/

**Comment by gkeishin** [comment]
Great. Thanks @rahulmah for the changes. Please take a look at above code change @mine260309

**Comment by rahulmah** [comment]
@mine260309 : Do you have issue for LinkTimeOptimization? I am seeing that we are now getting proper error response while setting BMC and HOST time in required cases. But I am also seeing that, just after BMC /HOST set request failure, I am getting next consecutive get BMC time request failing with 404. From journal, I see below messages while failure is seen. ```Sep 06 09:14:27 witherspoon systemd[1]: Started SSH Per-Connection Server (9.3.62.216:42922).
Sep 06 09:14:37 witherspoon systemd[1]: Attaching egress BPF program to cgroup /sys/fs/cgroup/unified/system.slice/systemd-timedated.service failed: Invalid argument
Sep 06 09:14:37 witherspoon systemd[1]: Starting Time & Date Service...
Sep 06 09:14:37 witherspoon systemd-timedated[3023]: /etc/localtime should be a symbolic link to a time zone data file in /usr/share/zoneinfo/.
Sep 06 09:14:37 witherspoon systemd[1]: Started Time & Date Service.
Sep 06 09:14:39 witherspoon systemd[1]: xyz.openbmc_project.Time.Manager.service: Service hold-off time over, scheduling restart.
Sep 06 09:14:39 witherspoon systemd[1]: xyz.openbmc_project.Time.Manager.service: Scheduled restart job, restart counter is at 12.
Sep 06 09:14:39 witherspoon systemd[1]: Stopped Phosphor Time Manager daemon.
Sep 06 09:14:39 witherspoon systemd[1]: Starting Phosphor Time Manager daemon...
Sep 06 09:14:39 witherspoon systemd[1]: Started Phosphor Time Manager daemon.
Sep 06 09:15:03 witherspoon systemd-journald[737]: Forwarding to syslog missed 10 messages.```

**Comment by mine260309** [comment]
@rahulmah The phosphor-dbus-interfaces are changed, but the phosphor-time-manager's changes are not merged yet, so you are getting the issue.

**Comment by gkeishin** [comment]
So we would still need this @mine260309  https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-time-manager/+/11480/ right to have fully working one?

**Comment by gkeishin** [comment]
Merging it. Since its broken now also. when the new code comes in, we will be ready for it.
