### ISSUE TITLE
To fix the memory name and device type

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1422]
This is follow up the issue https://github.com/openbmc/openbmc-test-automation/issues/1411

We need to fix it. Planning to give this to Kaushik Venkatesh. Unfortunately not able to assign him. 
Last week, found his id in openbmc.  May be he need to get access to openbmc-test-automation repo, I guess.

**Comment by sivassrr** [comment]
- [ ] Need to fix the memory name and device type test cases

- [ ] remove skip test cases - what checked-in in #1411

**Comment by sivassrr** [comment]
Not able to assign this to @arpanamd

**Comment by arpanamd** [comment]
I am able to comment

**Comment by gkeishin** [comment]
This task is done.. closing
