### ISSUE TITLE
Security vulnerability testing- Qualys & AppScan

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1439]
### Testing when IPMI is enabled
- **Security vulnerability testing- Qualys**
   - [x] VM testing (2)
 - **Security vulnerability testing- Appscan**
    - [x] Full web vulnerability testing (2)

### Testing when IPMI is disabled
- **Security vulnerability testing- Qualys**
   - [ ] VM testing (2)
 - **Security vulnerability testing- Appscan**
    - [ ] Full web vulnerability testing (2)

**Comment by ratagupt** [comment]
Looks good to me.

**Comment by prkatti1** [comment]
Tools version:

Qualys applications:
Application Version:8.15.1.0-3
Online Help Version:8.15.36-1
SCAP Module Version:1.2

Appscan: Version 9.0.3

**Comment by prkatti1** [comment]
Closing this as these are executed.
