### ISSUE TITLE
Security vulnerability testing- Nessus & NMAP

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1440]
### 1. Security testing when IPMI is enabled
- **Security vulnerability testing- Nessus**
 - [x] Port scanning (2)
- [x] Application scanning (2)
- [x] Vulnerability testing (2)
- **Security testing- NMAP**
 - [x] Port scanning (2)
- [x] App scanning (2)

### 2. Security testing when IPMI is disabled
- **Security vulnerability testing- Nessus**
- [ ] Port scanning (2)
- [ ] Application scanning (2)
- [ ] Vulnerability testing (2)
- **Security testing- NMAP**
- [ ] Port scanning (2)
- [ ] App scanning (2)

**Comment by ratagupt** [comment]
Looks good to me.

**Comment by prkatti1** [comment]
Tools versions:
Nessus Version: 7.1.3 (#120) LINUX
NMAP: Zenmap 7.70

**Comment by prkatti1** [comment]
Closing this as these are executed.
