### ISSUE TITLE
IPMI disable network provisioning and Cipher support testing

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1441]
Test Plan: 

`IPMI enable/disable:`

- [x] Verify enabling IPMI via Host
- [x] Verify disabling IPMI via Host
- [x] Verify disabling IPMI via out of band

`IPMI encrypted sessions:` https://github.com/openbmc/openbmc-test-automation/issues/1447

- [x]  Verify IPMI function with Cipher suite 17 and 3
- [x]  Verify IPMI non-supported Cipher suites
- [x] Verify supported cipher suites from IPMI lan print
- [x] Verify cipher using "channel getciphers ipmi" command.

`BMC reset`
- [x] IPMI disable and reset BMC - Setting shouldn't flip back to enabled, else it exposes IPMI security vulnerability on every code update

`Code update`
- [x] IPMI disable and code update - Setting shouldn't flip back to enabled, else it exposes IPMI security vulnerability on every code update

**Comment by dkodihal** [comment]
@tomjoseph83 looks good to you?

**Comment by gkeishin** [comment]
- [x] Verify IPMI function with Cipher suite 17 and 3
- [x] Verify IPMI non-supported Cipher suites
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/12199/
Code merged

- [ ] Verify supported cipher suites from IPMI lan print,  @rahulmah did we plan to do this.

**Comment by rahulmah** [comment]
@gkeishin : Yes we have planned to test "supported cipher suites from IPMI lan print". Currently it's under development but I have stated to do parallel automation for the same for it.

**Comment by gkeishin** [comment]
We are doing very good progress here.. Thanks, @rahulmah for keeping on top of the things.

**Comment by gkeishin** [comment]
We can sign this off since the firmware and test code are in. @rahulmah
