### ISSUE TITLE
SSL certificate upload testing

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1442]
`Test planned`
- [ ] Verify REST API upload for a certificate
- [ ] Install valid certificate fo HTTPS server and verify
- [ ] Install valid certificate fo LDAP server and verify
- [ ] Delete installed certificate
- [ ] Install invalid certificate and verify
- [x] Verify expired certificate: @ojayanth informed, currently not planned,
- [ ] Verify certificate persistence after BMC code update.
- [ ] Verify certificate clean up after factory reset.

**Comment by gkeishin** [comment]
Readme - https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/11840/
Install certificates - https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/11912/

**Comment by ojayanth** [comment]
@gkeishin Initial version code doesn't support certificate expiry date specific check .
- Add test cases specific to https server and LDAP client certificate installation.
- Add  certificate delete specfic test case.

**Comment by rahulmah** [comment]
@gkeishin : We also need to add below test cases. Jayanth has suggested them. All other look fine to him.
- [ ] Verify certificate persistence after BMC code update.
- [ ] Verify certificate clean up after factory reset.

**Comment by gkeishin** [comment]
Tracked newly under https://github.com/openbmc/openbmc-test-automation/issues/1461
