### ISSUE TITLE
OpenBMC GUI deliverables Testing and Regression run

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1446]
`Test Plan`
- [x]  Verify Setting the power cap  - @ssombar 
- [x]  Verify Date Time management - @rahulmah 
- [x] Verify SNP Read ONLY- @prkatti1 
- [x] Full GUI regression Testing - @rahulmah 

@gtmills  Counterpart Developer to sync up on this.

**Comment by gtmills** [comment]
Also would like a general regression test on the GUI. :) 
Thanks!!

**Comment by gkeishin** [comment]
@rahulmah is doing regressing testing.
