### ISSUE TITLE
XYZ Network: Add network validation scenarios which got fixed

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1457]
Remove network test cases which got fixed from the skip lists and add them to regular bucket.
# TODO: Configure invalid IP address use cases.
-e Configure_Broadcast_IP
-e Configure_Multicast_IP
-e Configure_Loopback_IP
-e Configure_Network_ID
# TODO: Invalid gateway address configuration.
-e Configure_Invalid_Gateway_String
-e Configure_Out_Of_Range_IP_For_Gateway
-e Configure_Broadcast_IP_For_Gateway
-e Configure_Loopback_IP_For_Gateway
-e Configure_Multicast_IP_For_Gateway
-e Configure_Network_ID_For_Gateway
-e Configure_Less_Octet_IP_For_Gateway
-e Configure_Hexadecimal_IP_For_Gateway
-e Configure_Special_Char_IP_For_Gateway

**Comment by prkatti1** [comment]
Already done it. So closing this issue.

**Comment by gkeishin** [comment]
no longer valid
