### ISSUE TITLE
add logging test to Open BMC tool testing

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#1467]
Add testing of the remote logging capabilities of openbmctool.py to test_openbmctool.robot.
See related issue  "Open BMC tool test" https://github.com/openbmc/openbmc-test-automation/issues/1303

**Comment by gkeishin** [comment]
Good work there with tools. automation.

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/13797
