### ISSUE TITLE
add local_users testing to openbmctool test code

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#1472]
Add automated testing of _local_users_ function    `queryenabled` of openbmctool.py.

**Comment by gkeishin** [comment]
any update on this one there @ssombar

**Comment by ssombar** [comment]
Adding a test of openbmctool's  `local_users queryenabled` function.  The other `local_users` tests (namely `disableall` and `enableall`) will require LDAP.   Those will be tested under a separate issue where we will test those two functions as part of testing openbmctool's LDAP functions.

**Comment by gkeishin** [comment]
Oh yeah.. let's not code it then, it will make thing complicated in the tool..

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/16580
