### ISSUE TITLE
Split lib/utils.robot codes 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1487]
split lib/utils.robot   into   lib/utils.robot  and lib/common_utils.robot
The propose new:

> lib/utils.robot  - Should ONLY have variables and keywords which is using REST
> lib/common_utils.robot - Should NOT contain variable and keywords for REST

**Comment by sivassrr** [comment]
Is this work really important now, how it helps?
Are we going to rename utils.robot to some thing new now, what is the difference between common_utils.robot. If we are planning for Redfish, can we have some thing new. Just wanted to understand this.

**Comment by gkeishin** [comment]
This is to avoid dependencies between phosphor REST vs redfish.. since we are doing changes for redfish without messing the existing one to migrate,

**Comment by ssombar** [comment]
lib/utils.robot   will import   
   Resource     common_utils.robot
so that test cases using utils.robot will not break.

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/16431
