### ISSUE TITLE
Remove dual slashes in URLs of OpenBMC test cases

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#1492]
From Matt:  Can you fix the testcase that has these double slashes?
```Get To Stable State :: BMC cleanup drive to stable state      URI:https://x.x.x.x:443/xyz/openbmc_project/state/bmc0//attr/CurrentBMCState, method:Get, args:{}```

**Comment by ssombar** [comment]
From Matt:  Can you fix the testcase that has these double slashes?
```Get To Stable State :: BMC cleanup drive to stable state      URI:https://x.x.x.x:443/xyz/openbmc_project/state/bmc0//attr/CurrentBMCState, method:Get, args:{}```

**Comment by gkeishin** [comment]
Take a look at `Read Attribute`   

In rest_client.robot
```
${resp}=  OpenBMC Get Request  ${uri}/attr/${attr}  timeout=${timeout}
    ...  quiet=${quiet}
```
To
```
${resp}=  OpenBMC Get Request  ${uri}attr/${attr}  timeout=${timeout}
    ...  quiet=${quiet}
```
But it will break other places due to inconsistent URI passing..

**Comment by ssombar** [comment]
Awesome!  yes, I'm sure you found it.   Trying a CT regression test with that change to see what breaks.
