### ISSUE TITLE
BMC web master regression test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1496]
- [x] RAS @SrideviRamesh 
- [x] GUI @rahulmah 
- [x] Security @sivassrr  
- [x] CI / CT / other testing @gkeishin 
- [x] Network  @prkatti1 @gkeishin 
- [x] SNMP @prkatti1 @gkeishin

**Comment by rahulmah** [comment]
@gkeishin : GUI stories for automation: 

Server overview menu automation - https://github.com/openbmc/openbmc-test-automation/issues/1514
Server health automation - https://github.com/openbmc/openbmc-test-automation/issues/1515
Server control menu automation - https://github.com/openbmc/openbmc-test-automation/issues/1516
Server configuration menu automation - https://github.com/openbmc/openbmc-test-automation/issues/1517
User menu automation - https://github.com/openbmc/openbmc-test-automation/issues/1518
Header menu automation - https://github.com/openbmc/openbmc-test-automation/issues/1519

**Comment by gkeishin** [comment]
- [x] Network @prkatti1 This needs to be run the automated tests once the bmcweb is built in Master and complete the task.

**Comment by gkeishin** [comment]
@rahulmah @prkatti1 @sivassrr @SrideviRamesh can u guys run the existing test to see if nothing is broken and report.. If all is well, we close this story .

**Comment by gkeishin** [comment]
SNMP and NW automated one's run came clean..

**Comment by gkeishin** [comment]
@SrideviRamesh ran the existing RAS, see automation bug and fixed up.. there are BMC dump not getting generated errors but that can be tracked in Master testing

**Comment by gkeishin** [comment]
Awaiting GUI test result from @rahulmah and we will close this

**Comment by gkeishin** [comment]
@sivassrr @rahulmah test also came in.. look good there. Closing this
