### ISSUE TITLE
PreTag 0.8 Testing failure for 'Get OCC Status'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#15]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/288)

Get OCC status
Full Name:  Tests.Test Occ Powercap.Get OCC status
Documentation:  

This testcase is to test the OCCstatus for the system is Enabled or not
Start / End / Elapsed:  20160519 15:24:54.197 / 20160519 15:24:57.960 / 00:00:03.763
Status:     FAIL (critical)
Message:     != Enabled

---

@anoo1 commented on [Mon May 23 2016](https://github.com/openbmc/openbmc/issues/288#issuecomment-221069592)

The powercap should be available and working through the sensors. Perhaps the test case is looking at the settings file. @rahulmah could you take a look?

**Comment by sivassrr** [comment]
Found Get OCC status passes fine in Palmetto for 9 times except the last time where BMC failed to power on. (Check wiki for Palmetto logs).
