### ISSUE TITLE
Network: IPv4 configurations and verification

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1505]
Gateway configuration and verification
Netmask configuration and verification

**Comment by gkeishin** [comment]
You ll use this to write libraries and GOOD path scenarios.

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18014/ 
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18070/

**Comment by gkeishin** [comment]
split sub task https://github.com/openbmc/openbmc-test-automation/issues/1674

**Comment by gkeishin** [comment]
Remaining IPv4 test cases.  approx 20+ test case

**Comment by gkeishin** [comment]
- [x] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/22835/

**Comment by gkeishin** [comment]
- [x] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/22605/

**Comment by gkeishin** [comment]
9 TC pending
