### ISSUE TITLE
Network: MAC address testing and automation

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1506]
MAC address testing and automation

**Comment by gkeishin** [comment]
Burned 3 points using https://github.com/openbmc/openbmc-test-automation/issues/1504

**Comment by gkeishin** [comment]
sub task https://github.com/openbmc/openbmc-test-automation/issues/1680

**Comment by prkatti1** [comment]
Testing and automation done, closing this.
