### ISSUE TITLE
Network: Validation scenarios, hostname

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1509]
IP validation scenarios
Gateway validation scenarios & netmask validation scenarios
hostname testing
DNS testing

**Comment by gkeishin** [comment]
@prkatti1 please use this task to complete the remaining

**Comment by prkatti1** [comment]
This is addressed @ https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/23864

**Comment by gkeishin** [comment]
Code merged
