### ISSUE TITLE
[Automation]  Test case results into info database

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#151]
The test case results needed to be captured for analysis, reporting and statistical importance.

**Comment by sivassrr** [comment]
@gkeishin Feel free to reestimate.

**Comment by gkeishin** [comment]
This needs to be done in two prong approach.

1. Utilize the test_history logging ( need to update in the format database field needs)
2.  Parser to parse this result output and upload to database.

**Comment by gkeishin** [comment]
This code is already merged..  Closing..
