### ISSUE TITLE
[Automation]  SOL failure in test case run

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#152]
Today when the SOL fails to opens 
https://github.com/openbmc/openbmc/issues/658

the poweron test also fails.

There are two ways we can deal with this
1. If SOL logging fails yes the test fails or have a separate test case for SOL testing ( In plan )
2. For power on  Ignore the  SOL failure..

**Comment by sivassrr** [comment]
gkeishin will vote for 1. If SOL logging fails yes the test fails or have a separate test case for SOL testing ( In plan )
