### ISSUE TITLE
Redfish LDAP Test Plan (Extra if any)

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1520]
Already existing test plan, use this to extra use case above it if there is any.

**Comment by sivassrr** [comment]
- [ ]  Identify and list all test cases - Config, Login with LDAP user, Check for privilege activities

- [ ]  Update  test plan with Redfish API / curl commands

**Comment by sivassrr** [comment]
Basic Requirements: - Below requirements needed before executing any LDAP test cases. 
```
(1) 

Base   Steps:  Break the firewall between LDAP   server and BMC   telnet   command:   telnet   <IP address of LDAP server >

(2) 

Update   LDAP server IP and host name details in /etc/hosts of BMC   Sample   output of LDAP /etc/hosts

3) 

Check No   LDAP Config exists – Before creating LDAP config
```

**Comment by sivassrr** [comment]
Basic Requirements for LDAP readiness check:

    Break the firewall between LDAP server and BMC telnet command: telnet

    Update LDAP server IP and host name details in /etc/hosts of BMC Sample output of LDAP /etc/hosts

    Check No LDAP Config exists – Before creating LDAP config

**Comment by sivassrr** [comment]
Create Config and LDAP Login: Non - Secured

- [ ]  Create LDAP Configuration with Redfish commands using CURL  / Automation and ensure all required LDAP parameters are provided. 

1.  LDAP IP addr
2.  LDAP Secure type: Generally if we pass the LDAP url as ldao://<ldap ip> then it is non secured mode. 
3.  LDAP Binddn
4. LDAP Basedn
5. LDAP PAssword
6. LDAP Search scope : Value could be base, sub, one
7. LDAP Server type: Value could be ADS or openldap - Openbmc supports more openldap



- [ ]  Run LDAP enumerate command and see the config exists

- [ ]  Using the LDAP user, Log into LDAP server

**Comment by sivassrr** [comment]
Create Config and LDAP Login: Secured:

- [ ] Ensure LDAP secured is running in LDAP server

- [ ]  Certificate upload : Server CA Certificate

- [ ] Certificate upload: Client Certificate

- [ ]   Create LDAP Configuration with Redfish commands using CURL / Automation and ensure all required LDAP parameters are provided.


    LDAP IP addr
    LDAP Secure type: Generally if we pass the LDAP url as ldaps:// then it is non secured mode.
    LDAP Binddn
    LDAP Basedn
    LDAP PAssword
    LDAP Search scope : Value could be base, sub, one
    LDAP Server type: Value could be ADS or openldap - Openbmc supports more openldap

- [ ] Run LDAP enumerate command and see the config exists

- [ ] Using the LDAP user, Log into LDAP server

**Comment by sivassrr** [comment]
Privilege User Verification:

- [ ]  LDAP user with priv-admin who was able to login should be able to power on / power off the system and also able to list inventory etc. 

- [ ]  LDAP user with priv-user who will have only read permission, He/She shouldnt be able to power on / power off the system

- [ ] LDAP User with priv-operator who should be able to power on / power off the system. But not able to add any new user etc.  (TBD)

**Comment by sivassrr** [comment]
Delete Group Privileges and Delete Config:

- [ ]  Ability to delete Privilege 

- [ ] Ability to delete LDAP config and it should have been cleared. - No object should be available.

**Comment by sivassrr** [comment]
Need to test with new Redfish commands and added it in existing test plan. 
Dont know about openbmctool at this time. 

- [ ] Redfish commands and update test plan - 2

- [ ] openbmc tool commands update - 2 

Considering only 2 for estimate. Once confirmation on openbmctool happens then we can include that as well.

**Comment by sivassrr** [comment]
There are few new things as of now, I am observing that need to be taken care.

- [ ] Operator role which is new when compare to old implementation using REST

- [ ]  Settings / properties like 
             LDAPSearchSettings,
             LDAPService
             PrivilegeMap
             Roles
             ServiceEnabled
              PrivilegeMap
 
- [ ] And other settings / actions which is only associate with Redfish under AccountService

**Comment by sivassrr** [comment]
Not sure whether RemoteRoleMapping will come into picture in this release or getting implemented, need to check on that.

**Comment by gkeishin** [comment]
> Not sure whether RemoteRoleMapping will come into picture in this release or getting implemented, need to check on that.
> 
> RemoteGroup, RemoteUser also need to taken care

> That's a lot of new use cases..  so we keep this open still then ? or we can close it

**Comment by sivassrr** [comment]
I believe it is not lot of new use cases except user role - operator associate with. 
All other places are kind of we need to map from REST to Redfish Schema format. 
for eg. LDAPSearchSettings is something similar to LDAP Search Scope.

**Comment by gkeishin** [comment]
Closing since its completed
