### ISSUE TITLE
Redfish(LDAP) : Testing and server setup Activity 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1521]

**Comment by sivassrr** [comment]
- [ ] Check LDAP services up and running

- [ ] Check Redfish Account services configured with LDAPServices

- [ ] Create LDAP config

- [ ] Login with LDAP 

- [ ] Repeat the same for secured LDAP 

- [ ] LDAP User Management - Privilege and role related 

- [ ]

**Comment by sivassrr** [comment]
Basic Requirements for LDAP readiness check:

- [ ] Break the firewall between LDAP   server and BMC   telnet   command:   telnet   <IP address of LDAP server >

- [ ] Update   LDAP server IP and host name details in /etc/hosts of BMC   Sample   output of LDAP /etc/hosts

- [ ] Check No   LDAP Config exists – Before creating LDAP config

**Comment by sivassrr** [comment]
Considering existing setup of ADS / openldap

- [ ] ADS - 0.5 

- [ ]  OpenLDAP - 0.5

If it is a brand new then each setup can take between 2 and 3 days.

**Comment by sivassrr** [comment]
Thank you @gkeishin for the suggestion, Added 1 more point for unknown.

**Comment by gkeishin** [comment]
Marking activity completed
