### ISSUE TITLE
Redfish(LDAP) :Configuration Test Automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1522]

**Comment by sivassrr** [comment]
- [ ] Check for LDAP services / Readiness 

- [ ] Create a separate file for LDAP config and basic login test with / without secured

- [ ] Modify LDAP config 

- [ ] Delete LDAP Config

- [ ] LDAP user management related

**Comment by gkeishin** [comment]
Partially done.. continuing automation

**Comment by gkeishin** [comment]
@sivassrr please open new task for remaining test
