### ISSUE TITLE
Witherspoon Secure boot Automation

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1527]
- [x] Test plan
- [x] Test and verify
- [ ] Automation

**Comment by lkammath** [comment]
Secure Boot test automation is divided in to following main categories

1. Basic secure boot cold IPL/warm re-ipl/Any other type of IPL/reboot scenarios with TPM enabled /disabled 
2. Basic secure boot scenarios with Jumpers moved between on and off (Physical intervention needed or we need to ask jumper automation setup to drive the jumper power, also require support for power cycling)
3. Error path scenarios by corrupting various partitions including GARD, SBE, HBB, HBE,HBI, HBRT, HB-OCC, WOFDATA,HCODE, etc (Try with TPM enabled /disabled)
4. Dev to Transition and Transition to Production Key flow testing

**Comment by lkammath** [comment]
#1 already exists partially. Major work there is to make it work and it should work seamlessly. Currently there are hiccups to start the tests
