### ISSUE TITLE
Redfish local user management

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1529]
- [x] Test plan
- [x] Test and verify
- [x] Automation

Sandhya preparing the test plan for it

Docs:
https://github.com/openbmc/docs/blob/master/user_management.md

Dev: https://github.com/ibm-openbmc/dev/issues/236

**Comment by gkeishin** [comment]
### Test Plan

*GOOD PATH*
- [ ] 1 )  Create a redfish user with admin privilege role and verify its successfully created
- [ ] 2 )  Create a redfish user with operator privilege role and verify its successfully created
- [ ] 3 )  Create a redfish user with user privilege role and verify its successfully created
- [ ] 4 )  Create a redfish user with callback privilege role and verify its successfully created
- [ ] 5 )  Create large number of users and verify the limit and system behavior and verify they are successfully created
- [ ] 6 )  Create same username with different privileges and verify it is allowed

- [ ] 7 )  Delete a redfish user with admin privilege role and verify its successfully deleted
- [ ] 8 )  Delete a redfish user with operator privilege role and verify its successfully deleted
- [ ] 9 )  Delete a redfish user with user privilege role and verify its successfully deleted
- [ ] 10)  Delete a redfish user with callback privilege role and verify its successfully deleted
- [ ] 11)  Delete a redfish user with operator / user / callback privilege by user with admin privilege and verify its successfully deleted 

*BAD PATH*
- [ ] 12)  Login with redfish user with admin privilege role with invalid password and verify it doesnt work 
- [ ] 13)  Login with redfish user with operator privilege role with invalid password  and verify it doesnt work
- [ ] 14)  Login with redfish user with user privilege role with invalid password and verify it doesnt work 
- [ ] 15)  Login with redfish user with callback privilege role with invalid password and verify it doesnt work 

- [ ] 16)  Login with redfish user with admin privilege role  and try to set min and max password lengths
- [ ] 17)  Login with redfish user with operator privilege role  and try to reboot system 

*BAD PATH*
- [ ] 18)  Login with redfish user with operator privilege role  and try to change network settings

* GOOD PATH*

- [ ] 19)  Verify user with user privilege role has only read access. 
- [ ] 20)  Login with user privilege and verify if it has read access to all the information 
- [ ] 21)  Verify callback user privilege role

- [ ] 22)  Perform code update with users with different roles.

**Comment by gkeishin** [comment]
- [ ] 1 )  Create a redfish user with admin privilege role and verify its successfully created
	A) Create a redfish user with admin privilege role
	B) Login using the created user
	C) Perform some basic operation like reading system state
	
- [ ] 2 )  Create a redfish user with operator privilege role and verify its successfully created
	A) Create a redfish user with operator privilege role
	B) Login using the created user
	C) Perform some basic operation like reading system driver
	
- [ ] 3 )  Create a redfish user with user privilege role and verify its successfully created
	A) Create a redfish user with user privilege role
	B) Login using the created user
	C) Perform some basic operation ( TBD ) 
	
- [ ] 4 )  Create a redfish user with callback privilege role and verify its successfully created
	A) Create a redfish user with callback privilege role
	B) Login using the created user
	C) Perform some basic operation ( TBD ) 
	
- [ ] 5 )  Create large number of users and verify the limit and system behavior and verify they are successfully created
	A) Create 100s of redfish users with combinational privilege roles. 
	B) Verify that all users are successfully created by logging in with them. 
	
- [ ] 6 )  Create same username with different privileges and verify it is allowed
	A) Create a redfish user with callback privilege role
	B) Login using the created user
	C) Perform some basic operation 
	D) Create a redfish user with operator privilege role with same username as callback user
	E) Login using the created user
	F) Perform some basic operation like reading memory information
	
- [ ] 7 )  Delete a redfish user with admin privilege role and verify its successfully deleted
	A) Delete a redfish user with admin privilege role
	B) Try to login after deleting the user
	C) It should report an error
	
- [ ] 8 )  Delete a redfish user with operator privilege role and verify its successfully deleted
	A) Delete a redfish user with operator privilege role
	B) Try to login after deleting the user
	C) It should report an error
	
- [ ] 9 )  Delete a redfish user with user privilege role and verify its successfully deleted
	A) Delete a redfish user with user privilege role
	B) Try to login after deleting the user
	C) It should report an error
	
- [ ] 10)  Delete a redfish user with callback privilege role and verify its successfully deleted
	A) Delete a redfish user with callback privilege role
	B) Try to login after deleting the user
	C) It should report an error
	
- [ ] 11)  Delete a redfish user with operator / user / callback privilege by user with admin privilege and verify its successfully deleted 
	A) Login with user with admin privilege role
	B) Try to delete a user with operator privilege role
	C) It should work
	D) Login with user with operator / user privilege role
	E) Try to delete a user with callback privilege role
	F) It should not work. 
	
- [ ] 12)  Login with redfish user with admin privilege role with invalid password and verify it doesnt work - bad path
	A) Login with user with admin privilege role with invalid password
	B) Login should not be successful
	
- [ ] 13)  Login with redfish user with operator privilege role with invalid password  and verify it doesnt work- bad path
	A) Login with user with operator privilege role with invalid password
	B) Login should not be successful
	
- [ ] 14)  Login with redfish user with user privilege role with invalid password and verify it doesnt work - bad path
	A) Login with user with user privilege role with invalid password
	B) Login should not be successful
	
- [ ] 15)  Login with redfish user with callback privilege role with invalid password and verify it doesnt work - bad path 
	A) Login with user with callback privilege role with invalid password
	B) Login should not be successful
	
- [ ] 16)  Login with redfish user with admin privilege role  and try to set min and max password lengths
	A) Login with user with admin privilege role 
	B) Try to set password lengths and it should work
	C) Try to change network settings
	
- [ ] 17)  Login with redfish user with operator privilege role  and try to reboot system 
	A) Login with user with operator privilege role 
	B) Try to reboot system and it should work
	C) Try to set password lengths and it shouldnt work
	
- [ ] 18)  Login with redfish user with operator privilege role  and try to change network settings - bad path
	A) Login with user with operator privilege role 
	B) Try to change network settings it shouldnt work

- [ ] 19)  Verify user with user privilege role has only read access. 
	A) Login with user with user privilege role 
	B) Try to do some read operation and it should work. 
	C) Try to reboot system , it shouldnt work
	
- [ ] 20)  Login with user privilege and verify if it has read access to all the information 
    A) Login with user with user privilege role 
	B) Try to read most of the information and it should work. 
	
- [ ] 21)  Verify callback user privilege role
	A) Login with user with callback privilege role
	B) Verify the operations allowed for its role ( TBD ) 

- [ ] 22)  Perform code update with users with different roles.
	A) Try to perform code update with admin / operator / user / callback roles. 
	B) Should be allowed only with admin login
	
- [ ] 23)  Verify account lock upon timeout and release. 
	A) Keep any user account for the specified timeout ( TBD ) 
	B) Verify it gets locked by trying to login with it. 
	C) Verify it can be released
	D) Try logging in after releasing ( It should work ? )

**Comment by gkeishin** [comment]
@rthomaiy  @rahulmah @ratagupt Take a look at the above plan.

**Comment by sansomas** [comment]
Hi , Testing access

**Comment by sansomas** [comment]
- [ ] 1 )  Create a redfish user with admin privilege role and verify its successfully created
	A) Create a redfish user with admin privilege role 
		Command to create user : Refer to Create_User ( End of Document ) with RoleId as "Administrator"
	B) Login using the created user
	C) Perform some basic operation like reading system state
	
- [ ] 2 )  Create a redfish user with operator privilege role and verify its successfully created
	A) Create a redfish user with operator privilege role
		Command to create user : Refer to Create_User ( End of Document ) with RoleId as "Operator"
	B) Login using the created user
	C) Perform some basic operation like reading system driver
	
- [ ] 3 )  Create a redfish user with user privilege role and verify its successfully created
	A) Create a redfish user with user privilege role
		Command to create user : Refer to Create_User ( End of Document ) with RoleId as "User"
	B) Login using the created user
	C) Perform some basic operation ( TBD ) 
	
- [ ] 4 )  Create a redfish user with callback privilege role and verify its successfully created
	A) Create a redfish user with callback privilege role
		Command to create user : Refer to Create_User ( End of Document ) with RoleId as "Callback"
	B) Login using the created user
	C) Perform some basic operation ( TBD ) 
	
- [ ] 5 )  Create large number of users and verify the limit and system behavior and verify they are successfully created
	A) Create 100s of redfish users with combinational privilege roles. 
	B) Verify that all users are successfully created by logging in with them. 
	
- [ ] 6 )  Create same username with different privileges and verify it is allowed
	A) Create a redfish user with callback privilege role
		Command to create user : Refer to Create_User ( End of Document ) with RoleId as "Callback"
	B) Login using the created user
	C) Perform some basic operation 
	D) Create a redfish user with operator privilege role with same username as callback user
		Command to create user : Refer to Create_User ( End of Document ) with RoleId as "Operator"
	E) Login using the created user
	F) Perform some basic operation like reading memory information
	
- [ ] 7 )  Delete a redfish user with admin privilege role and verify its successfully deleted
	A) Delete a redfish user with admin privilege role
		Command to create user : Refer to Delete_User ( End of Document ) with RoleId as "Administrator"
	B) Try to login after deleting the user
	C) It should report an error
	
- [ ] 8 )  Delete a redfish user with operator privilege role and verify its successfully deleted
	A) Delete a redfish user with operator privilege role
		Command to create user : Refer to Delete_User ( End of Document ) with RoleId as "Operator"
	B) Try to login after deleting the user
	C) It should report an error
	
- [ ] 9 )  Delete a redfish user with user privilege role and verify its successfully deleted
	A) Delete a redfish user with user privilege role
		Command to create user : Refer to Delete_User ( End of Document ) with RoleId as "User"
	B) Try to login after deleting the user
	C) It should report an error
	
- [ ] 10)  Delete a redfish user with callback privilege role and verify its successfully deleted
	A) Delete a redfish user with callback privilege role
		Command to create user : Refer to Delete_User ( End of Document ) with RoleId as "Callback"
	B) Try to login after deleting the user
	C) It should report an error
	
- [ ] 11)  Delete a redfish user with operator / user / callback privilege by user with admin privilege and verify its successfully deleted 
	A) Login with user with admin privilege role
	B) Try to delete a user with operator privilege role
	C) It should work
	D) Login with user with operator / user privilege role
	E) Try to delete a user with callback privilege role
	F) It should not work. 
	
- [ ] 12)  Login with redfish user with admin privilege role with invalid password and verify it doesnt work - bad path
	A) Login with user with admin privilege role with invalid password
	B) Login should not be successful
	
- [ ] 13)  Login with redfish user with operator privilege role with invalid password  and verify it doesnt work- bad path
	A) Login with user with operator privilege role with invalid password
	B) Login should not be successful
	
- [ ] 14)  Login with redfish user with user privilege role with invalid password and verify it doesnt work - bad path
	A) Login with user with user privilege role with invalid password
	B) Login should not be successful
	
- [ ] 15)  Login with redfish user with callback privilege role with invalid password and verify it doesnt work - bad path 
	A) Login with user with callback privilege role with invalid password
	B) Login should not be successful
	
- [ ] 16)  Login with redfish user with admin privilege role  and try to set min and max password lengths
	A) Login with user with admin privilege role 
	B) Try to set password lengths and it should work
	C) Try to change network settings
	
- [ ] 17)  Login with redfish user with operator privilege role  and try to reboot system 
	A) Login with user with operator privilege role 
	B) Try to reboot system and it should work
	C) Try to set password lengths and it shouldnt work
	
- [ ] 18)  Login with redfish user with operator privilege role  and try to change network settings - bad path
	A) Login with user with operator privilege role 
	B) Try to change network settings it shouldnt work

- [ ] 19)  Verify user with user privilege role has only read access. 
	A) Login with user with user privilege role 
	B) Try to do some read operation and it should work. 
	C) Try to reboot system , it shouldnt work
	
- [ ] 20)  Login with user privilege and verify if it has read access to all the information 
    A) Login with user with user privilege role 
	B) Try to read most of the information and it should work. 
	
- [ ] 21)  Verify callback user privilege role
	A) Login with user with callback privilege role
	B) Verify the operations allowed for its role ( TBD ) 

- [ ] 22)  Perform code update with users with different roles.
	A) Try to perform code update with admin / operator / user / callback roles. 
	B) Should be allowed only with admin login
	
- [ ] 23)  Verify account lock upon timeout and release. 
	A) Keep any user account for the specified timeout ( TBD ) 
	B) Verify it gets locked by trying to login with it. 
	C) Verify it can be released
	D) Try logging in after releasing ( It should work ? ) 
	
Create_User:
============
-bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X POST https://${bmc}/redfish/v1/AccountService/Accounts -d '{
> "UserName":"UserName",
> "Password":"Pwd_Min_8",
> "RoleId":"RoleId_Refer_test_case",
> "Enabled":true}'	

UserName : End user defined username
Password : Min 8 , Max 31 characters
RoleId : Administrator / Operator / User / Callback

Delete_User:
=============
-bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X DELETE https://${bmc}/redfish/v1/AccountService/Accounts/UserName -d '{
"UserName":"UserName",
"RoleId":"RoleId_Refer_test_case",
}'

UserName : UserName which needs to be deleted
RoleId : Administrator / Operator / User / Callback

**Comment by gkeishin** [comment]
@rthomaiy Can u take a look at it , if we miss any use case there ..

**Comment by sansomas** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18547/ 
Gerrit link for test case # 1

**Comment by rthomaiy** [comment]
overall, mapping the user account with IPMI also has to be verified. But i believe @gkeishin created a separate issue for the same.

#4 --> as per our mapping, callback user is allowed to login only, no other configuration is allowed, including configureSelf.
#5 --> As of now, limited the users to maximum of 15 users by default (including IPMI support). Without IPMI, it can be set to max of 30 (but right now, it is with IPMI support only, i.e. if we create user, we will create the user with IPMI support too).
#6 --> This is not valid. Basically we won't allow same user name to be created in first place (even with different privileges). Note: We can change privilege of the already existing user.
#7 to #10 is almost same test case right? (Need clarification: Are we saying to delete a Administrator/User /Operator/Callback privilege user) or are we saying a user with callback privilege should be able to delete a user (because second case is not allowed. i.e. Callback user is only allowed to login, and he can't delete his own user account, whereas administrative privilege user can perform deleting any user account. (Add the test case accordingly, if it is not listed)
#11   #D itself should not work as the user is deleted.
#12 to #15 basically same to try with invalid password
#16 #C Reason for change network settings in this test case?? 
#23 AccountLockTimeout has to be enabled, and then tested (but guess, test case doesn't need to say that, but during implementation needs to make sure)


Note: as mentioned above, certain test case of cross validation has to be performed. 
1. Create user in REDFISH, login using IPMI, and vice versa. 
2. see users created with IPMI are visible and vice versa
3. Password /role /Enable status update through one, reflect in the another
4. Account lock reflected in both
5. User creation limits to 15
6. user accounts  & settings (password / roles etc..) are preserved across reboots. 
7. Not accepting invalid password / invalid username (or already existing username), and properly throwing the error.
8. Not accepting invalid role id etc.. and properly throwing error in REDFISH.
9. There is NO ACCESS in IPMI, currently i don't think it is mapped for REDFISH user. Guess we may need to map or atleast make sure, that role in that case is proper.

**Comment by gkeishin** [comment]
Linked new task  https://github.com/openbmc/openbmc-test-automation/issues/1654  for initial base changes

**Comment by gkeishin** [comment]
- [ ] BMC web PATCH account service bug https://github.com/openbmc/bmcweb/issues/59

**Comment by sansomas** [comment]
Creating below test cases based on above review comments. 

- [ ] 24)  Verify that user accounts and properties are saved through reboots
	A) Create any redfish user with any privilege
	B) Verify redfish login
	C) Perform system reboot
	D) Verify login after reboot and verify its properties
	
- [ ] 25)  Verify user properties ( password , enable , Role ) modification
	A) Create any redfish user with any privilege
	B) Verify redfish login
	C) Modify any of the user properties
	D) Verify its reflected
	
- [x] 26)  Verify creating user id by providing invalid role id
	A) Create any redfish user with invalid role id
	B) Verify it doesnt allow and verify proper error message is shown

        Status : Pass

**Comment by sansomas** [comment]
Adding few more test cases based on some technical discussions

- [ ] 27)  Verify creating user id without enabling it
	A) Create any redfish user with Enabled as false
	B) Verify login with created user and try some operations

- [ ] 28)  Verify BMC Gui login by creating redfish users with different privilege
	A) Create any redfish user with privilege - admin / operator / callback / user
	B) Verify login to GUI

**Comment by gkeishin** [comment]
Complete the remaining privilege role testing

**Comment by gkeishin** [comment]
This completes this story end to end

https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23064/
