### ISSUE TITLE
Feature: IPV6 Test Automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#153]

**Comment by gkeishin** [comment]
As per the discussion.. IPV6 we are not going to support as for now..

**Comment by sivassrr** [comment]
Closing it. And if Development comes back, We can revisit.

**Comment by gkeishin** [comment]
Yup.. There is no plan to enable or support IPv6 for now.. But yeah, we can revisit in future if development decides to enable and support it.. until then we are good here..
