### ISSUE TITLE
Community Monthly defect tracking

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1534]
Place holder to track defect for 2019 on daily basis.

Per month for logging / following / updating defect notes

**Comment by rahulmah** [comment]
**Unable to configure new IP address on eth interface** - https://github.com/openbmc/bmcweb/issues/36

**Comment by gkeishin** [comment]
### Feb Sprints Defects:

### Current Open Defects: 

>1. **Unable to configure new IP address on eth interface** - https://github.com/openbmc/bmcweb/issues/36
>- Fix available and need testing

>2. **Bmc web /redfish/v1/Managers/bmc Version mismatch** - https://github.com/openbmc/bmcweb/issues/38
>- Need Dev to debug and identify

>3. **gateway field for the link local address is not there in redfish**
https://github.com/openbmc/bmcweb/issues/39
>- Needs Dev to debug and identify 

>4. **SNMP: allowed to configure manager with out of range port value > 65535**  https://github.com/openbmc/bmcweb/issues/42
>- Needs Dev to debug and identify 

>5. **Unable to modify MAC address**
https://github.com/openbmc/bmcweb/issues/43

>6. **Unable to configure hostname using redfish**
https://github.com/openbmc/bmcweb/issues/44

>7. **Able to run IPMI command with user with IPMI messaging disabled and no access privilege**
https://github.com/openbmc/phosphor-host-ipmid/issues/125

>8. **Redfish: unable to enable VLAN**
https://github.com/openbmc/bmcweb/issues/51

>9. **DHCP configuration resource URL does not exist**
https://github.com/openbmc/bmcweb/issues/52

>10. **NTP resource URL does not exist**
https://github.com/openbmc/bmcweb/issues/53

>11. **Default gateway resouce URL does not exist on BMC**
https://github.com/openbmc/bmcweb/issues/54

> 12. **Unable to enable IPMI user with recent build**
https://github.com/openbmc/phosphor-host-ipmid/issues/127

> 13. **Disabled IPMI root user is able to run IPMI command**
https://github.com/openbmc/phosphor-host-ipmid/issues/128

### Closed Defects:
> 1. **Witherspoon-fan-watchdog.service: Main process exited** - https://github.com/openbmc/openbmc/issues/3479
>- Fix in the form of error log handling

>2. **Fails to power on due to FSI error** - https://github.com/openbmc/openbmc/issues/3477
> - Need more info

>3. **IPMI tool allowing to set different privilege for root user** - https://github.com/openbmc/phosphor-host-ipmid/issues/123

>4. **User list command without channel number is failing with inband -IPMI**https://github.com/openbmc/phosphor-host-ipmid/issues/124
