### ISSUE TITLE
BMC web session security test and automation

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1535]
- [x] Test Plan
- [x] Test and verify
- [x] Automation

**Comment by gkeishin** [comment]
@joseph-reynolds and I'll work on this one and see what we use cases we can add here

**Comment by gkeishin** [comment]
### Test plan
- [ ] 1.  Login to BMCweb using Invalid credentials
    - Wrong password
    - Wrong user name

- [ ] Access unsecured   http://<BMC>/redfish/v1

Add more as we discuss

**Comment by joseph-reynolds** [comment]
Here are some more test case ideas for Redfish security scenarios:
 - name: create many multiple concurrent Redfish sessions, then try using the first session
   tags: ["stress", "bmcweb", "security"]
 - name: establish a Redfish session, wait for it to time out, then try to use it
   tags:  ["bmcweb", "security"]
 - name: Create many bmcweb redfish sessions until the BMC crashes (DOS attack)
   tags: ["stress", "bmcweb", "security"]
 - name: Authenticate to Redfish, then log out and attempt to use the session
   tags:  ["bmcweb", "security"]
 - name: Login and check HTTP response headers:
   data: various, see Redfish SessionService, X-Auth-Token
     for examples, see https://github.com/openbmc/bmcweb/blob/master/include/security_headers_middleware.hpp
   tags:   ["bmcweb", "security"]

If phosphor-webui is configured into the OpenBMC image, validate HTTP response headers for URI=/index.html.  For example, the HTTP response should have correct content for the following headers: Content-Security-Policy, Strict-Transport-Security, etc.

Here are some more test ideas, partially coded in Robot:

```
HTTP Wrong Port 433 Bad Request
    [Documentation]  Ensure http fails on port 433
    [Tags]  Test_Http_Wrong_Port_433
    Create Session  openbmc  http://${OPENBMC_HOST}:443  max_retries=0
    ${resp}=  Get Request  openbmc  /
    Should Be Equal As Strings  ${resp.status_code}  ${HTTP_BAD_REQUEST}

HTTPS Wrong Port 80 Fails Protocol
    [Documentation]  Ensure https fails on port 80
    [Tags]  Test_Https_Wrong_Port_80
    Create Session  openbmc  https://${OPENBMC_HOST}:80  max_retries=0
    Run Keyword And Expect Error   SSLError: *UNKNOWN_PROTOCOL*
    ...  Get Request  openbmc  /

Unauth POST Access
    [Template]  Unauth POST ${path} Returns ${result}
    /                     ${HTTP_METHOD_NOT_ALLOWED}
    /index.html           ${HTTP_METHOD_NOT_ALLOWED}
    /xyz                  ${HTTP_METHOD_NOT_ALLOWED}
    /login                ${HTTP_BAD_REQUEST}
    /logout               ${HTTP_BAD_REQUEST}
    /redfish/v1/SessionService/Sessions
    ...                   ${HTTP_BAD_GATEWAY}
```

**Comment by gkeishin** [comment]
Awesome.. perhaps once the above base code commit goes in , you can push the above changes @joseph-reynolds

**Comment by gkeishin** [comment]
Login to http unsecured https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/17996/

**Comment by gkeishin** [comment]
The initial test code are in place, so u can go ahead and add ur code there 

https://github.com/openbmc/openbmc-test-automation/blob/master/redfish/service_root/test_service_root_security.robot

@joseph-reynolds may be time to push ur code there.. let me know when ready on gerrit..

**Comment by gkeishin** [comment]
Added for Redfish Login Using HTTPS Wrong Port 80 Protocol 

https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18124/

Take a look @joseph-reynolds

**Comment by gkeishin** [comment]
Split part of work done https://github.com/openbmc/openbmc-test-automation/issues/1629  for the sprint

**Comment by gkeishin** [comment]
Multiple session test https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18555/

**Comment by gkeishin** [comment]
Expired session test https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18569/

**Comment by gkeishin** [comment]
```
name: create many multiple concurrent Redfish sessions, then try using the first session
tags: ["stress", "bmcweb", "security"]
name: establish a Redfish session, wait for it to time out, then try to use it
```
The BMC web expiry is for like 1 hour and not configurable, so I have manually create session and check post 1 hour and it exits cleanly if not used the same session token.

So this is not ideal for test to wait on.

**Comment by gkeishin** [comment]
```
name: Create many bmcweb redfish sessions until the BMC crashes (DOS attack)
tags: ["stress", "bmcweb", "security"]
```
This i tested by flooding thousands of sessions and it survived more than 8 hours over the weekend.  Existing test can be use to flood this.. 

https://github.com/openbmc/openbmc-test-automation/blob/master/redfish/service_root/test_service_root_security.robot#L60

User can key in -v LOGIN_SESSION_COUNT:10000 to simulate this. for now 50 session by default in good case

**Comment by gkeishin** [comment]
Working on the the above last commit for this task
```
Check the hard-coded value for 7 of the 8 security headers:
                ```add_header X-Frame-Options deny;
                add_header X-XSS-Protection "1; mode=block";
                add_header X-Content-Type-Options nosniff;
                add_header Content-Security-Policy "frame-ancestors 'none'; default-src 'self' 'unsafe-eval' 'unsafe-inline'";
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
                add_header Cache-Control "no-store,no-cache";
                add_header Pragma "no-cache";    
                add_header Expires 0;```

But for Content-Security-Policy you only have to check if it is present.
```
