### ISSUE TITLE
Add plugin for redfish in existing FFDC 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1537]
Redfish code to call enumerate legacy equivalent

- [x] Add keyword method in openbmc_ffdc_methods.robot
- [x] Call `Enumerate Request` and write to a file
- [x] Test and verify

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/17944

**Comment by gkeishin** [comment]
Thanks @ssombar

**Comment by gkeishin** [comment]
@ssombar had to change few more time and test due to other changes impacting this code.. Thanks Steve for doing this,,
