### ISSUE TITLE
Continuous test metrics (ctmetrics)

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#1544]
CT metrics for witherspoon, we already have code for it.. but to maintain and update ahead for regular push ..

**Comment by ssombar** [comment]
CT metrics for witherspoon, we already have code for it.. but to maintain and update ahead for regular push ..

**Comment by gkeishin** [comment]
- [ ] Update to make it generic https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18818/
