### ISSUE TITLE
HTX runs for Host testing

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1553]
- [ ] Test plan
- [ ] Test and verify
- [ ] Automation

**Comment by bradbishop** [comment]
What is HTX?

**Comment by gkeishin** [comment]
@bradbishop  The Hardware Test Executive (HTX) is a suite of test tools for hardware validation of OpenPOWER system.

https://github.com/open-power/HTX/blob/master/README.md


We use this to stress the system for witherspoon.

**Comment by bradbishop** [comment]
On Wed, Feb 06, 2019 at 09:08:25PM -0800, George Keishing wrote:
>@bradbishop  The Hardware Test Executive (HTX) is a suite of test tools for hardware validation of OpenPOWER system.
>
>https://github.com/open-power/HTX/blob/master/README.md
>
>
>We use this to stress the system for witherspoon.
Thanks George!  This will help non-IBMers looking at this.

**Comment by gkeishin** [comment]
Code to run HTX from test infrastructure  https://github.com/openbmc/openbmc-test-automation/blob/master/systest/htx_hardbootme_test.robot
