### ISSUE TITLE
Redfish logging support

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1559]
rsyslog support
Test plan
Execution
Automation

**Comment by gkeishin** [comment]
- [ ] Dev commit https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/12018/

**Comment by gkeishin** [comment]
Dev https://github.com/ibm-openbmc/dev/issues/481

**Comment by gkeishin** [comment]
- [ ] Enable and try RESTfull calls and local user create/ update and delete and verify it doesnt log
- [ ] Disable and verify
