### ISSUE TITLE
Enhancement: Settings Support Categories to accomodate new d-bus interface

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#156]

**Comment by sivassrr** [comment]
settingsd - Support categories. #551 Basically we need to support more than host0 and automate. 
https://github.com/openbmc/openbmc/issues/551

**Comment by sivassrr** [comment]
Pls check for #552 as well. As discussed, I am assigning it to Prashanth.

**Comment by sivassrr** [comment]
@rahulmah Please check and let know whether we have equivalent. Then we can close it.

**Comment by sivassrr** [comment]
#1486, #1487, #1488, #1489
Please go thru above stories and start automation accordingly.

**Comment by rahulmah** [comment]
@sivassrr : as discussed, dev changes are now getting integrated. Started working on this story. Automation code will be up by tomorrow.

**Comment by rahulmah** [comment]
Here are the task for this story: 

- [ ] Move org settings to new xyz interfaces
- [ ] Preserve and sync settings
