### ISSUE TITLE
BMC firewall

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1560]
BMC Firewall testing.
Test plan
Test Execution & Automation

Dev: https://github.com/ibm-openbmc/dev/issues/242

**Comment by gkeishin** [comment]
As discussed @joseph-reynolds @prkatti1 moving this epic to future releases. Thanks

**Comment by yewdforwork** [comment]
I would like to ask : how do you start firewalld in openbmc system, or what should I do ?

When I introduced the firewalld module to openbmc, I failed to start Firewald. service. The following error message is displayed：
![image](https://user-images.githubusercontent.com/117135106/234201452-c5985b41-a67a-4b96-a7ff-d4f3e1daba7a.png)

Operation procedure：

The bb file path used:
openbmc/meta-openembedded/meta-networking/dynamic-layers/meta-python/recipes-connectivity/firewalld/[firewalld_1.2.0.bb](http://firewalld_1.2.0.bb/)
Add the firewalld module to [packagegroup-apps.bb](http://packagegroup-apps.bb/) in my project.
Note: Introduce other modules to work properly, such as sqlite and nginx
Compile->burn-> start openbmc system : firewalld module exists, but failed to start, manual execution also failed
In addition, I noticed that the firewalld community has similar issues with the status of open : https://github.com/firewalld/firewalld/issues/927

**Comment by williamspatrick** [comment]
We’re not a “support every package that exists in Linux” kind of project. No one else is using firewalld in any reference implementation. If it is something you want to get working, you’ll need to work with that project to figure it out.
