### ISSUE TITLE
GUI: Test Virtual Media page

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1566]
Test Virtual Media page in GUI

Dev Story - https://github.com/ibm-openbmc/dev/issues/176

**Comment by gkeishin** [comment]
- [ ] Download ISO image and start virtual media session from BMC web GUI
- [ ] Mount ISO and boot host, and view the Install at petitboot
- [ ] Mount ISO and boot to Host
- [ ] Install using petitboot after mount via virtual media
- [ ] Mount and confirm at petitboot and then unmount and confirm it auto unmounted
- [ ] Mount and start install and then un mount when install is in progress

**Comment by edineshkumar** [comment]
Is this working for IMG image? I mean HDD image redirection will success?
 I can able to redirect HDD (.img or .ima) image, but can not mount properly. Getting some  error like "can't read superblock".

![image](https://user-images.githubusercontent.com/41941042/84764938-181e4100-afec-11ea-8625-2197302793a7.png)

**Comment by mdmillerii** [comment]
@edineshkumar What happens if you try to mount your image using a loop device on the host?  This would isolate issues with your image from issues like block simze or unimplemented commands.

**Comment by edineshkumar** [comment]
@mdmillerii  I have raised issue on virtual media redirection, kindly help me out to resolving the same.

https://github.com/openbmc/openbmc/issues/3669
