### ISSUE TITLE
GUI: Test IPKVM

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1568]
Test IPKVM in GUI

Dev story - https://github.com/ibm-openbmc/dev/issues/183

**Comment by gkeishin** [comment]
-  [ ] Boot host and open KVM view and check 
-  [ ] Open KVM view at standby and Power on
-  [ ] Perform operation on the KVM view like open an application
-  [ ] Shutdown the host from KVM
-  [ ] Reboot Host from KVM
-  [ ] Refresh BMC web page
-  [ ] Switch from KVM view to other GUI pages and come back to KVM view
