### ISSUE TITLE
OBMC-Console related test enhanced automation / verification

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#157]
https://github.com/openbmc/obmc-console/issues/7
https://github.com/openbmc/obmc-console/issues/5
https://github.com/openbmc/openbmc/issues/585

**Comment by sivassrr** [comment]
@gkeishin I am sending this to backlog, In case if we need to do anything, Please check here. 
SOL - As of now we are kind of done, Do we need to do anything further, We need to evaluate it.

**Comment by gkeishin** [comment]
After discussion with Adriana the only thing we could do is to connect to Console and check if it established the session .. probbaly poweron and see if its getting the output...

**Comment by gkeishin** [comment]
The code are already in and use by poweron CI tests.. more supports have gone in or are coming in the form of using the Console log as a proof of data for opening defects specially for Host OS boot issues.

So this is considered closed..
