### ISSUE TITLE
BMC Backup and Restore

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1579]
Dev story - Backup and restore - https://github.com/ibm-openbmc/dev/issues/241

**Comment by gkeishin** [comment]
Backup and restore Design https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/18163/

**Comment by gkeishin** [comment]
@anoo1 Keep posted, just in case if things are moving there, I ll keep watch.

**Comment by gkeishin** [comment]
Looks like a feature in GUI to be sized in
