### ISSUE TITLE
Redfish(LDAP): Secure LDAP Testing

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1586]
dev#240[Redfish(LDAP): Map the sdbus error to Redfish and Secure LDAP Testing](/ibm-openbmc/dev/issues/240)

**Comment by sivassrr** [comment]
- [ ] Understanding Secure Redfish LDAP -  1

- [ ] Manual Testing - 2  ( If everything goes fine, Can be done in 1 day)

- [ ] Automation Coding - 1 ( Considering login with secure TC ) 

- [ ] Documentation - 0.3
