### ISSUE TITLE
freeipmi :  ipmipower  tool

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1597]
“openipmi-tools” and it’s tools like ipmipower on openbmc test . Seems like industry is moving towards these tools.  Input from @geissonator 

```
ipmipower
    A tool for remote power control.
```

**Comment by gkeishin** [comment]
https://www.gnu.org/software/freeipmi/

**Comment by gkeishin** [comment]
```
$ ipmipower -h xx.xx.xx.xx -u root -p 0penBMC --off
xx.xx.xx.xx: authentication type unavailable for attempted privilege level
````

**Comment by gkeishin** [comment]
```
-bash-4.1$ ipmipower -D LAN_2_0  -u admin -p 0penBmc -h xx.xx.xx --stat
xx.xx.xx: off
-bash-4.1$ ./ipmitool -I lanplus -H xx.xx.xx -U admin -P 0penBmc  chassis power status
Chassis Power is off
```

```
-bash-4.1$ ipmipower -D LAN_2_0  -p 0penBmc -h xx.xx.xx --stat
xx.xx.xx: off
-bash-4.1$ ./ipmitool -I lanplus -H xx.xx.xx -P 0penBmc  chassis power status
Chassis Power is off
```

**Comment by sansomas** [comment]
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --stat
9.41.165.233: off
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --on
9.41.165.233: ok
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --stat
9.41.165.233: on
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --pulse
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --soft
9.41.165.233: ok
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --wait-until-off
ipmipower>
ipmipower>
ipmipower>
ipmipower>
ipmipower>
ipmipower>
ipmipower>
ipmipower>
ipmipower>
ipmipower>
ipmipower> -bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --stat
9.41.165.233: on
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --wait-until-off
ipmipower> ^C
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --off
9.41.165.233: ok
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --stat
9.41.165.233: off
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --stat
9.41.165.233: off
-bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --wait-until-on
ipmipower>
ipmipower>
ipmipower>
ipmipower> -bash-4.1$ ipmipower -D LAN_2_0 -h 9.41.165.233 -u root -p 0penBmc --stat
9.41.165.233: off
-bash-4.1$
