### ISSUE TITLE
Autoreboot needs to be enabled by default for watchdog tests

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1600]
After injecting host watchdog error, system goes into quiesce if autoreboot is set to disable. So overcome this, we need to set auto reboot enable for watchdog test cases.

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18504/

**Comment by gkeishin** [comment]
Thanks Anusha for the code.
