### ISSUE TITLE
Redfish Boot Options

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1601]
Dev: https://github.com/ibm-openbmc/dev/issues/286

**Comment by gkeishin** [comment]
- [ ] Test plan
- [ ] Test and verify
- [ ] Automation

**Comment by gkeishin** [comment]
@SrideviRamesh Can update whats the test you intend to do here

**Comment by SrideviRamesh** [comment]
Test plan:
Set the various boot options and verify.
Testcases:
With "BootSourceOverrideEnabled": "Continuous" setting change and verify boot device type
1. Cd
2. Hdd
3. Diags
4. BiosSetup
5. Pxe

With "BootSourceOverrideEnabled": "Once" setting change and verify boot device type
1. Cd
2. Hdd
3. Diags
4. BiosSetup
5. Pxe

With "BootSourceOverrideEnabled": "Disabled" setting change and verify boot device type
1. Cd
2. Hdd
3. Diags
4. BiosSetup
5. Pxe

**Comment by gkeishin** [comment]
Commit https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18768/

**Comment by gkeishin** [comment]
@SrideviRamesh Can u add the bad path boot setting as well in above test plan or u do in next phase of commit ?
