### ISSUE TITLE
IPMI and Redfish combination for user management

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1605]
Some possible scenarios:

1. Create / Delete user through redfish, and try using the same in IPMI  (vice versa)
2. Update the password in redfish, and see whether it's getting used in IPMI (similarly others enable / priv) (vice versa)
3. Channel command privilege are working as per the channel (but at this point of time this differentiation can't be made due to architecture limitations, but ok to write test case and mark it as failed, rather than skipping the same)

Create user in REDFISH, login using IPMI, and vice versa.
- see users created with IPMI are visible and vice versa
- mapping the user account with IPMI also has to be verified
- As of now, limited the users to maximum of 15 users by default (including IPMI support). Without IPMI, it can be set to max of 30 (but right now, it is with IPMI support only, i.e. if we create user, we will create the user with IPMI support too).

**Comment by rahulmah** [comment]
Test cases : 


- [ ] Create User via Redfish And Use it using IPMI

1. Create Redfish user with valid name and password.
2. Verify that the newly created user can run IPMI command.
	ipmitool -I lanplus -C 3 -U <newly created user> -P <password for newly created user> -H <BMC_IP> <IPMI cmd>

- [ ] Create User via IPMI And Use it using Redfish - Passed

1. Create IPMI user with valid name using "set user name" command. Example :
	ipmitool -I lanplus -C 3 -U root -P 0penBmc -H <BMC_IP> user set name <user id> newuser
2. Verify that the newly created user can run Redfish command.



- [ ] Update Password via Redfish And Verify Using IPMI

1. Create IPMI user with valid name and password. 
2. Update password using Redish.
2. Verify that the newly created user can run Redfish command with updated password.


- [ ] Update Password via IPMI And Verify Using Redfish - Passed

1. Create Redfish user with valid name and password. 
2. Update password using IPMI.
2. Verify that the newly created user can run Redfish command with updated password.

**Comment by rahulmah** [comment]
Issue logged: 
Error message not proper while creating 16th user via Redfish - https://github.com/openbmc/bmcweb/issues/63

**Comment by rthomaiy** [comment]
Add one more test case related to Update privilege of the user in IPMI / REDFISH and verify the restrictions also updated for REDFISH / IPMI

**Comment by rahulmah** [comment]
> Add one more test case related to Update privilege of the user in IPMI / REDFISH and verify the restrictions also updated for REDFISH / IPMI

@rthomaiy : Done. Added below to test cases. Hope it now looks good. 

1. Update user privilege via Redfish And Verify Using IPMI
2. Update user privilege via IPMI And Verify Using Redfish

**Comment by rthomaiy** [comment]
@rahulmah yes, thanks

**Comment by gkeishin** [comment]
Reducing point from 4 to 2 , since largely are done. pending only needs to be tracked here

**Comment by gkeishin** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/1781 reference of effort work

**Comment by rahulmah** [comment]
Moved user group related test cases in https://github.com/openbmc/openbmc-test-automation/issues/1848

**Comment by gkeishin** [comment]
This story is marked completed after discussion with @rahulmah
