### ISSUE TITLE
Witherspoon: Basic RAS 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1606]
- [x] Test plan
- [x] Test and verify
- [x] Automation

**Comment by lkammath** [comment]
This EPIC includes following 

1. Covering error injections through Host for different targets like CORE/EX/EQ/CME/OCC/Memory Channel/DIMM/NX/NPU/GPU/Fabric (Most of them exists today. Just need to see what is pending from above mentioned list of targets)
2. Covering same set of error injections through pdbg tool on BMC ( Currently pdbg tool is not very mature. so, will need to see if it is really worth spending effort on pdbg as it will give same coverage as Host error injection). pdbg injection will be more helpful in IPL path error injections which could be definitely the scope ignoring pdbg injection support on BMC runtime
3. Basic SBE Halt error injection & Recovery (IPL time and Runtime)
4. SBE SEEPROM corruption and side switch verification (IPL time and runtime)
5. Basic PGOOD fault injection support (Inject different types of DPSS PGOOD faults and verify callouts) . This should be eventually covered by POWR testing and should create a work item for Marissa

**Comment by lkammath** [comment]
@gkeishin need to follow up on #5 with Marissa.

**Comment by gkeishin** [comment]
Will need to continue this ahead.
