### ISSUE TITLE
Redfish: Manager (missing properties)

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1609]
Dev https://github.com/ibm-openbmc/dev/issues/281

**Comment by ssombar** [comment]
I verified the presence of the attributes put in place by the 
code change for ibm-openbmc/dev/issues/281,  specifically
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20025

Note that state/bmc0 is alwayse "On".  I believe this is expected per
the note near the bottom of 281.
  
I see from comments that GraphicalConsole is TBD.
Looking at the code from 20025:
    // TODO (Santosh) : Uncomment when KVM support is in.
    // res.jsonValue["GraphicalConsole"]["ServiceEnabled"] = true;

The SerialNumber attribute is also TBD.  There is a separate issue for that
https://github.com/ibm-openbmc/dev/issues/480

**Comment by gkeishin** [comment]
@ssombar KVM is now enabled and available in Master.. perhaps.. we can ask Santosh to uncomment that ?

**Comment by ssombar** [comment]
I have sent Sandosh a direct message via slack.

**Comment by ssombar** [comment]
GraphicalConsole attribute enablement:  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/21082

**Comment by ssombar** [comment]
gerrit #21082 was merged this week.   
Looking at a recent build now I see the following at /redfish/v1/Managers/bmc

        GraphicalConsole": {
            "ConnectTypesSupported": [
                "KVMIP"
            ],
            "ServiceEnabled": true
        }

**Comment by ssombar** [comment]
I think we can close this issue now.
