### ISSUE TITLE
Redfish: Code upload via POST update

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1612]

**Comment by gkeishin** [comment]
```
curl -k -H "X-Auth-Token: $TOKEN" -H "Content-Type: application/octet-stream" -X POST -T ./obmc-phosphor-image-witherspoon.ubi.mtd.tar https://${BMC_IP}/redfish/v1/UpdateService
```

- [ ] Code upload and verify if its loaded

**Comment by gkeishin** [comment]
Docs: https://github.com/openbmc/docs/blob/master/designs/firmware-update-over-redfish.md

**Comment by gkeishin** [comment]
Write the keyword to do code image upload in python

**Comment by susilsi7** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23451/

**Comment by gkeishin** [comment]
- [ ] Manual Testing
- [ ] Automation
- [ ] Required new keywords
