### ISSUE TITLE
GUI: Update User Mgmt

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1613]
Dev https://github.com/ibm-openbmc/dev/issues/185

**Comment by rahulmah** [comment]
Test cases : 

- [ ] Create and verify admin role user via GUI

1. Create an admin role user using GUI .
2. Verify GUI login using the newly created user.
3. Verify that the newly created user can perform admin privilege task.


- [ ] Create and verify operator role user via GUI

1. Create a operator role user using GUI .
2. Verify GUI login using the newly created user.
3. Verify that the newly created user can perform operator privilege task only.


- [ ] Create and verify user role user via GUI

1. Create a user role user using GUI .
2. Verify GUI login using the newly created user.
3. Verify that the newly created user can perform user privilege task only.


- [ ] Create and verify callback role user via GUI

1. Create a callback role user using GUI .
2. Verify GUI login using the newly created user.
3. Verify that the newly created user can perform callback privilege task only.


- [ ] Verify proper error while creating more than max user limit.

1. Create total 15 users with valid name and password via GUI.
2. Now try to create 16th User via GUI.
3. Verify proper error while creating more than more than 15 users.


- [ ] Verify proper error while creating two users with same name

1. Create a user with name - "newuser".
2. Now again try to create a user with same name.
3. Verify proper error while creating 2nd user with same name.

- [ ] Delete and verify user via GUI

1. Create a user using GUI .
2. Verify GUI login using the newly created user.
3. Delete the newly created user via GUI.
4. Verify that the user is successfully deleted. 
5. Verify that the delete user is unable to login.


- [ ] Verify proper error while login GUI with invalid password

1. Create a user using GUI .
2. Verify proper error while login GUI with the newly created user with invalid password.


- [ ] Verify user properties modification

1. Create a user with any privilege
2. Modify any of the newly created user properties(password , enable , Role )
3. Verify changes are reflected and working as expected.


- [ ] Verify that user accounts and properties are saved through reboots

1. Create a user with any privilege via GUI.
2. Perform system reboot.
3. Verify the user properties after reboot.


- [ ] Verify creating user without enabling it

1. Create a user without enabling it via GUI
2. Verify login failed with newly created user and proper error while login.

**Comment by adathatri** [comment]
Below testcases are in review:
1. Verify Error When Duplicate User Is Created
2. Delete User And Verify
3. Verify Invalid Password Error
4. Edit And Verify User Property
5. Create And Verify User Without Enabling
