### ISSUE TITLE
GUI: SNMP

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1614]

**Comment by NamanNH** [comment]
- [ ] Navigate to SNMP Settings Page to check accessibility
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Check to see if the page is reachable.

- [ ] Edit and save an existing configuration and verify
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Click on the edit button of an already existing configuration and save.
   3.Check if the changes are reflected GUI as well as REST.

- [ ] Edit and cancel an existing configuration and verify 
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Click on the edit button of an already existing configuration and cancel.
   3.Check if the changes made aren’t reflected in GUI.

- [ ] Add two or more managers to the SNMP configuration then save and verify
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Add multiple manager configuration and save.
   3.Verify that multiple manager configuration is reflected in GUI. 

- [ ] Add two or more managers to the SNMP configuration then cancel and verify
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Add multiple manager configuration.
   3.Click on cancel button to cancel operation.
   4.Verify that multiple manager configuration is not reflected in GUI.

- [ ] Add invalid port and verify if acceptable
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Add any port number above 65535 configuration and save.
   3.Check if “invalid port” error message appears.

- [ ] Add invalid IP and verify if acceptable
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Add any invalid IP to the configuration and save.
   3.Check if bad request error message is handled and reflected on the page.


- [ ] Functionally validate the increment up/down buttons in the port field.
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Click on the UP/Down arrow button in the port field.
   3.Check if it increments or decrements and verify the boundary conditions as well (0-65535).

- [ ] Verify save settings operation while deleting SNMP configuration
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Click on the delete button of an already existing configuration and save.
   3.Check if the changes made are reflected in GUI.

- [ ] Verify cancel operation while deleting SNMP configuration
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Click on the delete button of an already existing configuration and cancel.
   3.Check if the changes made aren’t reflected in GUI.

- [ ] Add same configuration twice and verify
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Add the same configuration multiple times and save.
   3.Verify if “Unable to set Managers” error message appears while adding same configuration multiple time.

- [ ] Verify add manager button
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Click on add manager button and see if new IP & Port fields appear.


- [ ] Verify if “cancel” button is disabled before the edit phase or after the configuration is saved
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Check if cancel button is disabled before anything is added or edited 
   3.Check if cancel button is disabled after add or edit operation is saved.
 

- [ ] Verify if “save settings” button is disabled before the edit/add phase or after the configuration is already saved once. 
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Check if “save settings” button is disabled before anything is added or edited 
   3.Check if “save settings” button is disabled after add or edit operation is already saved once.
