### ISSUE TITLE
GUI: Date Time : Test Plan 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1616]

**Comment by rahulmah** [comment]
Dev story - https://github.com/openbmc/phosphor-webui/issues/46

**Comment by rahulmah** [comment]
@gkeishin : Please assign this story to @sivassrr

**Comment by sivassrr** [comment]
- [ ] Test Plan Creation.

**Comment by gkeishin** [comment]
Thanks @sivassrr closing
