### ISSUE TITLE
Automation of SecureBoot Bad path scenarios

### ISSUE THREAD

**Issue by lkammath** [openbmc/openbmc-test-automation#1619]
Will be covering following scenarios

1. Payload partition corrupted : Verify Cold Boot failure
2. SBE partition corrupted : Verify Cold boot failure
3. HBI partition corrupted : Verify Cold boot failure
4. Verify Recovery from  Secure Boot SBE SEEPROM corruption
5. A/C power cycle During SBE update ; Verify system recovers
6. HBB partition corrupted ; Verify cold Boot failure
7. OCC partition corrupted; Verify cold boot failure
8. HBRT partition corrupted; verify cold boot failure
9. HBBL partition corrupted; verify cold boot failure
10.  HCODE partition corrupted; verify cold boot failure
11.  HBD partition corrupted; verify cold boot failure
12.  BOOTKERNEL partition corrupted; verify cold boot failure
13.  CAPP partition corrupted; verify cold boot failure
14.  WOFDATA partition corrupted; verify cold boot failure
15. MEMD partition corrupted; verify cold boot failure
16. RING Override ;Verify ring overrides not possible with secure boot enabled
17. Read/ Write Blacklisted SCOM register;Ensure request rejected

**Comment by gkeishin** [comment]
- [ ] Sub task https://github.com/openbmc/openbmc-test-automation/issues/1681

**Comment by lkammath** [comment]
All others are done . Pending one's are below. Which will be taken May/June
1) Verify Recovery from Secure Boot SBE SEEPROM corruption
2) A/C power cycle During SBE update ; Verify system recovers
3) RING Override ;Verify ring overrides not possible with secure boot enabled
4) Read/ Write Blacklisted SCOM register;Ensure request rejected

#1, 3, 4 is important

#2 requires PDU support in the code

**Comment by lkammath** [comment]
Can be taken in p10
