### ISSUE TITLE
Witherspoon RAS: Boot time error injection using PDGB tool 

### ISSUE THREAD

**Issue by lkammath** [openbmc/openbmc-test-automation#1621]
This story covers all the error injection that is covered by HOST error injection using PDBG @ Boot time/ HB IPL time . Covers both recoverable threshold and Unrecoverable errors

1. CPU/CORE
2. EX
3. EQ
4. CME
5. CAPP
6. OCC
7. GPU
8. NCU
9. NPU
10. L2
11. L3
12. MCA
13. MCI
14. CXA
15. OBUS
16. NXDMAENG
17. CXA

Effort involves implementing keyword for pedbg injection , Manage expectation change for Boot time injection like , reconfigure loop/can continue boot and also esel checking

**Comment by SrideviRamesh** [comment]
I will be completing this story in phases.

Phase 1 : 
Adding BMC RAS recoverable error injection through pdbg tool test scenarios with threshold limit '1', '5', '32'.
Phase 2:
I will add unrecoverable error injection through pdbg tool test scenarios.
