### ISSUE TITLE
RAS: Basic SBE Halt error injection & Recovery (Boot time and Runtime)

### ISSUE THREAD

**Issue by lkammath** [openbmc/openbmc-test-automation#1622]
Scope of this Automation will include following

1. Inject SBE halt error during Boot time and expect recovery until threshold is exceeded (Perform this on master and slave SBE)
2. Inject SBE SEEPROM error injection during Boot time and expect recovery until threshold is exceeded  (Perform this on slave SBE) . Also need to include check for the SEEPROM side switch as part of expectation

Repeat #1 and #2 @ BMC/Host runtime and check for the SBE recovery at Host runtime (Before threshold) - Additional expectation is to check if the expected error logs with correct FAPI RC for SBE failure is captured in the error logs

**Comment by gtmills** [comment]
@lkammath IPL is an IBMism, can you use more industry-standard terminology ? boot?

**Comment by lkammath** [comment]
Done @gtmills
