### ISSUE TITLE
PLDM tool verification 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1634]

**Comment by gkeishin** [comment]
This has a depending on the PLDM tooling development.. Need to link the story as dependencies to this @lkammath

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/22942

Here is the first version of pldmtool upstream

**Comment by lkammath** [comment]
The scope of this story is limited to the implementation of the pldmtool

https://github.com/openbmc/openbmc-test-automation/issues/1910 will track the automation framework and code around pldmtool

**Comment by lkammath** [comment]
Tracking the tool work
https://github.com/ibm-openbmc/dev/issues/380
