### ISSUE TITLE
Redfish: Network initial probing manually 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1637]
Dev: https://github.com/ibm-openbmc/dev/issues/440

This activity to help Network team to get and idea what are the task they would need to target for Redfish Network support in general.

**Comment by gkeishin** [comment]
@ratagupt :
Seems George, I would recommend that we don't need to test ETE now, but what we can test the redfish url and on the backend D-bus object are getting updated..

If the D-bus objects are getting updated..we should be ok as we have done this testing before..
@prkatti1 have all the busctl querys otherwise the network doc have all the busctl querys.

@gkeishin :
sounds like a good plan there..

**Comment by gkeishin** [comment]
Update from Prashanth Katti @prkatti1 

```=> Configure IP address    Fail
=> Delete IP address    Fail
=> Configure DNS    Fail
=> Configure NTP    Fail
=> Configure VLAN    TBD
=> Delete VLAN    TBD
=> Configure DHCP(Enable/Disable)    TBD
=> Configure DHCP options    TBD
=> Configure HostName    Fail
=> Configure Default Gataeway    TBD
=> Configure MAC Address    Fail
```
Testing in progress

**Comment by prkatti1** [comment]
=> Configure IP   address | Fail | https://github.com/openbmc/bmcweb/issues/36
-- | -- | --
=> Delete IP address | Fail | https://github.com/openbmc/bmcweb/issues/36
=> Configure DNS | Fail | No option
=> Configure NTP | Fail | No option
=> Configure VLAN | TBD |  
=> Delete VLAN | TBD |  
=> Configure DHCP(Enable/Disable) | TBD |  
=> Configure DHCP options | TBD |  
=> Configure HostName | Fail | https://github.com/openbmc/bmcweb/issues/44
=> Configure Default Gataeway | TBD |  
=> Configure MAC Address | Fail | https://github.com/openbmc/bmcweb/issues/43

**Comment by gkeishin** [comment]
@dkodihal @ratagupt ^^^

**Comment by prkatti1** [comment]
@gkeishin This activity is done and results are as below:

=> Configure IP   address | Fail | https://github.com/openbmc/bmcweb/issues/36
-- | -- | --
=> Delete IP address | Fail | https://github.com/openbmc/bmcweb/issues/36
=> Configure DNS | Fail | https://github.com/openbmc/bmcweb/issues/50
=> Configure NTP | Fail | https://github.com/openbmc/bmcweb/issues/53
=> Configure VLAN | Fail | https://github.com/openbmc/bmcweb/issues/51
=> Delete VLAN | Fail | https://github.com/openbmc/bmcweb/issues/51
=> Configure DHCP(Enable/Disable) | Fail | https://github.com/openbmc/bmcweb/issues/52
=> Configure DHCP options | Fail | https://github.com/openbmc/bmcweb/issues/52
=> Configure HostName | Fail | https://github.com/openbmc/bmcweb/issues/44
=> Configure Default Gataeway | Fail | https://github.com/openbmc/bmcweb/issues/54
=> Configure MAC Address | Fail | https://github.com/openbmc/bmcweb/issues/43

**Comment by gkeishin** [comment]
Thanks  @prkatti1 . since you have sent out to community mailing list.. This task is now marked completed.
