### ISSUE TITLE
update eSEL raw IPMI command string

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#1639]
[George K.]For eSEL for host.. I remember there was a change needed there.. what was that?

```
# ipmitool -C 3 raw 0x0a 0x42
04 00

# ipmitool -C 3 raw 0x3A 0xf0 0x04 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0xdf 0x00 
     0x00 0x00 0x00 0x20 0x00 0x04 0x12 0x65 0x6f 0xaa 0x00 0x00
02 00

**Comment by gkeishin** [comment]
- [ ] Test and verify
- [ ] Update the IPMI raw string

**Comment by ssombar** [comment]
impacts  esel_utils.robot   and possibly test_esel.robot

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18951
