### ISSUE TITLE
[Automation] ConnectionError while doing GET operation on enumerate

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#164]
Some time GET operation to /org/openbmc/enumerate is taking more time. Enumerate is done at suite setup of sensor test. Due to this failure, all sensor test are failing with ConnectionError: HTTPSConnectionPool error. 

This can be resolve by doing GET on /org/openbmc/enumerate with increased timeout value.

**Comment by gkeishin** [comment]
32 test cases are failing in sensor.. this is now a priority defect..

**Comment by rahulmah** [comment]
@gkeishin : Recent checkin (https://gerrit.openbmc-project.xyz/#/c/755/) fixes this issue. Cross checked it and found to be working.

**Comment by rahulmah** [comment]
Still seeing issue on Barreleye. Reopening the issue.
