### ISSUE TITLE
Fix the PNOR SBE corruption related Secureboot violation testcase and documentation

### ISSUE THREAD

**Issue by lkammath** [openbmc/openbmc-test-automation#1643]
Scope of this issue is following

Changes:
    - 1) Update the Test case tags and descriptions (e.g: Use "Secure Cold Boot" instead just "Secure Boot"
    - 2) Checking the error RC instead of Error log/SRC code/Reference code
    - 3) Adding Corrupted SBE image to sandbox path
    - 4) Added more documentation wherever necessary

**Comment by gkeishin** [comment]
In review https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18614/
