### ISSUE TITLE
Automation Python 3.6 compatibility  issue

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1645]
```
$ python -V
Python 3.6.3
```

```
$ robot -v OPENBMC_HOST:xx.xx.xx.xx templates/test_openbmc_setup.robot
[ ERROR ] Error in file '/home/root/openbmc-test-automation/extended/obmc_boot_test_resource.robot': Importing test library '/home/root/openbmc-test-automation/lib/obmc_boot_test.py' failed: OrderedDict mutated during iteration
Traceback (most recent call last):
  File "/home/root/openbmc-test-automation/lib/obmc_boot_test.py", line 47, in <module>
    boot_table = create_boot_table()
  File "/home/root/openbmc-test-automation/lib/boot_data.py", line 71, in create_boot_table
    for sub_state in boot_table[boot][state_key]:
PYTHONPATH:

```

**Comment by maximyep** [comment]
max@myepanes-bmc:~/openbmc/openbmc-test-automation$ git diff lib/boot_data.py
diff --git a/lib/boot_data.py b/lib/boot_data.py
index 070a0e6..abb41b7 100755
--- a/lib/boot_data.py
+++ b/lib/boot_data.py
@@ -68,7 +68,7 @@ def create_boot_table(file_path=None):
         for boot in boot_table:
             state_keys = ['start', 'end']
             for state_key in state_keys:
-                for sub_state in boot_table[boot][state_key]:
+                for sub_state in list(boot_table[boot][state_key]):
                     if sub_state.startswith("os_"):
                         boot_table[boot][state_key].pop(sub_state, None)

**Comment by gkeishin** [comment]
Commit https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18886/

**Comment by gkeishin** [comment]
Thanks @maximyep for the feedback.. @micwalsh has the fix out there and clean on 
```
Python 3.6.3
Python 3.4.2
Python 2.7.8
```

**Comment by maximyep** [comment]
Fixed, needed to be closed.

**Comment by sivassrr** [comment]
Fix can be closed automatically once the corresponding commit gets merged.
