### ISSUE TITLE
update utility which creates CSV file for metrics

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#1652]
A new change requested in
 https://github.com/openbmc/openbmc-test-automation/blob/master/tools/ct_metrics/gen_csv_results.py
  l_test_type:
       It could be functional, DVT etc.. so dont default, take it from user. 
       If nothing is given, default to FVT (functional verification test)
  l_proc:
      If nothing is given, default to OPENPOWER```

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18818

**Comment by gkeishin** [comment]
Merged
