### ISSUE TITLE
DMTF Redfish-JsonSchema-ResponseValidator 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1656]
- [x] Test BMC using Redfish-JsonSchema-ResponseValidator 
- [x] Test code to call this DMTF tool
- [x] Package installation

**Comment by maximyep** [comment]
Bug and related files:

https://github.com/openbmc/bmcweb/issues/57
https://github.com/openbmc/bmcweb/blob/d45d2d0f40413ca91af7fdc2f08b71f2bd828825/static/redfish/v1/%24metadata/index.xml#L1316
https://github.com/openbmc/bmcweb/blob/master/scripts/update_schemas.py#L98

**Comment by gkeishin** [comment]
@maximyep and I are working on the tool commit

- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18767/

**Comment by gkeishin** [comment]
- [ ] https://github.com/openbmc/bmcweb/issues/58

**Comment by gkeishin** [comment]
- [ ] build script https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-build-scripts/+/18921/
