### ISSUE TITLE
Alternate Fan Settings Needed for Optical Cable Case

### ISSUE THREAD

**Issue by garzam** [openbmc/openbmc-test-automation#1661]
- [x] Test plan
- [x] Verify Test use case
- [x] Automate

**Comment by bradbishop** [comment]
On Fri, Mar 01, 2019 at 05:38:27PM +0000, Marissa Garza wrote:
>Created to cover scenario from Defect SW453065

Please don't include references to internal IBM bugtrackers.

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/19241/

**Comment by gkeishin** [comment]
Merged
