### ISSUE TITLE
Network: BMC MAC address testing

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1675]
Base code 
Configure new valid mac address
configure zero mac
configure broadcast mac
code to handle both error and valid scenario

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/19247/
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18549/
