### ISSUE TITLE
Openbmc: Re test MAC address tests once dev code has fix for MAC issue

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1676]
Re test the MAC test automation suite once following is fixed.
https://github.com/openbmc/bmcweb/issues/43

**Comment by maximyep** [comment]
Current results are:

```
Configure_Broadcast_MAC_And_Verify PASS
Configure_Valid_MAC_And_Verify FAIL
Configure_Zero_MAC_And_Verify PASS

```
Reason why 2 tests are passed: changing of the MAC is not supported.

**Comment by prkatti1** [comment]
@maximyep 2 tests are error scenarios. Althoguh broadcast and Zero MAC are valid MACs but have specific purpose and system should not allow to configure it. Since BMC is not allowing it to configure we are fine.

**Comment by prkatti1** [comment]
Tested on latest master, we are able to configure MAC address.
Opened new issue: https://github.com/openbmc/bmcweb/issues/71.
Closing this issue and will track above issue.
