### ISSUE TITLE
OpenPower SecureBoot: Host boot partition corruption test cases enablement

### ISSUE THREAD

**Issue by lkammath** [openbmc/openbmc-test-automation#1681]
This is rip off from https://github.com/openbmc/openbmc-test-automation/issues/1619

Covers following

- [ ] HBI partition corrupted : Verify Cold boot failure
- [ ] HBB partition corrupted ; Verify cold Boot failure
- [ ] OCC partition corrupted; Verify cold boot failure
- [ ] HBRT partition corrupted; verify cold boot failure
- [ ] HBBL partition corrupted; verify cold boot failure
- [ ] HBD partition corrupted; verify cold boot failure

and some enhancement in the code to use REST interfaces

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/19419/
Commit in review
