### ISSUE TITLE
Network tests: MAC address persistence and reverting to old MAC

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1682]
MAC address persistence and reverting to old MAC.
1. Configure MAC, reboot BMC and check persistency
2. Revert to initial MAC
3. Configure invalid MAC

**Comment by prkatti1** [comment]
gerrit code:
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/19487/

**Comment by sivassrr** [comment]
This changes also address test tear down and which pushes BMC MAC config to original.
