### ISSUE TITLE
FFDC - Improvise file logging via SCP

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1684]
- [ ] Find the list of FFDC collects files
- [ ] Replace them with SCP over cat file and save wherever improves performance.

**Comment by gkeishin** [comment]
https://github.com/openbmc/openbmc-test-automation/blob/master/lib/openbmc_ffdc_methods.robot#L154

for Host 

https://github.com/openbmc/openbmc-test-automation/blob/master/lib/openbmc_ffdc_list.py#L51
if we can scp than cat and write to file..

**Comment by gkeishin** [comment]
@micwalsh hit into trouble when the host logs are huge, doing a cat on a well defined files is a waste of write time operation actually. May not be true for all use cases but the host FFDC is definetely a candidate.

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/20818
