### ISSUE TITLE
HTX run white list error log on bootme

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1687]
- [ ] "Description": "OCC metric data collected"   is logged every 24 hours
- [ ] HTX bootme runs checks for errors every interval set and during shutdown path , so this error is information and known. So need to add a whitelist if this is encountered so that HTX can be run for longer period.

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/19766

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/20028

**Comment by ssombar** [comment]
Print eSELs during HTX run.   Continue run if eSEL are Informational, fail if not.
