### ISSUE TITLE
PreTag 0.8 Testing failure for 'Set the power with string of characters'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#17]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/280)

Robot Test Case failed
Full Name: 	Tests.Test Generic Conf.Set the power with string of characters
Documentation: 	

**BAD PATH** This test case set the power values with string of characters Expectation is to return error.
Start / End / Elapsed: 	20160519 15:17:43.333 / 20160519 15:17:46.618 / 00:00:03.285
Status: 	FAIL (critical)
Message: 	''abcdefg'=='abcdefg'' should not be true.

---

@rahulmah commented on [Tue Jun 14 2016](https://github.com/openbmc/openbmc/issues/280#issuecomment-225851286)

@ratagupt : Can you please look at this failure? I think this test case was never working.

**Comment by gkeishin** [comment]
@ratagupt  

The question here is , we shouldn't be able to set strings of characters in this attribute. It is allowing to set it.. so this needs to be fix not in automation.

Set the power with string of characters :: ***BAD PATH***             ..URI:https://9.3.164.153/org/openbmc/settings/host0/attr/power_cap, method:Put, args:{u'data': {u'data': u'&#*?~'}, u'headers': {u'Content-Type': u'application/json'}}
Response code:200, Content:{
  "data": null, 
  "message": "200 OK", 
  "status": "ok"
}
.URI:https://9.3.164.153/org/openbmc/settings/host0/attr/power_cap, method:Get, args:{}
Response code:200, Content:{
  "data": "&#*?~", 
  "message": "200 OK", 
  "status": "ok"
}
Set the power with string of characters :: ***BAD PATH***             | FAIL |
''&#*?~'=='&#*?~'' should not be true.
------------------------------------------------------------------------------

==============================================================================
Test Generic Conf :: This suite will verifiy the Generic Configuration Rest...
==============================================================================
Set the power with string of characters :: ***BAD PATH***             ..URI:https://9.3.164.153/org/openbmc/settings/host0/attr/power_cap, method:Put, args:{u'data': {u'data': u'May the force be with U for allowing me to write badly'}, u'headers': {u'Content-Type': u'application/json'}}
Response code:200, Content:{
  "data": null, 
  "message": "200 OK", 
  "status": "ok"
}
.URI:https://9.3.164.153/org/openbmc/settings/host0/attr/power_cap, method:Get, args:{}
Response code:200, Content:{
  "data": "May the force be with U for allowing me to write badly", 
  "message": "200 OK", 
  "status": "ok"
}
Set the power with string of characters :: ***BAD PATH***             | FAIL |
''May the force be with U for allowing me to write badly'=='May the force be with U for allowing me to write badly'' should not be true.

**Comment by gkeishin** [comment]
Duplicate

https://github.com/openbmc/openbmc-test-automation/issues/26
