### ISSUE TITLE
OpenPower SecureBoot: Host boot partition corruption test cases enablement - Phase II

### ISSUE THREAD

**Issue by lkammath** [openbmc/openbmc-test-automation#1704]
Will cover following scenarios automation in March 21 - April 3  possibly

Payload partition corrupted : Verify Cold Boot failure
HCODE partition corrupted; verify cold boot failure
BOOTKERNEL partition corrupted; verify cold boot failure
CAPP partition corrupted; verify cold boot failure
WOFDATA partition corrupted; verify cold boot failure
MEMD partition corrupted; verify cold boot failure

**Comment by lkammath** [comment]
Will be checking in code today

CAPP is invalid for Witherspoon. Rest all implemented

**Comment by gkeishin** [comment]
- [ ] In review https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/20571/
