### ISSUE TITLE
FFDC Enable or Disable switch. 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1707]
FFDC collection should be enabled by default as it is now. 

When you are trying to run some sample test / regression, We should have a switch to enable or disable FFDC collection. 

With that we can avoid delay in regression or use the system time wisely. 

Mostly, currently we call it at the time of test failure. We should collect FFDC based on user input in the form of argument during the invocation.

Logic is as follows:

Create a argument variable say  FFDC_Disable="Y" 
```
IF "FFDC_Disable" = "Y" 
     Do normal FFDC collection at the time of test failure
Else
     Skip  FFDC collection for test case failure
Endif
```

**Comment by sivassrr** [comment]
Need to get Shiva Prasad id shnayak2 is not working currently to assign it.

**Comment by mdmillerii** [comment]
```
 IF "FFDC_Disable" = "Y" 
     Do normal FFDC collection at the time of test failure
Else
     Skip  FFDC collection for test case failure
Endif
```
That logic looks exactly backwards to me, @sivassrr .

**Comment by sivassrr** [comment]
@mdmillerii  Thank you. While preparing code it is taken care. Currently it is under test. 
```
 IF "FFDC_Disable" = "Y" 
     Skip  FFDC collection for test case failure
 Else
      Do normal FFDC collection at the time of test failure
Endif
```

**Comment by gkeishin** [comment]
export   OVERRIDE_FFDC_ON_TEST_CASE_FAIL=1
To disable FFDC collection
