### ISSUE TITLE
Redfish local user management - manual and automation test

### ISSUE THREAD

**Issue by sansomas** [openbmc/openbmc-test-automation#1721]
Automated below test cases:
====================
- [x] 7 )  Delete a redfish user with admin privilege role and verify its successfully deleted
	A) Delete a redfish user with admin privilege role
		Command to create user : Refer to Delete_User ( End of Document ) with RoleId as "Administrator"
	B) Try to login after deleting the user
	C) It should report an error

        Status : PASS
        Gerrit link : https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/19326
	
- [x] 8 )  Delete a redfish user with operator privilege role and verify its successfully deleted
	A) Delete a redfish user with operator privilege role
		Command to create user : Refer to Delete_User ( End of Document ) with RoleId as "Operator"
	B) Try to login after deleting the user
	C) It should report an error

        Status : PASS
        Gerrit link : https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/19326
	
- [x] 9 )  Delete a redfish user with user privilege role and verify its successfully deleted
	A) Delete a redfish user with user privilege role
		Command to create user : Refer to Delete_User ( End of Document ) with RoleId as "User"
	B) Try to login after deleting the user
	C) It should report an error

        Status : PASS
        Gerrit link : https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/19326
	
- [x] 10)  Delete a redfish user with callback privilege role and verify its successfully deleted
	A) Delete a redfish user with callback privilege role
		Command to create user : Refer to Delete_User ( End of Document ) with RoleId as "Callback"
	B) Try to login after deleting the user
	C) It should report an error

        Status : PASS
        Gerrit link : https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/19326

**Comment by gkeishin** [comment]
Sub task from Redfish local user management #1529
