### ISSUE TITLE
FFDC to collect RHEL sosreport

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1736]
sosreport --batch  --tmp-dir /var/tmp/

sosreport (version 3.5)

This command will collect diagnostic and configuration information from
this Red Hat Enterprise Linux system and installed applications.

An archive containing the collected information will be generated in
/var/tmp/sos.Wy9FES and may be provided to a Red Hat support
representative.

Any information provided to Red Hat will be treated in accordance with
the published support policies at:

  https://access.redhat.com/support/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

 Setting up archive ...
 Setting up plugins ...
....

...
  Running 92/98: udev...
  Running 93/98: usb...
  Running 94/98: vhostmd...
  Running 95/98: x11...
  Running 96/98: xen...
  Running 97/98: xfs...
  Running 98/98: yum...

Creating compressed archive...

Your sosreport has been generated and saved in:
  /var/tmp/sosreport-xx.xx.xx.xx-20190409051857.tar.xz

The checksum is: 784640ed2294f778f560f93f33a2f42b

Please send this file to your support representative.

**Comment by gkeishin** [comment]
```
sosreport --batch  --tmp-dir /var/tmp/ --name=opal_log
```
```
Your sosreport has been generated and saved in:
  /var/tmp/sosreport-opallog-20190409052632.tar.xz
```

**Comment by gkeishin** [comment]
Heading to @ssombar to add this one up..

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/24590

**Comment by ssombar** [comment]
I'm told Ubuntu has this tool too.

**Comment by gkeishin** [comment]
Thanks @ssombar
