### ISSUE TITLE
[Automation] Clear persistent files in update process

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#175]
This is to validate this https://github.com/openbmc/openbmc/issues/635

Looks like we need to flush the file persistency during update.  However need to check if that impacts other BMC network setting perserve settings

**Comment by mdmillerii** [comment]
You will notice a proposal to use systemd to update the passwd file.

**Comment by gkeishin** [comment]
This working with MFG team so that they can do part of their update...

**Comment by gkeishin** [comment]
No longer applicable. closing
