### ISSUE TITLE
Redfish : Certificate Manual testing 

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1766]
This task is to test certificate via Redfish

**Comment by rahulmah** [comment]
### Certificate Manual Testing


### Good Path
- [ ] Verify server certificate view via Redfish - `Passed`
1. Install valid https server certificate via Redfish.
2. Verify installed certificate via Redfish's view server certificate.


- [ ] Verify server certificate view via Openssl - `Fails after uploading new server certificate.`
1. Install valid https server certificate via Redfish
2. Verify installed certificate has been uploaded via openssl tool.
openssl s_client -connect <BMC_IP>:443 -showcerts


- [ ] Verify client certificate view via Redfish - `Passed`
1. Install valid ldap client certificate via Redfish.
2. Verify installed certificate via Redfish's view client certificate.


- [ ] Verify CA certificate view via Redfish - `Fails CA certificate via REST fails.`
1. Install valid CA certificate via Redfish.
2. Verify installed certificate via Redfish's view CA certificate.


- [ ] Verify replace server certificate via Redfish - `Passed`
1. Install valid server certificate via Redfish.
2. Replace server certificate via Redfish.
3. Verify replaced certificate via Redfish's view server certificate.


- [ ] Verify replace client certificate via Redfish  - `Passed`
1. Install valid client certificate via Redfish.
2. Replace client certificate via Redfish.
3. Verify replaced certificate via Redfish's view client certificate.


- [ ] Verify replace CA certificate via Redfish - `NA. CA certificate replace uri will not be supported.`
1. Install valid CA certificate via Redfish.
2. Replace CA certificate via Redfish.
3. Verify replaced certificate via Redfish's view CA certificate.

- [ ] Verify Generate CSR via Redfish - `Passed`
1. Generate CSR via Redfish.
2. Verify generated CSR via Redfish.


- [ ] Test not yet valid https server certificate install - `Passed'
1. Install not yet valid https server certificate via Redfish 
2. Verify using Redfish view certificate that server certificate is uploaded in BMC.
openssl s_client -connect <BMC_IP>:443 -showcerts


- [ ] Test not yet valid ldap client certificate install - `Passed'
1. Install not yet valid ldap client certificate via Redfish
2. Verify using Redfish view certificate that client certificate is uploaded in BMC



- [ ] Test certificate persistence after BMC code update. - `Fails. https certificate does not persist after code update.`
1. Install valid https server and ldap client certificate via Redfish
2. Perform BMC code update. 
3. Verify certificate persistency after code update.


- [ ] Test certificate clean up after factory reset. - `Fails. System generated https certificate is not visible vi Redfish`
1. Install valid https server and ldap client certificate via Redfish
2. Perform factory reset. 
3. Verify that after a factory reset, bmcweb auto generates a self signed certificate for https server. 4. Also verify that LDAP certificates is not present after factory reset. 


- [ ] End to end verification of ldap client certificate verification
1. Install client and CA certificate on BMC and create secure CA config.
2. Now check if we are able to login to BMC via secure path(ldaps). Authentication should pass here.


- [ ] End to end verification of ldap client expired certificate verification
1. Install expired client and valid CA certificate on BMC and create secure CA config.
2. Now check if we are able to login to BMC via secure path(ldaps). Authentication should fail here.


- [ ] CA certificate upload of server certificate verification
1. Install CA certificate for https server on BMC.
2. Now verify trusted mark in OpenBMC GUI and other certificate details




### Bad Path

- [ ] Test invalid https server certificate replace - `Passed. getting internal error but that is already tracked`
1. Install valid https server certificate via Redfish.
2. Replace https server certificate with invalid certificate(empty private key, empty certificate, invalid private key, corrupted certificate, invalid format) via Redfish
3. Verify error while replacing invalid https server certificate.


- [ ] Test invalid ldap client certificate install - `Fails. InternalError while uploading invalid certificate.`
1. Install invalid ldap client certificate(empty private key, empty certificate, invalid private key, corrupted certificate, invalid format) via Redfish.
2. Verify error while installing invalid certificate.


- [ ] Test client CA certificate install with Empty certificate - `Cant run as feature not available`
1. Install invalid ldap client CA certificate(with empty certificate) via REST /xyz/openbmc_project/certs/authority/ldap 
2. Verify error while installing empty certificate.


- [ ] Test expired https server certificate install - `Passed. getting internal error but that is already tracked`
1. Install expired https server certificate via Redfish.
2. Verify error while installing expired certificate..


- [ ] Test expired ldap client certificate install - `Passed. getting internal error but that is already tracked`
1. Install expired ldap client certificate via Redfish.
2. Verify error while installing expired certificate.

**Comment by gkeishin** [comment]
Completed for last sprint. Open new for pending task
