### ISSUE TITLE
OpenBMC Functional Test specification

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1769]
Based on discussion in test community call, Have come up with OpenBMC functional test specification. Thanks to @joseph-reynolds for taking look and review it. 
[OpenBMC FVT Community June Release FVT specification V1.docx](https://github.com/openbmc/openbmc-test-automation/files/3205551/OpenBMC.FVT.Community.June.Release.FVT.specification.V1.docx)

**Comment by krtaylor** [comment]
This is excellent. Please convert to markdown (.md) and push it to gerrit for review. You can mark it as WIP if it is not fully ready.

**Comment by gkeishin** [comment]
This looks promising but here are few points we need to look at before committing to it
> 1.  Who is going to sign those off per release. Shouldn't be specific responsibility to org or individual test competency 
> 2.  We should look at it more like a release content doc then spec.
> 3.  also not make FVT specific at the same time, need to keep generic test. 
> 4.  And also post it to mailing list once you see its good to share with the community

**Comment by joseph-reynolds** [comment]
I like how it breaks down the testing into
- unit test performed by contributors
- function test performed by testers
- regression tests, largely performed by automated test cases

**Comment by sivassrr** [comment]
[OpenBMC FVT Community June Release FVT specification V2.docx](https://github.com/openbmc/openbmc-test-automation/files/3235413/OpenBMC.FVT.Community.June.Release.FVT.specification.V2.docx)
