### ISSUE TITLE
Witherspoon: RAS Reset Reload related automation scenarios

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#1772]
RAS Reset Reload related automation scenarios.

-  Inject checkstop through BMC and do reset reload.
- Inject checkstop through HOST and do reset reload.
- Do reset reload and inject checkstop through BMC when HOST is booting.

**Comment by lkammath** [comment]
What about doing reset reload and then inject check-stop through BMC and host at runime

reverse case of #1 and 2

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/27140/

**Comment by SrideviRamesh** [comment]
Implemented & code is merged
