### ISSUE TITLE
Network- Threshold octet tests

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1773]
Add tests to octet threshold validation.
4th octet lowest and threshold value 
3rd octet lowest and threshold value 
2nd octet lowest and threshold value 
1st octet lowest and threshold value

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/22078/
