### ISSUE TITLE
BMC File mirroring from REST to Redfish

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1786]
tests/test_bmc_file_mirroring.robot

to 
redfish/extended/

However there are code needed to change to update Host name using redfish

**Comment by gkeishin** [comment]
- [ ] git mv tests/test_bmc_file_mirroring.robot redfish/extended/
- [ ] Change the bellow with Redfish logic
```
    ${host_name_dict}=  Create Dictionary  data=${mirror_filename}
    Write Attribute  ${NETWORK_MANAGER}config  HostName  data=${host_name_dict}
    ...  verify=${TRUE}  expected_value=${mirror_filename}
```

**Comment by susilsi7** [comment]
Gerrit Link : https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/22693/
