### ISSUE TITLE
PreTag 0.8 Testing failure for 'Set the power with greater then MAX_POWER_VALUE'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#18]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/281)

Full Name: 	Tests.Test Generic Conf.Set the power with greater then MAX_POWER_VALUE
Documentation: 	

**BAD PATH** This test case sets the power value which is greater then MAX_ALLOWED_VALUE,Expectation is to return error
Start / End / Elapsed: 	20160519 15:17:46.619 / 20160519 15:17:50.565 / 00:00:03.946
Status: 	FAIL (critical)
Message: 	1010 == 1010

---

@rahulmah commented on [Tue Jun 14 2016](https://github.com/openbmc/openbmc/issues/281#issuecomment-225853114)

@ratagupt : It seem like we are able to set power with value greater then 1000(like 1010 of your test case). Please let us know if a test case problem or it is fw issue.

**Comment by gkeishin** [comment]
Already place holder for it.. duplicate

https://github.com/openbmc/openbmc-test-automation/issues/26

Closing
