### ISSUE TITLE
Barreleye: CT Run, Evaluate logs and open issues accordingly

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#180]

**Comment by gkeishin** [comment]
Maintained here.. https://github.com/openbmc/openbmc-test-automation/issues/220

**Comment by sivassrr** [comment]
Oops, We need to assign estimate to other issue #220 then (It should be disturbed between Barreley, Witherspoon and Palmetto. )

**Comment by gkeishin** [comment]
Probably add 2 Story point for each System per sprint.. if needed to accommodate as part of the sprint plan..
