### ISSUE TITLE
[Automation] Restore Power off State for Pre Code update process

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#182]
We are seeing this issues where we are doing poweroff and reboot to prepare for update and we found that the system policy due to poweron restore policy if set to HOST_BOOTED results in failure where codeupate pre setup expect it to be BMC_READY.

We would need to ensure the Host policy is set to Poweroff before doing code update to avoid failure..

**Comment by mdmillerii** [comment]
This sounds like a test expectation problem?
