### ISSUE TITLE
GUI : Boot Options - Test plan

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1821]
Dev story - https://github.com/openbmc/phosphor-webui/issues/82

**Comment by SrideviRamesh** [comment]
1. Verify various boot source options under "Default Boot Settings"
    -> Choose various boot source options such as PXE, Hard-drive, Hard-drive in safe mode,
       CD/DVD, BIOS setup, Removable media, Remote media.

2. Verify various boot source options under "One Time Boot Settings".
    -> Select a Boot source type under "Default Boot Settings".
    -> Select option "Boot with one time settings".
    -> Choose various boot options under "One Time Boot Settings".
 
3. Verify Reboot buttons under "Reboot" operation.
    -> Select required boot source type.
    -> verify reboot buttons Orderly/Immediate are functional.

   
4. Verify shutdown buttons under Shutdown operation.
    -> Select required boot source type.
    -> verify shutdown buttons Orderly/Immediate are functional.


5. Verify Reboot operations with "Default Boot Settings".
    -> Select required boot source type.
    -> select reboot buttons Orderly/Immediate to perform reboot operation.
    -> check for a valid message on the pop-up window.
    -> verify if Boot operation is success.
     
6. Verify Reboot operations with "One Time Boot Settings".
   -> Select a Boot source type under "Default Boot Settings".
   -> Select option "Boot with one time settings".
   -> Choose a boot option under "One Time Boot Settings".
   -> select reboot buttons Orderly/Immediate to perform reboot operation.
   -> check for a valid message on the pop-up window.
   -> verify if Boot operation is success.

7. Verify Reboot operations with "One Time Boot Settings" and verify default setting on second boot.
   -> Select a Boot source type under "Default Boot Settings".
   -> Select option "Boot with one time settings".
   -> Choose a boot option under "One Time Boot Settings".
   -> select reboot buttons Orderly/Immediate to perform reboot operation.
   -> verify if Boot operation is success.
   -> Now manually perform reboot operation and verify if default settings are updated on the second boot.
   
8. Verify Shutdown operations with "Default Boot Settings".
    -> Select required boot source type.
    -> select shutdown buttons Orderly/Immediate to perform shutdown operation.
    -> check for a valid message on the pop-up window.
    -> verify if shutdown operation is success.

9. Verify shutdown operations with "One Time Boot Settings".
   -> Select a Boot source type under "Default Boot Settings".
   -> Select option "Boot with one time settings".
   -> Choose a boot option under "One Time Boot Settings".
   -> select Shutdown buttons Orderly/Immediate to perform reboot operation.
   -> check for a valid message on the pop-up window.
   -> verify if shutdown operation is success.

10. Verify Shutdown operations with "One Time Boot Settings" and verify default setting on second boot.
   -> Select a Boot source type under "Default Boot Settings".
   -> Select option "Boot with one time settings".
   -> Choose a boot option under "One Time Boot Settings".
   -> select shutdown buttons Orderly/Immediate to perform reboot operation.
   -> verify if Boot operation is success.
   -> Now manually perform shutdown operation and verify if default settings are updated on the second boot.

11. Verify close button on Reboot operation on pop-window. 
   -> choose a required boot mode.
   -> select reboot buttons Orderly/Immediate to perform reboot operation.
   -> check for a valid message on the pop-up window.
   -> close pop-window before proceeding to boot operation.
   -> verify the updated boot settings.

12. Verify close button on shutdown operation on pop-window.
   -> choose a required boot mode.
   -> select shutdown buttons Orderly/Immediate to perform shutdown operation.
   -> check for a valid message on the pop-up window.
   -> close pop-window before proceeding to boot operation.
   -> verify the updated boot settings.


11. Verify Information icon on "Default Boot Settings" and "One Time Boot Settings".
   -> check for valid information message displayed on clicking information icon symbol on both
      "Default Boot Settings" and "One Time Boot Settings".


12. Verify if correct host name is displayed on boot setting page.
   -> Check if the correct host name is displayed on boot setting page.


13. Verify host state on boot setting page.
   -> Check if correct host state on boot setting page displayed after Reboot/Shutdown operation.

14. Verify Last power operation time on boot setting page.
   -> check the power operation time before reboot/shutdown operation.
   -> Do reboot/shutdown operation and note the time.
   -> Check if right time is displayed after the reboot/shutdown operation.

15. Verify Cancel button on reboot pop-window.
   -> choose a required boot mode.
   -> select reboot buttons Orderly/Immediate to perform reboot operation.
   -> check for a valid message on the pop-up window.
   -> choose cancel button on pop-window before proceeding to boot operation.
   -> verify the updated boot settings.

16. Verify Cancel button on shutdown popup-window.
   -> choose a required boot mode.
   -> select shutdown buttons Orderly/Immediate to perform shutdown operation.
   -> check for a valid message on the pop-up window.
   -> choose cancel button on pop-window before proceeding to boot operation.
   -> verify the updated boot settings.

17. Verify 'Power on' button after shutdown operation.
   -> choose a required boot mode.
   -> select shutdown buttons Orderly/Immediate to perform shutdown operation.
   -> When host is in reachable state check if 'power on' button is displayed.
   -> Select 'power on' option and check the host state.

18. Verify unavailabilty of Reboot/Shutdown operation when host is powering on.
   -> Power on host.
   -> No Reboot/Shutdown operation are displayed.

19. Manually do Shutdown/Reboot operation and verify boot setting page.
   -> Manually do shutdown/Reboot operation.
   -> check no reboot/shutdown operation are available.

20. verify 'Cancel' and 'Saving Settings' buttons on boot setting page.
   -> choose a required boot mode.
   -> choose 'Cancel' button and verify the values on the boot setting page.
   -> choose 'Save Settings' after selecting required boot mode.
   -> check if the pop-window opens and allow to perform reboot/shutdown operation

**Comment by rahulmah** [comment]
@SrideviRamesh : Please find my review comments in the attached doc. 
[Review comments for boot settings.docx](https://github.com/openbmc/openbmc-test-automation/files/3349145/Review.comments.for.boot.settings.docx)

**Comment by rahulmah** [comment]
@dixsie @derick-montague  @gtmills : Please review this GUI boot option test plan and provide you comments.

**Comment by jandraa** [comment]
I noticed in the current Server power operations page, if I start a power operation (reboot, shutdown or turn on) and I refresh the page (using our own refresh button - not the browser refresh) in the middle of an operation, the page reloads with all the buttons instead of the messaging that indicates an operation is in progress. This makes it seem like the operation is cancelled by the refresh but I think it is actually being done because eventually the 'last power operation' time updates.

I am not sure if we need to reload the page with the 'in progress' messaging and keep the operation in progress, or if we need to reload the page as it is now but actually cancel the operation. Personally, I think the operation should continue but we should reload with the appropriate messaging.

@rahulmah It would be great if we could test this works as intended when a page Refresh is triggered in the middle.

**Comment by rahulmah** [comment]
@jandraa : We would like to have "in progress" message. But I believe we don't have REST or Redfish API to let user know that power off is in progress. So doubt if you guys can implement it. Your comment seem to be more related to Server power operations page. As far as testing in "Server power operations page" is concerned, will add this test in that test plan

**Comment by rahulmah** [comment]
@jandraa : I got it now. I see that in boot option screen shot in prototype, I see that you guys display there is "no power operation to display while power operation in progress". We can look for this message while testing reboot and shutdown in boot option page. Thanks for pointing it out.

**Comment by SrideviRamesh** [comment]
Add new testcases which verifies 'TPM Required policy'  disabled.

1. Verify Reboot operations with various 'BOOT SETTING OVERRIDE' options and  disable TPM policy settings.

2. Verify Shutdown operations with various 'BOOT SETTING OVERRIDE' options and  disable TPM policy settings.

3. Verify Reboot operations with "Enable one time boot" and disable TPM policy settings.

4. Verify shutdown operations with "Enable one time boot" and disable TPM policy settings.

5. Enable/Disable 'TPM REQUIRED POLICY' at BMC standby/Runtime and check the display message
