### ISSUE TITLE
GUI : Boot Options - Execution

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1822]
Test plan link - https://github.com/openbmc/openbmc-test-automation/issues/1821

**Comment by SrideviRamesh** [comment]
1. Verify various boot source options under "Default Boot Settings"
    -> Choose various boot source options such as PXE, Hard-drive, Hard-drive in safe mode,
       CD/DVD, BIOS setup, Removable media, Remote media.

2. Verify various boot source options under "One Time Boot Settings".
    -> Select a Boot source type under "Default Boot Settings".
    -> Select option "Boot with one time settings".
    -> Choose various boot options under "One Time Boot Settings".
 
3. Verify Reboot buttons under "Reboot" operation.
    -> Select required boot source type.
    -> verify reboot buttons Orderly/Immediate are functional.

   
4. Verify shutdown buttons under Shutdown operation.
    -> Select required boot source type.
    -> verify shutdown buttons Orderly/Immediate are functional.


5. Verify Reboot operations with "Default Boot Settings".
    -> Select required boot source type.
    -> select reboot buttons Orderly/Immediate to perform reboot operation.
    -> check for a valid message on the pop-up window.
    -> verify if Boot operation is success.
     
6. Verify Reboot operations with "One Time Boot Settings".
   -> Select a Boot source type under "Default Boot Settings".
   -> Select option "Boot with one time settings".
   -> Choose a boot option under "One Time Boot Settings".
   -> select reboot buttons Orderly/Immediate to perform reboot operation.
   -> check for a valid message on the pop-up window.
   -> verify if Boot operation is success.

7. Verify Reboot operations with "One Time Boot Settings" and verify default setting on second boot.
   -> Select a Boot source type under "Default Boot Settings".
   -> Select option "Boot with one time settings".
   -> Choose a boot option under "One Time Boot Settings".
   -> select reboot buttons Orderly/Immediate to perform reboot operation.
   -> verify if Boot operation is success.
   -> Now manually perform reboot operation and verify if default settings are updated on the second boot.
   
8. Verify Shutdown operations with "Default Boot Settings".
    -> Select required boot source type.
    -> select shutdown buttons Orderly/Immediate to perform shutdown operation.
    -> check for a valid message on the pop-up window.
    -> verify if shutdown operation is success.

9. Verify shutdown operations with "One Time Boot Settings".
   -> Select a Boot source type under "Default Boot Settings".
   -> Select option "Boot with one time settings".
   -> Choose a boot option under "One Time Boot Settings".
   -> select Shutdown buttons Orderly/Immediate to perform reboot operation.
   -> check for a valid message on the pop-up window.
   -> verify if shutdown operation is success.

10. Verify Shutdown operations with "One Time Boot Settings" and verify default setting on second boot.
   -> Select a Boot source type under "Default Boot Settings".
   -> Select option "Boot with one time settings".
   -> Choose a boot option under "One Time Boot Settings".
   -> select shutdown buttons Orderly/Immediate to perform reboot operation.
   -> verify if Boot operation is success.
   -> Now manually perform shutdown operation and verify if default settings are updated on the second boot.

11. Verify close button on Reboot operation on pop-window. 
   -> choose a required boot mode.
   -> select reboot buttons Orderly/Immediate to perform reboot operation.
   -> check for a valid message on the pop-up window.
   -> close pop-window before proceeding to boot operation.
   -> verify the updated boot settings.

12. Verify close button on shutdown operation on pop-window.
   -> choose a required boot mode.
   -> select shutdown buttons Orderly/Immediate to perform shutdown operation.
   -> check for a valid message on the pop-up window.
   -> close pop-window before proceeding to boot operation.
   -> verify the updated boot settings.


11. Verify Information icon on "Default Boot Settings" and "One Time Boot Settings".
   -> check for valid information message displayed on clicking information icon symbol on both
      "Default Boot Settings" and "One Time Boot Settings".


12. Verify if correct host name is displayed on boot setting page.
   -> Check if the correct host name is displayed on boot setting page.


13. Verify host state on boot setting page.
   -> Check if correct host state on boot setting page displayed after Reboot/Shutdown operation.

14. Verify Last power operation time on boot setting page.
   -> check the power operation time before reboot/shutdown operation.
   -> Do reboot/shutdown operation and note the time.
   -> Check if right time is displayed after the reboot/shutdown operation.

15. Verify Cancel button on reboot pop-window.
   -> choose a required boot mode.
   -> select reboot buttons Orderly/Immediate to perform reboot operation.
   -> check for a valid message on the pop-up window.
   -> choose cancel button on pop-window before proceeding to boot operation.
   -> verify the updated boot settings.

16. Verify Cancel button on shutdown popup-window.
   -> choose a required boot mode.
   -> select shutdown buttons Orderly/Immediate to perform shutdown operation.
   -> check for a valid message on the pop-up window.
   -> choose cancel button on pop-window before proceeding to boot operation.
   -> verify the updated boot settings.

17. Verify 'Power on' button after shutdown operation.
   -> choose a required boot mode.
   -> select shutdown buttons Orderly/Immediate to perform shutdown operation.
   -> When host is in reachable state check if 'power on' button is displayed.
   -> Select 'power on' option and check the host state.

18. Verify unavailabilty of Reboot/Shutdown operation when host is powering on.
   -> Power on host.
   -> No Reboot/Shutdown operation are displayed.

19. Manually do Shutdown/Reboot operation and verify boot setting page.
   -> Manually do shutdown/Reboot operation.
   -> check no reboot/shutdown operation are available.

20. verify 'Cancel' and 'Saving Settings' buttons on boot setting page.
   -> choose a required boot mode.
   -> choose 'Cancel' button and verify the values on the boot setting page.
   -> choose 'Save Settings' after selecting required boot mode.
   -> check if the pop-window opens and allow to perform reboot/shutdown operation
