### ISSUE TITLE
GUI : Network Settings - Test plan

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1823]
Dev Story - https://github.com/openbmc/phosphor-webui/issues/62

**Comment by NamanNH** [comment]
#1796 GUI: Certificate - Test Plan
GUI Certificate Test plan

Test Test cases :

- [ ] Navigate to Network configuration page
   1.Go to “Server Configuration” => “Network Settings” on the BMC page
   2.Check to see if the page is reachable.

- [ ] Verify all buttons in Network configuration field (e.g. Save, cancel, radio button - DHCP, Static)
   1.Go to “Server Configuration” => “Network Settings” on the BMC page
   2.click on every button to check if it is clickable.


- [ ] Verify BMC IP correctly displayed in static configuration.
   1.Go to “Network Settings” BMC page assign a static IP and save.
   2.Verify via redfish and compare to check if it is same as assigned value.

- [ ] Verify fully qualified domain name.
    1.Go to “Network Settings” BMC page assign a name in FQDN field and save.
    2.Check if FQDN is being accepted. 

- [ ] Verify Network interface
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.check if the number of network interfaces reflected is correct, verify via CLI 

- [ ] Verify DNS server details
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Check if the DNS server displayed is correct, verify via CLI. 

- [ ] Verify MAC address
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Check if the number of MAC address displayed is same as the one from redfish. 

- [ ] Verify setting Default gateway.
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.In the static mode add the default gateway and save.
   3.Check if the number of gateways assigned is same as the one from redfish. 


- [ ] Verify adding new static IP address.
   1.Click on add static IP and subnet, save>
   2.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   3.Click on static button add IP & subnet and save.
   4.Check if the newly added information persists.

- [ ] Add static DNS server
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Make sure to have static IP address, click on add static DNS, enter value, save
   3.Verify newly added DNS server using Redfish

- [ ] Verify cancel button during IP address change.
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click on static button add IP & subnet and click on cancel.
   3.Verify newly added DNS server using Redfish

- [ ]   Verify deleting IP address button.
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click on static button, navigate to the delete button next to the configured IP/Subnet field.
   3.Click on delete button to delete the IP and verify that IP is deleted successfully.

- [ ] Verify deleting DNS server button.
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click on static button, navigate to the delete button next to the configured IP/Subnet field.
   3.Click on delete button to delete the DNS server IP and verify that DNS server IP is deleted successfully.

- [ ] Verify editing IP address button.
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click on static button, navigate to the IP/Subnet field attempt to edit it.
   3.Edit the IP address and verify that the new IP address is modified successfully.

- [ ] Verify information icon at DHCP, FQDN.
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click on “i” icon to see if displays any additional info and verify.

- [ ] Verify setting DHCP configuration (with DNS server off in DHCP configuration)
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click the “dhcp” option click on “DHCP configuration” setting disable “DNS server”.
   3.Verify that DNS server in empty. Check via GUI as well.

- [ ] Verify setting DHCP configuration (with DNS server on in DHCP configuration)
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click the “dhcp” option click on “DHCP configuration” setting enable “DNS server”.
   3.Verify that DNS server in correct. Check via GUI as well.

- [ ] Verify setting DHCP configuration (with NTP server on in DHCP configuration)
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click the “dhcp” option click on DHCP configuration” setting enable “NTP server”.
   3.Check BMC time is synced with DHCP’s NTP server.

- [ ] Verify setting DHCP configuration (with NTP server off in DHCP configuration)
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Click the “dhcp” option click on DHCP configuration” setting disable “NTP server”.
   3.Check BMC time is not synced with DHCP’s NTP server.

- [ ] Verify setting DHCP configuration (with Hostname on in DHCP configuration)
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.Click the “dhcp” option click on DHCP configuration” setting enable “Hostname”.
    3.Check on GUI if newly hostname assigned by DHCP is displayed. 


- [ ] Verify setting DHCP configuration (with Hostname off in DHCP configuration)
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.Click the “dhcp” option click on “DHCP configuration” setting disable “Hostname”.
    3.Check on GUI if previous hostname remains.


- [ ] Verify setting DHCP configuration (with send Hostname on in DHCP configuration)
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.Determine the BMC IP and login via CLI and check hostname.
    3.check the dhcp request and determine hostname sent to the dhcp server is the same as the BMC configured hostname.

- [ ] Verify setting DHCP configuration (with send Hostname off in DHCP configuration)
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.Determine the BMC IP and login via CLI and check hostname.
    3.check the dhcp request and determine hostname sent to the dhcp server is the same as the BMC configured hostname.

- [ ] Verify Cancel button at DHCP configuration.
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.Click the “dhcp” option click on “DHCP configuration” setting and make some changes.
    3.click on the cancel button and verify if data is not set.


- [ ] Verify Static to DHCP switching
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.Click the static button and make some changes and save settings.
    3.switch to dhcp mode and save settings.
    4.go back to static settings and check if the static IP previously assigned does not persist.



Bad path:

- [ ] Verify adding invalid static IP address.
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.Click the static option add an Invalid IP and verify if error message for invalid IP is displayed.

- [ ] Verify setting invalid Default gateway.
    1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
    2.Click the static option edit gateway IP to invalid and verify if error message for invalid Default gateway is displayed.

- [ ] Verify setting invalid FQDN.
   1.Go to “Server Configuration” => “Network Settings” to get to the BMC page.
   2.Edit FQDN to assign an invalid string, verify if error message for invalid FQDN is displayed.

**Comment by rahulmah** [comment]
@derick-montague  @gtmills : Please review this GUI Network test plan and provide you review comments.
