### ISSUE TITLE
Security: To test feature of BMC chip lock down

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#183]
Associated Development story: https://github.com/openbmc/openbmc/issues/258

**Comment by sivassrr** [comment]
@joseph-reynolds your expert advise / suggestion will be good .

**Comment by joseph-reynolds** [comment]
I don't know how this is different from issue 59.  Would this be covered by https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/11164/2/security/obmc-securityarchitecture.md?

**Comment by sivassrr** [comment]
As development not considered this, Will reopen if we get associate issue/feature get open by development.
