### ISSUE TITLE
Redfish Set DateTime TC: Using REST API to set to owner  BMC.

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1838]

**Comment by gkeishin** [comment]
@susilsi7 please talk to @sivassrr and get this done. 

Test    Verify_Set_Time_Using_Redfish

**Comment by sivassrr** [comment]
@susilsi7 Thank you Sushil for looking into it. Pls take a look at the code which I had shared. 
Also in our code - We need to add "To Do:  Need to remove REST calls once Redfish API available" from Redfish/managers code as in located at https://github.com/openbmc/openbmc-test-automation/blob/master/redfish/managers/test_managers_bmc_time.robot

**Comment by susilsi7** [comment]
Gerrit Link: https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/22701/
