### ISSUE TITLE
NTP: Verify DateTime Persist After Reboot

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1851]
Based on discussion with @gkeishin and it seems he hit with this error. 
Hence decided to automated it. 

- [x] Verify DateTime Persist After Reboot

Have ran more than 15 times with automation and manually didnt hit it.

**Comment by gkeishin** [comment]
In review https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/22830/
