### ISSUE TITLE
Security: Security test plan based on new security consideration

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1853]
S.No | Use Case | Results | Comments/Defects
-- | -- | -- | --
1 | Flood   ICMP type 8 packets towards BMC from multiple IPs, check BMC behavior |   | ICMP   flooding, DoS attack
2 | Send   ICMP type 18 message netmask request |   | Security   feature
3 | Send   ICMP type 13 timestamp request |   | Security feature
4 | Inititate   POST method without Auth Token |   |  
5 | Inititate   PUT method without Auth Token |   |  
6 | Inititate   DELETE method without Auth Token |   | Stability   of authentication module
7 | Flood   POST method without Auth Token |   |  
8 | Flood   PUT method without Auth Token |   |  
9 | Flood   DELETE method without Auth Token |   | Stability   of authentication module
10 | Make   10000 wrong login attempts to REST inetrface, in a fast interval without even   waiting for response |   |  
11 | Make   10000 wrong login attempts to Redfish sessions, in a fast interval without   even waiting for response |   |  
12 | Make   10000 wrong login attempts to SSH, in a fast interval without even waiting   for response |   |  
13 | Make   10000 wrong login attempts to IPMI, in a fast interval without even waiting   for response |   | Reducing   attack surface
14 | Check   enabling and disabling feature, when service is disabled its equivalent port   should be closed |   |  
15 | Try   enabling and disabling feature 100 times, when service is disabled its   equivalent port should be closed |   |  
16 | Create   max allowed REST connection sessions, check these sessons are auto cleaned   after timeout value if there is no traffic |   | Security   feature
17 | Create   max allowed Redfish connection sessions, check these sessons are auto cleaned   after timeout value if there is no traffic |   |  
18 | Create   max allowed GUI sessions, check these sessons are auto cleaned after timeout   value if there is no traffic |   |  
19 | Create   max allowed SSH sessions, check these sessons are auto cleaned after timeout   value if there is no traffic |   |  
20 | Create   max allowed connection sessions, check if throws an error on new connection   request |   |  
21 | Create   max allowed REST connection sessions, keep trying establishing sessions |   |  
22 | Create   max allowed Redfish connection sessions, keep trying establishing sessions |   |  
23 | Create   max allowed GUI connection sessions, keep trying establishing sessions |   |  
24 | Create   max allowed SSH connection sessions, keep trying establishing sessions |   |  
25 | Create   max allowed connection sessions, check if throws an error on new connection   request |   | page   refresh will consume lot of resources from server and lead to DoS
26 | Open   http connections, keep refreshing the home page |   |  
27 | Send   continous traffic towards redfish port 443 |   |  
28 | Send   continous traffic towards IPMI port 623 |   |  
29 | Send   continous traffic towards SSH port 22 |   |  
30 | Send   continous traffic towards SOL port 2200 |   |  
31 | Make   10000 wrong login attempts to Rest when LDAP enabled |   |  
32 | Make   10000 wrong login attempts to GUI when LDAP enabled |   |

**Comment by gkeishin** [comment]
Derived from @joseph-reynolds  https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/22106

**Comment by joseph-reynolds** [comment]
This looks like a good start.

I wonder if we can actually do all of the "flooding / DoS" tests.  We may need multiple systems attacking the BMC to cause problems.  But, I think that having a single system attacking the BMC by accident is a foreesable situation, so I am okay with limiting the test cases to those scenarios.

We have existing test cases to check SSH ciphers.  Seee https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/21137.  We should also specify test cases to check which HTTPS and IPMI RAKP ciphers are offered.  I've added a reminder to add this to the Network Threat Model doc - https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/22106 (patch set 6 line 77).

**Comment by gkeishin** [comment]
@prkatti1 can u look at @joseph-reynolds  input there above. .Thanks
