### ISSUE TITLE
LDAP: Read Privilege related test case automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1854]
- [x]  Verify LDAP User With "Callback" which is Read Privilege Should Not Do Host Poweron

- [x]  Verify LDAP User With "User" which is Read Privilege Should Not Do Host Poweron

- [x]  Verify LDAP User With  "Callback" Read Privilege Able To Check Inventory

- [x] Verify LDAP User With  "User" Read Privilege Able To Check Inventory

Above test cases applicable for both secured and non-secured LDAP

**Comment by gkeishin** [comment]
In review
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23053/
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23307/
