### ISSUE TITLE
LDAP: LDAP Service Disabled And LDAP Config

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1860]
This issue to add following 2 test cases: (Applicable for both Secured/Non-secured and also for both AD/OpenLDAP)

- [x] Verify LDAP Service Disable

- [x] Verify LDAP Configuration Created

**Comment by gkeishin** [comment]
@sivassrr can u add the gerrit commit. Thanks

**Comment by sivassrr** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/23307 - It is in review
