### ISSUE TITLE
GUI: SNMP Settings Update - Test Cases

### ISSUE THREAD

**Issue by NamanNH** [openbmc/openbmc-test-automation#1865]
- [ ] Verify if the edit / delete buttons are disabled during the edit phase.
    1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
    2.Click on add manager button.
    3.While populating the fields verify if the edit / delete buttons are disabled.

- [ ] Verify text color of the saved configuration matches the body color.  
   1.Go to “Server Configuration” => “SNMP Settings” on the BMC page
   2.Verify if the saved IP/Port field text color uses the body color.

**Comment by gkeishin** [comment]
@rahulmah please check on this

**Comment by rahulmah** [comment]
Dev story - https://github.com/ibm-openbmc/dev/issues/938. It seems like dev has move this work for OP950
