### ISSUE TITLE
BMC image POST code update test automation - ApplyTime

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1869]
- [x] Upload image
- [x] Verify Update progress
- [x] Verify installation process
- [x] Automation

**Comment by gkeishin** [comment]
- [ ] BMC update with Apply Time OnReset
- [ ] BMC update with Apply Time Immediate

**Comment by gkeishin** [comment]
- [ ] Code update with OnReset
- [ ] Code update with Immediate

**Comment by susilsi7** [comment]
It's in progress.

**Comment by susilsi7** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/24145/
