### ISSUE TITLE
DNS testing and automation via redfish

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1874]
- [x] Verification of existing DNS settings
- [x] DNS configuration and verification
- [x] Revert back to old settings
- [x] Delete DNS server configuration
- [x] DNS persistency testing

**Comment by gkeishin** [comment]
In review:
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23385/

**Comment by prkatti1** [comment]
Automated these tests via:
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23385/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23289/
