### ISSUE TITLE
Automation failure  - Set Asset Tag With Invalid String Length

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1882]
Test failing link below - 

```

  | ${stderr} =      DCMI request failed because: Parameter out of range (c9)  Error setting asset tag!
```

```Set Asset Tag: p4pfmq074CLygoBjYlHnl9a6kUjVDNnPsxbvqsRQbIqN8sEX' does not contain 'parameter out of range'```

**Comment by gkeishin** [comment]
Still need this ? @adathatri @rahulmah  ???

**Comment by adathatri** [comment]
This issue is not seen in latest build 940.13
