### ISSUE TITLE
Enable test scenarios RAS unrecoverable error injection through pdbg tool during HOST boot

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#1889]
Enable test scenarios RAS unrecoverable error injection through pdbg tool during HOST boot

1. Verify Pdbg Unrecoverable Callout Handling For NCUFIR At Host Boot
2. Verify Pdbg Unrecoverable Callout Handling For L3FIR At Host Boot
3. Verify Pdbg Unrecoverable Callout Handling For L2FIR At Host Boot
4. Verify Pdbg Unrecoverable Callout Handling For NXDMAENG At Host Boot
5. Verify Pdbg Unrecoverable Callout Handling For CXA At Host Boot
6. Verify Pdbg Unrecoverable Callout Handling For MCA At Host Boot
7. Verify Pdbg Unrecoverable Callout Handling For MCI At Host Boot
8. Verify Pdbg Unrecoverable Callout Handling For CoreFIR At Host Boot

**Comment by gkeishin** [comment]
- [ ] In review https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23766/

**Comment by gkeishin** [comment]
code merged
