### ISSUE TITLE
Code update required keywords and TFTP / Image URI bad path use case

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1898]
- [x] Invalid image
- [x] Invalid MANIFEST
- [ ] Invalid key type

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/23965/
Needed keyword work for GOOD and bath path use case,

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/24013/

**Comment by susilsi7** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/24901/
