### ISSUE TITLE
PreTag 0.8 Testing failure for 'Set the boot flags with string'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#19]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/282)

Full Name: 	Tests.Test Generic Conf.Set the boot flags with string
Documentation: 	

**BAD PATH** This test case sets the boot flag with some invalid string Expectation is it should not be set.
Start / End / Elapsed: 	20160519 15:17:57.046 / 20160519 15:18:00.763 / 00:00:03.717
Status: 	FAIL (critical)
Message: 	3ab56f == 3ab56f

---

@rahulmah commented on [Tue Jun 14 2016](https://github.com/openbmc/openbmc/issues/282#issuecomment-225853832)

@ratagupt : I think this test case was never passing. Please let me know if it has ever worked.

**Comment by gkeishin** [comment]
Duplicate.. 

https://github.com/openbmc/openbmc-test-automation/issues/26
