### ISSUE TITLE
Fix IPMI Test failure

### ISSUE THREAD

**Issue by adathatri** [openbmc/openbmc-test-automation#1900]

**Comment by adathatri** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/1881, 
https://github.com/openbmc/openbmc-test-automation/issues/1882, 
https://github.com/openbmc/openbmc-test-automation/issues/1883

**Comment by gkeishin** [comment]
There is #1882 tracking.. 2 are fixed. closing this one.
