### ISSUE TITLE
Witherspoon Secure boot Manual testing

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1906]
- [x] End to end manual testing

**Comment by mstrbill** [comment]
6 TERs executed during Sprint. 3 Passed, 3 failed.

**Comment by mstrbill** [comment]
Passed 3 manual TERS during sprint. Still waiting on fix for no eSEL data collection

**Comment by gkeishin** [comment]
Thanks for update @mstrbill

**Comment by gkeishin** [comment]
Closing this manual testing task.. would need to open new one for pending one ahead.
