### ISSUE TITLE
Device Tree verification 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#191]
https://github.com/openbmc/openbmc/issues/421
https://github.com/openbmc/openbmc/issues/629

**Comment by gkeishin** [comment]
I dint think we would need this as part of the functional test.. this is more of the unit test..

**Comment by sivassrr** [comment]
@gkeishin We need to check all the REST interfaces population, right.

**Comment by gkeishin** [comment]
@sivassrr The best way to get answer is to put this question to the development team, if we need anything on this.

**Comment by sivassrr** [comment]
@gkeishin yup, As discussed, we thought of having this discussion in our last design interlock. But it was cancel, we can touch base it on Monday.

**Comment by sivassrr** [comment]
Device Tree check was requested by development.  And there is a difference between AST2500 and AST2400.  Need to check right things are populated and verification should be done.
