### ISSUE TITLE
Develop infrastructure and write Test cases around pldmtool

### ISSUE THREAD

**Issue by lkammath** [openbmc/openbmc-test-automation#1910]
Till date, pldmtool supports two commands

GetPLDMType - Base
GetPLDMVersion - Base

Eventually will add support for GetPLDMCommands and also support taking raw commands as input and give the response back for raw commands sent

The goal of creating this issue is two have following

- [x] Create infrastructure to parse pldmtool response for the various commands sent over MCTP

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/24735/

**Comment by SrideviRamesh** [comment]
We can close this issue.
1. Completed creating test plan and updating it in RQM.
2. Also provided the variable file required for the pldm tool test automation implementation.
