### ISSUE TITLE
Automate CSR test cases

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1932]

**Comment by gkeishin** [comment]
What use case are we looking at here @rahulmah ?

**Comment by rahulmah** [comment]
Use cases
    - Verify CSR generation for server certificate
    - Verify CSR generation for client certificate
    - Verify CSR generation for server certificate with invalid value
    - Verify CSR generation for client certificate with invalid value

**Comment by rahulmah** [comment]
Code in Review - https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/24808/
