### ISSUE TITLE
LDAP automation:  additional bad path scenarios

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1935]
- [ ] - Login as the user defined on the LDAP server with invalid data
- [ ] - Try to access LDAP Authenticated user without password
- [ ] -  Empty the privilege mapping and check that privilege is not working fine
- [ ] - Add LDAP server to openbmc system with out Base dn(Search order) and check it works
- [ ] - Create group with some privilege which doesn't exist on the openbmc

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/24733/
