### ISSUE TITLE
Test the QEMU integration with Palmetto/Witherspoon-bmc machine model

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#194]
#498 Integrate qemu with palmetto-bmc machine model

https://github.com/openbmc/openbmc/issues/498

**Comment by sivassrr** [comment]
Hi Sridevi, Will you be available this sprint. Otherwise, Please work with Prasanth Katti..

**Comment by SrideviRamesh** [comment]
Long back i have finished this task... QEMU testing on plametto... 
please close this task.
