### ISSUE TITLE
Additional LDAP test cases: 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1940]
Around 6 Test cases targeting this sprint.

**Comment by sivassrr** [comment]
- [ ] LDAP Server Config with Invalid Base DN and Invalid Bind DN

- [ ] LDAP Server Config with Invalid Base DN

- [ ] LDAP Server Config with Invalid Bind DN

- [ ]  LDAP Server Config with Invalid Bind DN Password

- [ ] login with a user where user is not defined in the LDAP server and verify that login is not allowed

- [ ] Create Privilege where it is already exist:

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/25040/

IN review
