### ISSUE TITLE
Test expired password via GUI

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1951]
Test expired password via GUI

dev story - https://github.com/ibm-openbmc/dev/issues/1049

This dev story is also need to be resolved - https://github.com/ibm-openbmc/dev/issues/1122

**Comment by rahulmah** [comment]
Test cases

- [ ] Verify setting new password after expired password
- [ ] Verify password persistence while doing code update from OP940 to OP940.01
- [ ] Verify password persistence while doing code update from OP940.01 to OP940
- [ ] Verify no expired password after doing code update from OP940 to OP940.01
- [ ] Verify error message while login with incorrect password after factory reset
- [ ] Verify error message while login with incorrect password after setting new password

**Comment by gtmills** [comment]
@rahulmah Test plan looks good. You should not be referencing internal IBM releases here.

**Comment by rahulmah** [comment]
@gtmills : Thanks for pointing. I have corrected it.
