### ISSUE TITLE
Fix callback test cases which reads - Phase 1

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1954]
With recent changes, callback privilege LDAP user no longer has read permission.
Following test cases to be fixed.

- [ ] Verify LDAP User With Read Privilege Able To Check Inventory

- [ ]  Update_LDAP_Group_Name_And_Verify_Operations

Currently both test cases failing with the latest changes from development.

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/25590/

**Comment by sivassrr** [comment]
Basically callback changes rolled out in IBM release. 
So changes may not go in.

**Comment by sivassrr** [comment]
But will use this issue to improve the code changes and put the callback changes back.
