### ISSUE TITLE
OP940 Witherspoon Secureboot manual regression Test Plan,

### ISSUE THREAD

**Issue by mstrbill** [openbmc/openbmc-test-automation#1957]
1)   Develop regression test plan with Vijay
2)   Run regression TERS by Nov 10th end of OP regression Test
3)  Create and track defects as needed.

**Comment by gkeishin** [comment]
Continued this sprint..

**Comment by gkeishin** [comment]
can we close this ? @mstrbill

**Comment by gtmills** [comment]
@mstrbill We should not reference internal IBM releases out here.
