### ISSUE TITLE
Check host relevant file exists after code update

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1958]
We observe some time /etc/host* related file missing after code update.

**Comment by anoo1** [comment]
They're not missing, they seem to be out of sync with the overlay. If the file in the overlay is deleted, then the files are back to being available.

**Comment by gkeishin** [comment]
- [ ] https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/25981/
