### ISSUE TITLE
PreTag 0.8 Testing failure for 'minimal fan inventory'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#20]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/283)

Full Name:  Tests.Test Inventory.minimal fan inventory
Start / End / Elapsed:  20160519 15:20:33.029 / 20160519 15:20:33.050 / 00:00:00.021
Status:     FAIL (critical)
Message:    '0>4' should be true.

This test checks the number of fans with a presence value of 'True' .  Seems like there is not any

---

@rahulmah commented on [Mon Jun 13 2016](https://github.com/openbmc/openbmc/issues/283#issuecomment-225562159)

Same issue is also seen with miminum cpu, dimm, memory buffer and core.

**Comment by gkeishin** [comment]
No longer valid as we are moving to xyz for inventory
