### ISSUE TITLE
[Automation] Separate branch stream for GAed vs New Systems 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#202]
Branch test code for GA system vs Newer
	- Need a branch / Release checkpoint in github for the Barreleye vs witherspoon

**Comment by sivassrr** [comment]
We can target this for Nov Sprint.

**Comment by gkeishin** [comment]
Now the branch is split.. the master will continue and for GAed https://github.com/openbmc/openbmc-test-automation/tree/v1.0-stable  created..

**Comment by gkeishin** [comment]
@geissonator created "v1.0-stable” branch in test repo. Closing this
