### ISSUE TITLE
[Automation] URI changes for the REST 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#203]
REST changes due to Inventory and URI changes ( Most of the test changes will be impacted)
	- Need to come up with a prefix in resource file so and replace in the code

**Comment by sivassrr** [comment]
We need to have equivalent stories of development. Last sprint as per Andrew/Patrick, Changes were going on. @gkeishin Shall we get all the equivalent stories.

**Comment by gkeishin** [comment]
The new OpenBMC URI would start with /xyz/openbmc_project ahead.
    This means all our existing tests and library would be impacted.

    To make the transition easier from existing /org/openbmc to newer
    /xyz/openbmc_project a new variable is introduced in resource.txt

**Comment by gkeishin** [comment]
More changes will be required for this.. We have already put in lots of code for URI changes in last couple of sprint.. expecting this and next sprint more changes...

**Comment by gkeishin** [comment]
This can be termed closed.. since Dec most of the URI changes doesn't have the git number.. updating the actual spend on it.
