### ISSUE TITLE
[Automation] Error Logging and verification test tools

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#205]
Errorlog Tooling which can be use for create/delete/specify other parameters and use as tool for the error testing
	- Write a wrapper tool and parameterize to test different sets of error logging

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc/issues/727 - Looks like dbus+ interface getting introduced.

**Comment by gkeishin** [comment]
After discussion with Adriana, we have way to generate error log SELs through ipmi.. So will need to work on that aspect.

**Comment by mtritz** [comment]
- [ ] Identify errors that the tool should be able to throw, and how to throw them
- [ ] Develop a tool that can throw a basic error
- [ ] Add capabilities to the tool for each of the identified errors

**Comment by gkeishin** [comment]
This code is merged https://gerrit.openbmc-project.xyz/#/c/2528/  ( tool )

Packaging is still pending https://gerrit.openbmc-project.xyz/#/c/2997/ 
Once merged.. will close this

**Comment by gkeishin** [comment]
Code merged and available in tarball

**Comment by gkeishin** [comment]
@sivassrr any reason we are re-opening this ?

**Comment by sivassrr** [comment]
I think we re

**Comment by sivassrr** [comment]
By mistake, I reopened it.
