### ISSUE TITLE
BMC- VLAN testing and automation

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#2054]
1.Create existing vlan and check for error
2.Add and Delete Vlan multiple 5 times
3.add ip, and delete ip , delete vlan check persistence on reboot
4.create vlan via ipmi when one lan and vlan exist on bmc
5.add & delete vlan reboot bmc multiple times
6.switch off vlan via ipmi when there are multiple vlans
7.swicth off vlan  via ipmi and check vlan deleted
8.modify ip address of vlan via ipmi
9.create multiple vlan through ipmi should not allow
10.delete non existing vlan interface
11.delete vlan when mutiple vlans exist

**Comment by anvesh001** [comment]
@prkatti1 
4..create vlan via ipmi when one lan and vlan exist on bmc
6.switch off vlan via ipmi when there are multiple vlans
7.swicth off vlan via ipmi and check vlan deleted
8.modify ip address of vlan via ipmi
