### ISSUE TITLE
System AutoReboot policy setting

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2057]
```
$ redfishtool -r xx.xx.xx.xx -u root -p 0penBmc123 -S Always raw GET /xyz/openbmc_project/control/host0/auto_reboot
{
    "status": "ok",
    "data": {
        "AutoReboot": true
    },
    "message": "200 OK"
}
```

**Comment by gtmills** [comment]
This can be moved to Redfish

https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32520


curl -k -v  -X PATCH https://${bmc}/redfish/v1/Systems/system -d \
'{"Boot":{"AutomaticRetryConfig": "Disabled"}}'

curl -k -v  -X PATCH https://${bmc}/redfish/v1/Systems/system -d \
'{"Boot":{"AutomaticRetryConfig": "RetryAttempts"}}'
