### ISSUE TITLE
Firmware Factory reset

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2063]
```
/xyz/openbmc_project/software/action/Reset
```

**Comment by gtmills** [comment]
This can be done in Redfish now 

curl -k -X POST \
https://${bmc}/redfish/v1/Managers/bmc/Actions/Manager.ResetToDefaults \
-d '{"ResetToDefaultsType": "ResetAll"}'

https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32991
