### ISSUE TITLE
[Automation] powercap url path need to be taken care in 

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#207]
In Palmetto, url path for power cap is /org/openbmc/sensors/host/PowerCap while in Barreley it is /org/openbmc/sensors/host/powercap. Due to this "Disable PowerCap" test case is failing in Palmetto system. This little difference need to be taken care in automation.

**Palmetto**
```
rahulmah@rackspace:~$ curl -c cjar -b cjar -k https://xx.xx.xx.xx/org/openbmc/sensors/host/PowerCap
{
  "data": {
    "error": 0,
    "units": "",
    "value": 0
  },
  "message": "200 OK",
  "status": "ok"
}rahulmah@rackspace:~$
```

**Barreleye**
```
rahulmah@rackspace:~$ curl -c cjar -b cjar -khttps://9.3.23.32/org/openbmc/sensors/host/powercap
{
  "data": {
    "error": 0,
    "units": "",
    "value": 0
  },
  "message": "200 OK",
  "status": "ok"
```

Test case failing due to this issue.
```
04:15:09 Disable PowerCap :: Test set powercap with 0 and make sure powerca... URI:https://xx.xx.xx.xx/org/openbmc/sensors/host/powercap/action/setValue, method:Post, args:{u'data': {u'data': [0]}, u'headers': {u'Content-Type': u'application/json'}}
04:15:09 Response code:404, Content:{
04:15:09   "data": {
04:15:09     "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /org/openbmc/sensors/host/powercap"
04:15:09   }, 
04:15:09   "message": "404 Not Found", 
04:15:09   "status": "error"
```

**Comment by sivassrr** [comment]
@rahulmah , there was similar issues opened by @gkeishin and he is already working on it, I guess. 
Shall we revisit. And close one of them.

**Comment by gkeishin** [comment]
@sivassrr  This one is different .. @rahulmah is talking about a particular powercap path difference between the Barreleye and Palmetto.. With this he plan to add code to rectify that in the code.. 

However having said that.. this shouldn't really be an Automation but a question to development why they have different Strings naming..

**Comment by rahulmah** [comment]
@spinler : PowerCap path differs between Palmetto and Barreleye. Please let us know if there is plan to correct it or we have to live with such cases and handle them in our automation.

**Comment by spinler** [comment]
Yea, looks like they are just written differently in the .py config files.  I don't know the history behind it though. 
 @causten @ratagupt  Is it safe to change the PowerCap in Palmetto.py to powercap like in barreleye?

**Comment by rahulmah** [comment]
Opened https://github.com/openbmc/openbmc-test-automation/issues/207 issue in openbmc for the same. So closing this.
