### ISSUE TITLE
VLAN via IPMI- Restore primary IP when multiple IPs exist on BMC before VLAN configuration

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#2078]
Restore network when multiple IPs exist on BMC before VLAN configuration.
1. When LAN & VLAN exist with IP address configured
2. When LAN is configured with multiple IPs

**Comment by anvesh001** [comment]
@prkatti1 
1.When LAN & VLAN exist with IP address configured
