### ISSUE TITLE
Fix the input entry for Verify SetStateEffecterStates

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#2080]
Earlier 

pldmtool platform GetPDR -d <effecterID, requestSet, effecterState>

pldmtool platform SetStateEffecterStates -d 1 1 1

Now

pldmtool platform GetPDR -i <effter_handle> -c <count>  -d <effecterID, effecterState>

 pldmtool platform SetStateEffecterStates -i 1 -c 1 -d 1 1

**Comment by SrideviRamesh** [comment]
For more information refer to https://github.ibm.com/openbmc/openbmc/blob/master/meta-ibm/meta-witherspoon/recipes-phosphor/pldm/pldm/11.json

https://www.dmtf.org/sites/default/files/standards/documents/DSP0249_1.0.0.pdf

**Comment by gkeishin** [comment]
fixed https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/30207/
