### ISSUE TITLE
Remove TimeOwner interface

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2089]
Reference mailing list Thread:   https://lists.ozlabs.org/pipermail/openbmc/2020-April/021409.html

```
- Remove TimeOwner feature :                          https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-time-manager/+/31278/
- Consume changes to NTP/MANUAL settings immediately: https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-time-manager/+/31284/
```
we will need to refresh our test code too.. So I have created a github task to fix our code..

**Comment by gkeishin** [comment]
is this one @adathatri  done ?

**Comment by adathatri** [comment]
@gkeishin Time owner feature change is done. The dev code is still not merged to consume NTP/Manual settings immediately.

**Comment by adathatri** [comment]
Code merged.
- Remove TimeOwner feature :  https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/32912
- Consume changes to NTP/MANUAL settings immediately: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/34199
