### ISSUE TITLE
Fix  Redfish_Usecase_Checkers.robot  suite

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2090]
```
From: David Wang (王振宇) 
Sent: Tuesday, May 5, 2020 11:36 AM
To: 'gkeishin@in.ibm.com' <gkeishin@in.ibm.com>
Cc: 'openbmc@lists.ozlabs.org' <openbmc@lists.ozlabs.org>
Subject: Runing openbmc-test-automation with latest DMTF tool
 
Hi George:
 
I’m testing my BMCs with Redfish_Usecase_Checkers.robot which is using DMTF tool clone from github.com/DMTF/Redfish-Usecase-Checkers.git
 
The reason for the failure is that the latest DMTF tool can’t recognize -v argument in account_management.py, and –F in power_control.py.
 
Do you have any suggestion? Is it fine if I only restore the DMTF tool with previous revision and test my BMCs?
 
Thanks
Best Regards,
David
 
```

**Comment by gkeishin** [comment]
We havent updated the test code to take the latest args.. looking for volunteer here to fix :)

**Comment by gkeishin** [comment]
@manashsarma can u take a look

**Comment by manashsarma** [comment]
Yes I have started looking

**Comment by manashsarma** [comment]
As per first level analysis, it looks like that '-v' and '-F' are unrecognized arguments for respective commands as I checked using help:

1. 
bash-4.2$ python3 Redfish-Usecase-Checkers/account_management/account_management.py -h
usage: account_management.py [-h] --user USER --password PASSWORD --rhost
                             RHOST [--Secure SECURE] [--directory DIRECTORY]

Usecase checker for account management

optional arguments:
  -h, --help            show this help message and exit
  --user USER, -u USER  The user name for authentication
  --password PASSWORD, -p PASSWORD
                        The password for authentication
  --rhost RHOST, -r RHOST
                        The address of the Redfish service
  --Secure SECURE, -S SECURE
                        When to use HTTPS (Always, IfSendingCredentials,
                        IfLoginOrAuthenticatedApi, Never)
  --directory DIRECTORY, -d DIRECTORY
                        Output directory for results.json

2.
bash-4.2$ python3 Redfish-Usecase-Checkers/power_control/power_control.py -h
usage: power_control.py [-h] --user USER --password PASSWORD --rhost RHOST
                        [--Secure SECURE] [--directory DIRECTORY]

Usecase checker for power and reset operations

optional arguments:
  -h, --help            show this help message and exit
  --user USER, -u USER  The user name for authentication
  --password PASSWORD, -p PASSWORD
                        The password for authentication
  --rhost RHOST, -r RHOST
                        The address of the Redfish service
  --Secure SECURE, -S SECURE
                        When to use HTTPS (Always, IfSendingCredentials,
                        IfLoginOrAuthenticatedApi, Never)
  --directory DIRECTORY, -d DIRECTORY
                        Output directory for results.json

Additionally, I found no implementation of arguments '-v' and '-F' inside the respective python command files :

'Redfish-Usecase-Checkers/account_management/account_management.py' and
Redfish-Usecase-Checkers/power_control/power_control.py

**Comment by dvcyw** [comment]
I think they were modified by the following commits:
[Modified account management checker to leverage Tacklebox](https://github.com/DMTF/Redfish-Usecase-Checkers/commit/b8475d5427f1bc27411e04b1e82e8cc3a30959b4#diff-061ddbfd7af81715fb123e004bb093e6)
[Updated power control to use redfish_utilities](https://github.com/DMTF/Redfish-Usecase-Checkers/commit/95cd6499467192b2b14bbad827b2337ec64fad01#diff-99caca55eb0df4a5aea5789ce5ba3e6d)

**Comment by manashsarma** [comment]
As 'Redfish-Usecase-Checkers/account_management/account_management.py' and  'Redfish-Usecase-Checkers/power_control/power_control.py'  no longer supports the arguments -v and -F, the robot script 'Redfish_Usecase_Checkers.robot' should not use these the arguments for these two python command files.

**Comment by gkeishin** [comment]
In Review https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/33359/
@dvcyw

**Comment by manashsarma** [comment]
I am doing the this task " in phase wise. In first commit, I am focusing on correcting and improving the test case 'Test BMC Redfish Account Management' which is about account management use cases.  I have pushed the changes for this and waiting for review comment.

I shall do the fix of related test cases of 'power control'  through another commit. For test case related to power control use cases, it would require some investigation.

**Comment by gkeishin** [comment]
Sounds like a plan there.. looking forward to it @manashsarma

**Comment by gkeishin** [comment]
Code fixed in test.. merged
