### ISSUE TITLE
[Redifsh] Do not hard code server-id and chassis-id

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/openbmc-test-automation#2091]
In Redfish test cases, the `server-id` and the `chassis-id` are hard-coded to `system` and `chassis`.
Real systems could use different names, and when running the HW CI on such systems, it will fail because the hard-coded URL does not exist.

So the test cases should be "improved" to get the `server-id` and `chassis-id` dynamically.
Both could be got from the `@odata.id` in `Members` of below example query:
```
$ curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Systems/
{
...
  "Members": [
    {
      "@odata.id": "/redfish/v1/Systems/foo"
    }
  ],
}

$ curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Chassis
{
...
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/bar"
    }
...
}
```

**Comment by gkeishin** [comment]
That's a good point there.. we will try to improvise it.

**Comment by Jayashree-D** [comment]
I am also facing this issue. Is there any updates on this part?

**Comment by gkeishin** [comment]
@Jayashree-D 

There are code to find the id or object properties from a given path like in the above example. 

If you have a particular test you are looking for in the test repo where you are facing this, let me know , so that I can use that test as starting point to tweak/add further logic to dynamically load and find it. That would help.

**Comment by Jayashree-D** [comment]
While testing "Test Power Reading Via IPMI With Host Booted", the get attribute for redfish is hard-coded as /redfish/v1/Chassis/chassis/Power.

In my case, the path present in redfish is /redfish/v1/Chassis/TiogaPass_Baseboard/Power.

**Comment by gkeishin** [comment]
Suppose we do a  search of base   `/redfish/v1/Chassis/`  and look up for `Power`
we end up finding these example :

```
/redfish/v1/Chassis/chassis/Power
/redfish/v1/Chassis/motherboard/Power
```

both are in the same path but under different context of the chassis vs motherboard.  but yeah I ll add up a logic first to get the possible paths containing the endpoint in the redfish path under a given base path

**Comment by gkeishin** [comment]
This needs to be done in 3 commits
1.  Initial changes to find the list dynamically https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/34640/
2.  changes to get property based on the caller and embed the above function logic
3. Update the test case 

2 and 3 are work in progress.

**Comment by leiyu-bytedance** [comment]
> This needs to be done in 3 commits
> 
> 1. Initial changes to find the list dynamically https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/34640/

I am not sure if this is the right direction.
The issue here is due to the **hard-coded** `system` and `chassis`, and this could be retrieved by query the Redfish API.
So I was expecting some code to read the response of the `/redfish/v1/Systems`, `/redfish/v1/Chassis`, parse the json response, get the corrected `server-id` and the `chassis-id`, and use them in future requests.

I am not sure why it needs regex to parse the URL.

**Comment by gkeishin** [comment]
Thats right, you wont need to hard code when all the pieces are done. this piece is to walk through all the paths under any given base path

example, to find  say end point `Power` in this case under /redfish/v1/Chassis

sample code:
```
    ${power}=  redfish_utils.Get Endpoint Path List  /redfish/v1/Chassis/  Power
    Log To Console  \n ${power}
```

```
#(CDT) 2020/07/13 23:53:40.682226 -    0.022657 - Executing: list_request(resource_path = '/redfish/v1/Chassis/')

['/redfish/v1/Chassis/chassis/Power', '/redfish/v1/Chassis/motherboard/Power']
```

like I said this is the initial piece for the whole scheme of things to reach to there. 

There will be another 2nd part to get the id's and the properties under the cover in next commit. 

so accessing to get the corrected `server-id` and the `chassis-id`,  to it find it and test can use them.

**Comment by leiyu-bytedance** [comment]
> There will be another 2nd part to get the id's and the properties under the cover in next commit.
> 
> so accessing to get the corrected `server-id` and the `chassis-id`, to it find it and test can use them.

Good to know!

**Comment by gkeishin** [comment]
_Sample test
    ${valid_list}=  redfish_utils.Get Members URI  /redfish/v1/Chassis/  PowerSupplies
    Log To Console  \n ${valid_list}_


**Here the sample code to call the base path with given attribute to search if it exist in /redfish/v1/Chassis/**

**Example:**
_/redfish/v1/Chassis/foo/Power
{
    "PowerSupplies": [
        {
            "@odata.id": "/redfish/v1/Chassis/foo/Power#/PowerSupplies/0",
            "EfficiencyPercent": 90,
            "IndicatorLED": "Off",
            "Manufacturer": "",
            "MemberId": "powersupply0",
            "Model": "0000",
            "Name": "powersupply0",
            "PartNumber": "",
            "PowerInputWatts": 0.0,
            "SerialNumber": "",
            "Status": {
                "Health": "Critical",
                "State": "Enabled"
            }
        },_


**Here is what the run would look like when called from the test code**

**<Gives the list of members under the base path /redfish/v1/Chassis/ >**
_#(CDT) 2020/07/14 08:38:21.001387 -    0.069105 - Executing: get('/redfish/v1/Chassis/')
['/redfish/v1/Chassis/chassis', '/redfish/v1/Chassis/motherboard']_

**<The code then iterate and find all the child nodes in the path>**
_#(CDT) 2020/07/14 08:38:21.069960 -    0.068573 - Executing: list_request(resource_path = '/redfish/v1/Chassis/chassis')
['/redfish/v1/Chassis/chassis', '/redfish/v1/Chassis/chassis/Power', '/redfish/v1/Chassis/chassis/Sensors', '/redfish/v1/Chassis/chassis/Sensors/ps0_input_power', '/redfish/v1/Chassis/chassis/Sensors/ps0_output_current', '/redfish/v1/Chassis/chassis/Sensors/ps1_input_power', '/redfish/v1/Chassis/chassis/Sensors/ps1_output_current', '/redfish/v1/Chassis/chassis/Thermal', '/redfish/v1/Systems/system/PCIeDevices']_

**<The code then iterate and find all the child nodes in the path>**
_#(CDT) 2020/07/14 08:38:23.246497 -    0.071443 - Executing: list_request(resource_path = '/redfish/v1/Chassis/motherboard')
['/redfish/v1/Chassis/motherboard', '/redfish/v1/Chassis/motherboard/Power', '/redfish/v1/Chassis/motherboard/Sensors', '/redfish/v1/Chassis/motherboard/Thermal', '/redfish/v1/Systems/system/PCIeDevices']_

<Does a GET check while the above is iterating and list ONLY the one which the test is looking for e.g PowerSupplies >

<**A path which is dyanamically search and listed>**
_['/redfish/v1/Chassis/chassis/Power']_


------------------------------------------
**Another example where PowerControl could be found in multiple place**

_Sampe Test 
    ${valid_list}=  redfish_utils.Get Members URI  /redfish/v1/Chassis/  PowerControl
    Log To Console  \n ${valid_list}_


**<A path which is dynamically search and listed>**
_['/redfish/v1/Chassis/chassis/Power', '/redfish/v1/Chassis/motherboard/Power']_


_/redfish/v1/Chassis/motherboard/Power
{
    "@odata.id": "/redfish/v1/Chassis/motherboard/Power",
    "@odata.type": "#Power.v1_5_2.Power",
    "Id": "Power",
    "Name": "Power",
    "PowerControl": [
        {
            "@odata.id": "/redfish/v1/Chassis/motherboard/Power#/PowerControl/0",
            "@odata.type": "#Power.v1_0_0.PowerControl",
            "MemberId": "0",
            "Name": "Chassis Power Control",
            "PowerLimit": {
                "LimitException": "NoAction",
                "LimitInWatts": null
            }
        }
    ],_


_/redfish/v1/Chassis/chassis/Power
{
    "@odata.id": "/redfish/v1/Chassis/chassis/Power",
    "@odata.type": "#Power.v1_5_2.Power",
    "Id": "Power",
    "Name": "Power",
    "PowerControl": [
        {
            "@odata.id": "/redfish/v1/Chassis/chassis/Power#/PowerControl/0",
            "@odata.type": "#Power.v1_0_0.PowerControl",
            "MemberId": "0",
            "Name": "Chassis Power Control",
            "PowerLimit": {
                "LimitException": "NoAction",
                "LimitInWatts": null
            }
        }
    ],_

**Comment by gkeishin** [comment]
To get the member id URI, existing code can be still used
        _# Get the member id list.
        # e.g. ['/redfish/v1/Chassis/foo', '/redfish/v1/Chassis/bar']
        resource_path_list = self.get_member_list(resource_path)_

As for the above note the changes https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/34661/

post this , I ll start modifying a test case to use the above changes. and we can see from there where all we need to modify

_Test Power Reading Via IPMI With Host Booted
    [Documentation]  Test power reading via IPMI with host in booted state and
    ...  verify using Redfish.
    [Tags]  Test_Power_Reading_Via_IPMI_With_Host_Booted_

**Comment by gkeishin** [comment]
@Jayashree-D This should be the one for the _Test_Power_Reading_Via_IPMI_With_Host_Booted_

https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/34670/

Please check and see if it works in your env as well.

**Comment by Jayashree-D** [comment]
I tested the changes and it works fine in my env.
Thanks George

**Comment by gkeishin** [comment]
> I tested the changes and it works fine in my env.
> Thanks George

Neat.. Thanks @Jayashree-D  appreciated
