### ISSUE TITLE
mTLS test and automation

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#2092]
mutual TLS authentication test and automation.

```OpenBMC master has recently added a mTLS capability (https://en.wikipedia.org/wiki/Mutual_authentication).  Design: https://github.com/openbmc/docs/blob/master/designs/redfish-tls-user-authentication.md  This allows a network user to authenticate as part of HTTPS connection, so no additional passwords or login is needed.  The interface is unfinished at this time, so for example, the root user has concatenate the user’s certificate into a file on the BMC.```

User Config Guide ```User config guide https://github.com/openbmc/docs/blob/master/security/TLS-configuration.md```

**Comment by gkeishin** [comment]
we have already code in to support this

```
lib/resource.robot:# MTLS_ENABLED indicates whether mTLS is enabled.
lib/resource.robot:${MTLS_ENABLED}        False
```

anything else needed ?
