### ISSUE TITLE
Need Redfish session delete to handle error response code

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2097]
Add valid state code  could be 200 or 404 depending on use case for Redfish session delete in test code

**Comment by gkeishin** [comment]
The support is in.. 
```
Redfish.patch  ${URI}  body=&{data}  valid_status_codes=[${valid_status_codes}]

redfish.delete  ${URI}   valid_status_codes=[200, 404, 500]
```
where one can pass the status response code 200 / 400 or needed / use case per test case.

```
valid_status_codes=[200, 404, 500]
```

**Comment by Aishwarya2378** [comment]
Hi team,
While testing session deletion via Redfish (DELETE /redfish/v1/SessionService/Sessions/{id}), I noticed that many compliant implementations return 204 No Content, which is valid per Redfish spec.
Currently, the test expects only 200 OK, which causes false failures.
Could we update the test to include 204 in valid_status_codes?
Thanks!
