### ISSUE TITLE
PreTag 0.8 Testing failure for 'Verify system vpd properties'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#21]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/284)

Full Name: 	Tests.Test Inventory.Verify system vpd properties
Start / End / Elapsed: 	20160519 15:20:33.478 / 20160519 15:20:33.493 / 00:00:00.015
Status: 	FAIL (critical)
Message: 	Lengths are different: 20 != 5

---

@anoo1 commented on [Mon May 23 2016](https://github.com/openbmc/openbmc/issues/284#issuecomment-221070554)

@rahulmah what is the test case trying to do?

---

@causten commented on [Mon May 23 2016](https://github.com/openbmc/openbmc/issues/284#issuecomment-221123523)

the test cases doesn't exist anymore. Hold off on this one

**Comment by gkeishin** [comment]
This failure is same with https://github.com/openbmc/openbmc-test-automation/issues/90
