### ISSUE TITLE
https PORT number needs to be included along with hostname. 

### ISSUE THREAD

**Issue by bnagaiah** [openbmc/openbmc-test-automation#2100]
https://github.com/openbmc/openbmc-test-automation/blob/50bb5a1e84e359a14194b7bc5c90a4878ec8d1d0/gui/lib/resource.robot#L109

Many openbmc developers use qemu for the development and port forwarding is very common on those. hence alternative port numbers are used in place of ssh and gui standard ports. In the snippet given below the login is directed to standard port. Hence suggesting to add port number with the url.

```
@@ -102,7 +102,7 @@ Login OpenBMC GUI

     Go To  ${obmc_gui_url}
     Wait Until Element Is Enabled  ${xpath_textbox_hostname}
-    Input Text  ${xpath_textbox_hostname}  ${OPENBMC_HOST}
+    Input Text  ${xpath_textbox_hostname}  ${OPENBMC_HOST}:${HTTPS_PORT}
     Input Text  ${xpath_textbox_username}  ${username}
     Input Password  ${xpath_textbox_password}  ${password}
     Click Element  login__submit

```

**Comment by gkeishin** [comment]
@bnagaiah You wont need to do that, it is taken care in two ways
1. If default  443

${HTTPS_PORT}       443

2. If you are targeting on different HTTPS port  say xxxx configured for your system, if you either do

```
export HTTPS_PORT=xxxx  ( before executing the robot test )
```
or
```
-v HTTPS_PORT:xxxx    ( for robot command line execution )
```

The code initialization takes care of, replacing them in run time
```
AUTH_SUFFIX = ":" + BuiltIn().get_variable_value("${HTTPS_PORT}", os.getenv('HTTPS_PORT', '443'))
```
in lib resource file
https://github.com/openbmc/openbmc-test-automation/blob/master/lib/resource.robot#L15
```
# AUTH_SUFFIX here is derived from variables.py
${AUTH_URI}       https://${OPENBMC_HOST}${AUTH_SUFFIX}
```

hope that helps

**Comment by gkeishin** [comment]
Closing this ticket. Thank you
