### ISSUE TITLE
Redfish & D-Bus API: Should manage session 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc-test-automation#2102]
Logging in:

```
curl --insecure -X POST -D headers.txt https://${bmc}/redfish/v1/SessionService/Sessions -d    '{"UserName":"root", "Password":"0penBmc"}'
{
  "@odata.id": "/redfish/v1/SessionService/Sessions/0JB0CRhFrr",
  "@odata.type": "#Session.v1_0_2.Session",
  "Description": "Manager User Session",
  "Id": "0JB0CRhFrr",
  "Name": "User Session",

```

To delete the session:

`curl -k -X DELETE https://${bmc}/redfish/v1/SessionService/Sessions/0JB0CRhFrr`

On https://github.com/openbmc/bmcweb/issues/167 we saw 32000 sessions. 
Ideally, openbmc-test-automation deletes a session after it is finished using

**Comment by gkeishin** [comment]
I ll work on this one.. we have it in test infrastructure, but needed by the test to call it explicitly.

**Comment by gkeishin** [comment]
@swanman @gtmills   This should do the work https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/38771/

**Comment by gkeishin** [comment]
merged
