### ISSUE TITLE
Fix test_redfishtool_local_user.robot Verify_Error_While_Creating_User_With_Invalid_Role Teardown

### ISSUE THREAD

**Issue by wilsonsuen** [openbmc/openbmc-test-automation#2103]
https://github.com/openbmc/openbmc-test-automation/blob/a053fb3472c2151d0f41667abfb035e2d1d320ae/redfish/dmtf_tools/test_redfishtool_local_user.robot#L116

User "UserT100" is never created in test case, therefore teardown should expect 404.
`[Teardown]  Redfishtool Delete User  "UserT100"  404`

**Comment by gkeishin** [comment]
@rahulmah can u look into this.

**Comment by gkeishin** [comment]
Assigned to @manashsarma .. Please looked into it..

**Comment by manashsarma** [comment]
I am looking this. Thanks.

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/38869/
