### ISSUE TITLE
Test to enable fully Redfish ONLY support

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2109]
- The xyz properties would no longer be working 
- Relies on ONLY Redfish /redfish/v1/xxx  for the test code 
- Infrastructure and back end changes
- Testing involved 
- Inform community when ready

*IMPORTANT*
- Should not break Code update
- Should not break Boot test
- Should not break FFDC
- Should not impact upstream HW CI test 
- Should not break existing REST infrastructure for community depending on it.
- Should not break a mix of REST + Redfish mixed builds for community

**Comment by gkeishin** [comment]
We have done this changes over multiple commits. Closing this

**Comment by kiko886** [comment]
Excuse me,how to set it
