### ISSUE TITLE
update_service: test_firmware_tftp_upload_image.robot get status code 202 instead of 200

### ISSUE THREAD

**Issue by minimada** [openbmc/openbmc-test-automation#2116]
Dear all,
I found after bmcweb commit d7a596bd7e449cdbfb92e961cc7049f80775e61f,
the test suite  test_firmware_tftp_upload_image.robot all test cases will get same error like:
```
FAIL	ValueError: The HTTP status code was not valid:
status:                                           202
valid_status_codes:
  [0]:                                            200
```

The root cause seems the task for tftp function is worked, and the task will return status code 202 and the task progress information by link.
Does there is any existed plan for add task support for update service?
Or the bmcweb should return status code 200 is more sensible?

**Comment by mdmillerii** [comment]
Sounds like we added task support and didn't update the test @gkeishin

**Comment by gkeishin** [comment]
```
${HTTP_OK}                               200
${HTTP_CREATED}                          201
${HTTP_ACCEPTED}                         202

```
looks like we can add 202 as accepted value response for upload.. will change it up .. 

Thanks @mdmillerii

**Comment by minimada** [comment]
Hi all, 
I found the task change for bmcweb may also effect the tftp test cases under test_redfish_image_upload.robot.
Redfish TFTP Failure to Upload Empty BMC Image and Redfish TFTP Failure to Upload Empty Host Image get failed:

```
ValueError: The HTTP status code was not valid:
status:                                           202
valid_status_codes:
  [0]:                                            200
```

But Redfish TFTP Failure to Upload BMC Image With Bad Manifest and Redfish TFTP Failure to Upload Host Image With Bad Manifest get failed like:
```
ValueError: The HTTP status code was not valid:
status:                                           500
valid_status_codes:
  [0]:                                            200
```
I am not sure the return status 500 is expected or not for these cases...

**Comment by gkeishin** [comment]
@susilsi7 any new update on the code changes for this one ?

**Comment by gkeishin** [comment]
Any new update here ? @susilsi7

**Comment by gkeishin** [comment]
https://gerrit.openbmc.org/c/openbmc/openbmc-test-automation/+/66944

code merged..

closing this ticket
