### ISSUE TITLE
Test plan: Security panel to Enable/Disable SSH/IPMI/HTTP/USB

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#2118]
<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/PRASHA~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/PRASHA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>

S.No | Test Cases | Results
-- | -- | --
Enable/Disable   SSH BMC Shell | &nbsp; | &nbsp;
1 | Verify   default value of SSH is enabled and ssh works | &nbsp;
2 | Disable   SSH and verify ssh to BMC stops working | &nbsp;
3 | Enable   SSH 22 and verify ssh to BMC 22 starts working | &nbsp;
4 | Open   SSH session, then disable SSH. Existing session should not have any issue | &nbsp;
5 | Disable   SSH and verify ssh to BMC stops working and check ssh to 2201 works | &nbsp;
6 | Toggle   to enable and verify ssh services are restored | &nbsp;
7 | Disable   SSH, do BMC reboot and verify persistency of SSH disable | &nbsp;
8 | Enable   SSH, do BMC reboot and verify persistency of SSH enable | &nbsp;
Enable/Disable   SSH BMC console 2201 | &nbsp; | &nbsp;
9 | Verify   default value of SSH 2201 is enabled and ssh works | &nbsp;
10 | Disable   SSH 2201 and verify ssh to BMC 2201 stops working | &nbsp;
11 | Enable   SSH 2201 and verify ssh to BMC 2201 starts working | &nbsp;
12 | Open   SSH 2201 session, then disable SSH 2201. Existing session should not have any   issue | &nbsp;
13 | Disable   SSH 2201 and verify ssh to BMC 2201 stops working and check ssh to 22 works | &nbsp;
14 | Toggle   to enable and verify ssh services to 2201 are restored | &nbsp;
15 | Disable   SSH 2201, do BMC reboot and verify persistency of SSH 2201 disable | &nbsp;
16 | Enable   SSH 2201, do BMC reboot and verify persistency of SSH 2201 enable | &nbsp;
Enable/Disable   IPMI | &nbsp; | &nbsp;
17 | Verify   default value of ipmi is disabled and ipmi does not work | &nbsp;
18 | Enable   ipmi and verify ipmi commands to BMC starts working | &nbsp;
19 | Disable   ipmi and verify ipmi commands to BMC stops working | &nbsp;
20 | Disable   ipmi and verify ipmi to BMC stops working and check ipmi via host OS works | &nbsp;
21 | Toggle   to enable and verify ipmi services are restored | &nbsp;
22 | Disable   ipmi, do BMC reboot and verify persistency of ipmi disable | &nbsp;
23 | Enable   ipmi, do BMC reboot and verify persistency of ipmi enable | &nbsp;
Enable/Disable   http | &nbsp; | &nbsp;
24 | Verify   default value of http is disabled and http does not work | &nbsp;
25 | Enable   http and verify http sessions to BMC starts working | &nbsp;
26 | Disable   http and verify http sessions to BMC stops working | &nbsp;
27 | Toggle   to enable and verify http services are restored | &nbsp;
28 | Disable   http, do BMC reboot and verify persistency of http disable | &nbsp;
29 | Enable   http, do BMC reboot and verify persistency of http enable | &nbsp;
Enable/Disable   usb | &nbsp; | &nbsp;
30 | Verify   default value of usb is enabled and usb works | &nbsp;
31 | Disable   usb and verify usb sessions to BMC stops working | &nbsp;
32 | Toggle   to enable and usb http services are restored | &nbsp;
33 | Disable   usb, do BMC reboot and verify persistency of usb disable | &nbsp;
34 | Enable   usb, do BMC reboot and verify persistency of usb enable | &nbsp;
Enable/Disable   2 functions at a time | &nbsp; | &nbsp;
35 | Disable   SSH 22 &amp; SSH 2201, verify ssh stops working for both 22 and 2201 | &nbsp;
36 | Disable   SSH 22 &amp; IPMI, verify ssh stops working &amp; IPMI stops working | &nbsp;
37 | Disable   SSH 22 &amp; HTTP, verify ssh stops working &amp; HTTP stops working | &nbsp;
38 | Disable   SSH 22 &amp; USB, verify ssh stops working &amp; USB stops working | &nbsp;
39 | Disable   SSH 22 &amp; SSH 2201, verify persistency on reboot ssh stops working for   both 22 and 2201 | &nbsp;
40 | Disable   SSH 22 &amp; IPMI, verify persistency on reboot ssh stops working &amp; IPMI   stops working | &nbsp;
41 | Disable   SSH 22 &amp; HTTP, verify persistency on rebootssh stops working &amp; HTTP   stops working | &nbsp;
42 | Disable   SSH 22 &amp; USB, verify persistency on reboot ssh stops working &amp; USB   stops working | &nbsp;
43 | Enable   SSH 22 &amp; SSH 2201, verify ssh starts working for both 22 and 2201 | &nbsp;
44 | Enable   SSH 22 &amp; IPMI, verify ssh starts working &amp; IPMI starts working | &nbsp;
45 | Enable   SSH 22 &amp; HTTP, verify ssh starts working &amp; HTTP starts working | &nbsp;
46 | Enable   SSH 22 &amp; USB, verify ssh starts working &amp; USB starts working | &nbsp;
47 | Enable   SSH 22 &amp; SSH 2201, verify persistency on reboot ssh starts working for   both 22 and 2201 | &nbsp;
48 | Enable   SSH 22 &amp; IPMI, verify persistency on reboot ssh starts working &amp; IPMI   starts working | &nbsp;
49 | Enable   SSH 22 &amp; HTTP, verify persistency on reboot ssh starts working &amp; HTTP   starts working | &nbsp;
50 | Ensable   SSH 22 &amp; USB, verify persistency on reboot ssh starts working &amp; USB   starts working | &nbsp;
51 | Disable   SSH 2201 &amp; IPMI, verify ssh 2201stops working &amp; IPMI stops working | &nbsp;
52 | Disable   SSH 2201 &amp; HTTP, verify ssh 2201 stops working &amp; HTTP stops working | &nbsp;
53 | Disable   SSH 2201 &amp; USB, verify ssh 2201 stops working &amp; USB stops working | &nbsp;
54 | Disable   SSH 2201 &amp; IPMI, verify persistency on reboot ssh 2201 stops working   &amp; IPMI stops working | &nbsp;
55 | Disable   SSH 2201 &amp; HTTP, verify persistency on reboot ssh 2201 stops working   &amp; HTTP stops working | &nbsp;
56 | Disable   SSH 2201 &amp; USB, verify persistency on reboot ssh 2201 stops working &amp;   USB stops working | &nbsp;
57 | Enable   SSH 2201 &amp; IPMI, verify ssh 2201 starts working &amp; IPMI starts working | &nbsp;
58 | Enable   SSH 2201 &amp; HTTP, verify ssh 2201 starts working &amp; HTTP starts working | &nbsp;
59 | Enable   SSH 2201 &amp; USB, verify ssh 2201 starts working &amp; USB starts working | &nbsp;
60 | Enable   SSH 2201 &amp; IPMI, verify persistency on reboot ssh 2201 starts working   &amp; IPMI starts working | &nbsp;
61 | Enable   SSH 2201 &amp; HTTPS, verify persistency on reboot ssh 2201 starts working   &amp; HTTPs starts working | &nbsp;
62 | Ensable   SSH 2201 &amp; USB, verify persistency on reboot ssh 2201 starts working   &amp; USB starts working | &nbsp;
63 | Disable   IPMI &amp; HTTP, verify IPMI stops working &amp; HTTP stops working | &nbsp;
64 | Disable   IPMI &amp; USB, verify IPMI stops working &amp; USB stops working | &nbsp;
65 | Disable   IPMI &amp; HTTP, verify persistency on reboot IPMI stops working &amp; HTTP   stops working | &nbsp;
66 | Disable   IPMI &amp; USB, verify persistency on reboot IPMI stops working &amp; USB   stops working | &nbsp;
67 | Enable   IPMI &amp; HTTP, verify IPMI starts working &amp; HTTP starts working | &nbsp;
68 | Enable   IPMI &amp; USB, verify IPMI starts working &amp; USB starts working | &nbsp;
69 | Enable   IPMI &amp; HTTP, verify persistency on reboot IPMI starts working &amp; HTTP   starts working | &nbsp;
70 | Enable   IPMI &amp; USB, verify persistency on reboot IPMI starts working &amp; USB   starts working | &nbsp;
71 | Disable   http &amp; USB, verify http stops working &amp; usb stops working | &nbsp;
72 | Disable   http &amp; usb, verify persistency on reboot Iusb stops working &amp; HTTP   stops working | &nbsp;
73 | Enable   http &amp; usb, verify USB starts working &amp; HTTP starts working | &nbsp;
74 | Enable   http &amp; usb, verify persistency on reboot usb starts working &amp; HTTP   starts working | &nbsp;
Enable/Disable   3 functions at a time | &nbsp; | &nbsp;
75 | Disable   SSH 22 &amp; SSH 2201, IPMI, verify ssh stops working for both 22 and 2201   &amp; IPMI stops working | &nbsp;
76 | Enable   SSH 22 &amp; SSH 2201, IPMI, verify ssh starts working for both 22 and 2201   &amp; IPMI starts working | &nbsp;
77 | Disable   SSH 22 &amp; SSH 2201, IPMI, verify persistency on reboot&nbsp; ssh stops working for both 22 and 2201   &amp; IPMI stops working | &nbsp;
78 | Enable   SSH 22 &amp; SSH 2201, IPMI, verify persistency on reboot ssh starts working   for both 22 and 2201 &amp; IPMI starts working | &nbsp;
79 | Disable   SSH 22 &amp; SSH 2201, http, verify ssh stops working for both 22 and 2201   &amp; http stops working | &nbsp;
80 | Enable   SSH 22 &amp; SSH 2201, http, verify ssh starts working for both 22 and 2201   &amp; http starts working | &nbsp;
81 | Disable   SSH 22 &amp; SSH 2201, http, verify persistency on reboot&nbsp; ssh stops working for both 22 and 2201   &amp; http stops working | &nbsp;
82 | Enable   SSH 22 &amp; SSH 2201, http, verify persistency on reboot ssh starts working   for both 22 and 2201 &amp; http starts working | &nbsp;
83 | Disable   SSH 22 &amp; SSH 2201, USB, verify ssh stops working for both 22 and 2201   &amp; USB stops working | &nbsp;
84 | Enable   SSH 22 &amp; SSH 2201, USB, verify ssh starts working for both 22 and 2201   &amp; USB starts working | &nbsp;
85 | Disable   SSH 22 &amp; SSH 2201, USB, verify persistency on reboot&nbsp; ssh stops working for both 22 and 2201   &amp; usb stops working | &nbsp;
86 | Enable   SSH 22 &amp; SSH 2201, usb, verify persistency on reboot ssh starts working   for both 22 and 2201 &amp; usb starts working | &nbsp;
87 | Disable   SSH 2201, IPMI &amp; http, verify ssh, IPMI &amp; http stops working | &nbsp;
88 | Enable   SSH 2201, IPMI &amp; http, verify ssh, IPMI &amp; http starts working | &nbsp;
89 | Disable   SSH 2201, IPMI &amp; http,&nbsp; verify   persisetcny on reboot ssh, IPMI &amp; http stops working | &nbsp;
90 | Enable   SSH 2201, IPMI &amp; http,&nbsp; verify   persisetcny on reboot ssh, IPMI &amp; http starts working | &nbsp;
91 | Disable   usb, IPMI &amp; http, verify usb, IPMI &amp; http stops working | &nbsp;
92 | Enable   usb, IPMI &amp; http, verify usb, IPMI &amp; http starts working | &nbsp;
93 | Disable   usb, IPMI &amp; http,&nbsp; verify   persisetcny on reboot usb, IPMI &amp; http stops working | &nbsp;
94 | Enable   usb, IPMI &amp; http,&nbsp; verify   persisetcny on reboot usb, IPMI &amp; http starts working | &nbsp;
Enable/Disable   4 functions at a time | &nbsp; | &nbsp;
95 | Disable   SSH 22, SSH 2201, IPMI &amp; http, verify ssh stops working for both 22 and   2201 &amp; IPMI &amp; http stops working | &nbsp;
96 | Enable   SSH 22, SSH 2201, IPMI &amp; http, verify ssh starts working for both 22 and   2201 &amp; IPMI &amp; http starts working | &nbsp;
97 | Disable   SSH 22, SSH 2201, IPMI &amp; http, verify persistency on reboot ssh stops   working for both 22 and 2201 &amp; IPMI &amp; http stops working | &nbsp;
98 | Enable   SSH 22, SSH 2201, IPMI &amp; http, verify persistency on reboot ssh starts   working for both 22 and 2201 &amp; IPMI &amp; http starts working | &nbsp;
99 | Disable   SSH 22, SSH 2201, IPMI &amp; usb, verify ssh stops working for both 22 and   2201 &amp; IPMI &amp; usb stops working | &nbsp;
100 | Enable   SSH 22, SSH 2201, IPMI &amp; USB, verify ssh starts working for both 22 and   2201 &amp; IPMI &amp; usb starts working | &nbsp;
101 | Disable   SSH 22, SSH 2201, IPMI &amp; USB, verify persistency on reboot ssh stops   working for both 22 and 2201 &amp; IPMI &amp; USB stops working | &nbsp;
102 | Enable   SSH 22, SSH 2201, IPMI &amp; USB, verify persistency on reboot ssh starts   working for both 22 and 2201 &amp; IPMI &amp; USB starts working | &nbsp;
103 | Disable   SSH 2201, IPMI, HTTP &amp; usb, verify ssh 2201, IPMI, http &amp; usb stops   working | &nbsp;
104 | Enable   SSH 2201, IPMI, HTTP &amp; usb, verify ssh 2201, IPMI, http &amp; usb starts   working | &nbsp;
105 | Disable   SSH 2201, IPMI, HTTP &amp; usb, verify persisetncy on reboot ssh 2201, IPMI,   http &amp; usb stops working | &nbsp;
106 | Enable   SSH 2201, IPMI, HTTP &amp; usb, verify persistency on reboot ssh 2201, IPMI,   http &amp; usb starts working | &nbsp;
107 | Disable   SSH 22, IPMI, HTTP &amp; usb, verify ssh 22, IPMI, http &amp; usb stops   working | &nbsp;
108 | Enable   SSH 22, IPMI, HTTP &amp; usb, verify ssh 22, IPMI, http &amp; usb starts   working | &nbsp;
109 | Disable   SSH 22, IPMI, HTTP &amp; usb, verify persisetncy on reboot ssh 22, IPMI, http   &amp; usb stops working | &nbsp;
110 | Enable   SSH 22, IPMI, HTTP &amp; usb, verify persistency on reboot ssh 22, IPMI, http   &amp; usb starts working | &nbsp;
111 | Disable   SSH 22, SSH 2201, USB &amp; http, verify ssh stops working for both 22 and   2201 &amp; USB &amp; http stops working | &nbsp;
112 | Enable   SSH 22, SSH 2201, USB &amp; http, verify ssh starts working for both 22 and   2201 &amp; USB &amp; http starts working | &nbsp;
113 | Disable   SSH 22, SSH 2201, USB &amp; http, verify persistency on reboot ssh stops   working for both 22 and 2201 &amp; USB &amp; http stops working | &nbsp;
114 | Enable   SSH 22, SSH 2201, USB &amp; http, verify persistency on reboot ssh starts   working for both 22 and 2201 &amp; USB &amp; http starts working | &nbsp;
Enable/Disable   all 5 functions at a time | &nbsp; | &nbsp;
115 | Disable   SSH 22, SSH 2201, IPMI, USB &amp; http, verify ssh stops working for both 22   and 2201 &amp; IPMI, USB &amp; http stops working | &nbsp;
116 | Enable   SSH 22, SSH 2201, IPMI, USB &amp; http, verify ssh starts working for both 22   and 2201 &amp; IPMI, USB &amp; http starts working | &nbsp;
117 | Disable   SSH 22, SSH 2201, IPMI, USB &amp; http, verify persistency on reboot ssh   stops working for both 22 and 2201 &amp; IPMI, USB &amp; http stops working | &nbsp;
118 | Enable   SSH 22, SSH 2201, IPMI, USB &amp; http, verify persistency on reboot ssh   starts working for both 22 and 2201 &amp; IPMI, USB &amp; http starts working | &nbsp;
Factory Reset | &nbsp; | &nbsp;
119 | Factory   reset and check SSH &amp; SSH 2201 is enabled, IPMI, HTTP &amp; USB are   disabled by default | &nbsp;

**Comment by prkatti1** [comment]
@joseph-reynolds @gkeishin Can you take a look and provide your input.

**Comment by gkeishin** [comment]
Any other comments here

**Comment by gkeishin** [comment]
Closing this test plan. No further action required.
