### ISSUE TITLE
Basic Performance check for BMC

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#212]
Need to right basic performance check for BMC

BMC_STEADY state and HOST_BOOTED_STATE
Need to address issue like this https://github.com/openbmc/openbmc/issues/741

**Comment by gkeishin** [comment]
What are the factors we are looking at for this... because it would be different for different systems .

**Comment by sivassrr** [comment]
CPU and Memory availability should be more than 10 % at BMC ready state. That is the expectation.

**Comment by sivassrr** [comment]
Basically after code update, need to check whether given driver had put the system in BMC_ready state and minimial resources are available.  This helps to identify defect like openbmc/openbmc#741.
