### ISSUE TITLE
BMC:GUI: Replace/Use 'Select Checkbox' for checkbox element

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#2125]
Replace/Use 'Select Checkbox' for checkbox element
Exa:
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/46258
Enable/disable SSH checkbox, we are currently using Redfish to disable, waiting for it to get disabled then using GUI Click Element to enable back.
Instead replace all this code with one liner Select Checkbox, so it saves time & removes the dependency on redfish into GUI code.

This should be done wherever possible like Network page, LDAP page etc.

**Comment by gkeishin** [comment]
@meghagn12345 @rahulmah  can u guys look into it.

**Comment by gkeishin** [comment]
Closing this ticket.. no plan to fix it.
