### ISSUE TITLE
Different Python Shebangs Used In Files 

### ISSUE THREAD

**Issue by ltarlton** [openbmc/openbmc-test-automation#2126]
The python shebangs are different in the files, thus causing some files to launch the python2 interpreter while others launch the python3 interpreter.  #!/usr/bin/env python3 should be used in all files to resolve python version issues.
This is the accepted and recommended practice, especially since python2 is no longer supported as of January 1, 2020.

**Comment by gkeishin** [comment]
Patch up for testing  https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/46566

**Comment by gkeishin** [comment]
Looks good in our testing.. can u also check if it's alright in your setup with this patch. @ltarlton

**Comment by gkeishin** [comment]
Merged and closing
