### ISSUE TITLE
IPMI SOL default /tmp path need to be changed

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2132]
```
Activate SOL Via IPMI
    [Documentation]  Start SOL using IPMI and route output to a file.
    [Arguments]  ${file_path}=/tmp/sol_${OPENBMC_HOST}
````

```
$ grep -r "Activate SOL Via IPMI" lib/ ipmi/
lib/ipmi_client.robot:Activate SOL Via IPMI
ipmi/test_ipmi_sol.robot:    Activate SOL Via IPMI
ipmi/test_ipmi_sol.robot:        Activate SOL Via IPMI
ipmi/test_ipmi_sol.robot:    Activate SOL Via IPMI
```

we'll need to add up something so that the user can control, where the IPMI logs need to stream off instead of /tmp/ to avoid running into issues if the same system from a different workspace id creating permission issues.

**Comment by generatz** [comment]
Seen with `Set SOL Enabled`

**Comment by gkeishin** [comment]
Thanks @generatz 

there are two things here.. 

1. SOL bug https://github.com/openbmc/phosphor-net-ipmid/issues/19  
2. The file default /tmp 

So we are going to fix up the 2) one using this task..

**Comment by gkeishin** [comment]
@generatz Fix up for the 2)  https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/48908
