### ISSUE TITLE
IPMI protocol disabled after run test_bmc_protocol_settings.robot

### ISSUE THREAD

**Issue by minimada** [openbmc/openbmc-test-automation#2135]
The IPMI function is important feature for BMC, does any any risk to enable it after run test cases?

**Comment by gkeishin** [comment]
@prkatti1 Can u respond to this..

**Comment by prkatti1** [comment]
No risk there. You can enable it back if the ipmi feature is required.

**Comment by gkeishin** [comment]
Closing this if no further question. Thanks
