### ISSUE TITLE
Should noaccess user login success?

### ISSUE THREAD

**Issue by minimada** [openbmc/openbmc-test-automation#2138]
The test cases in test_ldap_configuration.robot try to use "noaccess" user login redfish, and expect get error while patch something to redfish.
But if we set a user to "noaccess" group, should we give it login or logout permission(create/delete session)?

**Comment by minimada** [comment]
ref:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/49295
https://github.com/openbmc/bmcweb/issues/227

**Comment by gkeishin** [comment]
@prkatti1 Can you check on this

**Comment by prkatti1** [comment]
once the new function is implemented successfully, no-access user will not have any permissions not even login & logout.
Once that is merged, we need to change the expected behavior of test cases involving no-access user.

**Comment by gkeishin** [comment]
@prkatti1 is this still a thing for upstream?

**Comment by gkeishin** [comment]
> ref: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/49295 [openbmc/bmcweb#227](https://github.com/openbmc/bmcweb/issues/227)

This commit is abandoned.. so closing the ticket. No further action required
