### ISSUE TITLE
Test BMC Redfish Boot Host And GracefulShutdown (DMTF) misconfigured

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2140]
In Dmtf Tools.Redfish Usecase Checkers.Test BMC Redfish Boot Host And GracefulShutdown

The test attempts to issue:
`python3 Redfish-Usecase-Checkers/power_control/power_control.py -r ${OPENBMC_HOST} -u root -p 0penBmc -S Always On`

but the `On` argument is no longer supported.

**Comment by generatz** [comment]
Same/similar problem with the other two Redfish Usecase Checkers tests: an argument is provided that is no longer supported.

**Comment by gkeishin** [comment]
@peterp-ibm Can u check on this one..

**Comment by peterp-ibm** [comment]
I have committed a change to handle this case.  The change is pending review.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/50058

**Comment by gkeishin** [comment]
Thanks @peterp-ibm

**Comment by gkeishin** [comment]
@peterp-ibm can u follow up on the commit

**Comment by gkeishin** [comment]
Merged
