### ISSUE TITLE
security/test_bmc_network_security.robot requires sudo for ICMP

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2142]
security/test_bmc_network_security.robot uses nping with ICMP. ICMP creates a raw socket, which requires root privilege / sudo.

At a minimum, this should be mentioned in the Documentation on the second line of the file.
I'd also like to see a check in the appropriate test's Setup that verifies that the EUID is 0.
And perhaps the script should be split in two, putting the tests that require sudo into a separate script for safety and convenience.

**Comment by gkeishin** [comment]
Thanks @generatz for the feedback..

Documentation, we should definitely add, as for the script to handle, I ll let @prkatti1 take a call on it.

**Comment by prkatti1** [comment]
Looked into it, will add the documentation for which TCs we need sudo privileges.
For 1 or 2 TCs we'll not have separate suite, will leave it to user to have proper infrastructure before running it.(New Documentation will help here).

**Comment by matthewfischer** [comment]
fixed with commit c1a260c2904cae6b80c10ee4d14385b347b57632

**Comment by matthewfischer** [comment]
@gkeishin please close, I don't have permissions

**Comment by williamspatrick** [comment]
> fixed with commit [c1a260c](https://github.com/openbmc/openbmc-test-automation/commit/c1a260c2904cae6b80c10ee4d14385b347b57632)

The commit message for that is pretty weak so it's hard to tell that it matches this issue, but if you can get the contributors to write "Fixes openbmc/openbmc-test-automation#XXX" (where XXX = 2142 in this case), then when it syncs from Gerrit it'll automatically close.
