### ISSUE TITLE
many test keywords and tags do not match

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2149]
There are a number of cases where test keywords and associated tags do not correspond as intended. For example the tag for the test shown below is missing an 's' on the end of 'Addresse':
```
Configure And Verify Multiple IPv4 Addresses
    [Documentation]  Configure multiple IPv4 addresses and verify.
    [Tags]  Configure_And_Verify_Multiple_IPv4_Addresse
```
This is a cause for confusion and error when using the tests.

Does there exist or is there already a trivial way to screen for these so they can easily be remediated (and perhaps be caught early, say with Jenkins testing)?

**Comment by gkeishin** [comment]
Good catch.. mismatching tag with test cases shouldn't be a problem but a practice where we keep the same.

**Comment by gkeishin** [comment]
@generatz  Fixed I think this should cover for all https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/50355
