### ISSUE TITLE
Ipmi.Test Ipmi User.Verify IPMI Root User Password Change: assumes root is user 1

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2150]
This test attempts to set the root password assuming that the root UID is always 1, which is not the case.
Here is an example from a log file:
**KEYWORD** **ipmi_client . Run IPMI Standard Command** user set password ${root_userid} ${valid_password}
. . .
TRACE 	Arguments: [ ${command}='user set password 1 0penBmc1' | ${fail_on_err}=1 | ${expected_rc}=0 | &{options}={} ]

The test ought to first determine what the root UID is before setting it.

**Comment by generatz** [comment]
https://res-openbmc-team-jenkins.swg-devops.com/view/%20%20openbmc%20ibmscm/job/run_one_test_multiple_times_ibmscm/3/

**Comment by gkeishin** [comment]
@AshwiniC777 can u look into it.. Thanks

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/52675
