### ISSUE TITLE
many tags do not correspond to test or task names

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2152]
Many of the test-cases/tasks have tags that do not correspond to the test-case/task names as expected. 
I found over 100 such cases using the check_robot_tags.awk script [here](https://github.com/generatz/check_robot_tags).

Please use the script to fix the name<->tag correspondence as appropriate.

I recommend that the script be included somewhere in your process to help eliminate this issue in the future.

**Comment by gkeishin** [comment]
Thank you for the feedback.. Will look into it..

**Comment by gkeishin** [comment]
Fix 1: under redfish/   https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/50788

**Comment by gkeishin** [comment]
Fix 2: under openpower/ directory  https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/50790

**Comment by gkeishin** [comment]
Fix 3: under different suites https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/50791

**Comment by gkeishin** [comment]
That should be it.. Thanks @generatz .. Closing
