### ISSUE TITLE
redfish.update_service. test_redfish_bmc_code_update.robot need to downgrade the BMC to the old image for next case validation.

### ISSUE THREAD

**Issue by nagarjunb22** [openbmc/openbmc-test-automation#2155]
In test_redfish_bmc_code_update.robot script 
1) In first case "Redfish Code Update With ApplyTime OnReset"  it will do firmware upgrade for BMC from older version to newer version(the image we provide) with applytime onreset.
2)BMC will be in newer version while staring next testcase "Redfish Code Update With ApplyTime Immediate". In this case  script will try to do firmware upgrade with same image we used in previous case. since BMC already having the same image it will fail.

My Suggestion:  we need to downgrade the BMC to older version at teardown for each case.

**Comment by gkeishin** [comment]
@susilsi7 can u work on this one.

**Comment by gkeishin** [comment]
Now, we do not need to downgrade or explicitly handle this in the test code, the firmware updater allows the same image can be installed back to back. Closing this ticket
