### ISSUE TITLE
testcase 'Security.Test Bmc Expire Password.Expire And Change Root Password Via GUI' Teardown insufficient

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2159]
In some recent testing on a development BMC, the subject testcase failed. As a result, the last testcase in the suite, `Verify New Password Persistency After BMC Reboot`, also failed. Modifying the Teardown in the subject testcase as described below eliminated the second fail.

Here are the fails in `Expire And Change Root Password Via GUI` seen before modifying the Teardown:
![image](https://user-images.githubusercontent.com/6298273/152239637-f8478d42-d956-423f-9a0b-d58cf8abad0a.png)

Immediately after above fail, `Verify New Password Persistency After BMC Reboot` fails in the same run as follows:
![image](https://user-images.githubusercontent.com/6298273/152239844-4672eca0-abe6-4dad-aaaa-6c9f1e1f15de.png)
(Note that the failure of `Verify New Password Persistency After BMC Reboot` happens whether or not the intervening testcase `Verify Maximum Failed Attempts And Check Root User Account Locked` is skipped.)

-----
As a workaround I appended `    ...  AND  Test Teardown Execution` to the subject test and re-ran. With that change,`Verify New Password Persistency After BMC Reboot` passes as shown:
![image](https://user-images.githubusercontent.com/6298273/152240228-eb848ea4-77a2-4b5f-aaf3-965f8b369d92.png)

Please remediate the Teardown for `Expire And Change Root Password Via GUI` as appropriate.

**Comment by gkeishin** [comment]
@rahulmah Please look into it

**Comment by gkeishin** [comment]
opps.. may be @prkatti1 @swe12345 needs to look at this expire password for GUI

**Comment by generatz** [comment]
I just observed that `Restore Default Password For Root User` now succeeds in `Expire And Change Root Password Via GUI` when the fail occurs. Consequently, I no longer see a fail in `Verify New Password Persistency After BMC Reboot`. 
Closing as fixed.
