### ISSUE TITLE
RR: [Feature] BMC reset Reload Test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#216]
This is yet to be done by development.. Place holder for test.. need to link to the development story..

**Comment by sivassrr** [comment]
We have some thing similar already right, #224 if it is duplicate we can close .

**Comment by gkeishin** [comment]
@sivassrr Nope BMC reset reload is entirely a different feature. This has nothing to do with #224

**Comment by gkeishin** [comment]
Couple of pre-req works are in progress like BOOT count / BOOT time and State Manager base mapping.
