### ISSUE TITLE
support files for redfish/update_service/test_redfish_image_upload.robot unavailable

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2163]
I do not find the files listed below (by the test file) in the repository:
```
...                   This test expects the following bad tarball image files
...                   to exist in the BAD_IMAGES_DIR_PATH/TFTP_SERVER:
...                       bmc_bad_manifest.ubi.mtd.tar
...                       bmc_nokernel_image.ubi.mtd.tar
...                       bmc_invalid_key.ubi.mtd.tar
...                       pnor_bad_manifest.pnor.squashfs.tar
...                       pnor_nokernel_image.pnor.squashfs.tar
...                       pnor_invalid_key.pnor.squashfs.tar
```

**Comment by gkeishin** [comment]
These are manually cooked files, I can asked my folks to generate them for bad path testing. but we would need the working BMC and Host images tar files to prep those images.. @generatz

**Comment by generatz** [comment]
@gkeishin Thanks, but I don't have an urgent need for those files. I would prefer to see documentation for generating the files. And, as possible/appropriate, a set of tools for generating the files.

**Comment by gkeishin** [comment]
Sounds good @generatz 

@susilsi7 can u add documentation for it how to do those ? perhaps in the documentation for it ?

**Comment by generatz** [comment]
@susilsi7 @gkeishin For this suite, it seems there is no attempt to actually install these files, furthermore, they are defective. So I think there is no need for images that are customized to the BMC. We could, for example, use a pair of appropriately 'cooked' romulus BMC images.
I've no idea about the PNOR images, but it seems like the same logic might apply.

- If that makes sense, please cook something up.

Secondarily, the following two files are not used, so they can be dropped from the list:
```
bmc_invalid_key.ubi.mtd.tar
pnor_invalid_key.pnor.squashfs.tar
```
