### ISSUE TITLE
lib/bmc_network_security_utils.robot   `*** Keywords ***` header missing

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2166]
Several tests in `security/test_bmc_network_security.robot` had been working until recent changes to lib/bmc_network_security_utils.robot. After the changes several formerly passing tests failed with the message:
`No keyword with name 'Send Network Packets And Get Packet Loss'`

I found that the `*** Keywords ***` header was missing in lib/bmc_network_security_utils.robot and added it.
Subsequently, the aforementioned error disappeared.

**Comment by gkeishin** [comment]
The upstream has the resource added https://github.com/openbmc/openbmc-test-automation/blob/master/security/test_bmc_network_security.robot#L10

```
Resource                ../lib/resource.robot
Resource                ../lib/bmc_redfish_resource.robot
Resource                ../lib/ipmi_client.robot
Resource                ../lib/bmc_network_security_utils.robot
```

so probably you level is bit lower where the recent changes were made, Please rebase
