### ISSUE TITLE
update service: need support uploading same image for multiple times

### ISSUE THREAD

**Issue by minimada** [openbmc/openbmc-test-automation#2167]
The openbmc merged the new software manager commit: https://github.com/openbmc/phosphor-bmc-code-mgmt/commit/59b640b07148c56e0a344dda198fcac0cd9af836

This function will affect the version ID presentation. For example, the exist version will calculate by [version + flashId](https://github.com/openbmc/phosphor-bmc-code-mgmt/commit/59b640b07148c56e0a344dda198fcac0cd9af836#diff-437bb0b08d640a93aa00fc8355baf4156d581dd0096ce614435aece643707acaR224)
But when user upload image, the version id will calculate by [version + salt](https://github.com/openbmc/phosphor-bmc-code-mgmt/commit/59b640b07148c56e0a344dda198fcac0cd9af836#diff-b078e38b0585d572e20bbeb1b24d2b68985d081c7e287db1be2909ea88053e61R193)

And the utility function "Redfish Upload Image And Check Progress State" in lib/redfish_code_update_utils.robot use the fixed version id to check image update status.

I think the update service test cases may need add some modification for support software manager code changed.

**Comment by gkeishin** [comment]
@susilsi7 can u check on this ?

**Comment by gkeishin** [comment]
@susilsi7 any new update on this one ?

**Comment by susilsi7** [comment]
Can you point me a test case for this scenario.

For Image id, we are using till image becomes active and we should be good there.

**Comment by minimada** [comment]
For example: Update Service.Test Redfish Bmc Code Update.Redfish Code Update With ApplyTime Immediate.

**Comment by gkeishin** [comment]
now the firmware allows same image to upload multiple times.  @susilsi7 can you check if this is done ?

**Comment by susilsi7** [comment]
Same firmware upload multiple times, code is available with keyword "Redfish Code Update Same Firmware Multiple Times" and
file path is "openbmc-test-automation/redfish/update_service/test_redfish_bmc_code_update.robot".

**Comment by gkeishin** [comment]
Thank you @susilsi7 @minimada 

Closing the ticket.
