### ISSUE TITLE
[DB Metrics] populate Driver and release info into the database

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#217]
To further continue support on https://github.com/openbmc/openbmc-test-automation/issues/151

**Comment by gtmills** [comment]
please also add environment, processor family, platform, and url

**Comment by gkeishin** [comment]
@gtmills  Yeah,, I have to figure those how to add those data and from where i need to capture it since this is a post operation directly derived from result robot XML file and it doesn't have those data..

**Comment by sivassrr** [comment]
Thank you @gkeishin for adding it in this sprint. I was about to add. There were several enquiries on this since last sprint.

**Comment by gkeishin** [comment]
Yeah.. coding progress..

**Comment by gkeishin** [comment]
Code under review.. https://gerrit.openbmc-project.xyz/#/c/2292/
