### ISSUE TITLE
test_openbmc_setup.robot  fails REST Setup test

### ISSUE THREAD

**Issue by ruudharing** [openbmc/openbmc-test-automation#2170]
The README.md of the openbmc-test-automation project's main page, section: [Testing Setup Steps](https://github.com/openbmc/openbmc-test-automation#testing-setup-steps)  refers to running `templates/test_openbmc_setup.robot`   to verify that "the installation setup is completed and ready to execute".

However, this test is broken when running against a QEMU process of a recent image:
obmc-phosphor-image-romulus-20220226025230.static.mtd

The sub-test:  `Test REST Setup`  is supposed to execute
```
${resp}=  Get Request  openbmc  /xyz/openbmc_project/
    Should Be Equal As Strings  ${resp.status_code}  ${HTTP_OK}
```
but fails with
```
------------------------------------------------------------------------------
Test REST Setup :: Verify REST works.                                 | FAIL |
404 != 200
------------------------------------------------------------------------------
```

**Comment by gkeishin** [comment]
The templates/test_openbmc_setup.robot contains both REST and redfish new, probably I should split them

or add Check to skip them vice versa.

**Comment by gkeishin** [comment]
Updated template code check 

https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/51855


However, if the system you are running supports only Redfish and not REST, then the failure is expected.
