### ISSUE TITLE
some test cases in several suites have the Redfish path `/redfish/v1/Chassis/chassis` hard-coded 

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2173]
Instead, the last element in the path should be determined from the OData entry.
An example is the keyword `Enumerate Sensors And Check For Errors` in systest/test_bmc_poll_errors.robot:
```
Enumerate Sensors And Check For Errors
    [Documentation]  Enumerate and check if there is any error reported.

    Redfish.Get  /redfish/v1/Chassis/chassis/Sensors

    Check For Error Logs  ${ESEL_IGNORE_LIST}
```
In the above example, the value 'chassis' is hardcoded. In other BMC implementations it could just as easily be '1U', as demonstrated in the [DTMF mockup](https://redfish.dmtf.org/redfish/mockups/v1/1146).

This problem is analogous to the path problem in issue #2172 and can be fixed in an analogous way.

**Comment by gkeishin** [comment]
Fix https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/51948
