### ISSUE TITLE
Regression: Need to run all test including skip test and review the result and open issues accordingly - On all systems

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#218]
Need to run it on Barreleye, Palmetto, Witherspoon.

**Comment by sivassrr** [comment]
@rahulmah could you pls run the latest test on all 3 systems and revisit the skip list. 
Please do this as higher priority.

**Comment by rahulmah** [comment]
Barreleye: Test cases execution from skip_list with build v1.99.0-309
==============================================================================
Tests                                                            
37 critical tests, 6 passed, 31 failed
37 tests total, 6 passed, 31 failed
==============================================================================

**Comment by gkeishin** [comment]
This can be close as this is done on every sprint by most of the team members
