### ISSUE TITLE
move redfish/extended/test_occ_power.robot suite under openpower/ directory

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2182]
This suite tests the OCC power module. The OCC is the OpenPOWER On Chip Controller. The suite should be moved into the openpower/ directory tree.

**Comment by gkeishin** [comment]
Sounds like a plan.. Will do.

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/52451
