### ISSUE TITLE
tests-ipmi-test_fru.robot excuted failed

### ISSUE THREAD

**Issue by Bruce2813** [openbmc/openbmc-test-automation#2194]
No keyword with name 'OBMC Boot Test Py' found.Did you mean:
    obmc_boot_test_resource.OBMC Boot Test
how to due this problem?

**Comment by gkeishin** [comment]
@Bruce2813 I assume you are referring to ./tests/ipmi/test_fru.robot  this test suite.. 

1. Test suites under tests/  directory is deprecated but you can continue to use it or refer to build new test cases but with REST-only supported platforms drivers/builds   All the newer one's for IPMI are under here now https://github.com/openbmc/openbmc-test-automation/tree/master/ipmi

2.  If you still want to execute it, you can still do something like this

```
robot -v OPENBMC_HOST:xx.xx.xx.xx -v REDFISH_SUPPORT_TRANS_STATE:0 ./tests/ipmi/test_fru.robot
```

**Comment by gkeishin** [comment]
All good ?  @Bruce2813  If you need further information leave me a note here. Thanks

**Comment by gkeishin** [comment]
Please re-open if you still face problems. Closing ticket. Thanks
