### ISSUE TITLE
OpenBMC:Network: Create new resource file in lib to define all the variables for network buckets.

### ISSUE THREAD

**Issue by swe12345** [openbmc/openbmc-test-automation#2197]
Create new resource file in lib to define all the variables for the network buckets.

Redfish, GUI, SNMP and VMI can reuse the same set of variables defined in the file.

**Comment by gkeishin** [comment]
We already have the generic lib resource file for it.. lets extend it to use and not create new one, unless its more optimize way of doing it.

**Comment by swe12345** [comment]
Closing this issue as we have a generic library in place as of now.
