### ISSUE TITLE
Any restriction for the usage of Log or Log Console

### ISSUE THREAD

**Issue by susilsi7** [openbmc/openbmc-test-automation#2198]
In a Keyword if there are multiple action performed and a user wants to print each action in log and console then is he allowed to use both.

**Comment by gkeishin** [comment]
By default, robot collects logs for all the paths it executes and that would be good enough to tell what is executed and not. Having said that if there is a critical point you want to log which robot wouldn't automatically log, then you can probably add those but not just print statements here and there making the code too many loggings.
