### ISSUE TITLE
[Redfish]CertificateService: Enhance error handling for ReplaceCertificate 

### ISSUE THREAD

**Issue by MickDaDa** [openbmc/openbmc-test-automation#2199]
https://github.com/openbmc/openbmc-test-automation/blob/468d85faee9fcd558926ab0e26132fdea1be0937/redfish/dmtf_tools/test_redfishtool_certificate.robot#L383
Keyword: Verify Redfishtool Replace Certificate

Hi,
Seems this case need to change \\$\{HTTP_NOT_FOUND} to \\${HTTP_INTERNAL_SERVER_ERROR} ??
follow:
https://github.com/openbmc/bmcweb/commit/90d2d1e887e68c70f8e5923eb69c3c9356dae547

Tested:
* Replace HTTPS certificate at /redfish/v1/Managers/bmc/NetworkProtocol
  /HTTPS/Certificates/0 (Invalid URL) returns ResourceNotFound.
* Replace HTTPS certificate at /redfish/v1/Managers/bmc/NetworkProtocol
  /HTTPS/Certificates/1 with CertificateString not containing private
  key returns InternalError.

**Comment by gkeishin** [comment]
@rahulmah @manashsarma  can u handle this

**Comment by manashsarma** [comment]
I am looking. shall update

**Comment by manashsarma** [comment]
We have tested 'replace certificate' with following error scenarios  :

1. Empty Certificate, Empty Privatekey
2. Empty Certificate, Valid Privatekey
3. Valid Certificate, Empty Privatekey

For each of above case, response of 
**Redfishtool Post  ${payload}  /redfish/v1/CertificateService/Actions/CertificateService.ReplaceCertificate**  comes as:

   redfishtool: Transport: Response Error: status_code: 404 -- Not Found
   redfishtool: raw: Error sending POST to resource, aborting

so,  ${expected_resp} in such error cases is kept as ${HTTP_NOT_FOUND} in the code:

*******   code snippet ***********
 ${expected_resp}=  Set Variable If  '${expected_status}' == 'ok'  ${HTTP_OK}
    ...  '${expected_status}' == 'error'  ${HTTP_NOT_FOUND}

    ${response}=  Redfishtool Post
    ...  ${payload}  /redfish/v1/CertificateService/Actions/CertificateService.ReplaceCertificate
    ...  expected_error=${expected_resp}
***********************************************

Please feel free if you have additional query / comment. Or you can share with us your test scenario.

**Comment by gkeishin** [comment]
@MickDaDa See if the above response answers your query.

**Comment by MickDaDa** [comment]
Please see the information below:
https://github.com/openbmc/bmcweb/commit/90d2d1e887e68c70f8e5923eb69c3c9356dae547

I am not sure if the version is the same.

Tested:
* Replace HTTPS certificate at /redfish/v1/Managers/bmc/NetworkProtocol
  /HTTPS/Certificates/0  (Invalid URL) returns ResourceNotFound                     <<*** Invalid URL returns NotFound 
* Replace HTTPS certificate at /redfish/v1/Managers/bmc/NetworkProtocol
  /HTTPS/Certificates/1 with CertificateString not containing private
  key returns InternalError.                                                                                 <<***  not containing returns InternalError

**Comment by manashsarma** [comment]
@MickDaDa  I checked. Still the same result (NotFound). Can you please confirm if you are getting 'InternalError' in two testcases below  while passing : 'Valid Certificate 'and 'Empty Privatekey' . I understand this is same as 'CertificateString not containing privatekey' as you mention.

Verify Redfishtool Replace Server Certificate Errors
Verify Redfishtool Replace Client Certificate Errors

**Comment by manashsarma** [comment]
@MickDaDa the redfishtool version used for verifying this  is 1.1.5.

redfishtool -V
redfishtool Version: 1.1.5

**Comment by gkeishin** [comment]
@MickDaDa @manashsarma  all good here ?

**Comment by gkeishin** [comment]
I believe we have no further query on this. Thank you for reaching out to us. Feel free to leave a note if more information is needed. Thank you for your contribution.


Closing the ticket.
