### ISSUE TITLE
PreTag 0.8 Testing failure for 'Blink Slow the Identify LED'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#22]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/285)

Blink Slow the Identify LED
Full Name:  Tests.Test Led.Blink Slow the Identify LED
Documentation:  

This testcase is to test the setBlinkSlow functionality of the Identify LED. The LED state is sampled to figure out whether the LED is blinking. There is no distinguishing between whether the LED is blinking fast or slow for this testcase to pass.
Start / End / Elapsed:  20160519 15:21:21.448 / 20160519 15:21:42.413 / 00:00:20.965
Status:     FAIL (critical)
Message:    '0 > 0 and 5 > 0' should be true.

---

@vishwabmc commented on [Tue May 24 2016](https://github.com/openbmc/openbmc/issues/285#issuecomment-221178445)

Alright... I feel its not a bug wrt the LED blinking.. It should be about how we are sampling it. Doing it via network REST way definitely adds onto time. I would visually verify if the LED is blinking slow and if there are issues we can look into it. The duty cycle ratio was agreed with Norm after he visually inspected the LEDs.. 

Or are you saying its just about the Automated Testability request  ?

---

@causten commented on [Tue May 24 2016](https://github.com/openbmc/openbmc/issues/285#issuecomment-221180542)

Can the user use rest to discover if the led is set to what they asked it to be set to?  The test case indicates they can not.  So how does the user determine if the Led is blinking via rest ?

 Sent from my iPhone using IBM Verse

 On May 24, 2016, 1:31:30 AM, notifications@github.com wrote:

 From: notifications@github.com
 To: openbmc@noreply.github.com
 Cc: austenc@us.ibm.com, author@noreply.github.com
 Date: May 24, 2016 1:31:30 AM
 Subject: Re: [openbmc/openbmc] PreTag 0.8 Testing failure for 'Blink Slow the Identify LED' (#285)

   Alright... I feel its not a bug wrt the LED blinking.. It should be about how we are sampling it. Doing it via network REST way definitely adds onto time. I would visually verify if the LED is blinking slow and if there are issues we can look into it. The duty cycle ratio was agreed with Norm after he visually inspected the LEDs..  
  Or are you saying its just about the Automated Testability request ? 
  —You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

---

@vishwabmc commented on [Tue May 24 2016](https://github.com/openbmc/openbmc/issues/285#issuecomment-221181689)

So the user can use REST to see if its blinking looking at the pattern.. REST way can not today tell if its binking fast or slow since there would always be these network odds.. So back then, the requirement was to see if its blinking.. If we need at the granularity of duty cycle, we need to put some change into code and return what is the state  by looking at our own settings since those settings are what is directing the LEDs. 

We can take this change .. but would be a change to suffice testability aspects only.

**Comment by gkeishin** [comment]
@vishwabmc anything on this? we are now started the older failure here..  Can you provide us the details how to use the new REST way for this.. I see there is a defect on LED's as well currently https://github.com/openbmc/openbmc/issues/590

**Comment by gkeishin** [comment]
By the way i tried using CURL to mimic the test and it is working as per REST

$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://xx.xx.xx.xx/org/openbmc/control/led/heartbeat/action/setBlinkSlow -d "{\"data\":[]}"
{
  "data": 0,
  "message": "200 OK",
  "status": "ok"
}
gkeishin@gfwa124 ~/openbmc-test-automation
$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://xx.xx.xx.xx/org/openbmc/control/led/heartbeat/action/GetLedState -d "{\"data\":[]}"
{
  "data": [
    0,
    "On"
  ],
  "message": "200 OK",
  "status": "ok"
}
$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://xx.xx.xx.xx/org/openbmc/control/led/heartbeat/action/GetLedState -d "{\"data\":[]}"
{
  "data": [
    0,
    "Off"
  ],
  "message": "200 OK",
  "status": "ok"
}

Checking in automation as well what else we could do if there is any.

**Comment by gkeishin** [comment]
I think a simple tweak would be for now to increase the sampling rate to get better success result in this scenario.

**Comment by gkeishin** [comment]
Adding to skip list until the development has put the new code in for LEDs restructuring as discussed with Chris.

**Comment by gkeishin** [comment]
code is getting refactored...
