### ISSUE TITLE
Doc: [OpenBMC] Tickets / Issues / Test Status Report

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#220]
Place holder reports for  Driver builds , test results and issue tracking for OpenBMC.

To update.. click edit, copy to notepad or any text editor and add new one by just copying the previous table content.. and preview before saving it , all well then comment..

**Comment by gkeishin** [comment]
```**Driver Build Reports**```

`List` | `Build ` |  `System Tested` |  `Test Result %`
- [x]   v1.99.0-238-g14ceb26  Barreleye  100

**Comment by gkeishin** [comment]
**Currently Open**

|``` Status ```  |        ``` Description   ```                           |        ```   Git Number ```                      |
| -------------- | ------------------------------------------------------ | ------------------------------------------------ |
|       1        |  ` Failed to start Phosphor IPMI BT DBus Bridge `      | https://github.com/openbmc/openbmc/issues/760    |
|  Joel fixed this. Build tested, expected to be in master soon.         |
|       2        |  ` Failed to start Restore Last State `                | https://github.com/openbmc/openbmc/issues/755    |
|  Under Investigation |


**Recently Closed**

|``` Status ```  |        ``` Description   ```                           |        ```   Git Number ```                      |
| -------------- | ------------------------------------------------------ | ------------------------------------------------ |
|  Closed        | ` System went for maintenance mode post reboot`        | https://github.com/openbmc/openbmc/issues/750    |

**Comment by gkeishin** [comment]
**Recently Closed**

|``` Status ```  |        ``` Description   ```                           |        ```   Git Number ```                      |
| -------------- | ------------------------------------------------------ | ------------------------------------------------ |
|  Closed        | ` System went for maintenance mode post reboot`        | https://github.com/openbmc/openbmc/issues/750    |

**Comment by gkeishin** [comment]
**This if from OpenBMC test Automation perspective and purely for reference and understanding statistical history from various systems and test cycle runs**

**Common issues or factor impacting testing**


|  ``` Date ```  |        ``` Description   ```      |        ```   Comments ```                        |
| -------------- | --------------------------------- | ------------------------------------------------ |
|  11 Nov 2016   |  `PowerOn failures`               | Impacts genric and inventory test cases          |

**Comment by gkeishin** [comment]
**Monthly Report - NOVEMBER 2016**

|  ``` Date ```  |        ``` Description   ```                           |  ``` Github Number ```    |
| -------------- | ------------------------------------------------------ | --------------------------|
|  28 Nov 2016   |  `MTD device partition error for image-bmc`            | openbmc/openbmc#816       |
|  23 Nov 2016   |  `Poweron broken... Failed to boot HOST`               | openbmc/openbmc#828       |
|  23 Nov 2016   |  `The base /org listing pruned off ?`                  | openbmc/openbmc#830       |
|  22 Nov 2016   |  `Poweron didnt boot to HOST_BOOTED`                   | openbmc/openbmc#824       |
|  21 Nov 2016   |  `Firmware BIOS versioning format changed`             | openbmc/openbmc#821       |
|  21 Nov 2016   |  `Poweron didn't succeed to Host booted state`         | openbmc/openbmc#794       |
|  16 Nov 2016   |  `Phosphor settings services are not running`          | openbmc/openbmc#806       |
|  11 Nov 2016   |  `Failed to start Phosphor IPMI BT DBus Bridge`        | openbmc/openbmc#760       |
|  10 Nov 2016   |  `System went for maintenance mode post reboot`        | openbmc/openbmc#750       |

**Comment by sivassrr** [comment]
[WitherspoonlongrunwithskiptestDec16build.pdf](https://github.com/openbmc/openbmc-test-automation/files/661468/WitherspoonlongrunwithskiptestDec16build.pdf)

**Comment by sivassrr** [comment]
[witherspoon19Dec419Drivercombinedreport.pdf](https://github.com/openbmc/openbmc-test-automation/files/663466/witherspoon19Dec419Drivercombinedreport.pdf)

Found that first 5 iterations 100% Pass then next 5 Iterations 84% passed - Need to open issue for intermittent failure for boot/bootpolicy, time related test cases.

**Comment by rahulmah** [comment]
20 Dec - Barreleye CT results with Latest build : v1.99.0-338-gd6d3ef3 - https://openpower.xyz/job/openbmc-build/419/

- [ ] - Code update : Good
- [ ] - CT : 166 passed, Overall good
- [ ] - HW CI passed, Overall good

**Comment by sivassrr** [comment]
![](https://files.slack.com/files-pri/T0JA1U9GV-F3GV7CZJ7/pasted_image_at_2016_12_20_07_22_pm.png)
Rerun loop test (5 Iterations) using 419 Driver, No issues observed.

**Comment by sivassrr** [comment]
https://files.slack.com/files-pri/T0JA1U9GV-F3GV7CZJ7/pasted_image_at_2016_12_20_07_22_pm.png

**Comment by sivassrr** [comment]
Driver 422 ran loop test on Witherspoon: 
1st 5 Iterations: No failure observed: 
[Witherspoontest1st5Iterationgoodrun.pdf](https://github.com/openbmc/openbmc-test-automation/files/668638/Witherspoontest1st5Iterationgoodrun.pdf)

2nd 10 Iterations: Sensors, Errorlog, Association Test Suite failures observed . (Sensors failed because of Dbus exception)
[Witherspooncombined10iterationsDriver422.pdf](https://github.com/openbmc/openbmc-test-automation/files/668640/Witherspooncombined10iterationsDriver422.pdf)

**Comment by sivassrr** [comment]
[witherspoonDriver423Iterations10Report.pdf](https://github.com/openbmc/openbmc-test-automation/files/680403/witherspoonDriver423Iterations10Report.pdf)
Result similar to Driver 422 only.  I was told in another witherspoon system all CT test without power on passes. So trying it on that system.

**Comment by sivassrr** [comment]
With another system, All 144 TCs passed using Driver 423. 
[WitherspoonDr423Iterations10w6.pdf](https://github.com/openbmc/openbmc-test-automation/files/680487/WitherspoonDr423Iterations10w6.pdf)

**Comment by sivassrr** [comment]
Barreleye long run with latest driver 10 Iterations: (11 TCs failed out of 1660 TCs).
[barreleyelongrun10Iterations9Jan2017.pdf](https://github.com/openbmc/openbmc-test-automation/files/693621/barreleyelongrun10Iterations9Jan2017.pdf)

**Comment by sivassrr** [comment]
[WitherspoonDriver437Iterations10.pdf](https://github.com/openbmc/openbmc-test-automation/files/701326/WitherspoonDriver437Iterations10.pdf)

**Comment by sivassrr** [comment]
[witherspoon10iterationsDr442.pdf](https://github.com/openbmc/openbmc-test-automation/files/703706/witherspoon10iterationsDr442.pdf)
```
Good news with Dr 442 of Witherspoon is no Time related issue - looks like got fixed. But we started seeing eventlog/boot related TC failures. Overall Dr442 is good only 10 TCs out of 1440 failed. 
```

**Comment by sivassrr** [comment]
Earlier driver "Dbus Exception" error was concern. From Driver 442, Not observing it.
But now observing 503 Error which is related to REST service unavailable.

```
New issues are opened and their details as follows:
https://github.com/openbmc/openbmc/issues/966
https://github.com/openbmc/openbmc/issues/967
https://github.com/openbmc/openbmc/issues/968
https://github.com/openbmc/openbmc/issues/969

**Comment by sivassrr** [comment]
[966](https://github.com/openbmc/openbmc/issues/966)
[967](https://github.com/openbmc/openbmc/issues/967)
[968](https://github.com/openbmc/openbmc/issues/968)
[969](https://github.com/openbmc/openbmc/issues/969)

**Comment by sivassrr** [comment]
With driver 443 for Witherspoon, has lot of "503 - Service unavailable" related failures when compare to Driver 442. 
More over Time case which was passed earlier, now failing. [Equivalent defect is 915(https://github.com/openbmc/openbmc/issues/915)]
[witherspoonDr443Iterations10.pdf](https://github.com/openbmc/openbmc-test-automation/files/707277/witherspoonDr443Iterations10.pdf)

**Comment by sivassrr** [comment]
With Driver 449 for witherspoon, Little bit improvement from previously loop tested driver 443. 
98.6% is the passing percentage. 
```
Still observing 503 - Services unavailable intermittent errors
```
[WitherspoonDr449Iterations10.pdf](https://github.com/openbmc/openbmc-test-automation/files/710393/WitherspoonDr449Iterations10.pdf)

**Comment by sivassrr** [comment]
[witherspoonw6Dr453.pdf](https://github.com/openbmc/openbmc-test-automation/files/716558/witherspoonw6Dr453.pdf)
[witherspoonw1Dr453.pdf](https://github.com/openbmc/openbmc-test-automation/files/716559/witherspoonw1Dr453.pdf)

**Comment by sivassrr** [comment]
Driver 453 is not good when compare to previous driver. Failing percentage is more.

**Comment by sivassrr** [comment]
Driver 466 Test on Barreleye looks good **96.4%** passed with 9 Iterations. Need to check any new issues observe and open issues accordingly. Here is the report. 
[BarreleyeDr466Iteratioins9.pdf](https://github.com/openbmc/openbmc-test-automation/files/721812/BarreleyeDr466Iteratioins9.pdf)

**Comment by sivassrr** [comment]
[Witherspoonw6Dr468Iterations10.pdf](https://github.com/openbmc/openbmc-test-automation/files/722599/Witherspoonw6Dr468Iterations10.pdf)

**Comment by SrideviRamesh** [comment]
Palmetto build with version "v1.99.1-100" went to unpingable state after running basic poweron test 
https://github.com/openbmc/openbmc/issues/1064

still we are observing HOST_BOOTING issues with every palmetto release builds
https://github.com/openbmc/openbmc/issues/861

**Comment by gkeishin** [comment]
Closing this as we have new way to report status..
