### ISSUE TITLE
How to define the import section for python, robot , custom python module

### ISSUE THREAD

**Issue by susilsi7** [openbmc/openbmc-test-automation#2200]
Sample code from current File.

```
import os
import tempfile
import json
import glob
from tally_sheet import *

from robot.libraries.BuiltIn import BuiltIn
try:
    from robot.utils import DotDict
except ImportError:
    import collections

import gen_print as gp
import gen_valid as gv
import gen_misc as gm
import gen_cmd as gc
import var_funcs as vf

```

1. Which module has higher precedence robot / python / python custom module
2. can you provide sample code with section for each modules
3. Any space required between robot / python / python custom module

**Comment by williamspatrick** [comment]
We are going to enable black/Isort across the whole project soon.  Those probably answer most of your questions.

**Comment by gkeishin** [comment]
we have cleaned up a bunch and still, there are more for the future.. but this can be closed now.
