### ISSUE TITLE
Python function Docstrings write up guidelines 

### ISSUE THREAD

**Issue by susilsi7** [openbmc/openbmc-test-automation#2202]
Which will have high precedence.

1. Function Documentation
2. Description of argument
3. Example of function
4. Argument example

**Comment by gkeishin** [comment]
This is something we don't mandate apart from known community Python doc string.  There are examples already in the code in openbmc test Please follow it and if extra input feedback is required, we will see it on use case basis. since we don't plan to revamp all our documentation.
