### ISSUE TITLE
Valid Length get pass for empty min_length and max_length

### ISSUE THREAD

**Issue by susilsi7** [openbmc/openbmc-test-automation#2207]
Sample Code:

```
Test Valid Length
    [Documentation]  Test valid length.
    [Tags]  Test_Valid_ Length

    Set Test Variable  ${name_item}  BMC

    Valid Length  name_item
```

**Comment by gkeishin** [comment]
This is more of a code suggestion; we don't expect empty to be passed and don't check for bare length with a valid length logic which can be done by any robot or python logic exiting. Closing this ticket
