### ISSUE TITLE
Error: WebDriver.__init__() when starts GUI tests

### ISSUE THREAD

**Issue by kaospwnz** [openbmc/openbmc-test-automation#2211]
Hello everyone. 
I used Ubuntu 22.04(VMWare 16) and Geckodriver 33.0, IPMI tool alredy insstalled, and I got the trouble with GUI tests. 
Its isn't working, I get the error on every test: 

Verify Navigation To Sensors Page :: Verify navigation to Sensors ... | FAIL |
Parent suite setup failed:
Keyword 'Retry Browser Login Attempts' failed after retrying for 2 minutes 10 seconds. The last error was: TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'

Can you help me, please? What I need to do? Thanks a lot!

**Comment by gkeishin** [comment]
@kaospwnz  Can u check this setup and see if it matches or is similar for running Web UI test bucket runs 
https://github.com/openbmc/openbmc-test-automation/blob/master/docs/gui_setup_reference.md

**Comment by gkeishin** [comment]
Adding @rahulmah  to as well give his opinion on the above

**Comment by rahulmah** [comment]
Just try providing OPENBMC_USERNAME and OPENBMC_PASSWORD like below while running your suite and see if that works out for you.

```
python3 -m robot -v OPENBMC_HOST:x.x.x.x  -v OPENBMC_USERNAME:${BMC_USERNAME} -v OPENBMC_PASSWORD:${BMC_PASSWORD} \ -v GUI_MODE:header gui/gui_test/<Path_of_your_suite>
```

**Comment by gkeishin** [comment]
@kaospwnz all good ?

**Comment by gkeishin** [comment]
Closing the ticket.. If not working please re-open.. Thanks
