### ISSUE TITLE
Test Software Manager: Variable '${path}' not found.

### ISSUE THREAD

**Issue by justin0309** [openbmc/openbmc-test-automation#2213]
1.I am testing Test Software Manager, and the fourth test item (BMC Software Path) has a Variable '${path}' not found error. I wonder if P should be capitalized?
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/9103881e-b5e3-40aa-87a4-f80116a07a4b)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/eedd0135-61e5-4964-ac63-4568b87bf465)
2.The sixth test item (BMC Software Activation Association), '/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc', I still don’t quite understand this. It should be that we need to confirm whether there is support, right? If not We skip this test item ourselves?
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/31ff2a51-0045-40c6-b713-0aae55daec9b)

**Comment by gkeishin** [comment]
If your system is running with Redfish use this parameter by default in CLI 
```
-v REDFISH_SUPPORT_TRANS_STATE:1
```

**Comment by justin0309** [comment]
1.I tried to bring this parameter in, the result is the same.
robot -v REDFISH_SUPPORT_TRANS_STATE:1 -v OPENBMC_HOST:xxx.xxx.xxx.xx extended/code_update/test_software_manager.robot

**Comment by gkeishin** [comment]
Ah.. thats the old legacy code with REST..  the new ones are with Redfish which is
```
openbmc-test-automation/tree/master/redfish/update_service/

~/openbmc-test-automation/redfish/update_service$ tree
.
├── test_bmc_image_switch.robot
├── test_firmware_inventory.robot
├── test_firmware_property.robot
├── test_firmware_tftp_upload_image.robot
├── test_redfish_bmc_code_update.robot
├── test_redfish_host_code_update.robot
├── test_redfish_image_upload.robot
└── test_redfish_signed_image_update.robot
```
we don't support the extended/code_update/  anymore

**Comment by justin0309** [comment]
Thanks for your response,
In addition, I would like to ask whether we currently use the 2.12 version of the code base to test the auto-test of v3.0-stable. Are there any that do not support REST?
Will redfish be used for testing these test items in the future?

**Comment by gkeishin** [comment]
@justin0309 Thank you for reaching out to us.  Currently, we are in life support for legacy REST test cases. All the versions and current master also still support REST ( we don't plan to disable or support it anymore but kept it as a historical legacy for reference)

We have added in [README](https://github.com/openbmc/openbmc-test-automation#test-layout
) for users to inform that it is no longer supported by the community, but if you have a legacy system with builds running on it and have a fix patch for it, you are most welcome to push up a patch upstream and we can merge it after review.

Yes, currently OpenBMC has been on redfish for a few years and expects to use redfish in future. 

Hope that helps !!

**Comment by gkeishin** [comment]
Closing this ticket.
