### ISSUE TITLE
Test Firmware Inventory

### ISSUE THREAD

**Issue by justin0309** [openbmc/openbmc-test-automation#2215]
1. According to my understanding, the image updated for the first time will be the running image, and the image updated for the second time will be the backup image. Is this correct?
2. My situation is that my image version=none. Is it because my image versison is none, so there won’t be anything in the backup image?
3. I would like to ask how to modify the image version?
Thanks
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/28c2b4f5-ab86-4482-bfb3-0a57f2208bb8)

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/26ab4715-805b-47f5-b6eb-1a0014e1558e)

**Comment by gkeishin** [comment]
@susilsi7 can you respond to this. ?

**Comment by susilsi7** [comment]
1. When user update first firmware , consider A image then Running Image become A. when user update second firmware that is B, then Running Image become B and Backup Image A.
2. Could be image version=none. but needs to be checked and if backup image is not there either it got deleted or never updated. how you got the firmware with version none ?
3. user not allowed to change image version, it comes with the build.

**Comment by justin0309** [comment]
@susilsi7 Thank you for your reply.
1.I want to confirm first. Do I need two bmc flashes on the machine to update the backup image?
Or can we update two firmwares, one is the running image and the backup image? If so, where will they be stored?
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/c26714b6-ba90-440b-8ee3-f41a79a062c6)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/7cde9d13-94ba-449d-83ac-c5ac4bd019d5)
This is the problem I'm currently having, what should I try to resolve it?
2.So where can I change the version when building?
3.So how does openbmc know the bios version? Because I can't find this path on the machine. cat: can't open '/var/lib/phosphor-software-manager/pnor/ro/pnor.toc': No such file or directory
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/5c7071b2-4b5a-49a8-9a45-5065269ab216)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/6a69a338-8c81-4803-8bb4-b0a717f8f17b)

**Comment by gkeishin** [comment]
@justin0309  This is good feedback, we don't have x86 arch system to test for PNOR earlier.. 

I don't think you need to add any of those.. The test Verify BIOS version is checking Redfish vs any other method ( above via phosphor-software-manager ) to validate the version.

If you have info in x86 how can we check any other path since that phosphor-software-manager is not there in x86, we can amend the code to handle it.

**Comment by justin0309** [comment]
@gkeishin 
According to our machine
bios x86 architecture,
bmc arm architecture (aspeed)
two bmc flash

I'm glad to get this helpful information. Do you have any other ideas or solutions regarding the first and second points above?

Based on my research and testing these days, my idea is that because the calculated image IDs are all 039d44e1, they are considered to be the same image, so there is no way to update to the backup image. Is this correct?

**Comment by gkeishin** [comment]
In the current scheme, firmware updates should allow updating with the same ID as well.  

as for the question
```
1. So where can I change the version when building?

2. so there is no way to update to the backup image. Is this correct?  for PNOR
```
@anoo1 can give input there.

**Comment by justin0309** [comment]
@gkeishin @anoo1

For these two questions, I want to ask about the BMC part, or whether the bmc backup image part is also related to PNOR, because I don't know much about PNOR.

**Comment by justin0309** [comment]
@anoo1 
1. I confirmed my git tag and then changed it in the os-release file under the tmp/work/<machine>-openbmc-linux-gnueabi/obmc-phosphor-image/1.0-r0/rootfs/etc/os-release path The version and version id are the same as the tag, then bitbake obmc-phosphor-image, and update it through scp and uboot. The situation is still the same on the machine. I don’t know if I did something wrong in any step.Because there is still nothing in the backup image
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/a1494cc5-cc65-4a1e-a5b7-ac93db6f05bf)


2.PACKAGECONFIG[static-dual-image] = "-Dbmc-static-dual-image=enabled, -Dbmc-static-dual-image=disabled"

This line does exist in openbmc/meta-phosphor/recipes-phosphor/flash
Inside /phosphor-software-manager_git.bb

**Comment by mdmillerii** [comment]
The BMC code manager tries to obtain the version by mounting the alternate image and parsing os-release.   There is a helper script to mount and unmount the alternate image that may be missing from your system

**Comment by anoo1** [comment]
Like Milton mentioned, there's a script the mounts the alternate chip (it's a separate chip, not the same chip with 2 images): https://github.com/openbmc/phosphor-bmc-code-mgmt/blob/master/static/obmc-flash-bmc-static-mount-alt.service.in

In order to make this secondary chip visible to the script, need to specify it in the kernel device tree as alt-bmc, example:
https://github.com/openbmc/linux/blob/6f8bb353a755ae9f4985b3c084d4d1be62782baf/arch/arm/boot/dts/aspeed-bmc-bytedance-g220a.dts#L263

**Comment by mdmillerii** [comment]
As you surmised prefixing partitions with `alt-` is correct  and applies to all partitions including rwfs.   Remember that when booting on the alternate image (because the watchdog fired) causes the **physical chip to the software labels to be swapped**.   Unless you plan a special recovery firmware with limited functionality your includes should have identical content except for the alt prefix on label names.

This will need to be considered when actually recovering (where you want to update alt ) vs preserving golden (where you update primary active partitions) but this is a future detail to address.

Please clarify still doesn't work.   Have you written an image into the alternate device?  Was the alternate image mounted?

**Comment by justin0309** [comment]
Because flash 1 is welded to the machine, it cannot be used through the burner. Currently, the method I know can only be used to burn the backup image through uboot. Booting from the baukup image is no problem. , or is there another way based on the current situation?


Regarding **Was the alternate image mounted**? What does this probably mean? I have always wanted to know how to upload multiple files. My current approach is mostly to use scp to put image-bmc under run/initramfs/ for updates. And do the reboot action.

At present, when the burning operation is completed, it will be like the situation in my previous post /xyz/openbmc_project/software/xxxxxxx. There will only be the latest one. My understanding is that under normal conditions, there should be multiple images under the software, right?

**Comment by justin0309** [comment]
@anoo1 

https://github.com/openbmc/openbmc/blob/76ee43cd4c1ff7d1435465e164d2e39a2e8a7336/meta-phosphor/recipes-phosphor/flash/phosphor-software-manager_git.bb#L19  

Regarding what you said earlier about confirming whether this function is enabled, what I want to ask is that I only confirmed whether this line exists before, but I don’t know how to enable it. I don’t know if it is because this function is not enabled. problems encountered.

**Comment by anoo1** [comment]
> Currently there is only one line EXTRA_OEMESON:append = "-Dbmc-static-dual-image=enabled"

Hi, Try adding the packageconfig to your phosphor-software-manager_%.bbappend file:
`PACKAGECONFIG:append = "  static-dual-image"`

**Comment by justin0309** [comment]
@anoo1 @mdmillerii @gkeishin @susilsi7 

It worked, thank you all so much for your help, I hope this information helps others too.
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/5f440376-b2ff-43b7-a526-99d8967f6a6d)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/3a7e84fd-ca8f-4dee-b94d-96c5066043f7)

**Comment by gkeishin** [comment]
Sure thing.. Thanks for the feedback @justin0309 

Closing this ticket. Thanks @anoo1 @susilsi7
