### ISSUE TITLE
[OpenPower] test_bmc_devicetree, test teardown failed

### ISSUE THREAD

**Issue by tom-ky-wu** [openbmc/openbmc-test-automation#2219]
HI, when I test them separately, they pass. 
However, when I test them together, if the previous test case fails, it results in a subsequent test case "connection failed."

Here is my fixed content:
-Suite Setup         Open Connection And Log In
-Suite Teardown      Close All Connections
-Test Teardown       FFDC On Test Case Fail
+Test Setup         Open Connection And Log In
+Test Teardown      Run Keywords  Close All Connections
+...                AND           FFDC On Test Case Fail-Suite Setup         Open Connection And Log In

**Comment by gkeishin** [comment]
Good thought that.. fixed https://gerrit.openbmc.org/c/openbmc/openbmc-test-automation/+/67120  @tom-ky-wu
