### ISSUE TITLE
[OpenPower] check_error_logs teardown failed

### ISSUE THREAD

**Issue by tom-ky-wu** [openbmc/openbmc-test-automation#2220]
Teardown failed : Keyword 'openbmc_ffdc.FFDC On Test Case Fail' expected 0 arguments, got 1.
Keywords
FFDC On Test Case Fail  clean_up=${FALSE}
But keywords of this isn't get extra argument

**Comment by gkeishin** [comment]
Fix https://gerrit.openbmc.org/c/openbmc/openbmc-test-automation/+/67119
