### ISSUE TITLE
Redfish Service Validator

### ISSUE THREAD

**Issue by justin0309** [openbmc/openbmc-test-automation#2221]
Currently I am testing with v3.0-stable version.
I tested it in docker.

I know that the problem regarding branch_name in the dmtf test item has been corrected in the master version. 
For the following two test items, I can't find any relevant information for my reference. 
1.The first test (Test BMC Redfish Using Redfish Service Validator) fails. I don't know which direction to pursue. How should the member ID match to pass?
Is it odata.id": "/redfish/v1/Chassis/chassis/Power#/Voltages/**0** and "MemberId": "**ADC_12**" The number at the end must match?
2.The second test (Run Redfish Service Validator With Additional Roles) seems to be that it cannot be created once Get User Role is started.

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/a55946af-a82f-4d8d-a5ff-f5dd1040d9fe)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/cdaaf582-9406-434d-805a-ebceda3da1dc)

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/0233e1ec-ad54-448e-9597-754c963112bc)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/24100f28-8ced-44c0-94bb-81be08800f3d)
--------------------------------------------------------------------------------------------------------
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/87f75a91-030d-4136-9c1c-f3d55a060061)
I tried setting device_name to 0 and this one is pass.

So if the path is /xyz/openbmc_project/sensors/temperature/Sensor_Temp_2, the following Sensor_Temp_2 must be named according to 0, 1, 2, 3, 4 and so on. Is there any relevant information that I can refer to?

**Comment by justin0309** [comment]
@gkeishin can anyone assist me?

**Comment by justin0309** [comment]
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/17ac8402-512a-4112-842e-e18ee165205d)

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/0c22d718-c1c1-490a-9db1-11f7b7cb7792)

err.OemSession.v1_0_0.Session This error cannot tell where the actual error is.

**Comment by justin0309** [comment]
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/e46a9014-77bd-4328-b7ec-ea390801ebb1)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/ccb2d9d8-18d2-4fa9-abcc-286523e2ffdc)

err.OemSession.v1_0_0.Session This error cannot tell where the actual error is.

**Comment by mdmillerii** [comment]
The validator is complaining about the third session.  It appears two were formatted to json and the third likely is trying to generate an error response that (1) didn't create an error response and (2) didn't offer the client any details why.

**Comment by gkeishin** [comment]
1.The first test (Test BMC Redfish Using Redfish Service Validator) fails. I don't know which direction to pursue. How should the member ID match to pass?
Is it odata.id": "/redfish/v1/Chassis/chassis/Power#/Voltages/0 and "MemberId": "ADC_12" The number at the end must match?

> This is probably a schema vs implementation error which Redfish validator is complaining about.. Reach out to the OpenBMC community on discord ```https://discord.gg/GYqshvV8```

2.The second test (Run Redfish Service Validator With Additional Roles) seems to be that it cannot be created once Get User Role is started.

> This one, I can check on it..

**Comment by gkeishin** [comment]
@justin0309 it looks like with 0penBmc default password it doesn't seem to work for the additional roles while creating.. So probably I can update the test case like this to make it default for Operator and Read-only users

```

    #username      password             role        enabled
    operator_user  0penBmc123           Operator    ${True}
    readonly_user  0penBmc123           ReadOnly    ${True}
```

can you try with this changes if it works clean in your setup.. if all works I ll push up the changes..

**Comment by gkeishin** [comment]
Never mind. I have pushed up the patch fix for the additional role to work
https://gerrit.openbmc.org/c/openbmc/openbmc-test-automation/+/67609
@justin0309
