### ISSUE TITLE
[Openpower] Test Inband Bmc Auth Reset

### ISSUE THREAD

**Issue by tom-ky-wu** [openbmc/openbmc-test-automation#2231]
Hi , 
I would like to ask for test case:  Test Inband Bmc Auth Reset
![image](https://github.com/openbmc/openbmc-test-automation/assets/148036528/85161f4d-3fcb-457b-a0fe-1b5e696a2a46)

It appears that it is testing the functionality of the "ipmitool raw 0x3a 0x11" command. 
Therefore, before proceeding with this command, the HTTP response is expected to be 'OK,' which is a reasonable result.
However, what is the reason for performing verification steps before proceeding with this command in robot procedure?

**Comment by gkeishin** [comment]
I vaguely remember this test and it was meant as a script to recover the system in case of BMC REST gets locked or something.. as mentioned in the test suite file documentation.  

```
# This resets the BMC authentication:
# - Enable local users if they were disabled.
# - Delete the LDAP configuration if there was one.
# - Reset the root password back to the default one.
```

**Comment by gkeishin** [comment]
Closing this ticket as no further is required. Thank you for the ticket and feedback.
