### ISSUE TITLE
Test Ipmi Payload

### ISSUE THREAD

**Issue by justin0309** [openbmc/openbmc-test-automation#2234]
I would like to ask if you have encountered similar problems?
I added channel_config.json (0-15)
Unused channels are also changed to reserved.
does not contain 'rsp=0xcc

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/c7a938b4-c51d-4dda-b22e-ff74f81bcea6)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/e1c8f0df-af43-46fa-9ee3-9aeb5fcaf0f0)
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/e32ad0c7-1e0e-4b34-bbc4-a296778936f0)

**Comment by gkeishin** [comment]
@Ganesan149 can you respond to this?

**Comment by justin0309** [comment]
@gkeishin 
I have found that the step of setting the user in the test item sometimes fails.
This fail will appear in different test items from time to time.
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/7709b27c-6516-4ace-acfa-ea954f6dec08)

**Comment by gkeishin** [comment]
ok. if we can figure out what causes the intermittent failure would be great.  Having said that probably there is a problem causing the user creation failure or failed to clean up.

**Comment by justin0309** [comment]
Is the failure to set the user name related to the setting of the Privilege permission level?

`/xyz/openbmc_project/ipmi/sol/eth0:
    - Interface: xyz.openbmc_project.Ipmi.SOL
      Properties:
          Enable:
              Default: 'true'
          Privilege:
              Default: 4
          Progress:
              Default: 0`

**Comment by justin0309** [comment]
As far as I know, there is a problem with the determination of invalid user and invalid channel.
If you need to meet the requirements of robot test, you should modify the test like this to pass

1.Verify Set User Access Payload For Invalid User
https://github.com/openbmc/phosphor-host-ipmid/blob/ea46f3ca61dd12b210a74cf78e464c78e0987a47/user_channel/user_mgmt.cpp#L862C1-L862C1
std::string userName;
userName.assign(reinterpret_cast<char*>(userInfo->userName), 0,
                    ipmiMaxUserName);
    if (userName.empty())
    {
        log<level::DEBUG>("User name not set / invalid");
        return ccInvalidFieldRequest;
    }
2.Verify Get User Access Payload For Invalid User
https://github.com/openbmc/phosphor-host-ipmid/blob/ea46f3ca61dd12b210a74cf78e464c78e0987a47/user_channel/user_layer.cpp#L213
std::string userName;
userName.assign(reinterpret_cast<char*>(userInfo->userName), 0,
                    ipmiMaxUserName);
    if (userName.empty())
    {
       return ccInvalidFieldRequest;
    }
3.Verify Get Channel Payload Support For Invalid Channel
https://github.com/openbmc/phosphor-host-ipmid/blob/ea46f3ca61dd12b210a74cf78e464c78e0987a47/user_channel/channel_mgmt.cpp#L153
These codes below should be deleted,

if (!isValidChannel(chNum))
    {
        log<level::ERR>("Invalid channel number.",
                        entry("CHANNEL_ID=%d", chNum));
        throw std::invalid_argument("Invalid channel number");
    }

**Comment by gkeishin** [comment]
These areas @Ganesan149 and @nagarjunb22 can help explain or look at it ..

**Comment by gkeishin** [comment]
@justin0309 posted a question to them on discord https://discord.gg/ygQcVkuD   

may be you can as well join the discord to talk to them on it.

**Comment by justin0309** [comment]
@gkeishin I think I have solved this problem, thank you
