### ISSUE TITLE
Verify Set IP Address source to unspecified address source via IPMI.

### ISSUE THREAD

**Issue by justin0309** [openbmc/openbmc-test-automation#2236]
I have tried every bit according to the ipmi spec. Currently, only 0h = unspecified will cause problems.
![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/f34995bb-3b9d-4022-8b0d-8de980f771f6)

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/8a63b292-9232-4ed3-b026-006732069476)

**Comment by gkeishin** [comment]
@ishwaryamathim @Ganesan149 could help there. 

and there are bunch of IPMI fixes in review as well 

https://gerrit.openbmc.org/q/project:openbmc/openbmc-test-automation+status:open+IPMI

**Comment by justin0309** [comment]
The source code expects case IPSrc::Unspecified: to return response(ccParamNotSupported); but the robot expects 0xcc, which one should be followed?

https://github.com/openbmc/phosphor-host-ipmid/blob/ea46f3ca61dd12b210a74cf78e464c78e0987a47/transporthandler.cpp#L821
