### ISSUE TITLE
[Automation]  BIOS versioning string changed 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#226]
Please refer : https://github.com/openbmc/openbmc/issues/821

for details of the information.

**Comment by gkeishin** [comment]
@SrideviRamesh  I think the string are now as per original one i think.. Confirm the same and close this..

**Comment by rahulmah** [comment]
This is the BIOS string which we are seeing at the preset. This string the not matching with our test and failing our test.
```
1:30:13     "Name": "OpenPOWER Firmware", 
21:30:13     "Serial Number": "", 
21:30:13     "Version": "IBM-barreleye-ibm-OP8_v1.12_2.77", 
21:30:13     "fault": "False", 
21:30:13     "fru_type": "SYSTEM", 
21:30:13     "is_fru": 1, 
21:30:13     "present": "True", ```

**Comment by gkeishin** [comment]
Again the Versioning changed... ?

**Comment by gkeishin** [comment]
Closing as the new interface xyz is coming up..
