### ISSUE TITLE
PreTag 0.8 Testing failure for 'get names /'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#23]
@causten commented on [Thu May 19 2016](https://github.com/openbmc/openbmc/issues/287)

Full Name:  Tests.Test Obmcrest.get names /
Start / End / Elapsed:  20160519 15:23:39.010 / 20160519 15:23:53.120 / 00:00:14.110
Status:     FAIL (critical)
Message:    ConnectionError: HTTPSConnectionPool(host='9.3.23.24', port=443): Max retries exceeded with url: /enumerate (Caused by ReadTimeoutError("HTTPSConnectionPool(host='9.3.23.24', port=443): Read timed out. (read timeout=5.0)",))
00:00:14.109 KEYWORD ${resp} = rest_client . OpenBMC Get Request /enumerate 

---

@anoo1 commented on [Mon May 23 2016](https://github.com/openbmc/openbmc/issues/287#issuecomment-221070050)

What is the test case trying to do? @rahulmah could you take a  look?

---

@rahulmah commented on [Tue May 24 2016](https://github.com/openbmc/openbmc/issues/287#issuecomment-221276901)

@anoo1 : 'get names /' internally fo GET for /enumerate

}rahuls-MacBook-Pro:~ rahulmaheshwari$ curl -c cjar -b cjar -k -X GET -d "{\"data\":[]}" https://9.3.23.30/enumerate
{
  "data": {
    "/org/openbmc": {}, 
    "/org/openbmc/HostIpmi/1": {}, 
    "/org/openbmc/NetworkManager/Interface": {}, 
    "/org/openbmc/UserManager/Group": {}, 
    "/org/openbmc/UserManager/Groups": {}, 
    "/org/openbmc/UserManager/User": {}, 
    "/org/openbmc/UserManager/Users": {}, 
    "/org/openbmc/buttons": {}, 
    "/org/openbmc/buttons/power0": {
      "state": 0, 
      "timer": 0
    }, 
    "/org/openbmc/buttons/reset0": {
      "state": 0,

**Comment by sivassrr** [comment]
Found this test cases now passes on barreleye. Need to check it on Palmetto as well.

**Comment by gkeishin** [comment]
We see this failure on barreleye as well..

**Comment by sivassrr** [comment]
Issue is on and off. Need to verify and close it.

**Comment by gkeishin** [comment]
I dont see this anymore on latest build  v1.99.0-251-gb78c6de on witherspoon. Checking on Barreleye

**Comment by gkeishin** [comment]
The following test cases which were skipped due to failure are now working and verified on driver v1.99.0-251-gb78c6de

enabling back the test cases in main bucket.
