### ISSUE TITLE
Bringup, Driver Analysis and issue open

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#245]

**Comment by gkeishin** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/220

**Comment by gkeishin** [comment]
Ticket Raised on Github

1.  https://github.com/openbmc/openbmc/issues/880
2.  https://github.com/openbmc/openbmc/issues/879
3.  https://github.com/openbmc/openbmc/issues/881

1.  https://github.com/openbmc/openbmc-test-automation/issues/238
2.  https://github.com/openbmc/openbmc-test-automation/issues/237
3.  https://github.com/openbmc/openbmc-test-automation/issues/234
4.  https://github.com/openbmc/openbmc-test-automation/issues/231
5.  https://github.com/openbmc/openbmc-test-automation/issues/230
6.  https://github.com/openbmc/openbmc-test-automation/issues/229
7.  https://github.com/openbmc/openbmc-test-automation/issues/240
8.  https://github.com/openbmc/openbmc-test-automation/issues/241

**Comment by gkeishin** [comment]
Updated as well in https://github.com/openbmc/openbmc-test-automation/issues/257

Closing this for this sprint
