### ISSUE TITLE
OpenFSI Test

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#251]
To test the implementation of OpenFSI Test

**Comment by sivassrr** [comment]
@gkeishin Feel free to update the estimate or if you have any question, Please let know. 
http://openpowerfoundation.org/wp-content/uploads/resources/OpenFSI-spec/content/ch02.html

**Comment by gkeishin** [comment]
Sounds good to me.. Will take a look at this..

**Comment by gkeishin** [comment]
From the discussion so far gathered.. 
1. The OpenFSI supported driver changes is not yet in the build.
2. They are tested through Update, poweron , resets and Host few to mention 
3. Another option is using SCOM operation from HOST Os to do checkstop

**Comment by sivassrr** [comment]
This got covered during our loop / Power on Test. So I am closing it.
