### ISSUE TITLE
XCAT Test Automation / Manual configuration

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#256]
Current planned spread across for next 2 sprints

- [ ] Infra structure for XCAT ( connect/ loging / add BMC nodes)  https://github.com/openbmc/openbmc-test-automation/issues/597
- [ ] Node poweron/ off and verify   https://github.com/openbmc/openbmc-test-automation/issues/598
- [x] Dependencies :  
     1. Dedicated XCAT setup ( Manual for now ) 
     2. XCAT server should be in same network with the system under test  ( BMC )

Note:  
We have a setup as for pilot testing however for regression testing we will need to setup a dedicated XCAT

**Comment by sivassrr** [comment]
Please check with me. Will pass power system details where QEMU is installed on Power system. Using that you need to connect to XCAT. 
Basically create multiple QEMU and try to connect XCAT using that. 
As discussed with XCAT team, openbmc may not have XCAT support yet. Please check and open issues accordingly.

**Comment by sivassrr** [comment]
Feel free to add your estimate accordingly.

**Comment by sivassrr** [comment]
Feel free to update your estimate.

**Comment by sivassrr** [comment]
http://wiki.qemu.org/Documentation/Platforms/PowerPC

You can get more details about QEMU on PowerPC in the above link

**Comment by sivassrr** [comment]
http://wiki.qemu.org/Documentation/Platforms/POWER - Right one

**Comment by sivassrr** [comment]
Shared the system detail where QEMU on Power is installed.

**Comment by sivassrr** [comment]
We could successfully install XCAT and able to add FSP/openpower system. Now need to work on openbmc system.

**Comment by gkeishin** [comment]
Task already completed as per @prkatti1  closing
