### ISSUE TITLE
Jan Support: Auto Test, log evaluation and opening issues - Witherspoon

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#257]

**Comment by sivassrr** [comment]
Expectation is to run loop test and evaluate the test results and open issues accordingly. 
Also update the status in https://github.com/openbmc/openbmc-test-automation/issues/220

**Comment by gkeishin** [comment]
[Automation State Manager] Move test cases for poweron's to new interface keywords
    [Automation State Manager] Power and Power off interface changes
    [Automation] BMC driver version info
    [Documentation] Manual FFDC collection
    [Automation] Power Restore policy State Check
    [Automation] Remove duplicate variables
    [Automation]Update IPMI client lib with new URI
    [New URI changes] Logic for Get VPD Inventory List

	
    [Barreleye v1.99.0-361-g8ce17d1] BMC state behaviour
    [Barreley v1.99.0-361-g8ce17d1] State Manager Core dumped
    [Barreley v1.99.0-360-g96d8e17] Unwanted characters in the BIOS Custom fields
    [Barreleye v1.99.0-360-g96d8e17 ] Power Restore policy messing BMC state ?

**Comment by gkeishin** [comment]
[Power] Set the boot flags with string 
 [State Manager] Defining global state variables 
 [Automation] Code fixes for extended

 [ Barreleye v1.99.0-392-g8e04907 ] DBusException: org.freedesktop.DBus.Error
 [ witherspoon v1.99.0-394-g9dcf2cb] Error log events are not cleared or delelte

**Comment by gkeishin** [comment]
Task completed for Jan,,, Closing
