### ISSUE TITLE
Jan Support: Auto Test, Log evaluation and opening issues - Barreleye

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#258]

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/220 - Run loop test and evaluate the test result, open issues and update it in 220 issue

**Comment by rahulmah** [comment]
4th Jan - Barreleye CT results with build #423

- [ ]  Code update : Good
- [ ]  CT : 166 passed, 0 failure - All Good
- [ ] Loop test - 5 iteration - 790 passed, 40 failure - Failure due to BMC stuck at BASE_APPS and BMC_STARTING. And some are due to present property and fault missing for membuf0.

**Comment by rahulmah** [comment]
This task is complete so can be closed.
