### ISSUE TITLE
[Automation] Suite teardown is failing in test_bios_update.robot

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#265]
Issue:
Suite teardown is failing in test_bios_update.robot due to 'cat: can't open '/tmp/obmc-console.log': No such file or directory' should be empty' .

Log info:
Host BIOS Update And Boot :: This test updates the PNOR image on t... | PASS |
Test Bios Update :: This testsuite updates the PNOR image on the h... | FAIL |
Suite teardown failed:
'cat: can't open '/tmp/obmc-console.log': No such file or directory' should be empty.

1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed

**Comment by gkeishin** [comment]
Closing this.. since there is already a tracker for this ..https://github.com/openbmc/openbmc-test-automation/issues/285
