### ISSUE TITLE
Loop test report generation: Need to cleanup if directory logsdir already exist.

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#266]
This is related to loop test.

Loop test report generation: Need to cleanup if directory logsdir already exist.

@SrideviRamesh, As discussed, If previous residual output.xml  there then chances are there that report can get generate using the same.

Basically need to add "rm *" or its equivalent if logsdir already exist.

**Comment by gkeishin** [comment]
@SrideviRamesh Use Library  Operating System  File Exist keywords to check for the directories..
