### ISSUE TITLE
Integration of MFG tool kit in our automation - We can have few TCs in extended and call it. 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#280]

**Comment by gkeishin** [comment]
Need discussion with MFG team ( Rajesh ) on the tooling.. We may need to write a new test for this.. For now parking with 3 points estimation, it may increase.

**Comment by gkeishin** [comment]
Rajesh and I were trying setup on the VM  and we land into some hiccups there for now, During the process we also brainstorm really good ideas like on packaging the MFG package dependencies .. 

Right now we are block hereto proceed further.

george@basab-KVM:~$ spstate
ERROR: (eth_transfer::initialize): Unable to Connect to Service Processor on : xx.xx.xx.xx
ERROR: (Controller::transfer_open): Failure occurred while trying to open the transfer protocol: error code 37749072 (TRANSFER_DEVICE_DRIVER_INIT_FAIL)
***ERROR: cmtGetSPState : ecmdQuerySP failed. RC = 0x02400150
george@basab-KVM:~$


We will work on it to resolves those and continue further on it.. Thanks

**Comment by gkeishin** [comment]
No further work needed here
