### ISSUE TITLE
[Tagging ] Tags test suite change phase 1

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#287]
Initial tagging changes for few of the test suite as a phase 1. 

Main place holder - https://github.com/openbmc/openbmc-test-automation/issues/126

**Comment by SrideviRamesh** [comment]
@gkeishin 
In tests/test_association.robot test suite following TC do not have tags
Create error log on two FRU
Create multiple error logs
Association with invalid FRU
Assocition with no FRU error event

In test_bootpolicy.robot test suite following TC do not have tags
Set Onetime boot policy using REST
Set Permanent boot policy using REST
Set Onetime boot policy using IPMITOOL
Set Permanent boot policy using IPMITOOL
Boot order with permanent boot policy
Persist ONETIME Boot Policy After Reset
Persist PERMANENT Boot Policy After Reset

I will add tags tags for the above mentioned two test suites
