### ISSUE TITLE
[Loop Test] BMC hangs in iteration, stop the test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#292]
If BMC hangs in iteration, we need to stop the test because it is going to fail all in any case and also system resource.

Scenario 

1. Iteration in completed
2. BMC was hang or not in BMC Ready state
3. Next iteration shouldn't continue since it is always going to add delta test failure..

**Comment by sivassrr** [comment]
Even if loop test fails, as you know it fails all remaining iteration in quick time..
And just go thru the report, we can get to know the status of the test.

**Comment by sivassrr** [comment]
Try to recreate this scenario and update the loop test result in this.

**Comment by gkeishin** [comment]
Are you saying if this scenario happens also  we should still continue the iteration .. not sure whats the motivation behind it if the BMC is not responding post nth iteration, n+1 iteration shouldnt continue. Thats my thought,

**Comment by vishwabmc** [comment]
Without any data here, we can not do anything. Next time this happens, leave the BMC in that state with the minicom attached and then have Dev look into it.

Since I was told that this system was AC cycled, this issue can be closed

**Comment by gkeishin** [comment]
Closing the ticket
