### ISSUE TITLE
Tag:20160613175742: OLD_GATEWAY not set - Persistance check for IP address TC fails

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#3]
Ran with Level 20160613175742 build on Barreleye and found Persistance check for IP address TC fails for the following reason.  
Documentation: 	

Sets variable based on the given condition.
Start / End / Elapsed: 	20160614 02:15:31.894 / 20160614 02:15:31.896 / 00:00:00.002
02:15:31.896 	FAIL 	Variable '${OLD_GATEWAY}' not found. Did you mean:
    ${gateway}

**Comment by gkeishin** [comment]
This and https://github.com/openbmc/openbmc-test-automation/issues/11 are same.. So we can close either one of them

**Comment by gkeishin** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/16

Duplicate.. closing
