### ISSUE TITLE
[BMC code update] handle old BMC check vs New Keyword

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#306]
This is needed because one would end up where the driver doesnt have the new interface and this would likely fail. So we need to consider both cases in case of code update.

**Comment by gkeishin** [comment]
The logical check would to do a compatibility check and then decide the interfaces to use...

**Comment by sivassrr** [comment]
Do we still need this . Or we can re-utilize what Michael Walsh is implemented in python.

**Comment by gkeishin** [comment]
Already implemented.. code in review @sivassrr

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/2130/
