### ISSUE TITLE
[MRW] Build FRU data for automation parsing Machine XML

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#309]
https://raw.githubusercontent.com/open-power/witherspoon-xml/master/witherspoon.xml

**Comment by gkeishin** [comment]
Probably we need to see 
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Decorator/Asset.interface.yaml
https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Inventory

**Comment by gkeishin** [comment]
Since the YAML seems to serve the purpose for us .. looks like we may not need this..  However if we need to pull data from XML than we need to go through MRW

**Comment by sivassrr** [comment]
@gkeishin can we leverage openbmc leverage code and estimate to 2.5.

**Comment by gkeishin** [comment]
Not going to support. We dont have a use case to support this at the moment
