### ISSUE TITLE
suite setup failed in the new repository - Around 75 TCs failing because of it. IPMItool need to fix it. 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#31]
FAIL (critical)
Message: 	Parent suite setup failed:
The ipmitool program could not be found in the tools directory. It is not part of the automation code by default. You must manually copy or link the correct openbmc version of the tool in to the tools directory in order to run this test suite.

**Comment by gkeishin** [comment]
In new repo there is no ipmi binary yet uploaded in tools/  so it is expected to fail..

One thing we can for work around before running the test is to copy the ipmi binary from old repo and copy to tools/ until fixed...

**Comment by sivassrr** [comment]
@gkeishin yup, George, Intention of this issue is to copy the ipmi binary and fix this issue.

**Comment by sivassrr** [comment]
With IPMI tool, observing following error. Need to fix it. 
 	FAIL (critical)
Message: 	'/tmp/ipmitool: /usr/lib/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /tmp/ipmitool)' should be empty.

**Comment by williamspatrick** [comment]
This tells me that the version of ipmitool you have compiled is no longer compatible with the flash images you are using.  We upgraded Yocto from 2.0.1 to 2.1 and I know openssl updated.  You probably need to use the SDK that goes along with the code that is running on the BMC.

**Comment by sivassrr** [comment]
Used the latest IPMITool and overcome the failure related to IPMItool. Now failure reduced to 52 with the latest level as follows:
root@barreleye:~# cat /etc/version
20160707143158
root@barreleye:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="0.1.0 (krogoth)"
VERSION_ID="v1.0-67-g2ad67f6-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 0.1.0 (krogoth)"
BUILD_ID="v1.0"
