### ISSUE TITLE
[Code Update] Add boot count check to track update process

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#311]
This code check will help track reboots during code update.. There were phantom reset seen during code update but we didn't have checks to catch such scenario. Now with this check it will catch such bugs.

Reference : https://github.com/openbmc/openbmc-test-automation/issues/294

**Comment by sivassrr** [comment]
@gkeishin Can we not assign this to Gunnar Mills. Who will be the codeupdate dev and test.

**Comment by gkeishin** [comment]
@sivassrr Gunnar is now doing development.. and this logic is a sequel of the boot logic i added recently.. https://github.com/openbmc/openbmc-test-automation/issues/294

This is not just for code update.. this are for general reboot tests as well.

The code is ready and I havent pushed it because of this bug https://github.com/openbmc/openbmc/issues/1077

**Comment by gkeishin** [comment]
Code pushed for review https://gerrit.openbmc-project.xyz/2325
