### ISSUE TITLE
[Time Test] Fix Float to integer for comparision

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#315]
BuiltIn . Should Be True ${bmc_diff_old_new} <= ${ALLOWED_TIME_DIFF}
Documentation: 	

Fails if the given condition is not true.
Start / End / Elapsed: 	20170202 00:55:22.549 / 20170202 00:55:22.553 / 00:00:00.004
00:55:22.553 	FAIL 	'7.0 <= 3' should be true.

So this is a float and int comparison which would not work well.. Need the conversion

**Comment by gkeishin** [comment]
@SrideviRamesh  Can u take a look at it..

**Comment by SrideviRamesh** [comment]
added changes in TC Get_System_Time & Set_Valid_System_Time

**Comment by rahulmah** [comment]
This fix is not required as "Should Be True" Keyword does not require both to be integer value. We should be more worrying - "why we are getting 7 second here". We kept 3 secs reference value, based on the time its taking for ROBOT command to execute. See if that need to be changed.

**Comment by sivassrr** [comment]
@gkeishin We had a discussion on this. Do we really need to be considered as a bug. 
As long as it is works then it is not a bug. But comparing with same data type is valid. But float and integer can be compare in the real world.

**Comment by SrideviRamesh** [comment]
I have not implemented the changed due to https://github.com/openbmc/openbmc-test-automation/issues/334

**Comment by gkeishin** [comment]
Closing this as 
https://github.com/openbmc/openbmc-test-automation/issues/334

code is now merged
