### ISSUE TITLE
[BMC reboot] Test automation to replace reboot command

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#318]
Place holder for this migration

**Comment by gkeishin** [comment]
tests/test_association.robot
tests/test_eventlog.robot
tests/test_warmreset.robot

**Comment by rahulmah** [comment]
We are currently keeping this on hold as new BMC reboot interface is causing some problem - https://github.com/openbmc/openbmc/issues/1070

**Comment by SrideviRamesh** [comment]
hi george,
As per our discussion
tests/test_bootpolicy.robot, tests/test_warmreset.robot has a keyword 'Trigger Warm Reset' .. i am changing 'Trigger Warm Reset' to 'Initiate BMC Reboot'

**Comment by gkeishin** [comment]
@SrideviRamesh  That's correct..

**Comment by rahulmah** [comment]
@gkeishin : "Trigger Warm Reset" and "BMC reboot" are two different thing. I believe, we dont need to change warm reset with BMC reboot.

**Comment by gkeishin** [comment]
well.. warm reset as a different meaning.. but looks like the implementation uses reboot internally so its basically reboot only for now.. yeah @SrideviRamesh leave this file for now and do for others..

**Comment by SrideviRamesh** [comment]
okay will update only test_association.robot & test_eventlog.robot as of now
