### ISSUE TITLE
Enabling External IPMI - Remove from Skip list

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#321]

**Comment by sivassrr** [comment]
@rahulmah As discussed, could you enable External IPMI which is already enabled in the driver.

**Comment by rahulmah** [comment]
External/Network IPMI is now working - https://github.com/openbmc/openbmc/issues/1110. We will have to keep this on hold till it is resolved.

**Comment by sivassrr** [comment]
@rahulmah Shall we close this issue.  You are working on external network ipmi and I believe we have another story for the same.

**Comment by rahulmah** [comment]
@sivassrr : Keep this on hold. Once external/network IPMI is enabled, I will test and remove test cases from skip list. Then this story can be closed.
