### ISSUE TITLE
Quiesce mode and Stop on Error Automated Test

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#322]
Story openbmc/openbmc#1033 and openbmc/openbmc#942 deal with a new quiesce mode for error paths and for controlling the automatic reboots of the system during these fails.  This story will track writing automated tests for this function.

Some thoughts:
- Disable automatic reboots, force a systemd service to fail during IPL, verify quiesce mode is entered and appropriate error is logged
- Disable automatic reboots, force a host watchdog error, verify quiesce mode is entered
- Enable automatic reboots, force a host watchdog error, verify quiesce mode is entered, error is logged, and system automatically reboots to OS

I believe Sridevi has a separate story for host checkstop testing, which would also use this function.

**Comment by sivassrr** [comment]
@rahulmah  As per discussion in today's call, Assigned to RAhul.

**Comment by gkeishin** [comment]
1 story point for analysis.. based on that we will decide on the implementation details estimation.. Thanks

**Comment by rahulmah** [comment]
@geissonator : There are two ways to handle quiesce mode in our automation. I prefer the second option. What your say on these?
1. Create test cases in extended to get the system in quiesce mode(using three scenarios which you have mentioned) and later recover it. 
2. Manually check if the system is going into Quiesce mode using your scenarios. Add a check in automation to check of "quiesce mode" at the end of each test case of the suite (where we expect system to land up in this state). If system has landed up in Quiesce mode, then STOP the entire test automation flow.

**Comment by rahulmah** [comment]
Here is the plan for testing this.
- [ ] Add a keyword to check "quiesce mode".
- [ ] Check quiesce state at the end of all the test case where host is powered ON.
- [ ] STOP the entire test automation flow, if system has landed up in Quiesce mode.

**Comment by gkeishin** [comment]
- [ ] Ensure the Test logs are generated when stopped.

**Comment by rahulmah** [comment]
Here is the update on this story: 
1. Manual testing completed. Found one problem - Auto reboot never stops - #1181
2. All code for automation is ready and up for review.

- [ ] Enable test cases for testing Quiesce state - https://gerrit.openbmc-project.xyz/#/c/2684/
- [ ] Added keyword to check host reboot. - https://gerrit.openbmc-project.xyz/#/c/2424/
- [ ] Fails TC and collect FFDC if host reaches quiesced state at the end test case run. - https://gerrit.openbmc-project.xyz/#/c/2636/
- [ ] Added a keyword to check "quiesced state". - https://gerrit.openbmc-project.xyz/#/c/2534/
