### ISSUE TITLE
IPMI RMCP Encryption related TC automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#329]
https://github.com/openbmc/openbmc/issues/870  

Based on discussion in yesterday's call with Tom/Andrew/rest of development, Decided to automate scenarios related to IPMI .

**Comment by sivassrr** [comment]
@rahulmah  Any update here?

**Comment by rahulmah** [comment]
@sivassrr : Now we have support sending encrypted ipmi command. This is how most customer will be using. So we should also be running all out test cases with RMCP encryption. Currently we send unencrypted IPMI command using "-C 1".  For encrypted IPMI command we should be using "-C 3" option.
I have checked in the code using https://gerrit.openbmc-project.xyz/#/c/2896/
