### ISSUE TITLE
[Automation] Identify the right BMC System type

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#332]
Based on the device tree population , System type will be determined

**Comment by gkeishin** [comment]
This info will be pretty helpful for metrics.. so when providing.. please provide a utility function for this so that code can call into it to fetch the platform / System type. Thanks

**Comment by gkeishin** [comment]
i think cat /sys/firmware/devicetree/base/model

this should do the trick for it..
