### ISSUE TITLE
Palmetto: Feb Support: Do loop test, Analyze the results and open issues if there is no issue open already. 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#333]

**Comment by SrideviRamesh** [comment]
10th Jan - Palmetto "v1.99.1-100"
BMC codeupdate : good
Still observing HOST_BOOTED issues on latest palmetto February  builds
https://github.com/openbmc/openbmc/issues/861

**Comment by SrideviRamesh** [comment]
feb3 -  Palmetto CT result with version "v1.99.1-95"
BMC codeupdate : good
170 critical tests, 156 passed, 14 failed
13 TC Failed due to openbmc/openbmc#861
1 TC Failed due to https://github.com/openbmc/openbmc/issues/1031

**Comment by SrideviRamesh** [comment]
feb6 - Palmetto build with version "v1.99.1-96"
BMC codeupdate : good
Still observing HOST_BOOTED issues on latest palmetto February builds
openbmc/openbmc#861
170 critical tests, 157 passed, 13 failed
12 TC Failed due to openbmc/openbmc#861
1 TC Failed due to openbmc/openbmc#1031

**Comment by SrideviRamesh** [comment]
feb8 -  Palmetto build with version "v1.99.1-100"
BMC codeupdate : good
System went to unpingable state after running basic poweron test
https://github.com/openbmc/openbmc/issues/1064

**Comment by swe12345** [comment]
Feb 13 - Palmetto Build with version "v1.99.2-24"
BMC Code Update : Good
170 critical Tests, 161 Passed, 9 Failed
8 Failed due to openbmc/openbmc#1072 and 1 failed due to known issue

**Comment by swe12345** [comment]
Feb 14 - Palmetto Build with version "v1.99.2-32"
BMC Code Update : Good
170 critical Tests, 159 Passed, 11 Failed
10 Failed due to openbmc/openbmc#1072 and 1 failed due to known issue

**Comment by swe12345** [comment]
Feb 15 - Palmetto Build with version "v1.99.2-46"
BMC Code Update : Good
170 critical Tests, 163 Passed, 7 Failed
6 Failed due to openbmc/openbmc#1072 and 1 failed due to known issue

**Comment by swe12345** [comment]
Feb 16 - Palmetto Build with version "v1.99.2-60""
BMC Code Update : Good
170 critical Tests, 161 Passed, 9 Failed
8 Failed due to openbmc/openbmc#1072 and 1 failed due to known issue

**Comment by swe12345** [comment]
Feb 17 - Palmetto Build with version "v1.99.2-66""
BMC Code Update : Good
170 critical Tests, 161 Passed, 9 Failed
8 Failed due to openbmc/openbmc#1072 and 1 failed due to known issue

**Comment by swe12345** [comment]
Feb 17 - Palmetto Build with version "v1.99.2-142""
BMC Code Update : Good
197 critical Tests, 183 Passed, 8 Failed
8 Failed due to openbmc/openbmc#1072

**Comment by geissonator** [comment]
#1072 is closed and fixed.  Must be new issue causing those failures.
