### ISSUE TITLE
[Automation] REST delay need to be handled while comparing time difference

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#334]
GET BMC/HOST Time is done before and after setting BMC/HOST time. This is for calculating whether time has changed or not. At present, 3 sec is kept as allowed time difference between these time. This 3 seconds is not enough as sometime it is observed that time diff is more because for REST slow responses. So it need to be better handled.

```
BuiltIn . Should Be True ${bmc_diff_old_new} <= ${ALLOWED_TIME_DIFF}
Documentation:

Fails if the given condition is not true.
Start / End / Elapsed: 20170202 00:55:22.549 / 20170202 00:55:22.553 / 00:00:00.004
00:55:22.553 FAIL '7.0 <= 3' should be true.

So this is a float and int comparison which would not work well.. Need the conversion
```

**Comment by rahulmah** [comment]
@SrideviRamesh : As discussed, try to count time between two get time operation and add 3 secs allowed time buffer before comparing time difference.

**Comment by gkeishin** [comment]
This fix needs to go in.. blocking CT run for Witherspoon.. Will bump up the estimate depending on the code and complexity.. @SrideviRamesh
