### ISSUE TITLE
[Automation] - HostIPMI Softpower off

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#342]
https://github.com/openbmc/openbmc/issues/930

**Comment by rahulmah** [comment]
@sivassrr : I had a discussion on this with development @vishwabmc . At present there is no plan to provide interfaces (neither ipmi or REST) for soft power off. Dev plan is to enable code to soft power off for internal usage. So this is not a testable content and should be closed.

**Comment by sivassrr** [comment]
Thank you for the update @rahulmah . Will close it accordingly.
