### ISSUE TITLE
[State manager] Add support to initiate HOST reboot using new xyx interface

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#350]
We need to have keyword to initiate HOST's reboot using new xyx interface.

**Comment by gkeishin** [comment]
what do we meant by host reboot here ?  u mean Host OS reboot ???

**Comment by rahulmah** [comment]
Yes with Host I mean Host OS.

**Comment by sivassrr** [comment]
@rahulmah  Code is in review, right.
