### ISSUE TITLE
ConnectionError seen while enumerating sensor url in automation

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#351]
Suite setup for sensor test is failing as REST connection is timeout while enumerating sensor URL. It is seen that enumeration is now taking close to 2 mins to return all the data. Seem like time out for enumeration need to be increase.

```
02:04:54 ==============================================================================
02:04:54 Tests.Test Sensors :: This example demonstrates executing commands on a rem...
02:04:54 ==============================================================================
02:04:58 URI:https://xx.xx.xx.xx/org/openbmc/enumerate, method:Get, args:{}
02:07:54 Verify connection                                                     | FAIL |
02:07:54 Parent suite setup failed:
02:07:54 ConnectionError: HTTPSConnectionPool(host='9.3.23.32', port=443): Max retries exceeded with url: /org/openbmc/enumerate (Caused by ReadTimeoutError("HTTPSConnectionPool(host='9.3.23.32', port=443): Read timed out. (read timeout=30.0)",))
```

**Comment by sivassrr** [comment]
Could you pls run the same in curl and see the difference.

**Comment by rahulmah** [comment]
Already checked, It takes close to 2 mins to enumerate.

**Comment by rahulmah** [comment]
In Automation, it is actually taking close to 60 seconds for REST response for enumeration. So it seem like we should be increasing REST time out to 120 secs so that we dont see this problem in future.

```
04:28:55 URI:https://xx.xx.xx.xx/org/openbmc/enumerate, method:Get, args:{}
04:29:48 Response code:200, Content:{
```

**Comment by gkeishin** [comment]
Can't we just enumerate the sensor pah and be done with it ? any other use case why we would need to do the enitre base path from /org/openbmc/

**Comment by rahulmah** [comment]
Sensor test file needs url from both sensor and inventory URL paths. That is what I am enumerating from base.

**Comment by gkeishin** [comment]
ok.. then that does make sense.. in one way

**Comment by rahulmah** [comment]
Seem like change is not needed. I run the tests with latest driver (v1.99.2-46-g04f01f7/20170215035342) today and REST response seem to have improved. So closing this. I will reopen if this issue is seem again.
00:18:54 URI:https://9.3.23.30/org/openbmc/enumerate, method:Get, args:{}
00:19:13 Response code:200, Content:{
