### ISSUE TITLE
[Kernel Stability] Test BMC kernel stability test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#352]
- [x]   Kernel panic test (In plan using https://github.com/openbmc/openbmc-test-automation/issues/348)
- [x]   Kernel boot test and verify using boot time logic

create a test file under tests
-[x]   tests/test_BMC_kernel_stability.robot    and add the two above use case

**Comment by swe12345** [comment]
Code under Review
https://gerrit.openbmc-project.xyz/#/c/2447
