### ISSUE TITLE
[FFDC] Collect /proc from system

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#353]
Kernel issues and other application failures , /proc info would be needed..

**Comment by sivassrr** [comment]
Also can we collect as a general TC and also part of FFDC which can capture at the time of failure. 
Or things which are not changing in FFDC, Can be collected only at the beggining of test execution. Then we can remove it from FFDC. This can help us to minimize redundant data.

**Comment by rahulmah** [comment]
There are so many files I see in /proc folder. Which ones are required to be captured.

**Comment by gkeishin** [comment]
Done pieces of getting the pid active as part of the FFDC.. closing.. if more neded we will open another one to address this
