### ISSUE TITLE
[Defect screen data] Tool to get pre-req info from the system

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#354]
The following basic info are needed while opening defect

- [ ]  System Type /Model
- [ ] cat /etc/version
- [ ] cat /etc/os-release
- [ ] BMC state
- [ ] BMC uptime
- [ ] System services info like systemctl status xxxxxxx | cat ( In case of service failed to start )

we would need more like a stand alone tool probably in python / robot which is simpler and easy to use..

**Comment by sivassrr** [comment]
Basically we need to collect the above data and update that in the issue.

**Comment by rahulmah** [comment]
We are capturing most of these while collecting FFDC in *_BMC_general.txt file. We can also initiate FFDC manually.  So I dont think there is a need to have a stand alone tool here.

**Comment by gkeishin** [comment]
We dont want to manually go and check those data and update those info.. just write a script to pull those data into a text and just paste in to the defect...

**Comment by gkeishin** [comment]
FFDC have those data. Closing. If there are request from community we will re-consider
