### ISSUE TITLE
[Cleanup] Remove dependencies from old interface code lib/boot poweron and off

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#361]
grep -r boot_resource_master.robot *
extended/standby_bmc.robot:Resource          ../lib/boot/boot_resource_master.robot
extended/test_power_restore.robot:Resource        ../lib/boot/boot_resource_master.robot
extended/code_update/update_bmc.robot:Resource          ../../lib/boot/boot_resource_master.robot
tests/test_occ_powercap.robot:Resource                ../lib/boot/boot_resource_master.robot

**Comment by swe12345** [comment]
Code Under Review
https://gerrit.openbmc-project.xyz/#/c/3495/
