### ISSUE TITLE
[SCP] IPMI tool Copying improvement

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#367]
https://github.com/openbmc/openbmc-test-automation/blob/master/lib/ipmi_client.robot#L140
```
Copy ipmitool
    OperatingSystem.File Should Exist   tools/ipmitool      msg=The ipmitool program could not be found in the tools directory. It is not part of the automation code by default. You must manually copy or link the correct openbmc version of the tool in to the tools directory in order to run this test suite.

    Import Library      SCPLibrary      WITH NAME       scp
    scp.Open connection     ${OPENBMC_HOST}     username=${OPENBMC_USERNAME}      password=${OPENBMC_PASSWORD}
    scp.Put File    tools/ipmitool   /tmp
    SSHLibrary.Open Connection     ${OPENBMC_HOST}
    Login   ${OPENBMC_USERNAME}    ${OPENBMC_PASSWORD}
    Execute Command     chmod +x /tmp/ipmitool
```

Currently the code doesnt check if the ipmitool is already exist or copied.. so this is an over head for copying each time.. Add check to avoid copying if already file exist in BMC /tmp

**Comment by gkeishin** [comment]
Some more robot coding learning needed for here.. so bumping up estimation.

**Comment by sivassrr** [comment]
George and Sweetha, Could you pls hold off this changes. We can decide based on today's discussion. We can even move all internal IPMI tool related TCs to External IPMI way. Then this may not needed.

**Comment by gkeishin** [comment]
@sivassrr That thing would probably take more time before we even change the test and the all the utility in it. So let @swe12345 give a try and fix this..

**Comment by gkeishin** [comment]
@sivassrr Yeah make sense..
