### ISSUE TITLE
20160707143158:Barreleye:Build141: All Inventory Test Cases fails due to suite setup fail

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#37]
root@barreleye:~# cat /etc/version
20160707143158
root@barreleye:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="0.1.0 (krogoth)"
VERSION_ID="v1.0-67-g2ad67f6-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 0.1.0 (krogoth)"
BUILD_ID="v1.0"
root@barreleye:~#
root@barreleye:~#
root@barreleye:~# obmcutil state
 = HOST_BOOTED
root@barreleye:~# obmcutil host
debug_mode = 0
flash_side = primary
root@barreleye:~# obmcutil bootprogress
units =
value = FW Progress, Starting OS
error = 0

=======================================
But Suite Setup for Inventory Test suite fails because of  following statement 
 "Wait Until Keyword Succeeds   3 min         10 sec    Is Power On" 

 	Suite setup failed:
Keyword 'Is Power On' failed after retrying for 3 minutes. The last error was: FW Progress, Baseboard Init != FW Progress, Starting OS
00:03:02.087 SETUP Setup The Suite
Start / End / Elapsed: 	20160709 20:34:19.627 / 20160709 20:37:21.714 / 00:03:02.087
00:03:02.087 KEYWORD utils . Power On Host
Start / End / Elapsed: 	20160709 20:34:19.627 / 20160709 20:37:21.714 / 00:03:02.087
00:00:00.000 KEYWORD @{arglist} = BuiltIn . Create List
00:00:00.000 KEYWORD ${args} = BuiltIn . Create Dictionary data=@{arglist}
00:00:02.064 KEYWORD ${resp} = rest_client . Call Method /org/openbmc/control/chassis0/, powerOn, data=${args}
Start / End / Elapsed: 	20160709 20:34:19.630 / 20160709 20:34:21.694 / 00:00:02.064
00:00:00.001 KEYWORD ${base_uri} = BuiltIn . Catenate SEPARATOR=, ${DBUS_PREFIX}, ${uri}
00:00:02.063 KEYWORD ${resp} = rest_client . OpenBMC Post Request ${base_uri}/action/${method}, &{kwargs}
20:34:21.694 	INFO 	${resp} = <Response [200]> 	
00:00:00.000 KEYWORD BuiltIn . Should Be Equal As Strings ${resp.status_code}, ${HTTP_OK}
Documentation: 	

Fails if objects are unequal after converting them to strings.
Start / End / Elapsed: 	20160709 20:34:21.695 / 20160709 20:34:21.695 / 00:00:00.000
20:34:21.695 	INFO 	Argument types are:
<type 'int'>
<type 'unicode'> 	
00:03:00.019 KEYWORD BuiltIn . Wait Until Keyword Succeeds 3 min, 10 sec, Is Power On
Documentation: 	

Runs the specified keyword and retries if it fails.
Start / End / Elapsed: 	20160709 20:34:21.695 / 20160709 20:37:21.714 / 00:03:00.019
00:00:01.708 KEYWORD utils . Is Power On
Start / End / Elapsed: 	20160709 20:34:21.696 / 20160709 20:34:23.404 / 00:00:01.708

**Comment by williamspatrick** [comment]
I think you need the host console output to determine why the host os is not starting.  Maybe you need to reset the PNOR on your system?
