### ISSUE TITLE
[AES] AES variant retries

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#375]
Take a look at the code update and see if you could do the same for AES extended/standby_bmc.robot

**Comment by gkeishin** [comment]
Use this code as an opportunity to understand the old interface and new one.. and also to help walk through the code..

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/2803/

**Comment by sivassrr** [comment]
As this lab tool, not to be part of backlog Sep 2017. So not moving to it.
