### ISSUE TITLE
[PNOR] Software version Management

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#376]
Support PNOR check in the test FW version
Follow up task from
https://gerrit.openbmc-project.xyz/#/c/2355/

**Comment by sivassrr** [comment]
could you pls add estimate. Thank you.

**Comment by gkeishin** [comment]
The changes has not yet came.. Gunnar will let me know once its up from developement

**Comment by gkeishin** [comment]
This is valid with the new PNOR, will start off coding a bit

**Comment by gkeishin** [comment]
This test code is already in place
