### ISSUE TITLE
Mar 2017: Palmetto Driver Test with loop/stability test when needed at least once in a week

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#377]

**Comment by swe12345** [comment]
```
                                         Palmetto CT
```



`Date`     |      `Build`          | `CU`  | `CT-PASS` | `CT-FAIL` | `New Defects Logged`
--------- | ------------------- | ---- | ------- | ------- | -------------------------------------------------------
16th Mar  | v1.99.3-93-gf0a463a | OK  | 128    | 13     	 | 
17th Mar  | v1.99.3-106-gc6c2998 | OK | 130     | 16    	 |

**Comment by swe12345** [comment]
`Date`     |      `Build`          | `CU`  | `CT-PASS` | `CT-FAIL` | `New Defects Logged`
--------- | ------------------- | ---- | ------- | ------- | -------------------------------------------------------
21st Mar  | v1.99.3-118-g0032233 | OK  | 127   | 7   	 |
