### ISSUE TITLE
Mar 2017: Barreleye Driver Test with Loop / Stability Test once in a week

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#378]

**Comment by rahulmah** [comment]
```
                                    Barreleye CT
```



`Date`     |      `Build`          | `CU`  | `CT-PASS` | `CT-FAIL` | `New Defects Logged`
--------- | ------------------- | ---- | ------- | ------- | -------------------------------------------------------
1st Mar  | v1.99.1-65-g07df806 | OK  | 170     | 8     	 | openbmc/openbmc#1052, openbmc/openbmc#1031, #314, #313
2nd Mar  | v1.99.1-82-gbfd622e | OK | 170     | 8    	 |


**Current Blocking OpenBMC Issues**

`No.` | `Github#`                         | `Reason/Heading`                                             | `Current Status`
-----  |-------------------------  |---------------------------------------------- | ---------------
1	 |                                             |                                                                              |

**Comment by sivassrr** [comment]
If there is any update here today, you can put it in slack or update here as well. I am closing as of now.
