### ISSUE TITLE
20160707143158:Barreleye:Build141: Host is in booting state for more than 18 minutes

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#38]
root@barreleye:/etc# obmcutil state
 = HOST_BOOTING
root@barreleye:/etc# obmcutil bootprogress
units =
value = FW Progress, Baseboard Init
error = 0
root@barreleye:/etc# date
Sat Jul  9 18:12:29 UTC 2016
root@barreleye:/etc# date; obmcutil bootprogress; date
Sat Jul  9 18:12:46 UTC 2016
units =
value = FW Progress, Baseboard Init
error = 0
Sat Jul  9 18:12:48 UTC 2016
=============================
root@barreleye:/etc# obmcutil state; obmcutil bootprogress;date
 = HOST_BOOTING
units =
value = FW Progress, Baseboard Init
error = 0
Sat Jul  9 18:31:19 UTC 2016
root@barreleye:/etc#

**Comment by sivassrr** [comment]
[journaloutput.txt](https://github.com/openbmc/openbmc-test-automation/files/355686/journaloutput.txt)

**Comment by mdmillerii** [comment]
@bradbishop I notice the inventory upload didn't seem happy but it did go to the next state:

    Jul 09 17:54:36 barreleye system_manager.py[928]: Error: <stdin>:1.4305-4306 syntax error
    Jul 09 17:54:36 barreleye system_manager.py[928]: FATAL ERROR: Unable to parse input tree
    Jul 09 17:54:36 barreleye system_manager.py[928]: Partition 'BMC_INV' not found !
    Jul 09 17:54:36 barreleye system_manager.py[928]: Uploading inventory to PNOR in dtb format...

The `PNOR` was tuned before, so that does not explain the missing `BMC_INV` partition.  @sivassrr does `pflash` find other partitions or does the `PNOR` look corrupt?

    Jul 09 17:47:31 barreleye system_manager.py[928]: Running System State: BMC_READY
    Jul 09 17:47:31 barreleye system_manager.py[928]: Starting process: /usr/sbin/discover_system_state.py: restore
    Jul 09 17:47:34 barreleye system_manager.py[928]: Starting flasher: bios,,/org/openbmc/control/flash/bios,
    Jul 09 17:47:34 barreleye system_manager.py[928]: flasher: , BMC = 0, address = 0x0
    Jul 09 17:47:34 barreleye system_manager.py[928]: Setting up BIOS flash
    Jul 09 17:47:34 barreleye system_manager.py[928]: Flash tuned
    Jul 09 17:47:36 barreleye system_manager.py[928]: Starting flasher: bios,,/org/openbmc/control/flash/bios,
    Jul 09 17:47:36 barreleye system_manager.py[928]: flasher: , BMC = 0, address = 0x0
    Jul 09 17:47:36 barreleye system_manager.py[928]: Setting up BIOS flash
    Jul 09 17:47:36 barreleye system_manager.py[928]: Flash tuned

**Comment by bradbishop** [comment]
The PNOR shouldn't be touched if the BMC_INV partition can't be found.  To me that suggests the PNOR is corrupt before we even get started.

**Comment by williamspatrick** [comment]
Have you looked at the host console?  I see a change to the watchdog interval to... 20 minutes?  A change of the watchdog interval tells me that the host sent down some IPMI messages.  So we need to debug why the host firmware didn't get all the way to runtime.
