### ISSUE TITLE
Security Scan: Mar 2017

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#383]

**Comment by sivassrr** [comment]
Please run the automated tool and scan BMC and Petitboot Partition as well. If possible automate the analysis as well. 
And open issues if there is any accordingly.

**Comment by sivassrr** [comment]
Prashanth, I am closing it now. Hope we have done scanning for this month.

**Comment by prkatti1** [comment]
Yes, done.
