### ISSUE TITLE
Feature: To collect FFDC for OpenBMC systems 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#39]
Basically for each test case failure, Would like to collect relevant data like
Journalctl
PS
BMC version
OS Version - if it is related 
TOP output - if it is performance issue 
Hostboot state - output of obmcutil state, obmcutil bootprogress etc..

**Comment by sivassrr** [comment]
@gkeishin - George working on it already

**Comment by gkeishin** [comment]
Currently planned in 3 subsequent commits

1. Initial generic code library and supporting base supports basically a Robot Resource lib code

2. Default and custom log support - Default generic logs and User defined logs per test case on demand

3. Enable FFDC into the existing test cases - Plug into Teardown  ( 190 + test cases )

There could be limitation in some of the cases where we need to look into writing our own user library robot keywords to address those...

**Comment by gkeishin** [comment]
some of restructuring needed as pre work are addressed with https://github.com/openbmc/openbmc-test-automation/issues/41

**Comment by gkeishin** [comment]
Will use this ticket to drop the base infrastructure support code for open BMC FFDC.

A sample FFDC log is attached here..

The FFDC directory structure 

logs/testSuiteName/testcaseName/openbmc_ffdc_report.txt  

Example
$ tree logs
logs
└── TestSampleSuite
    └── Verifyconnection
        └── openbmc_ffdc_report.txt

2 directories, 1 file

[openbmc_ffdc_report.txt](https://github.com/openbmc/openbmc-test-automation/files/370801/openbmc_ffdc_report.txt)

**Comment by gkeishin** [comment]
Current FFDC performance collection is 6 seconds... 
 
==============================================================================
Test Sample
==============================================================================
Verify Connection                                                     F
FFDC Collection Started 2016-07-20 00:46:42,185863
FFDC Collection Completed 2016-07-20 00:46:48,010589
Verify Connection                                                     | FAIL |
testing != OOPS
------------------------------------------------------------------------------
Test Sample                                                           | FAIL |

**Comment by gkeishin** [comment]
Mailing list posted https://lists.ozlabs.org/pipermail/openbmc/2016-July/004272.html
