### ISSUE TITLE
[FFDC]  Collect REST data if SSH fails

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#393]
There could be use case where the SSH fails but REST alive as suggested by @sivassrr ... tracker to work on it.

**Comment by sivassrr** [comment]
If serial port connection available then we should also try to get data from there, ji. That add more value.

**Comment by gkeishin** [comment]
For that I have already code written and available on github.. Take a look https://github.com/openbmc/openbmc-test-automation/blob/master/lib/oem/ibm/serial_console_client.robot

**Comment by gkeishin** [comment]
This is also done in the FFDC
