### ISSUE TITLE
PreTag: [System - barreleye Build - 20160610155319 ] : Test non-SSL Connection to port 80 - Fails

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#4]
This test case is failing as ConnectTimeout error is not seen. ConnectionError is seen in place of it.

Expected error 'ConnectTimeout*' but got 'ConnectionError: HTTPConnectionPool(host='9.3.23.24', port=80): Max retries exceeded with url: //list (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 61] Connection refused',))'

**Comment by gkeishin** [comment]
This testcase is for test to check OpenBMC machine will not accepts the non-secure connection that is with http to port 80 and expect a connection error.. I think this one seems correct just that it should not fail the test case..

**Comment by gkeishin** [comment]
Expected error 'ConnectionError:' but got 'ConnectionError: HTTPConnectionPool(host='

So the code needs to be fixed like this ..

Run Keyword And Expect Error    ConnectionError*   Get Request    openbmc   /list

Now the test case is correct.. Will push this code as well.. Thanks
