### ISSUE TITLE
To test host state heartbeat and target work on reset reload

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#403]
Currently this is related to Andrew work, We need to automate the same and test it. 
Expect to come this in the second half of Mar.

**Comment by gkeishin** [comment]
Yeah.. I had a discussion on this a bit with Andrew. There are few infra-structure ready for it, hope it should be useful to automate it.. Will keep posted on this..

**Comment by sivassrr** [comment]
As discussed in today's scrum, Will be assigning this to Rahul.

**Comment by sivassrr** [comment]
Equivalent Development story is https://github.com/openbmc/openbmc/issues/1274

**Comment by rahulmah** [comment]
@sivassrr : Here is the progress on this story. There are two development story which need to be taken care for below RR design. 

- Handle a BMC reset while Chassis is powered on - openbmc/openbmc#1094 
: Status : Dev code is merged for this. Manual testing is also completed. Test automation is in progress.

- Handle a BMC reset while Host is running - openbmc/openbmc#1274
: Status : Dev code in progress. Current development plan is to get this completed in this sprint.

**Comment by sivassrr** [comment]
Do we want to handle it separately, Or do you want to drop the code together.

**Comment by rahulmah** [comment]
@sivassrr : Lets this story be only for "Handle a BMC reset while Chassis is powered on".
I have also pushed code for it - https://gerrit.openbmc-project.xyz/#/c/3214/. 

Code for other story will come little later.
