### ISSUE TITLE
Real Validation of Boot Flag

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#406]
Real validation of Boot Flag - Currently we are setting it. Need to validate it as well

We can split this story into 2

Test we can automation remotely will be handle by Rahul
Others would like Leonel @lgon  to automate. 

Rahul, Could you pls work with Leonel.

**Comment by rahulmah** [comment]
@sivassrr : As discussed, there are two ways to test this story:
1. Automate negative test like try to boot system to CDROM without any media:  I tested this and found that there is no error thrown at present in such case. So seems support for this error is not there. 
2. Manually running boot flag test cases like booting system to CDROM with media: For this we need support person to do the task.

At present, both of the above ways are not possible. So please put this story on hold.

**Comment by gkeishin** [comment]
@rahulmah any plans to do here ?

**Comment by sivassrr** [comment]
This is needed to verify from E2E perspective.
