### ISSUE TITLE
VPD Verification of DIMM & CORE

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#416]
This sprint development (squad1) works on to bring VPD for DIMM & CORE.
 Basically CPU CORE inventory creation and DIMM functional state. 

Please feel free to change the estimate.

**Comment by gkeishin** [comment]
@tomjoseph83 and @ratagupt are working on this... So need to discuss what functional test we can add from test point of view..

**Comment by gkeishin** [comment]
Coding in progress

**Comment by gkeishin** [comment]
Code under review
