### ISSUE TITLE
Feature: Generic Power on / Power off

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#42]
Will add details using new updated template

**Comment by gkeishin** [comment]
This can be contained in tests/test_power_restore.robot  however it would be good if we do separately ...

**Comment by gkeishin** [comment]
What are the list of test cases we are looking at here ? are we going to do as a separate test suite or extend the use case in one of the existing test ?

**Comment by gkeishin** [comment]
Will work on this.. to create a new suite to have only power on and off.. we can extend the generic use cases here ahead...

**Comment by gkeishin** [comment]
Code pushed for review..
