### ISSUE TITLE
March Support: Auto Test, log evaluation and opening issues - Palmetto

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#425]
```
                                    Palmetto CT
```

`Date`     |      `Build`          | `CU`  | `CT-PASS` | `CT-FAIL` | `New Defects Logged`
--------- | ------------------- | ---- | ------- | ------- | -------------------------------------------------------
1st Mar  | v1.99.1-65-g07df806 | OK  | 170     | 8     	 | openbmc/openbmc#1052, 

**Current Blocking OpenBMC Issues**

`No.` | `Github#`                         | `Reason/Heading`                                             | `Current Status`
-----  |-------------------------  |---------------------------------------------- | ---------------
1	 |                                             |                                                                              |

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/377 - It is already there. So closing it.
