### ISSUE TITLE
Network new interface (XYZ etc..)

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#429]
https://github.com/openbmc/openbmc/issues/1284

**Comment by sivassrr** [comment]
openbmc/openbmc#1293 - Based on discussion in today's interlock, Still it is in merge. So interface is not finalized. @prkatti1 Please work with Ratan.

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc/issues/1292 - Related.

**Comment by sivassrr** [comment]
- [ ] Have a discussion with @ratagupt - List applicable test cases with automation capability / manual

- [ ] Create stories with task for automation

**Comment by gkeishin** [comment]
Task already completed as per @prkatti1  closing
