### ISSUE TITLE
[Barreleye/Palmetto - build v1.0-89-g5bc571e-dirty ]  Test Firmware Version Regex failed

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#43]
Expectation regex for version v1.0-89-g5bc571e  but got  v1.0-89-g5bc571e-dirty

Test Firmware Version :: This testcase is for testing the fw version. | FAIL |
'"v1.0-89-g5bc571e-dirty"' does not match '^v\d+.\d+'

 Should Match Regexp     ${jsondata["data"]["version"]}      ^v\\d+\.\\d+

This could be fix in the test case.. but just wanted to understand if this  "-dirty" suffix in the version, is this to be going forward this format ?

**Comment by vishwabmc** [comment]
IMO, whatever that is in the /etc/os-release needs to be accepted.

example :: VERSION_ID="v1.0-89-g5bc571e-dirty"

Is there a requirement that the version needs to match a particular Regex pattern ?

**Comment by gkeishin** [comment]
I really doesn't see value add in this test case though.. but if we do to take whatever it is in the version also, but still doesn't serve any purpose from my personal view.. 

@williamspatrick @geissonator @causten  any thought on this one... ?

**Comment by williamspatrick** [comment]
The presence of 'dirty' tells me something is wrong with the CI build process. That means the process is modifying the repository rather than building exactly what is in it. I think there is some value in keeping it so we ensure the build process is done correctly.

**Comment by williamspatrick** [comment]
Please move as an issue in 'openbmc-build-tools' and assign to @geissonator.

**Comment by sivassrr** [comment]
Is this not related   to issue in openbmc repository https://github.com/openbmc/openbmc/issues/453?

**Comment by gkeishin** [comment]
Opened against build https://github.com/openbmc/openbmc-build-scripts/issues/10
