### ISSUE TITLE
[LED] Assert fault LED's when association is set and cleared

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#432]
https://github.com/openbmc/openbmc/issues/941

I doubt whether we have it, We can evaluate accordingly.

**Comment by sivassrr** [comment]
As per team discussion and interlock, Assigning it to Swetha.

**Comment by sivassrr** [comment]
@rahulmah Could you pls work with Swetha on this.

**Comment by rahulmah** [comment]
@sivassrr : I have already helped her on this story. She has also dropped the code for this.

**Comment by swe12345** [comment]
In Review
Waiting for the development code to be merged for the functionality to work
https://gerrit.openbmc-project.xyz/#/c/4389/
https://gerrit.openbmc-project.xyz/#/c/4668/

**Comment by swe12345** [comment]
Code in Review
https://gerrit.openbmc-project.xyz/#/c/4039/
