### ISSUE TITLE
[Inventory] Disable inventory test for Barreleye/ Palmetto

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#435]
These 2 systems are non MRW systems so the inventory wouldnt be populated.. so until Dev add the fix for it, please add to the skip list

1. Add tag in the tests/test_inventory.robot   file
`Force Tags   inventory`

2.  Add in skip list file
```
-rw-rw-r-- 1 rango rango 2066 Mar 17 00:12 test_lists/skip_test   <--- DONT change here
-rw-rw-r-- 1 rango rango 2153 Mar 17 00:12 test_lists/skip_test_barreleye
-rw-rw-r-- 1 rango rango 2103 Mar 17 00:12 test_lists/skip_test_palmetto
-rw-rw-r-- 1 rango rango 2119 Mar 17 00:12 test_lists/skip_test_witherspoon
```
add this line in the files

`-e inventory`

**Comment by swe12345** [comment]
Closing this as code is already pushed for it using https://github.com/openbmc/openbmc-test-automation/issues/441
