### ISSUE TITLE
Fan Control Automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#442]
All Fan Control Related Stories to be addressed in this automation.

https://github.com/openbmc/openbmc/issues/946  -  Parameter Override ability
https://github.com/openbmc/openbmc/issues/945  -  Fan Control LEDs
https://github.com/openbmc/openbmc/issues/944 - Monitoring function

https://github.com/openbmc/openbmc/issues/940  -  Control Functions
https://github.com/openbmc/openbmc/issues/935   -

**Comment by sivassrr** [comment]
Some of them, George started automating it. So assigning him as well.

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/9972
