### ISSUE TITLE
Power Supply LED Test Automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#445]
https://github.com/openbmc/openbmc/issues/922

**Comment by sivassrr** [comment]
@lgon Basically we should be able to switch on LED / switch off LED via REST. Also if host is powered on, we should be able to check power supply led state. Need to check whether we are going to have identify led here. If it is implemented then we should automate that as well.  Group Power on  LED as well.

**Comment by lgon** [comment]
I talked to Matt Spinler, and according to him "we still won't be looking into power supply support for another 2 months or so"  Do you want me to work on Task #516 instead?
----- Original message -----From: sivassrr <notifications@github.com>To: openbmc/openbmc-test-automation <openbmc-test-automation@noreply.github.com>Cc: Leonel Gonzalez/Austin/Contr/IBM@IBMUS, Mention <mention@noreply.github.com>Subject: Re: [openbmc/openbmc-test-automation] Power Supply LED Test Automation (#445)Date: Wed, Apr 26, 2017 11:13 AM 
@lgon Basically we should be able to switch on LED / switch off LED via REST. Also if host is powered on, we should be able to check power supply led state. Need to check whether we are going to have identify led here. If it is implemented then we should automate that as well. Group Power on LED as well.

**Comment by sivassrr** [comment]
I believe this is still needed, not implemented yet.  May be this will be get implemented in Redfish.

**Comment by gkeishin** [comment]
Closing older epics and stories which are no longer relevant
