### ISSUE TITLE
Automate GPU Inventory Collection

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#447]
https://github.com/openbmc/openbmc/issues/1044 - GPU Inventory Collection

**Comment by ssombar** [comment]
I see GPU inventory has already been implemented.     For example,
curl -c cjar -b cjar -k https://$BMC_IP/xyz/openbmc_project/inventory/enumerate  | grep -A3 gv
gives
xyz/openbmc_project/inventory/system/chassis/motherboard/gv100card0
xyz/openbmc_project/inventory/system/chassis/motherboard/gv100card1
xyz/openbmc_project/inventory/system/chassis/motherboard/gv100card2
xyz/openbmc_project/inventory/system/chassis/motherboard/gv100card3
