### ISSUE TITLE
[Automation] RAS testcase with autoreboot option disabling

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc-test-automation#449]

**Comment by SrideviRamesh** [comment]
currently we are concentrating RAS test with auto reboot option always enabled....
please close this issue

**Comment by sivassrr** [comment]
This is for automation. Is your current code changes considering it. Then can we dup to that.

**Comment by SrideviRamesh** [comment]
Currently we are having all the automation test scenarios with auto-reboot option enabled..
We will be not enabling this scenario for now.
We can close this issue.

**Comment by gkeishin** [comment]
Closing as requested by @SrideviRamesh  Task completed
