### ISSUE TITLE
AES standby test still having old org interface to check BMC state at one place.

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#453]
AES standby test having old org interface to check BMC state. This is due to "Reboot and Wait for BMC Online" keyword used here. Seem like we can remove this check as we have new interfaces in place.

```
    ${rest_status}=  Run Keyword And Return Status  Initialize OpenBMC
    Run Keyword If  '${rest_status}' == '${False}'
    ...  Reboot and Wait for BMC Online
```

**Comment by gkeishin** [comment]
openbmc/openbmc-test-automation#375
