### ISSUE TITLE
[logging-test]  logging-test elog exception

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#462]
```
Feb 22 06:07:37 witherspoon logging-test[952]: This is a simple test error.
Feb 22 06:07:37 witherspoon logging-test[952]: Error in mapper call
```
```
02:04:36.783     INFO     Executing command 'logging-test -c AutoTestSimple'.     
02:04:37.836     INFO     Command exited with return code 0.     
02:04:37.837     INFO     ${stdout} = elog exception caught: example.xyz.openbmc_project.Example.Elog.AutoTestSimple     
02:04:37.837     INFO     ${stderr}
```

**Comment by mtritz** [comment]
logging-test itself doesn't call the mapper - that happens here https://github.com/openbmc/phosphor-logging/blob/master/elog.cpp
In the last few days, the mapper dbus path was changed from /xyz/openbmc_project/ObjectMapper to /xyz/openbmc_project/object_mapper. Are you sure you're running this on an updated system? If not, that would break your dbus calls.

**Comment by gkeishin** [comment]
Its the latest code with the object mapper with the lower case
```
Executing: GET  /xyz/openbmc_project/

/xyz/openbmc_project/
[
    "/xyz/openbmc_project/sensors",
    "/xyz/openbmc_project/software",
    "/xyz/openbmc_project/object_mapper",
    "/xyz/openbmc_project/logging"
]
-bash-4.1$
```

```
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/649/
- [x] VERSION_ID : v1.99.3-128-ga0040f7
```

**Comment by mtritz** [comment]
I ran `logging-test -c AutoTestSimple` and watched it with dbus-monitor, resulting in 

signal time=1487751939.183829 sender=org.freedesktop.DBus -> destination=:1.173 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.173"
method call time=1487751939.189542 sender=:1.173 -> destination=xyz.openbmc_project.ObjectMapper serial=2 path=/xyz/openbmc_project/ObjectMapper; interface=xyz.openbmc_project.ObjectMapper; member=GetObject
   string "/xyz/openbmc_project/logging/internal/manager"
   array [
      string "xyz.openbmc_project.Logging.Internal.Manager"
   ]
error time=1487751939.209330 sender=:1.19 -> destination=:1.173 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=2
   string "Method "GetObject" with signature "sas" on interface "xyz.openbmc_project.ObjectMapper" doesn't exist
"

Note that `path=/xyz/openbmc_project/ObjectMapper`. You must not have the latest phosphor-logging.

**Comment by mtritz** [comment]
It's also worth noting that that `elog exception caught: example.xyz.openbmc_project.Example.Elog.AutoTestSimple` is, in fact, intended behavior - the point of logging-test is to create that exception and then commit it to the error log. Looks like everything is working as intended.

**Comment by gkeishin** [comment]
```
    "/xyz/openbmc_project/logging/entry/3": {
        "AdditionalData": [
            "STRING=FOO"
        ],
        "Id": 3,
        "Message": "example.xyz.openbmc_project.Example.Elog.AutoTestSimple",
        "Severity": "xyz.openbmc_project.Logging.Entry.Level.Error",
        "Timestamp": 1487744085901,
        "associations": []
    },
    "/xyz/openbmc_project/logging/entry/4": {
        "AdditionalData": [
            "STRING=FOO"
        ],
        "Id": 4,
        "Message": "example.xyz.openbmc_project.Example.Elog.AutoTestSimple",
        "Severity": "xyz.openbmc_project.Logging.Entry.Level.Error",
        "Timestamp": 1487744526155,
        "associations": []
    },
    "/xyz/openbmc_project/logging/internal/manager": {}
}
```

Closing issue..
