### ISSUE TITLE
[Automation] Download image/tarfile using wget on BMC

### ISSUE THREAD

**Issue by swe12345** [openbmc/openbmc-test-automation#467]
Opening this as a tracker requested by @sivassrr

**Comment by sivassrr** [comment]
@swe12345 @gkeishin I believe we may need to open a issue against openbmc / kernel for wget. 
Based on discussion with @geissonator , We may have to try with the latest Yocto 2.2 when upgraded and open issue accordingly.

**Comment by mdmillerii** [comment]
From the bmc command line,
- `wget` `HTTP` works.
- `wget` `HTTPS` works when no proxy is required.
- See openbmc/openbmc#135 for status of using a `HTTPS` proxy.

I don't know the status of going through REST.

**Comment by sivassrr** [comment]
Hi Swetha, Please try wget in openbmc and open issues accordingly.

**Comment by sivassrr** [comment]
@swe12345   

Here is the output without DNS and with DNS server setup. So wget works. 

(1 comment)
lib/utils.robot
Line 786:

-bash-4.1$ ssh root@xx.xx.xx.xx
root@xx.xx.xx.xx's password:
root@witherspoon:~# wget https://openpower.xyz/job/openbmc-build/655/distro=ubuntu,target=witherspoon/artifact/images/witherspoon/obmc-phosphor-debug-tarball-witherspoon.tar.xz
wget: bad address 'openpower.xyz'
root@witherspoon:~#


Looks like it doesnt understand the xyz on BMC
Sivas SRR
Mar 27 12:33 PM

Patch Set 3:

As mentioned in the slack, here is my try, 
root@barreleye:~# /usr/bin/wget  http://openpower.xyz/job/openbmc-build/655/distro=ubuntu,target=witherspoon/artifact/images/witherspoon/witherspoon-20170325031702.all.tar
Connecting to openpower.xyz (104.239.249.49:80)
Connecting to openpower.xyz (104.239.249.49:443)
wget: server returned error: HTTP/1.1 400 Bad Request

==========================================
I am fine if we have an issue for implementing with wget in later time. Please provide issue #, that helps.

**Comment by sivassrr** [comment]
Also check for @mdmillerii update.

**Comment by sivassrr** [comment]
@swe12345 - FYI  - This all associate with https://gerrit.openbmc-project.xyz/#/c/3255/

**Comment by mdmillerii** [comment]
It would appear from your testing that wget works with dns for http but not https , which is routed though an external openssl helper.  I'll just point it out, and let you decide if you want to raise a dev issue for that.

**Comment by swe12345** [comment]
@mdmillerii wget does not work for https even with proxy off
```
root@palmetto:~# wget --proxy off https://openpower.xyz
Connecting to openpower.xyz (104.239.249.49:443)
wget: server returned error: HTTP/1.1 400 Bad Request```
 
```

**Comment by swe12345** [comment]
Done..

**Comment by gkeishin** [comment]
Closing this one as the counterpart support is not going to be available
