### ISSUE TITLE
[Witherspoon] Poweron LED should blink at  BMC READY state

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#482]
https://github.com/openbmc/openbmc/issues/1399 - This needed  manual verification. 
And equivalent automation need to be done. 
Earlier we used REST LED interface to check whether LED is Blink etc..
Still Manual verification is needed.

**Comment by williamspatrick** [comment]
Keep in mind that this is a Witherspoon specific behavior. It is not a general openbmc requirement.

**Comment by sivassrr** [comment]
Sure @williamspatrick

**Comment by sivassrr** [comment]
@swe12345 Please work with Rahul. And develop the automation code. For real verification we can use Tan or @saqibkh @lgon for quick verification.
