### ISSUE TITLE
Use pdbg from tarball obmc-phosphor-debug-tarball-witherspoon.tar.xz and check getscom/putsocm and all other commands

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#489]
@SrideviRamesh This is for our RAS test preparation. 
Could you pls explore as discussed. 
Use pdbg from tarball obmc-phosphor-debug-tarball-witherspoon.tar.xz and check getscom/putsocm and all other commands

**Comment by sivassrr** [comment]
Please extract the tarball onto bmc and kick off error injection from BMC.

**Comment by SrideviRamesh** [comment]
I worked with lakshmi and we made progress with pdgb tool. But error injection using putscom did not work and i raised an issue regarding this https://github.com/open-power/pdbg/issues/18

**Comment by gkeishin** [comment]
Task completed.. Closing
