### ISSUE TITLE
[Automation] - RAS test failing in CT as it need OS host OS IP

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#496]
RAS test failing in CT as it need OS host OS IP. We need to either move this test case in extended or add a field in jenkin to provide Host OS's IP.

**Comment by sivassrr** [comment]
Is it not in extended test? If not we should move over there. @SrideviRamesh  could you look at it.

**Comment by SrideviRamesh** [comment]
ok will move under extended folder
