### ISSUE TITLE
PNOR Codeupdate: Check for same image updated already if it is exist then skip the code update

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#497]

**Comment by geissonator** [comment]
Also, seems like some efficiencies we can make in this path.  Not sure why we're doing a warm reset when updating PNOR?

```
12:42:34 ==============================================================================
12:42:34 Test Bios Update :: Update the PNOR image on the host for                     
12:42:34 ==============================================================================
12:42:34 Host BIOS Update And Boot :: Update PNOR image and verify that        [32m.[0mURI:https://<IP>/org/openbmc/control/chassis0//action/powerOff, method:Post, args:{u'data': {u'data': []}, u'headers': {u'Content-Type': u'application/json'}}
12:42:35 Response code:200, Content:{
12:42:35   "data": null, 
12:42:35   "message": "200 OK", 
12:42:35   "status": "ok"
12:42:35 }
12:42:36 URI:https://<IP>/org/openbmc/control/chassis0//action/getPowerState, method:Post, args:{u'data': {u'data': []}, u'headers': {u'Content-Type': u'application/json'}}
12:42:37 Response code:200, Content:{
12:42:37   "data": 0, 
12:42:37   "message": "200 OK", 
12:42:37   "status": "ok"
12:42:37 }
12:42:37 "Triggering warm reset"
12:42:37 URI:https://<IP>/org/openbmc/control/bmc0/action/warmReset, method:Post, args:{u'data': {u'data': []}, u'headers': {u'Content-Type': u'application/json'}}
12:42:38 Response code:200, Content:{
12:42:38   "data": null, 
12:42:38   "message": "200 OK", 
12:42:38   "status": "ok"
12:42:38 }
```

**Comment by sivassrr** [comment]
@geissonator I believe warmReset needed to get the PNOR updated. PNOR gets updated on reboot. Then only PNOR comes into effect.

**Comment by geissonator** [comment]
Hmm, nope, with PNOR, you just have to pflash it at BMC ready and no reboot of BMC needed.  The new PNOR gets picked up when you boot the system.

**Comment by sivassrr** [comment]
Cool, Sure we will verify it.

**Comment by micwalsh** [comment]
I'm addressing some of performance issues with https://gerrit.openbmc-project.xyz/#/c/3664/ (Made performance improvements to test_bios_update.robot).

**Comment by sivassrr** [comment]
Found pnor code update effective as soon pflashed it. 
Before PNOR update with the latest level : 
 pflash -r /dev/stdout -P VERSION
Reading to "/dev/stdout" from 0x027e0000..0x027e1000 !
[                                                  ] 0%IBM-witherspoon-ibm-OP9_v1.15_1.14
	op-build-v1.15-75-g986c911-dirty
	buildroot-2017.02-4-gc28573e
	skiboot-6a3a09c
	hostboot-a58f695
	linux-4.10.6-openpower1-pef4dc3d
	petitboot-v1.4.2-pe78e1ef
	witherspoon-xml-b208e4f
	occ-4141b5f
	hostboot-binaries-82b82cd
	capp-ucode-1bb7503
[==================================================] 100%

Code update triggered with latest PNOR available. 

root@witherspoon:/tmp# pflash -E -i -p ./witherspoon_20170410n.pnor
Flash info:
-----------
Name          = /dev/mtd7
Total size    = 128MB
Erase granule = 4KB

TOC@0x00000000 Partitions:
-----------
ID=00            part 00000000..00001000 (actual=00001000)
ID=01             HBB 00010000..000a0000 (actual=00090000) [ECC]
ID=02            HBEL 000a0000..000c4000 (actual=00024000) [ECC]
ID=03           GUARD 000d0000..000d5000 (actual=00005000) [ECC]
ID=04             HBD 000e0000..00200000 (actual=00120000) [ECC]
ID=05           DJVPD 00200000..00248000 (actual=00048000) [ECC]
ID=06            MVPD 00250000..002e0000 (actual=00090000) [ECC]
ID=07            CVPD 002e0000..00328000 (actual=00048000) [ECC]
ID=08             HBI 00330000..00f90000 (actual=00c60000) [ECC]
ID=09             SBE 00f90000..00fd8000 (actual=00048000) [ECC]
ID=10           HCODE 00fe0000..01100000 (actual=00120000) [ECC]
ID=11            HBRT 01100000..01580000 (actual=00480000) [ECC]
ID=12         PAYLOAD 01580000..01680000 (actual=00100000)
ID=13      BOOTKERNEL 01680000..02580000 (actual=00f00000)
ID=14           NVRAM 02580000..02610000 (actual=00090000)
ID=15             OCC 02610000..02730000 (actual=00120000) [ECC]
ID=16         FIRDATA 02730000..02733000 (actual=00003000) [ECC]
ID=17            CAPP 02740000..02764000 (actual=00024000) [ECC]
ID=18         SECBOOT 02770000..02794000 (actual=00024000) [ECC]
ID=19         BMC_INV 027a0000..027a9000 (actual=00009000)
ID=20            HBBL 027b0000..027b6000 (actual=00006000) [ECC]
ID=21        ATTR_TMP 027c0000..027c8000 (actual=00008000)
ID=22       ATTR_PERM 027d0000..027d8000 (actual=00008000) [ECC]
ID=23         VERSION 027e0000..027e1000 (actual=00001000)
ID=24     IMA_CATALOG 027f0000..02830000 (actual=00040000) [ECC]
ID=25         RINGOVD 02830000..02850000 (actual=00020000)
ID=26         WOFDATA 02850000..02b50000 (actual=00300000) [ECC]
ID=27     BACKUP_PART 03ff7000..03fff000 (actual=00000000)
About to erase chip !
WARNING ! This will modify your HOST flash chip content !
Enter "yes" to confirm:yes
Erasing... (may take a while !) done !
About to program "./witherspoon_20170410n.pnor" at 0x00000000..0x04000000 !
Programming & Verifying...
[==================================================] 100% ETA:0s
root@witherspoon:/tmp# pflash -r /dev/stdout -P VERSION
Reading to "/dev/stdout" from 0x027e0000..0x027e1000 !
[                                                  ] 0%IBM-witherspoon-ibm-OP9_v1.15_1.23
	op-build-v1.15-119-ge039579-dirty
	buildroot-2017.02-4-gc28573e
	skiboot-5.5.0
	hostboot-c4ede09
	linux-4.10.7-openpower1-p283aef5
	petitboot-v1.4.2-p632283b
	witherspoon-xml-07ef29d
	occ-e1889e5
	hostboot-binaries-d1b1312
	capp-ucode-1bb7503
[==================================================] 100%
root@witherspoon:/tmp# obmcutil state
CurrentBMCState:    xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState:  xyz.openbmc_project.State.Chassis.PowerState.Off
CurrentHostState:   xyz.openbmc_project.State.Host.HostState.Off

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc/issues/1332 - We may have to consider this story as well. Refactored one.
