### ISSUE TITLE
[Automation] BMC Reboot related test cases inconsistently fails with Connection reset by peer

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#509]
BMC Reboot related test cases inconsistently fails with Connection error due to Connection reset by peer

ConnectionError: HTTPSConnectionPool(host='9.41.165.233', port=443): Max retries exceeded with url: /xyz/openbmc_project/state/bmc0//attr/RequestedBMCTransition (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'

**Comment by sivassrr** [comment]
@rahulmah we are fixing this in automation.  I am updating this just to give full picture of this issue. Basically we are ignoring it. But actually BMC hang / freezes/serial connection dies etc https://github.com/openbmc/openbmc/issues/1161

**Comment by rahulmah** [comment]
@sivassrr : With this automation fix we are not fixing actually BMC hang issue from automation side. It is like some time the BMC reboot command through out "ConnectionError" but get executed.
