### ISSUE TITLE
CodeUpdate: Test for Download via TFTP

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc-test-automation#510]
Create automation test case for the download via TFTP REST interface.

**Comment by sivassrr** [comment]
Thank you @anoo1 . 
Could you pls let know equivalent development story. 
https://github.com/openbmc/openbmc/issues/1468 - Is all fall under this issue?

**Comment by saqibkh** [comment]
- [ ] Copy image using same name as that on TFTP server
- [ ] Copy image using a different name than what exists on TFTP server
- [ ] Copy image with invalid TFTP server address.
- [ ] Copy file that doesn't exist on the TFTP server
