### ISSUE TITLE
OCC Reset Automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#516]
https://github.com/openbmc/openbmc/issues/1363  - Automation of this story. 
Please work with Vishwa and start parallel automation. 

Let know if you have any questions.

**Comment by sivassrr** [comment]
If you folks need error injection then please feel free to use pdbg  https://github.com/open-power/pdbg

**Comment by sivassrr** [comment]
FYI pdbg is available in tarball.

**Comment by lgon** [comment]
#516 Tasklist
- [ ] Automate OCC Rest For Communication Failure.
- [ ] Automate OCC Reset when number of bits set in “OCCs Present” from master poll response does not match the number of OCCs the BMC is communicating with.
- [ ] Automate OCC Reset when current OCC State byte in poll response is “Safe” for one minute and the “OCC Active” sensor is TRUE.
