### ISSUE TITLE
SOL User Interface Test

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#52]
User Interface SOL test and its equivalent development story is at https://github.com/openbmc/openbmc/issues/362

**Comment by gkeishin** [comment]
This done as part of the Power on https://github.com/openbmc/openbmc-test-automation/blob/master/tests/test_basic_poweron.robot

But not as a test but more of a log collection.

**Comment by gkeishin** [comment]
Closing as per discussion. In future if we want to add a test if needed, we just have to call Start and stop SOL connection using 
https://github.com/openbmc/openbmc-test-automation/blob/master/lib/utils.robot#L238
https://github.com/openbmc/openbmc-test-automation/blob/master/lib/utils.robot#L256
