### ISSUE TITLE
Functional and System test common function

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#534]
Track all common work required by both functional and system test teams

Potential items not tracked currently (assumption is OS and drivers manually setup for now):
- Automated OS installation (~6PM)
- Automated Driver Updates
- Automated CUDA installation
- Automated HTX installation

Common Areas to be Investigated
- Energyscale tests
- RAS (checkstop injects)
- XCAT
- BMC stability (network stress, workload stress)

**Comment by gkeishin** [comment]
Closing. no plan to do this.  Already few are under https://github.com/openbmc/openbmc-test-automation/tree/master/systest
