### ISSUE TITLE
SerialNumber, PartNumber for motherboard is coming as 00

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#545]
At present systems in lab are not having vpd programmed due to this serial number, PartNumber and Manufacturer are not reflecting correct value. 

```
 "/xyz/openbmc_project/inventory/system/chassis/motherboard": {
      "BuildDate": "",
      "Manufacturer": "0000000000000000",
      "Model": "",
      "PartNumber": "0000000",
      "Present": 0,
      "PrettyName": "SYSTEM PLANAR   ",
      "SerialNumber": "000000000000"
```

**Comment by rahulmah** [comment]
So "Verify Chassis Motherboard Properties" test case needs to be skipped until system has programed VPD.

**Comment by gkeishin** [comment]
Inventory test take cares of catching this bug. Closing this
