### ISSUE TITLE
CPU and DIMM's present, fault TC failure in sensor suite.

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#546]
CPU and DIMM's present, fault TC failure in sensor suite.

**Comment by rahulmah** [comment]
CPU and DIMM's preset test case in sensor need to be removed as they uses old org path. With does not work now. We need to use xyz interface to get them in working.

CPU and DIMM's fault test cases are now no logged valid because if there is a fault then there will be an error associated with that item. So this field is removed.

**Comment by sivassrr** [comment]
@SrideviRamesh As discussed in today's scrum, Kindly fix this.

**Comment by gkeishin** [comment]
This is fixed already in inventory
