### ISSUE TITLE
Error / Event Manager verification

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#55]
Error and Event Manager verification and corresponding development story at https://github.com/openbmc/openbmc/issues/342

**Comment by gkeishin** [comment]
There is already test cases around 17 test cases for this.. not sure if we need to add anything beyond that.. 
tests/test_eventlog.robot 

Please confirm..

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc/issues/340 Need to see whether we need to automate anything from FVT perspective.

**Comment by sivassrr** [comment]
if anything can be automated parallel we can try on the same. Check with @anoo1

**Comment by sivassrr** [comment]
Oct 1st Sprint Development is focusing on https://github.com/openbmc/openbmc/issues/340
And expectation to have some new TCs related to error logging. We can add atleast some in the end of the sprint.

**Comment by mtritz** [comment]
With just one error available in the elog test tool at this time, it seems to me that the tasks here are...

- [ ] Commit the test error
- [ ] Use curl commands to verify that the error appears as intended in the error log

...using the Robot Framework.

**Comment by gkeishin** [comment]
@mtritz  Thats cool.. even if one is good place to start with..

**Comment by gkeishin** [comment]
@mtritz  errorlog tool Code under review 

While the test automation in review https://gerrit.openbmc-project.xyz/#/c/2923/

**Comment by gkeishin** [comment]
This code is ready for merged. awaiting tool packaging portion of the changes still in review

**Comment by gkeishin** [comment]
- [x] Error log  [In review for merge]
- [x] Event test TBD
- [x] Association  TBD
- [x] Call out TBD

**Comment by gkeishin** [comment]
First code dropr https://github.com/openbmc/openbmc-test-automation/issues/289

**Comment by gkeishin** [comment]
Callout association test in review https://gerrit.openbmc-project.xyz/#/c/3337/
