### ISSUE TITLE
Hard bootme test

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#553]
Boot system, run htx for a bit, stop htx, verify no errors, power down, rinse and repeat user input number of times.

**Comment by gkeishin** [comment]
Breaking down into few pre-reqs before dropping this changes
- [x]  https://github.com/openbmc/openbmc-test-automation/issues/542   [ Merged ]
- [x] https://github.com/openbmc/openbmc-test-automation/issues/558  [ In progress ]
- [x] HTX stress test [ In progress using this defect]

**Comment by gkeishin** [comment]
Address switching Boot to Os and Poweron using Run Key ..

**Comment by gkeishin** [comment]
This code is in review... https://gerrit.openbmc-project.xyz/#/c/4062/
