### ISSUE TITLE
Validate existing of bmc errors on host checkstop & host watchdog failures.

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#560]
https://github.com/openbmc/openbmc/issues/1266 - Associate with 
generate bmc errors on host checkstop and host watchdog failures

**Comment by sivassrr** [comment]
This is in 2 phases:
phase1: 
@SrideviRamesh you had already implemented host checkstop. Please re-run that test and check for bmc errors. 
Phase2:
Inject watchdog failure and check for errors.

**Comment by SrideviRamesh** [comment]
yes we have executed & verified these scenarios after RAS enable in witherspoon.....
please close this....
