### ISSUE TITLE
[Errorlog]  Add delete test case in errorlog

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#562]
Test case
   - [x]   Create elog and delete, verify if it is deleted
   - [x]   Create multiple elog and delete all and verify if its deleted
   - [x]   Create 2 elogs and delete 1 and verify its deleted and other elog exist

**Comment by gkeishin** [comment]
@swe12345 is working on it..

**Comment by swe12345** [comment]
https://gerrit.openbmc-project.xyz/#/c/4124/
