### ISSUE TITLE
Automation: Inventory: Check for FieldReplaceable and ensure automation added this scenario

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#564]
Related to issue #1545 Need to check entire inventory and ensure which ever part is "Field Replaceable", it should have the property and set to true.

**Comment by gkeishin** [comment]
The inventory code has code catching those.. that's why we see currently the FRU validation, functional state and DIMMs failure..

**Comment by gkeishin** [comment]
Code in place
