### ISSUE TITLE
[Inventory]  Fan presence detect

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#566]
```
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan0": {
        "Present": 1,
        "PrettyName": "fan0"
    },
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan1": {
        "Present": 1,
        "PrettyName": "fan1"
    },
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan2": {
        "Present": 1,
        "PrettyName": "fan2"
    },
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan3": {
        "Present": 1,
        "PrettyName": "fan3"
    }
}
```

need to confirm with folks on this .. why on present flag and no functional state..

**Comment by spinler** [comment]
functional state isn't implemented yet

**Comment by gkeishin** [comment]
Thanks @spinler .. Will add code to test once its in..

**Comment by gkeishin** [comment]
New code

    "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan0": {
        "Functional": 1,
        "Present": 1,
        "PrettyName": "fan0"
    },
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan1": {
        "Functional": 1,
        "Present": 1,
        "PrettyName": "fan1"
    },
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan2": {
        "Functional": 1,
        "Present": 1,
        "PrettyName": "fan2"
    },
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan3": {
        "Functional": 1,
        "Present": 1,
        "PrettyName": "fan3"
    }

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/4202/
