### ISSUE TITLE
[HTX] hardbootme timer countdown in the Console

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#581]
Right now until the loops comes back and print , user cant much know how much time is left for execution to complete.. it would be good to keep watch of it..

**Comment by ssombar** [comment]
Updated the description of the parameters in the test case, in the wiki, and in Jenkins to say:
HTX_LOOP              The  Number of HTX loops to be run.   HTX run will be approximately   HTX_LOOP  *  HTX_DURATION.    For example  2 hours * 4  = 8 hours.   Be sure to then add to that 20 minutes for each HTX_LOOP to allow for OS boot and  shutdown.    So if HTX_LOOP = 4, add an extra 80 minutes.

**Comment by ssombar** [comment]
Added a loop counter to HTX_HARDBOOTME under https://gerrit.openbmc-project.xyz/#/c/7456.
Its easy to tell how much time remains using this counter.

**Comment by ssombar** [comment]
In addition to the integer loop counter,  added estimated time to completion 
https://gerrit.openbmc-project.xyz/7721

**Comment by gkeishin** [comment]
Great Thanks @ssombar  Let see @micwalsh has some cleaner ways to do so. He'll comment on the code..
