### ISSUE TITLE
PNOR update on Palmetto fails while checking PNOR flashing state

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#584]
PNOR update on Palmetto fails while checking PNOR flashing state. 

```
 To JSON using : content={
  "data": {
    "filename": "/tmp/palmetto.pnor", 
    "flasher_instance": "bios", 
    "flasher_name": "flasher.exe", 
    "flasher_path": "/usr/sbin/flasher.exe", 
    "lock": 0, 
    "name": "", 
    "status": "Flashing: 2%"
  }, 
  "message": "200 OK", 
  "status": "ok"
} 
 	Flashing: 57% != Flashing
```

**Comment by gkeishin** [comment]
Yeah this one was there from beginning..  MFG folks had this question couple of sprint.. where the Flashing percentage going up and down during the update but eventually it would finish and complete the update..  Probably talk to Rajesh if they have internal CQ opened up or not for this..

There are instances where the update took longer then the once define wait for keyword.. but definitely worth looking into it,,

**Comment by rahulmah** [comment]
@gkeishin : As discussed, the issue is with the way we are checking PNOR flashing state. PNOR flashing state now has % value with it. So we should change the logic to take care of this % value. 

I have already dropped fix for this with https://gerrit.openbmc-project.xyz/#/c/4123/.
