### ISSUE TITLE
Network stress test

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#588]
Have OS and BMC share ethernet port, run htx network stress in OS, heavily utilize BMC network (code image uploads, REST queries, ...) and validate BMC/OS stay running, no errors, and no dropped messages

**Comment by gkeishin** [comment]
Pre-req: 

 - [x]   System setup configuration needed 
-  [x]   HTX network test case exerciser
-  [x]   Network data in case of failure ( To discuss )

**Comment by gkeishin** [comment]
Closing as this is completed..
