### ISSUE TITLE
Security Test: - PNOR read/write via IPMI

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#59]
Security Test related to PNOR read/write to IPMI - Its associated development story is as https://github.com/openbmc/openbmc/issues/357

**Comment by sivassrr** [comment]
Revisited the estimate, Will cover using mailbox daemon.

**Comment by sivassrr** [comment]
@joseph-reynolds Do we need to do anything here? your input will be helpful to keep it open or close this issue.

**Comment by joseph-reynolds** [comment]
The development work was for OpenPOWER systems firmware (SBE, hostboot, OPAL) to discontinue direct access to the PNOR storage and instead use the Mailbox protocol to access its PNOR.  I understand this is now using the hiomap protocol (described in https://github.com/openbmc/mboxbridge).  We could do a security review of the protocol, code, and test cases.

I understand that the BMC is holding access to the PNOR and has completely shut off access from the host, except through the hiomap protocol.  We could validate that with code walk-throughs and test cases.  

The way I understand it, the host is supposed to have unrestricted read/write access to its PNOR when accessed via hiomap, but no access to any other parts of the BMC's storage.  We could validate the hiomap protocol, do a code walk-through of its implementation, and write some testcases to access past the end of the PNOR, violate the protocol, and stuff like that.

But this area is outside my expertise, so I can offer only limited help.  So unless we find someone to do these tests, we can close this.  Note that James has a review with an intention to investigate this area.   See https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/11164/2/security/obmc-securityarchitecture.md.
