### ISSUE TITLE
PreTag: [System - barreleye Build - 20160613175742 ] : Test Occ Powercap - 4 TCs failing due to keyerror

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#6]
Below 4 test cases are failing due to keyerror

Replacing variables from keyword return value failed: Resolving variable '${jsondata["data"]["value"]}' failed: KeyError: 'value'

Set and Get PowerCap
Set Less Than Minimum PowerCAP
Set More Than Maximum PowerCAP
Get System Power Consumption

**Comment by gkeishin** [comment]
Closing this as there is a current discussion going at https://github.com/openbmc/openbmc/issues/557

Until https://github.com/openbmc/openbmc/issues/552 is implemented ..  this will still keep failing.. so there is no action from automation point at this time.

Closing this.
