### ISSUE TITLE
FFDC failing with several failures in automation code.

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#603]
Several failures occurred: 
1) EOFError 
2) SSHException: SSH session not active
3) Could not get length of 'None'. 
4) Could not get length of 'None'.

**Comment by gkeishin** [comment]
This is a good bug if we can resolve it.. @micwalsh is coming up new mechanism to re use the sessions.. once that's in place this would be history for most of the error..
