### ISSUE TITLE
[Poweron]  Set Auto reboot to disable for CI/CT 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#609]
We would need to set CI/CT poweron with Auto boot to disable for CI/CT that help catch the Host goinge to Quiesce state and can have system for debugging..

**Comment by gkeishin** [comment]
Probably come up with logic if we see it in quiesce state.. disable it.. probably some smart check we may need to introduce..

**Comment by swe12345** [comment]
Code in Review
https://gerrit.openbmc-project.xyz/#/c/7689/
