### ISSUE TITLE
[ELOG]  Resolved field testing

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#621]
- [x] Create elog with callout
- [x] Set the Resolved field 
- [x] Verify the callout for the entry where it is set is flushed automatically..

**Comment by gkeishin** [comment]
Coding in progress..

**Comment by swe12345** [comment]
REST Logging attribute "Resolved" can't be set from external 
https://github.com/openbmc/openbmc/issues/1640
