### ISSUE TITLE
GPU Test

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#625]
This is a test case specifically focused on stressing the GPU.  

GPU Test cases - There is a specific HTX that stresses this, so “hxtnvidia”
- htx error will list error
- nvidiasmi - use this to determine health of gpu’s
- dmesg also has set of messages to look for

**Comment by gkeishin** [comment]
- [x]  A separate GPU test perhaps only to test GPU specific.
- [x]  Identify nvidiasmi  output
- [x] Identify dmesg error message strings
