### ISSUE TITLE
Validate system configuration

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#626]
Building on #554.  Write a test case that takes as input the configuration generated by #554, retrieves the current config of the system, and verifies they are the same.

If they do not match up then this test case should clearly tell the user what has changed.

**Comment by ssombar** [comment]
I will be happy to work on this.

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/5005

**Comment by gkeishin** [comment]
Code merged. Closing
