### ISSUE TITLE
Revisit Factory Reset Automation

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#628]
- Revisit our existing factory reset automation
- Need to implement test automation for network only factory reset - [1575](https://github.com/openbmc/openbmc/issues/1575)
- Need to implement test for host factory reset - [1574](https://github.com/openbmc/openbmc/issues/1574)

**Comment by gkeishin** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/977
