### ISSUE TITLE
Explore cronus way of error injection and Automation capability for Witherspoon

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#629]
@SrideviRamesh As discussed yesterday, Could you please explore along with your ZZ manual exploration with cronus

- [ ] Manual error injection using Cronus on Witherspoon

- [ ] Propose on how we can automate common between Witherspoon and ZZ

**Comment by SrideviRamesh** [comment]
hi sivas.. can u please close this issue...

We have executed RAS related error injection through cronus.

**Comment by sivassrr** [comment]
Thank you @SrideviRamesh , I am closing it as completed.
