### ISSUE TITLE
Hardbootme Test

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#63]
Create a Partition, Activate a Partition with HTX running, Run soft bootme inside the partition and do periodic boot the entire system. This need to be supported on all OpenBMC systems

**Comment by sivassrr** [comment]
As you are working on it, George, I am assigning it to you.

**Comment by gkeishin** [comment]
I see there is already https://github.com/open-power/HTX
for HTX

**Comment by gkeishin** [comment]
With this we can do the following as suggested by @geissonator 

— Power on, verify OS boots, issue BMC reboot, ensure OS stays up, power off, power on again, verify OS

**Comment by gkeishin** [comment]
Code in place.. closing this
