### ISSUE TITLE
eSEL Test case automation - Remove IPMI tool dependency and enable inband / external IPMI way of testing

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#632]
@SrideviRamesh As discussed in today's scrum, We need to do following:

- [ ] Remove IPMI Tool copy dependency

- [ ] Enable the same code via inband (Host) / external IPMI

**Comment by SrideviRamesh** [comment]
Using Inband IPMI Standard Command to remove IPMI tool dependency.. will be enabling five TC in tests/test_esel.robot
