### ISSUE TITLE
[GPU] Test to verify temperature has not crossed threshold

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#637]
Sample output
Mon Sep 12 11:02:50 2016
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 361.89                 Driver Version: 361.89                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  On   | 0002:01:00.0     Off |                    0 |
| N/A   25C    P0    35W / 300W |    931MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  On   | 0003:01:00.0     Off |                    0 |
| N/A   26C    P0    40W / 300W |   1477MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  On   | 0006:01:00.0     Off |                    0 |
| N/A   25C    P0    35W / 300W |    931MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  On   | 0007:01:00.0     Off |                    0 |
| N/A   44C    P0   290W / 300W |    965MiB / 16280MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     28459    C   hxenvidia                                      929MiB |
|    1     28460    C   hxenvidia                                     1475MiB |
|    2     28461    C   hxenvidia                                      929MiB |
|    3     28462    C   hxenvidia                                      963MiB |
+-----------------------------------------------------------------------------+
NVRM version: NVIDIA UNIX ppc64le Kernel Module  361.89  Sat Aug 20 16:02:06 PDT 2016
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

**Comment by gkeishin** [comment]
Something we can do once the GPU system is setup @ssombar

**Comment by ssombar** [comment]
I wonder what the threshold value should be.   80 degrees C?

**Comment by ssombar** [comment]
MICHAEL FATTU
I believe the upper limit is 80 deg C, 
I think you may want to set it a little below 80 though as the GPU will start throttling at 80. 
Or make 80 a failure condition

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/8444

**Comment by gkeishin** [comment]
Excellent. Thanks @ssombar
