### ISSUE TITLE
Tests pass but FFDC still taken

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc-test-automation#641]
Running on QEMU...
tox -e qemu -- tests/test_rest_interfaces.robot

The very first test passed but it still produced the FFDC prints.  Is that right?  the test teardown calls 'FFDC On Test Case Fail'   but it didn't fail.  Is there a variable not getting initialized?

**Comment by gkeishin** [comment]
hmm this could be qemu thing.. the base env it would need is the IP OPENBMC_HOST:xx.xx.xx.xx  to work..

**Comment by gkeishin** [comment]
We have fix thing in those areas. FFDC is called on all test exits and ONLY collects FFDC if failed unless explicitly called to collect.
