### ISSUE TITLE
IPMI Test Plan

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#65]
IPMI Test Plan

**Comment by sivassrr** [comment]
External IPMI Test Plan in RTC - Place holder

**Comment by sivassrr** [comment]
We decided not to create new Test plan for IPMI or any other.  we will have auto generated document.

**Comment by sivassrr** [comment]
This can be closed, I guess. We decided to have documentation in the code itself.

**Comment by sivassrr** [comment]
@rahulmah pls review and close it accordingly ji.

**Comment by rahulmah** [comment]
Here are all IPMI related test cases at present. Please close this one.

[OpenBmc - IPMI test cases.xlsx](https://github.com/openbmc/openbmc-test-automation/files/857669/OpenBmc.-.IPMI.test.cases.xlsx)
