### ISSUE TITLE
XCAT- Advanced/Complex scenarios

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#659]
Suggest to add few more test scenarios with xCAT:

- [ ] After xCAT is connected to multiple/single compute node and BMC is at standby state, issue BMC reset/reboot, then make sure xCAT can be used to power on
- [ ] After xCAT is connected to multiple/single compute node and BMC is in the standby state, issue BMC reset/reboot, then make sure xCAT can be used to do code update.
- [ ] After xCAT is connected to multiple/single compute node, power on the computer node, once host OS is running, issue BMC reset/reboot and make sure xCAT connection is still functional
- [ ] After xCAT is connected to multiple/single compute node, power on the compute node, once host OS is running, issue BMC reset/reboot and once it is at ready state, code update still works.

**Comment by gkeishin** [comment]
Task already completed as per @prkatti1  closing
