### ISSUE TITLE
QEMU: Test with latest image, evaluate the results and open issues

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#66]

**Comment by gkeishin** [comment]
@SrideviRamesh  Can you take a look at the QEMU build process for this..  and we can put the code under extended folder or tools... 

1. Automated the QEMU build 
2. Automate the QEMU session
3.  Trigger the CI build run to start with.

**Comment by gkeishin** [comment]
@SrideviRamesh has wrote a basic shell script to automated the QEMU build and starting session. Using that we can now run the test cases.

**Comment by sivassrr** [comment]
Sridevi, Please ensure QEMU all test passes. IF there is failure, please open issues accordingly.

**Comment by sivassrr** [comment]
This is ongoing activity

**Comment by gkeishin** [comment]
@SrideviRamesh  Please track this internally via RTC.
