### ISSUE TITLE
Tag to be fixed in test_factory_reset_zero_config.robot

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#670]
./tools/generate_test_document
/Users/sivas/openbmc/1Jun2017Openbmcautomation/openbmc-test-automation/testsdire
ctoryTCdocs.html
/Users/sivas/openbmc/1Jun2017Openbmcautomation/openbmc-test-automation/extendedd
irectoryTCdocs.html
/Users/sivas/openbmc/1Jun2017Openbmcautomation/openbmc-test-automation/guidirect
oryTCdocs.html
/Users/sivas/openbmc/1Jun2017Openbmcautomation/openbmc-test-automation/systestdi
rectoryTCdocs.html
/Users/sivas/openbmc/1Jun2017Openbmcautomation/openbmc-test-automation/xcatdirec
toryTCdocs.html
[ ERROR ] Error in file '/Users/sivas/openbmc/1Jun2017Openbmcautomation/openbmc-
test-automation/mnfg/test_factory_reset_zero_config.robot': Invalid syntax in te
st case 'Zero Config': Non-existing setting 'Tag'.
/Users/sivas/openbmc/1Jun2017Openbmcautomation/openbmc-test-automation/mnfgdirec
toryTCdocs.html

Failure is due to proper tag syntax is not applied.

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/4531/
