### ISSUE TITLE
XCAT- Add validating group power status using XCAT group command

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#671]
Currently validating group power status. by validating power status on each node of the group one by one.
Add one more verification where it gets status of the whole group and validates.

**Comment by sivassrr** [comment]
@prkatti1 if there is any change in the estimation needed.

**Comment by prkatti1** [comment]
@sivassrr That seems to be fine Sivas.

**Comment by gkeishin** [comment]
Closing as task is done
