### ISSUE TITLE
Auto kick off test - Daily build and other release

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#672]
- [ ] Auto kick off test - Daily build and other release 

- [ ] Upload the test result 

- [ ] Check for existing issue / compare with previous test results

- [ ] Based on the check - declare the test results and inform tester for further review. 

Note: This we had discussed long time back and based on the idea / design what discussed with @gkeishin , Also implemented partially.  Now, high time to enable it.  Let know if you have any question(s) @gkeishin

**Comment by gkeishin** [comment]
Completed
