### ISSUE TITLE
[ Automation ] Add network persistent check before reboot test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#69]
While running automation test, we found that after certain point of the test, the BMC is not accessible.

While analyzing the log, we can see that the last command which triggered this behavior seems to be a reboot.

Start / End / Elapsed:     20160725 21:04:15.943 / 20160725 21:04:24.589 / 00:00:08.646
21:04:15.944     INFO     Executing command '/sbin/reboot'.     
21:04:24.588     INFO     Command exited with return code -1.     
21:04:24.589     INFO     ${output} =

So post this reboot test case.. all the test cases failed.

**Comment by gkeishin** [comment]
@williamspatrick @anoo1 @geissonator   is this a known issue ? This causes outages for even doing other test.

**Comment by gkeishin** [comment]
To avoid network getting reset when running automation test, we would need to add check to persist the network in case of reboot test case.

**Comment by vishwabmc** [comment]
I just got with @gkeishin and saw that the BMC was up for some good time. What was missing was the network configuration. So looks like test is doing ifconfig and then doing the test. Since ifconfig does not persist across reset, need to set that via REST so it persists.

Example : 
dbus-send --system --print-reply --dest=org.openbmc.NetworkManager /org/openbmc/NetworkManager/Interface org.openbmc.NetworkManager.SetAddress4 string:"eth0" string:"192.168.199.199" string:"255.255.255.0" string:"192.168.199.1"

**Comment by gkeishin** [comment]
It would be good if we could just set attribute in REST so that we don't have to worry about those IP's at least for simple    /sbin/reboot  test case where it does OS reboot directly

tests/test_association.robot:    ${output}=      Execute Command    /sbin/reboot
tests/test_eventlog.robot:    ${output}=      Execute Command    /sbin/reboot
tests/test_syslog.robot:    ${output}=      Execute Command    /sbin/reboot

**Comment by gkeishin** [comment]
@bradbishop  Would setting the REST attribute /org/openbmc/control/flash/bmc/attr/preserve_network_settings 

for the above use case .. would that help protecting the network or we have to do it via dbus only ?

**Comment by mdmillerii** [comment]
@gkeishin the `/org/openbmc/control/flash/bmc/attr/preserve_network_settings` is really _preserve u-boot environment when writing full flash image_,  With the current network scheme it only affects saving the MAC address for the ethernet.   The network settings are stored for `systemd-networkd` in the read-write partition in a file that is in the persistent files list.

The REST method that @vishwabmc mentioned will store the settings for them to be applied after reboot.

**Comment by gkeishin** [comment]
@mdmillerii sounds good then.. will check on it to do with dbus then.. Thanks for the info..

**Comment by bradbishop** [comment]
Thx @mdmillerii

**Comment by sivassrr** [comment]
If mere reboot not able to hold network settings , then I will consider it as a defect / issue. 
If we preserve the network setting and do the reboot test, then we are issuing a work around / not isolating the defect. 

So use dbus-send for network settings and do multiple reboot, We should not lose the network settings.

**Comment by gkeishin** [comment]
From test automation point of view, we wouldn't want to do this as it would not really test the Stack behavior of preserving the network as part of the test case.  There are already test doing reboot test ofr network tests/test_networkd.robot

Closing this.
