### ISSUE TITLE
Automation: Enable / Disable Watchdog

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#691]
This story  is associate with enable / disable watchdog. 

- [ ] Check for REST API

- [ ] Automate those
Check with @rahulmah and see whether anything else need to be added.

**Comment by SrideviRamesh** [comment]
Automating following 6 testcases

- Check Watchdog Timer On Host PowerOn
- Modify And Verify Watchdog Timer Interval
- Modify And Verify Watchdog TimeRemaining
- Enable Watchdog Timer And Verify TimeRemaining
- Check Watchdog Timer On Host PowerOff
- Disable And Verify Watchdog Timer Interval
