### ISSUE TITLE
Fan Speed control - Ready / Write via REST

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#696]
xyz.openbmc_project.Hwmon.hwmon1

    /xyz/openbmc_project
    /xyz
    /
    /xyz/openbmc_project/sensors
    /xyz/openbmc_project/sensors/fan_tach/fan2
        org.freedesktop.DBus.Peer
        org.freedesktop.DBus.Introspectable
        org.freedesktop.DBus.Properties
        xyz.openbmc_project.Control.FanSpeed
        xyz.openbmc_project.Sensor.Value
    /xyz/openbmc_project/sensors/fan_tach/fan3
        org.freedesktop.DBus.Peer
        org.freedesktop.DBus.Introspectable
        org.freedesktop.DBus.Properties
        xyz.openbmc_project.Control.FanSpeed
        xyz.openbmc_project.Sensor.Value
    /xyz/openbmc_project/sensors/fan_tach/fan0
        org.freedesktop.DBus.Peer
        org.freedesktop.DBus.Introspectable
        org.freedesktop.DBus.Properties
        xyz.openbmc_project.Control.FanSpeed
        xyz.openbmc_project.Sensor.Value
    /xyz/openbmc_project/sensors/fan_tach/fan1
        org.freedesktop.DBus.Peer
        org.freedesktop.DBus.Introspectable
        org.freedesktop.DBus.Properties
        xyz.openbmc_project.Control.FanSpeed
        xyz.openbmc_project.Sensor.Value
Note:
 If a compare between target and feed speeds will be made, they will not be equal (always changing), so must allow atleast a 15% deviation between target and feedback speeds

This is applicable only till the automatic fan control is enabled. 

@gkeishin Based on our discussion in scrum, I am sending your way. Let know if you have any concern.

**Comment by gkeishin** [comment]
Sweet.. I m on it @sivassrr

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/4865/
