### ISSUE TITLE
[ Automation ] Needs generic Call method in REST utility

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#70]
There are few cases where test developer are using locally call method in their test suite context to connect to REST object  as listed bellow .   

A better approach to be is to have common utility lib code to address this  ... This feedback is from @geissonator while we were having discussing for other test automation use case reviews.

$grep -ri "Call method" \* | sort | uniq 

lib/rest_client.robot:Call Method lib/utils.robot: ${resp}= Call Method /org/openbmc/control/chassis0/ powerOff data=${args} 

lib/utils.robot: ${resp}= Call Method /org/openbmc/control/chassis0/ powerOn data=${args} 

tests/test_networkd.robot: ${resp}= Call Method /org/openbmc/NetworkManager/Interface/ GetAddress4 data=${args} 

tests/test_networkd.robot: ${resp}= Call Method /org/openbmc/NetworkManager/Interface/ GetAddress4 data=${args} 

tests/test_networkd.robot: ${resp}= Call Method /org/openbmc/NetworkManager/Interface/ GetAddressType data=${args} 

tests/test_networkd.robot: ${resp}= Call Method /org/openbmc/NetworkManager/Interface/ GetHwAddress data=${args} 

tests/test_networkd.robot: ${resp}= Call Method /org/openbmc/NetworkManager/Interface/ SetAddress4 data=${args} 

tests/test_networkd.robot: ${resp}= Call Method /org/openbmc/NetworkManager/Interface/ SetHwAddress data=${args} 

tests/test_networkd.robot: run keyword and ignore error Call Method /org/openbmc/NetworkManager/Interface/ SetAddress4 data=${args} 

tests/test_power_restore.robot: ${resp}= Call Method /org/openbmc/control/chassis0/ powerOff data=${args} 

tests/test_power_restore.robot: ${resp}= Call Method /org/openbmc/control/chassis0/ powerOn data=${args}

**Comment by sivassrr** [comment]
@gkeishin lets discuss in our scrum and move this forward.

**Comment by gkeishin** [comment]
This no longer hold valid.. since more of the interface used are either correct and optimize...
