### ISSUE TITLE
OpenBMC Sprint 8 test procedure (updating soon)

### ISSUE THREAD

**Issue by iftekharuli** [openbmc/openbmc-test-automation#703]
# Prerequisites for test:
We are using xx.x for this test. So making sure the machine is up and running and there are log data available in that machine is important. When the machine restarts, the logs get cleared. 

Also browsing https://x.x/ and accepting security cookies are important as before. 

The full sprint demo recording video can be found here -

**Comment by sivassrr** [comment]
@iftekharuli we are not doing any testing currently on GUI. Waiting for official release. Please let know when we can get it.
