### ISSUE TITLE
Inventory:  Multiple reboots of Host & Compare inventories before and after.

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#705]
- [ ] Boot the system - Collect Inventory - Store as Inventory 1

- [ ] Reboot the system - Collect Inventory - Store as Inventory 2

- [ ] Both Inventory1 and Inventory 2 should match. 

Like this if we put it in loop, previous inventory should match with current inventory. 
If there is any diff. then we should see equivalent error / gard record.

**Comment by sivassrr** [comment]
@gkeishin for some reason, I am not able to see @swe12345 in the assignment. 
Could you pls work with her. That helps.

**Comment by swe12345** [comment]
Code in Review 
https://gerrit.openbmc-project.xyz/#/c/4830
