### ISSUE TITLE
IPMI Torture 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#714]
- [ ] Leverage IPMI torture test cases from op-test framework
https://github.com/open-power/op-test-framework/blob/master/testcases/IpmiTorture.py

- [ ] Call from Robot -> OP-Test framework -> IPMITorture

**Comment by gkeishin** [comment]
This can do directly without the need for OpenBMC test to call it.. Since op-test itself is a open and we should just use as it is.
