### ISSUE TITLE
Inventory: Persistency Check of the Inventory during BMC Reset Reload

### ISSUE THREAD

**Issue by swe12345** [openbmc/openbmc-test-automation#715]
Persistency Check of the Inventory
- Host Boot the System
- Collect Inventory- Inventory 1
- Get the BMC to Stand By
- Collect the Inventory at runtime- Inventory 2 
- Check Inventory should not be zero
- Inventory 1 and Inventory 2 must match 
- Now Reset the BMC
- Collect the Inventory - Inventory 3
- Compare Inventory 2 and Inventory 3

**Comment by ssombar** [comment]
I would like to help out on this.

**Comment by swe12345** [comment]
https://gerrit.openbmc-project.xyz/#/c/4934/

**Comment by swe12345** [comment]
Persistency for Inventory
https://github.com/openbmc/openbmc/issues/997

**Comment by gkeishin** [comment]
@swe12345 This code is already in place ? are u waiting on something here ?

**Comment by swe12345** [comment]
https://gerrit.openbmc-project.xyz/#/c/4934/
Waiting for https://github.com/openbmc/openbmc/issues/997 to be closed.
