### ISSUE TITLE
Code update: Remaining upload image of BMC/ PNOR test cases

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#746]
- [ ] BMC/PNOR: Upload image with incorrect MANIFEST

- [ ]  BMC/PNOR: Upload image with incorrect Image

**Comment by sivassrr** [comment]
Welcome @charleshofer , Please work with @saqibkh - Had established the base code update associate with upload images

**Comment by sivassrr** [comment]
We support individual image BMC or PNOR image upload. And also combined image (BMC & PNOR) as well. So pls add those scenarios as well.

**Comment by gkeishin** [comment]
This task is completed
