### ISSUE TITLE
Copy IPMI tool is called for each execution of IPMI RAW/Standard command

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#75]
Currently in ipmi_client.robot, Whenever there is a IPMI raw/standard command method is called, each time copy ipmi tool is called. Suggestion is to move copy ipmi tool under connection_client.robot

**Comment by gkeishin** [comment]
Let keep the IPMI related as it is to be under ipmi_client.robot.. in that way it would be cleaner to maintain and impact would be less as compared to connection_client which is for generic SSH to BMC/LPAR/SCP ...

**Comment by sivassrr** [comment]
We may not be doing any changes here if we bit recipe to generate ipmitool.  Place holder as of now.

**Comment by sivassrr** [comment]
IT may be duplicate.

**Comment by sivassrr** [comment]
As we no longer planning to use internal IPMITool, I am closing this.
