### ISSUE TITLE
Code update via Petitboot / OS

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#758]
- [ ] Code update via Petitboot using Pflash / other equivalent commands 

- [ ] Code update via Ubuntu OS https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W51a7ffcf4dfd_4b40_9d82_446ebc23c550/page/Updating%20firmware%20on%20a%20Power%20system%20running%20Ubuntu

**Comment by sivassrr** [comment]
Basically OS way of firmware update mostly thru the command update_flash.

**Comment by sivassrr** [comment]
One of you can own and add 2 or more TCs.

**Comment by gkeishin** [comment]
@sivassrr  is this specific or generic for community ?

**Comment by sivassrr** [comment]
Initially there was a plan to do code update via OS / Petitboot. And then now moved right shift for IBM based boxes. 
But still we can pursue this as this applicable to generic as well.
