### ISSUE TITLE
Test Boot Devices Suite Setup fails and all 12 TCs fails

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#760]
Test Boot Devices Suite Setup fails because we are checking the "Is OS Starting" without initiate hostboot. 

1
--
Test Suite Setup
  | [Documentation]  Do the initial suite setup.
  | ${current_state}=  Get Host State
  | Run Keyword If  '${current_state}' == 'Off'
  | ...  Initiate Host Boot     <===== Current_state was running and it didnt trigger host boot
  |  
  | Wait Until Keyword Succeeds   <=== This statement is not needed. 
  | ...  10 min  10 sec  Is OS Starting

Full Name:
--
This testsuite is for testing the Boot Device Functions
/tmp/fspcibld/29519/obmc-robot/tests/test_boot_devices.robot
20170707 14:40:22.491 / 20170707 14:50:29.731 / 00:10:07.240
12 critical test, 0 passed, 12 failed12 test total, 0 passed, 12 failed
Suite setup failed:
Keyword 'Is OS Starting' failed after retrying for 10 minutes. The last error was: Off != FW Progress, Starting OS

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/5264/

**Comment by gkeishin** [comment]
U can use this patch and test on ur sanbox and see if it fixes all

**Comment by gkeishin** [comment]
Did the above patch worked good @swe12345

**Comment by swe12345** [comment]
@gkeishin Tried it for all the three test cases when the system is in 'Running' state.. Works fine..

**Comment by gkeishin** [comment]
I mean did u tried running CT with those patch..
