### ISSUE TITLE
Sensor Test suite setup failed due to invalid check of keyword "Is OS Starting" 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#774]
![image](https://user-images.githubusercontent.com/19144129/28153983-eb30909c-67c5-11e7-9e5f-022b1b1d0d3a.png)

Similar to other defect / issue which @swe12345 working on it. 
Will give test repot to @swe12345 separately.

**Comment by sivassrr** [comment]
Fix can go here as well https://github.com/openbmc/openbmc-test-automation/issues/760

**Comment by gkeishin** [comment]
No longer applicable.
