### ISSUE TITLE
Intermittent connection failure against QEMU in robot CI tests

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-test-automation#78]
I've seen this pop up intermittently in our CI runs.  Looks to be about a 30% failure rate.

Here's the main link to the jenkins job - https://openpower.xyz/job/openbmc-test-qemu-ci/

The fail has the same signature each time, the first set of tests (events) fails but then the next set of REST tests pass fine.

Some things to investigate
- Do the tests use the same robot connection code?
- Do we retry the connection for each test or do we only try once per test suite?
- Is there any FFDC we can collect in situations like this?  Maybe try an ssh connection?
- Can we swap the test buckets so we can debug whether it's just the first tests that always fail?

Here's a link to the latest fail: https://openpower.xyz/job/openbmc-test-qemu-ci/51/console

Currently, jenkins is setup to not fail the job if CI fails.  We can't enable the fail of the job until we get this issue figured out (false CI fails are the worst kind of fail!)

0:54:26 ==============================================================================
20:54:26 Tests  
20:54:26 ==============================================================================
20:54:27 Tests.Test Eventlog :: This suite is used for testing the error logging  
20:54:27 ==============================================================================
20:54:32 valid path to logs :: Test list all events                            URI:https://172.17.0.3:443/org/openbmc/records/events/, method:Get, args:{}
20:54:32 F

valid path to logs :: Test list all events                            | FAIL |
20:54:32 ConnectionError: HTTPSConnectionPool(host='172.17.0.3', port=443): Max retries exceeded with url: /login (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))
20:54:32 ------------------------------------------------------------------------------

@sivassrr @gkeishin @causten

**Comment by gkeishin** [comment]
@geissonator  I ran few times CI on QEMU sessions now and then.. but I couldn't seems to see this issue..

@SrideviRamesh Can you start one and run in loops the CI run and check if u can see this problem

**Comment by geissonator** [comment]
Yeah, this is a lot more intermittent then I saw initially.  We've hit once out of maybe 20 times recently out on openpower.xyz.  But even once is too much, we gotta get to the bottom of this one.   For now could we swap the order of the tests to help get some more info?

**Comment by gkeishin** [comment]
Even in HW also we are seeing bunch of those REST connection issues.. so there must be a real reason behind REST not able to handle those request pumping one after another in the test.. 

https://github.com/openbmc/openbmc-test-automation/issues/83

**Comment by gkeishin** [comment]
@SrideviRamesh  Are u still seeing those in later QEMU run ?

**Comment by SrideviRamesh** [comment]
@gkeishin  i have created QEMU session. triggered CI runs in loop for 30 times. At 24th iteration two test cases failed

**Comment by gkeishin** [comment]
@SrideviRamesh Do u have the test log saved off somewhere I can take a look... Probably intermittent network issues.. however if it ran for 23rd iteration successful, we should be almost good there.. just this minor glitch ...

**Comment by gkeishin** [comment]
Closing this as we get no reports for such failure.. If there are new ones we will deal its newly..
