### ISSUE TITLE
Update 'update_bmc.robot' to first check if BMC is at latest-known good level- if yes, skip flashing, if not, flash.

### ISSUE THREAD

**Issue by sameerveer** [openbmc/openbmc-test-automation#780]
Need to modify "openbmc-test-automation/extended/code_update/update_bmc.robot":
1) First check if Witherspoon's  "VERSION_ID" matches exactly with the passed "$latest_good_fw" string. 
2) If matched, save time by skipping the flashing act and exiting the code.
3) If NOT matched, act by flashing BMC to the latest known good level using the passed $FILE_PATH to the BMC image file.

**Comment by gkeishin** [comment]
1 and 2, I can take care of from code. 3 one needs to be from jenkins default..

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/5384/
