### ISSUE TITLE
Code update: Upload valid BMC image test cases

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc-test-automation#783]
Write Robot test cases for uploading valid BMC images via TFTP and REST

**Comment by sivassrr** [comment]
@charleshofer @saqibkh - As discussed in yesterday's meeting we need to create template first and then we can enable upload BMC/PNOR/Both, Code update BMC/PNOR/Both etc.. 

- [ ] Please come up with code update automation design 

- [ ]  Consider common REST URL for upload / flash etc..

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/5405/
