### ISSUE TITLE
Test multiple transactions per HTTP connection

### ISSUE THREAD

**Issue by mdmillerii** [openbmc/openbmc-test-automation#784]
Looking at the fix for https://github.com/openbmc/openbmc/issues/1389, and based on the observation that there were multiple open connections to the rest server from the test harness, it would appear that we are not testing reusing the HTTP connections as allowed in HTTP1.1 and greater.

A quick look it would seem that each `GET`, `PUT`, and `DELETE` start by opening a new connection and logging in via `Initialize OpenBMC` (see [diff](https://github.com/openbmc/openbmc-test-automation/commit/08540c0f083a25b5b4e7a4c839080fe54383038c#diff-eb7ea0966720c85e394dc4bd58e9e9f0L110) ) instead of trying to cache and reuse the connection.

This would be similar to doing individual scripts vs. true applications that can try to cache and reuse the connections.  I would label this a concern for coverage, for example does memory leak during a long connection?  Perhaps we should do some tests with each mode.

**Comment by gkeishin** [comment]
This is interesting ... I ll take a dig into it..

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/5668/
