### ISSUE TITLE
Test hard and soft power off combinations in automation

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#787]
Test hard and soft power off combinations in automation.

**Comment by gkeishin** [comment]
- [ ]  System should be able to power on after Hard power off

- [ ]  System should be able to power on after Soft power off

- [ ]  System should be able to power on after Soft power off followed with hard power off

**Comment by gkeishin** [comment]
The best place to put this changes would be in tests/test_basic_poweron.robot

**Comment by rahulmah** [comment]
Need to test via IPMI and REST these combinations.
