### ISSUE TITLE
Testing auto reboot functionality when host is booted to OS

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#790]
Testing auto reboot functionality when host is booted to OS

**Comment by rahulmah** [comment]
This test case need OS parameter. So the test case needs to be there in extended.

**Comment by sivassrr** [comment]
We dont have explict TC, I guess. But our RAS team was testing with that. Still we can add.

**Comment by sivassrr** [comment]
Looks like Rahul is having fix already, so assigning it to him.

**Comment by gkeishin** [comment]
In review https://gerrit.openbmc-project.xyz/#/c/5419/
