### ISSUE TITLE
validate system configuration should default to being enabled

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#825]
We want CHECK_INVENTORY to default to being enabled.  Currently its default is disabled.
Background:
See related issue #626 Validate system configuration (https://github.com/openbmc/openbmc-test-automation/issues/626).
The way 626 is currently implemented, if -v CHECK_INVENTORY is not set or -v PREV_INV_FILE_PATH is not set then no inventory checking is done and we get a normal HTX run without inventory.

**Comment by ssombar** [comment]
Gerrit code review:
https://gerrit.openbmc-project.xyz/5745

**Comment by gkeishin** [comment]
Code is merged.. Thanks @ssombar good turn around here

**Comment by ssombar** [comment]
I need to add the new parameters to the jenkins helper job
http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/system_test
