### ISSUE TITLE
Test networks settings persitency on reboot

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#827]
@prkatti1 We need to add a test to test the persistency check.

To validate https://github.com/openbmc/openbmc/issues/2087

**Comment by gkeishin** [comment]
@dkodihal  Suggested that we should have test to verify like this type of scenario.

**Comment by prkatti1** [comment]
OK @gkeishin

**Comment by gkeishin** [comment]
Task already completed as per @prkatti1  closing
