### ISSUE TITLE
[FFDC] OS logs during failures

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#828]
Looking at the STC failure defects, these data seems pretty much needed

- [x] cat /sys/firmware/opal/msglog
- [x] lspci
- [x] syscfg and 
- [x] lscpu 

output and may be needed for OS FFDC collection.

Can we put something on this one. @ssombar Can u take a look those data, if it would be helpful if taken in general during failure.

**Comment by ssombar** [comment]
looking at this now.

**Comment by gkeishin** [comment]
Thanks @ssombar  let me know if you need info on this

**Comment by ssombar** [comment]
Two questions
 - Q1:  Are these commands for Ubuntu only, or do we need them for RH too?   I am thinking both
           but need to confirm.
 - Q2:  I find no syscfg command.   lscfg perhaps?

**Comment by gkeishin** [comment]
Hmm .. now since most or our system is Ubuntu.. well u start with ubuntu with this comit, we will add check next commit to no-op or use corresponding available commands for it..

**Comment by ssombar** [comment]
I will add
   lspci
   lscfg
   lscpu 
And I see   .../opal/msglog  is already collected by the FFDC tool:
#(CDT) 2017/08/14 13:14:13.315106 -    0.014113 - Issuing: cat /sys/firmware/opal/msglog

**Comment by ssombar** [comment]
Gerrit review
   https://gerrit.openbmc-project.xyz/5991

**Comment by ssombar** [comment]
The commands are in Ubuntu and 
(according to Google) also in RedHat.  If the command does not exist, the FFDC file is created anyway but its contents will say "Command <whatever_command_was_called_for_ffdc> not found.

**Comment by gkeishin** [comment]
Sweet.. lets gets those in. Thanks
