### ISSUE TITLE
Fix eSEL test cases

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#829]
The error log signature has changed and it needs to be updated

```
Verify eSEL Entries Using REST :: Verify that eSEL entries have data. | FAIL |
xyz.openbmc_project.Led.Fru.Monitor.Error.InventoryPathError != org.open_power.Error.Host.Event.Event
```

**Comment by rahulmah** [comment]
Recently tested and found below below failure 
"org.open_power.Host.Event.Error.Event != org.open_power.Error.Host.Event.Event"
