### ISSUE TITLE
[System - Barreleye/Palmetto ] Most REST related test case are failing due to ConnectionError

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#83]
Most REST related test cases are failing during Initialize OpenBMC due to ConnectionError

ConnectionError: HTTPSConnectionPool(host='9.3.164.153', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff0147550>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by gkeishin** [comment]
I recreated on QEMU even with simple AUTH initialization..  with FFDC enabled.. we were able to grab the logs.   This is same to https://github.com/openbmc/openbmc/issues/514   


Brad is  planning on switching to a different rest server... probably that may help.. thats what he says.. so for now we can assume this to pop up now and then until he do that.. and he says it wont be long when he put the new one in.

Alright then.. this is now we reach the bottom of it.. and have action item by Brad.

**Comment by gkeishin** [comment]
Got a way to consistently increase the success rate to 100% for network use case with increase in retry at REST init login... pushing the changes up..

**Comment by rahulmah** [comment]
Increase REST time out to always get response. Also added delay after network configuration. Code checked in for review.

**Comment by gkeishin** [comment]
Give a full test run once and see the behavior if that's working, we are good to go here..
