### ISSUE TITLE
Consolidate code update libraries

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#834]
- [x] merge this two into 1 *.py file extended/code_update/code_update.py and extended/test_uploadimage.py
- [x] rename the above file as code_update_utils.py and move to lib/ 
- [x] Update the path in the files impacted.

**Comment by gkeishin** [comment]
In review https://gerrit.openbmc-project.xyz/#/c/5858/

**Comment by charleshofer** [comment]
https://gerrit.openbmc-project.xyz/#/c/5858/
