### ISSUE TITLE
Most sensor test case are failing when run using python way

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#835]
Sensor related 23 test case are failing in our jenkin flow - CT_RUN. This is because we are unable to make use of model file with python way of triggering automation. 
We are getting below error 
`IOError: [Errno 2] No such file or directory`

**Comment by sivassrr** [comment]
@kantvijay could you pls take a look. Even though Sensors may have to rewrite with XYZ. But existing TCs should work fine.

**Comment by gkeishin** [comment]
This is more of a path issue than a problem though.. export PATH openbmc-test-automation/bin/ before executing test

**Comment by rahulmah** [comment]
This has to do with the python way. I reran and found that it works fine with the tox way but fails with python.
