### ISSUE TITLE
Refactor Sensor code with new xyz interface.

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#838]
Refactor Sensor code with new xzy interface.

**Comment by rahulmah** [comment]
https://gerrit.openbmc-project.xyz/#/c/8055/

**Comment by mdmillerii** [comment]
The subject and initial description spelled xyz as xzy @rahulmah .

**Comment by rahulmah** [comment]
Already merged - https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/8055/
