### ISSUE TITLE
systest: add systest inventory difference file to FFDC

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#849]
add systest inventory difference file to FFDC
  os_inventory_diff.json

**Comment by gkeishin** [comment]
- [x] Diff file
- [x] Initial file
- [x] Current file

all these 3 should be collected

**Comment by ssombar** [comment]
Gerrit review:
  https://gerrit.openbmc-project.xyz/6026

**Comment by ssombar** [comment]
need to update the FFDC_METHOD_CALL dictionary in lib/openbmc_ffdc_list.py with the description and keyword name that will accomplish this collection (write a new keyword to do it if necessary).

**Comment by ssombar** [comment]
Gerrit:
   https://gerrit.openbmc-project.xyz/6060
