### ISSUE TITLE
Automation execution time reduction with the help of BMC READY state and OS state as running

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#861]
Need help in making our automation execution faster. 

Now it takes more than 4 hrs for our CT with skip list. 

We can avoid multiple power on. 

- [ ] BMC READY STATE 

- [ ] OS State Running  (As we have OS installed in most of our system) 

Please feel free to take other team help in this.

**Comment by gkeishin** [comment]
We have been fixing this now and then.. So no further needed here.. Will handle as we see performance hits ahead per use case or test suites
