### ISSUE TITLE
FFDC update: Jounalctl update with keyword from failure test case name

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#867]
Create snippet from journalctl search 

- [ ]  Extract snippet based on common keyword "failed"
- [ ] Extract snippet based on keyword from test case name

- [ ] Extract snippet from keyword from the snippet of the failed text

**Comment by sivassrr** [comment]
@ssombar assign this to you. Basically we need to create snippet based on the above logic. 
Let know if you have question. Please ping me if you want to understand more. 

This snippet should be added in ffdc.

**Comment by gkeishin** [comment]
This is already there in FFDC as part of the general.txt
