### ISSUE TITLE
[Automation]  Network Related test failure

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#87]
tests/test_networkd.robot:    ${NEW_GATEWAY}=       Get Environment Variable    NEW_GATEWAY

From README

README.md:    $export NEW_BMC_IP=<openbmc machine ip address>

Anyway this code is not going to work until exported like in tools/generate_argumentfile.sh

echo "--variable NEW_BMC_IP:$NEW_BMC_IP" >> $ARG_FILE

However give a try by setting as read me and run this individual test case to verify  Get Environment Variable  in this code..

**Comment by gkeishin** [comment]
@SrideviRamesh Can you take a look at this..

**Comment by gkeishin** [comment]
Part of the env are handle with https://github.com/openbmc/openbmc-test-automation/issues/12

**Comment by sivassrr** [comment]
Duplicate: https://github.com/openbmc/openbmc-test-automation/issues/16
