### ISSUE TITLE
OWASP Security Test

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#870]
OWASP security test 

https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W746177d414b9_4c5f_9095_5b8657ff8e9d/page/OWASP%20Top%2010%20vulnerabilities%20--%20Understand.%20Explore.%20Detect

Basically go thru the above link and (Some may not be applicable like sensitive data.. but still we need to double check) see what all we can cover and come out with task list.

**Comment by sivassrr** [comment]
Hi @joseph-reynolds could you pls check whether this we can pursue, if not we can close it, Joseph.

**Comment by joseph-reynolds** [comment]
Yes, I intend to go through the OWASP top 10 for BMCWeb and its Redfish support, and for phosphor-webui.

**Comment by gkeishin** [comment]
No further action. closing.
