### ISSUE TITLE
"Check For Application Failures" TC failing with GHE

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#876]
Journal has below entry. Due to this "Check For Application Failures" TC failing.

Aug 16 17:34:32 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x401e78a000-i2c\x2dbus\x40180-ir35221\x4071.service: Failed with result 'core-dump'.

**Comment by rahulmah** [comment]
Issue already logged with Fw - https://w3.rchland.ibm.com/projects/bestquest/?defect=SW390730

**Comment by gkeishin** [comment]
We can close this one up. Update in the CQ as discussed...
