### ISSUE TITLE
Network Test: Configuration of NTP / DNS Server

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#877]
- [ ] https://github.com/openbmc/openbmc/issues/2106  DNS Server

- [ ] https://github.com/openbmc/openbmc/issues/2107 NTP Server

Today confirmed with the development team that it is for ESP seems. So we need to test and automate the same.

**Comment by gkeishin** [comment]
Closing as requested by @prkatti1
