### ISSUE TITLE
Teardown failing for IPMI chassis suite

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#878]
Teardown failing for  IPMI chassis suite with below error. It need to be fixed in Automation.

Teardown failed: Several failures occurred: 1) 403 != 200 2) 404 != 200 3) {u'description': u'org.freedesktop.DBus.Error.FileNotFound: path or object not found: /RESTORE_LAST_STATE'} != xyz.openbmc_project.Control.Power.RestorePolicy.Policy.Restore

**Comment by gkeishin** [comment]
The fix from https://gerrit.openbmc-project.xyz/#/c/6065/ should fix this ahead.. so need to watch out
