### ISSUE TITLE
Patch mode verification based on BMC field mode setting

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#884]
- [ ]  https://github.com/openbmc/openbmc/issues/1350

- [ ] Verify Patch mode is enabled https://github.com/openbmc/openbmc/issues/2149

George, Please work with Charlie on the same to automate / test execution.

**Comment by gkeishin** [comment]
The code now on for field mode , do we really need to do the patch mode testing here?

@anoo1 ?

**Comment by gkeishin** [comment]
No longer as use case for testing
