### ISSUE TITLE
Secure boot Automation base

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#885]
@kantvijay This is one of the basic TPM setting customer perspective other than the jumper (Customer dont change jumper settings,  I guess). 
- [ ] https://github.com/openbmc/openbmc/issues/2104 

I believe we already have similar changes for Boston - Using this we can start our base code automation. Currently we can keep jumper switch as manual till we get it automated way.

**Comment by gkeishin** [comment]
Initial code in place
