### ISSUE TITLE
Need to add test related to check the resource utilization

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#89]
Step1: We can use command top -n 1 -b 
Step 2: Validate resource utilization usage common. For eg. if any services uses resources >75% then need to fail the test case.

**Comment by sivassrr** [comment]
BMC DATA : Displays processor activity	Executed : top -n 1 -b 
------------------------------------------------------------------------ 
Mem: 123876K used, 375180K free, 9708K shrd, 9932K buff, 42564K cached
CPU: 100% usr   0% sys   0% nic   0% idle   0% io   0% irq   0% sirq
Load average: 0.31 0.14 0.11 3/98 946
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
  937     1 root     R    17740   4% 100% python /usr/sbin/obmc-rest    <===== Continuously at 100% not good.
  724   702 root     S    32664   7%   0% /usr/sbin/power_control.exe 3000 10
  725   702 root     S    32664   7%   0% /usr/sbin/control_host.exe
  744   702 root     S    32552   7%   0% /usr/sbin/flash_bios.exe
  735   702 root     S    32548   7%   0% /usr/sbin/control_bmc.exe
  730   702 root     S    32548   7%   0% /usr/sbin/host_watchdog.exe
  679     1 root     S    17968   4%   0% python /usr/sbin/netman.py
  726   702 root     S    17792   4%   0% {bmc_update.py} /usr/bin/python -u /usr/sbin/bmc_update.py
  683     1 root     S    16432   3%   0% python /usr/sbin/obmc-phosphor-userd
  702     1 root     S    16168   3%   0% {system_manager.} /usr/bin/python -u /usr/sbin/system_manager.py
  714   702 root     S    15904   3%   0% {sensor_manager2} /usr/bin/python -u /usr/sbin/sensor_manager2.py Palmetto
  677     1 root     S    15796   3%   0% python /usr/sbin/phosphor-mapper
  747   702 root     S    15660   3%   0% {hwmon.py} /usr/bin/python -u /usr/sbin/hwmon.py Palmetto
  728   702 root     S    15648   3%   0% {download_manage} /usr/bin/python -u /usr/sbin/download_manager.py Palmetto
  749   702 root     S    15600   3%   0% {inventory_items} /usr/bin/python -u /usr/sbin/inventory_items.py Palmetto
  729   702 root     S    15288   3%   0% {chassis_control} /usr/bin/python -u /usr/sbin/chassis_control.py
  670     1 root     S    15256   3%   0% {settings_manage} /usr/bin/python -u /usr/sbin/settings_manager.py
    1     0 root     S    13132   3%   0% {systemd} /sbin/init
  651     1 systemd- S    12952   3%   0% /lib/systemd/systemd-timesyncd
  394     1 root     S     5928   1%   0% /lib/systemd/systemd-journald
  687     1 root     S     5648   1%   0% /usr/sbin/ipmid
  682     1 root     S     5100   1%   0% /usr/sbin/obmc-phosphor-eventd -s ${LOG_SIZE_LIMIT} -t ${LOG_COUNT_LIMIT}
  673     1 messageb S     4988   1%   0% /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
  539     1 root     S     3820   1%   0% /lib/systemd/systemd-udevd
  665     1 root     S     3776   1%   0% /usr/sbin/btbridged
  727   702 root     S     3772   1%   0% /usr/sbin/led_controller.exe
  680     1 root     S     3768   1%   0% /usr/sbin/netman_watch_dns /run/systemd/netif/state
  936     1 systemd- S     3180   1%   0% /lib/systemd/systemd-networkd
  681     1 root     S     3052   1%   0% -sh
  928   927 root     S     3052   1%   0% -sh
  855   854 root     S     3052   1%   0% -sh
  943   942 root     S     3052   1%   0% -sh
  669     1 root     S     3048   1%   0% /sbin/syslogd -n -C
  678     1 root     S     2984   1%   0% /sbin/klogd -n
  946   942 root     R     2984   1%   0% top -n 1 -b
  676     1 root     S     2852   1%   0% /lib/systemd/systemd-logind
  854     1 root     S     2636   1%   0% /usr/sbin/dropbear -i -r /etc/dropbear/dropbear_rsa_host_key -B
  942     1 root     S     2636   1%   0% /usr/sbin/dropbear -i -r /etc/dropbear/dropbear_rsa_host_key -B
  927     1 root     S     2636   1%   0% /usr/sbin/dropbear -i -r /etc/dropbear/dropbear_rsa_host_key -B
  666     1 root     R     1712   0%   0% /usr/sbin/inarp
    3     2 root     SW       0   0%   0% [ksoftirqd/0]
  773   702 root     Z        0   0%   0% [discover_system]
  780   744 root     Z        0   0%   0% [flasher.exe]
   84     2 root     SW       0   0%   0% [kworker/u2:3]
    9     2 root     SW       0   0%   0% [kworker/u2:1]
    2     0 root     SW       0   0%   0% [kthreadd]
    5     2 root     SW<      0   0%   0% [kworker/0:0H]
    7     2 root     SW<      0   0%   0% [lru-add-drain]
    8     2 root     SW       0   0%   0% [kdevtmpfs]
   10     2 root     SW       0   0%   0% [oom_reaper]
  104     2 root     SW<      0   0%   0% [writeback]
  105     2 root     SW       0   0%   0% [kcompactd0]
  107     2 root     SW<      0   0%   0% [bioset]
  109     2 root     SW<      0   0%   0% [kblockd]
  123     2 root     SW<      0   0%   0% [watchdogd]
  136     2 root     SW<      0   0%   0% [rpciod]
  145     2 root     SW       0   0%   0% [kswapd0]
  146     2 root     SW<      0   0%   0% [nfsiod]
  172     2 root     SW<      0   0%   0% [bioset]
  175     2 root     SW<      0   0%   0% [bioset]
  176     2 root     SW<      0   0%   0% [bioset]
  177     2 root     SW<      0   0%   0% [bioset]
  187     2 root     SW<      0   0%   0% [bioset]
  190     2 root     SW<      0   0%   0% [bioset]
  193     2 root     SW<      0   0%   0% [bioset]
  196     2 root     SW<      0   0%   0% [bioset]
  199     2 root     SW<      0   0%   0% [bioset]
  202     2 root     SW<      0   0%   0% [bioset]
  205     2 root     SW<      0   0%   0% [bioset]
  208     2 root     SW<      0   0%   0% [bioset]
  219     2 root     SW<      0   0%   0% [bioset]
  224     2 root     SW<      0   0%   0% [bioset]
  229     2 root     SW<      0   0%   0% [bioset]
  234     2 root     SW<      0   0%   0% [bioset]
  239     2 root     SW<      0   0%   0% [bioset]
  244     2 root     SW<      0   0%   0% [bioset]
  249     2 root     SW<      0   0%   0% [bioset]
  255     2 root     SW<      0   0%   0% [bioset]
  324     2 root     SW<      0   0%   0% [ipv6_addrconf]
  331     2 root     SW<      0   0%   0% [deferwq]
  374     2 root     SWN      0   0%   0% [jffs2_gcd_mtd6]
  379     2 root     SW<      0   0%   0% [kworker/0:1H]
  774   744 root     Z        0   0%   0% [flasher.exe]
  805     2 root     SW       0   0%   0% [kworker/0:3]
  921     2 root     SW       0   0%   0% [kworker/0:2]
  935     2 root     SW       0   0%   0% [kworker/0:0]
  939     2 root     SW       0   0%   0% [kworker/0:1] 
------------------------------------------------------------------------

**Comment by bradbishop** [comment]
please keep in mind that obmc-rest is using 100% of the cpu because of the testcase...

**Comment by vishwabmc** [comment]
I would not report an issue due to transient surge. If the utilization continues to be high then we may need to think about.

**Comment by sivassrr** [comment]
@vishwabmc It is not an issue, This is for test automation to verify the performance. Using this issue # we will drop our code changes into test-automation

**Comment by sivassrr** [comment]
@vishwabmc we want to understand the performance expectations and will do the automation accordingly.
