### ISSUE TITLE
EnergyScale Automation:  task

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#893]
Provide Throttling & Overtemp information to external users
- [ ] https://github.com/openbmc/openbmc/issues/1821

OCC HWMON set label attribute

- [ ] https://github.com/openbmc/openbmc/issues/1693

Take care of OCC HWMON refactoring in automation

- [ ] https://github.com/openbmc/openbmc/issues/1694

OCC Power Values in hwmon to match with scale factor

- [ ] https://github.com/openbmc/openbmc/issues/2136

Verify OCC Error is getting detected
- [ ] https://github.com/openbmc/openbmc/issues/2165

**Comment by sivassrr** [comment]
@ssombar pls work with @gkeishin and start automating energy scale related. 
Test Plan for Energyscale will be available with Tan.

**Comment by ssombar** [comment]
I have no access to the test plan doc

**Comment by gkeishin** [comment]
Lets break down this into tasked @ssombar

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/#/c/9067
