### ISSUE TITLE
[Barreleye/Palmetto] Verify System VPD Properties mismatch with the model setup

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#90]
Looks like we need to change the test logic to do verification of the inventory field as per

https://github.com/openbmc/ipmi-fru-parser/blob/master/frup.c#L169

Reference : https://github.com/openbmc/openbmc/issues/532

**Comment by sivassrr** [comment]
Need to check on Witherspoon

**Comment by gkeishin** [comment]
Closing as the new interface are going to replace and the old skeleton model is going to go away
