### ISSUE TITLE
Side Switch Verification when we do unrecoverable error

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#904]
@lkammath Whenever we do unrecoverable error (Other than SBE error injection), We also need to verify that we are booting with the same side. We should not see any side switch. 

Below is output of one version. But unfortunately not recreating now. Requested @SrideviRamesh to try it out. 
```
root@witherspoon:/tmp/pdgb_tools/lib# cat test_journalctl.txt | grep -i 'Setting SBE seeprom side to'
Jul 28 18:40:02 witherspoon openpower-proc-control[1471]: Setting SBE seeprom side to 0
Jul 28 18:42:52 witherspoon openpower-proc-control[1998]: Setting SBE seeprom side to 1
Jul 28 18:53:20 witherspoon openpower-proc-control[2508]: Setting SBE seeprom side to 0
Jul 28 19:02:23 witherspoon openpower-proc-control[3032]: Setting SBE seeprom side to 0
Jul 28 19:13:00 witherspoon openpower-proc-control[3543]: Setting SBE seeprom side to 0
Jul 28 19:19:00 witherspoon openpower-proc-control[4073]: Setting SBE seeprom side to 1
Jul 28 19:24:40 witherspoon openpower-proc-control[4533]: Setting SBE seeprom side to 1
```

**Comment by SrideviRamesh** [comment]
retried the scenario by injecting MCACALFIR_UE at IPLIng through BMC
```
oot@witherspoon:/tmp/pdgb_tools/lib# cat test3_journalctl.txt | grep -i 'Setting SBE seeprom side to'
Jul 28 18:50:31 witherspoon openpower-proc-control[1452]: Setting SBE seeprom side to 0
Jul 28 18:54:55 witherspoon openpower-proc-control[1984]: Setting SBE seeprom side to 0
Jul 28 19:05:04 witherspoon openpower-proc-control[2495]: Setting SBE seeprom side to 0
Jul 28 19:06:33 witherspoon openpower-proc-control[3017]: Setting SBE seeprom side to 1
root@witherspoon:/tmp/pdgb_tools/lib#
```
[20170824054746061086_MyFFDCLogs.zip](https://github.com/openbmc/openbmc-test-automation/files/1248579/20170824054746061086_MyFFDCLogs.zip)
[test3_journalctl.txt](https://github.com/openbmc/openbmc-test-automation/files/1248581/test3_journalctl.txt)

**Comment by geissonator** [comment]
Design is that SBE side switch occurs if 2 IPL failures occur in a row.  This can be any type of IPL failure (pgood, host watchdog, checkstop).

**Comment by sivassrr** [comment]
https://github.com/openbmc/openbmc/issues/2114

**Comment by gkeishin** [comment]
More test info here https://github.com/openbmc/openbmc-test-automation/issues/965

**Comment by SrideviRamesh** [comment]
Lakshmi tested few combination of side switch scenarios and also opened a defect https://w3.rchland.ibm.com/projects/bestquest/?defect=SW409624

**Comment by gkeishin** [comment]
Code automated.
