### ISSUE TITLE
PNOR BAD PATH test cases 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#913]
`69    Update PNOR with wrong platform image    Update should Fail. Activation set to "Failed"`
`40    Try setting same priority for PNOR image as another active image    Should fail`

**Comment by charleshofer** [comment]
Do not need to do test 69. When uploading an image built for the wrong system, the activation should succeed.

**Comment by gkeishin** [comment]
ok.. so we should filter existing test plan..

**Comment by charleshofer** [comment]
https://gerrit.openbmc-project.xyz/#/c/6312/
