### ISSUE TITLE
Power capping test cases need to be move to xyz

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#914]
Power capping test cases are failing in suite setup

Set And Get Powercap
Set_Less_Than_Minimum_Powercap
Set_More_Than_Maximum_Powercap

```
Parent suite setup failed: Keyword 'Powercap Attributes Activated' failed after retrying for 5 minutes. The last error was: Failed to activate powercap interface attributes Following values were not found from first list: /org/openbmc/sensors/powercap/user_cap, /org/openbmc/sensors/powercap/system_power, /org/openbmc/sensors/powercap/curr_cap, /org/openbmc/sensors/powercap/max_cap, /org/openbmc/sensors/powercap/min_cap
```

I believe we have now xyz interface for power cap. Let move these test case to xyz interface.

**Comment by gkeishin** [comment]
Steven is doing the powercapping changes https://github.com/openbmc/openbmc-test-automation/issues/912

**Comment by gkeishin** [comment]
These are already covered and taken care under power capping test
