### ISSUE TITLE
Modify Verify Rear Power LED With Host Power Off TC to check for Blink at Host off

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#928]
Modify "Verify Rear Power LED With Host Power Off" TC to check for power led to Blink at Host off.

**Comment by rahulmah** [comment]
@swe12345 : Please take care of this issue.

**Comment by swe12345** [comment]
Code in Review
https://gerrit.openbmc-project.xyz/#/c/6337/
