### ISSUE TITLE
NW : Updated inventory test automation: ( UUID )

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#939]
Development issue: https://github.com/openbmc/openbmc/issues/1315

we may have already done this. .but pls double check anything missing here / need to be added.

**Comment by gkeishin** [comment]
This is for dev code to update the MAC in xyz inventory.. so we already have code that checks the inventory and defect for it.

**Comment by sivassrr** [comment]
No, We dont have automated it. This is related to UUID checking as well.

**Comment by prkatti1** [comment]
This is automated by sweta, closing this.

**Comment by gkeishin** [comment]
Shall we close this @sivassrr
