### ISSUE TITLE
Verify Persistency with new UBI:RW File system

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#940]
There is a change already, or a change coming, to make the /var location UBIFS:RW
previously it was the COW filesystem
we need to make sure all our persistent stuff - error logs, settings, inventory, don't break with that file system change.

New changes to watch out
https://gerrit.openbmc-project.xyz/#/c/6292/

**Comment by gkeishin** [comment]
- [x] Elog persistence code in place
- [x] Inventory persistence code in place and r/r in review
- [x] Dump persistency - TBD

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/6419/

@dkodihal @ojayanth

**Comment by anoo1** [comment]
Closed with https://gerrit.openbmc-project.xyz/#/c/6419/
