### ISSUE TITLE
Reset Reload SBE side selection test

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#965]
- [x] Boot system, Verify boot count at 2, inject watchdog fail
- [x] Let system auto reboot itself, Verify boot count at 1, inject watchdog fail
- [x] Let system auto reboot itself, Verify boot count at 0 and SBE side is on side 1
- [x] Easy way to verify sbe side is look at journal for “Setting SBE seeprom side to <0/1>” 
       If you want to get advanced you could use pdbg to read the cfam reg and look at the bit.
       pdbg -p0 getcfam 0x2808” and check for bit 17

This is needed for RR testing , This input is from @geissonator 

@SrideviRamesh  Let me know if u need help here..

**Comment by gkeishin** [comment]
You did this test last time, was it through actual error injection or via watchdog timer timedout to mimic this one @SrideviRamesh  ?

**Comment by gkeishin** [comment]
Already tracked here https://github.com/openbmc/openbmc-test-automation/issues/904

closing it

**Comment by gkeishin** [comment]
Re-opening so that @charleshofer can help us out here

**Comment by gkeishin** [comment]
- [x] Working on pdbg -p0 getcfam 0x2808” execution .. while @charleshofer works on the framework

**Comment by charleshofer** [comment]
Finally have this in https://gerrit.openbmc-project.xyz/#/c/7433/
