### ISSUE TITLE
Code update Field Mode enable setting

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#969]
```
/xyz/openbmc_project/software
{
    "FieldModeEnabled": 0
}
```

**Comment by gkeishin** [comment]
@anoo1  Whats the use case for this attribute in software..

**Comment by charleshofer** [comment]
This issue is the same thing as https://github.com/openbmc/openbmc-test-automation/issues/1032. I should have probably just commented with a list of things to do in this one. Can we close this one since the other as the point estimate?
