### ISSUE TITLE
test_ac_cycles reports success when it should fail

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc-test-automation#971]
A PDU is a remotely controlled power distribution unit.  The module extended/test_ac_cycles.robot 
is designed to power cycle a PDU slot (AC power outlet) given the PDU_SLOT_NO.

I am seeing test_ac_cycles.robot report PASS even though the expected power cycle did not happen.

Looking further, I don't see any checking for a correct response in lib/pdu/synaccess.robot, specifically 
there is no handling for ${ret}=  <Response [404]> 

Test scenario:  Specify PDU_TYPE=synaccess but set PDU_IP = to the address of an Eaton unit.

My thanks to Michael Walsh for helping to initially identify this issue!

**Comment by mdmillerii** [comment]
seems like the test needs to detect no reboot via session still active.

**Comment by gkeishin** [comment]
The current PDU cycle only works on synaccess management and not on others..

**Comment by gkeishin** [comment]
Let me know if we can close this one @ssombar  or still have further question on it

**Comment by ssombar** [comment]
The code reports the reset happened even though no reset occurred.   So still an issue I think.

**Comment by gkeishin** [comment]
Perhaps you could help add that up fix @ssombar  :)

**Comment by ssombar** [comment]
https://gerrit.openbmc-project.xyz/8529

**Comment by ssombar** [comment]
merged.  closing
