### ISSUE TITLE
Automation: Factory Reset  

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#977]
Verify all 3 factory reset - 
Corresponding epic is @ https://github.com/openbmc/openbmc/issues/865

- [ ] Network Factory Reset

- [ ] BMC Factory Reset

- [ ] Host Factory Reset

**Comment by sivassrr** [comment]
Please add TCs under MFGTest directory.

**Comment by ssombar** [comment]
Energy scale will need to call reset to verify energy/power settings return to default.
