### ISSUE TITLE
Default debug tar ball path needs to be change to have more space

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#979]
Debug tar ball path needs to be change from /home/root/tarball/ to /usr/local/share/pnor/ as /home/root/tarball/ does nt have much space.

```
 ${targ_tarball_dir_path}=/home/root/tarball/
```

**Comment by gkeishin** [comment]
There is a code in review which uses tmp instead of persisting.. we are doing now load on demand then persisting.. We had a discussion on it earlier and we decided to keep in tmp.. and this part is taken care the code which I shared earlier.
