### ISSUE TITLE
[Automation]  Code update - SCP over flaky network

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#98]
@geissonator echoes the concern we might end up seeing more SCP failure due to network intermittent issues.

We have seen code update initiation failure pertaining to SCP over network to BMC due to flaky network.

So we would need to come up with a retry method in cases of scp failure or other method to replace to give higher chances of success...

**Comment by causten** [comment]
Adding a checksum would work .  I'll dig in a bit to see if python already has a retry technique built it

**Comment by gkeishin** [comment]
@causten That would really be awesome... Thanks

**Comment by gkeishin** [comment]
we are seeing this back now specially for Barreleye...

**Comment by gkeishin** [comment]
Simple hack after SCP, check the file size is 32M, if not , delete the incomplete file , retry 1 more max

**Comment by gkeishin** [comment]
Since the new code update is going to come soon which is going to be via REST.. so putiing this code up
