### ISSUE TITLE
All UserAdd commands are failing due to REST timeout

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#99]
All UserAdd commands in test_user.robot are failing due to ConnectionError. Manually ran the command and found that REST command is taking close to 30 secs to respond. At present, REST command output is set to be receive in 5 secs (read timeout=5.0) which in this case does not happen. So to always capture REST response we should increase REST time out to a higher value in our automation code.

09:32:34 Create and delete user with user group name :: ***GOOD PATH***        URI:https://<BMC IP>/org/openbmc/UserManager/Groups/action/GroupAddUsr, method:Post, args:{u'data': {u'data': ['BGaYN8u9']}, u'headers': {u'Content-Type': u'application/json'}}
09:32:35 Response code:200, Content:{
09:32:35   "data": 0, 
09:32:35   "message": "200 OK", 
09:32:35   "status": "ok"
09:32:35 }
09:32:35 URI:https://<BMC IP>/org/openbmc/UserManager/Users/action/UserAdd, method:Post, args:{u'data': {u'data': ['fbZ65tLf', 'qvdeZMTd', 'BGaYN8u9', 'jsb9pTf7']}, u'headers': {u'Content-Type': u'application/json'}}
09:32:58 
09:32:58 FFDC Collection Started 	: 2016-09-03 09:32:58,108453
09:33:09 FFDC Collection Completed 	: 2016-09-03 09:33:09,678948
09:33:09 | FAIL |
09:33:09 ConnectionError: HTTPSConnectionPool(host='<BMC IP>', port=443): Max retries exceeded with url: /org/openbmc/UserManager/Users/action/UserAdd (Caused by ReadTimeoutError("HTTPSConnectionPool(host='<BMC IP', port=443): Read timed out. (read timeout=5.0)",))

rahulmah@rackspace:~$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://<BMC IP>/login -d "{\"data\": [ \"root\", \"0penBmc\" ] }"
{
  "data": "User 'root' logged in",
  "message": "200 OK",
  "status": "ok"
**}rahulmah@rackspace:~$ date
Sat Sep  3 14:16:45 CDT 2016**
rahulmah@rackspace:~$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d "{\"data\": [\"myuser\", \"bmcuser11\", \"abc11\", \"abc123\"]}" https://<BMC IP>/org/openbmc/UserManager/Users/action/UserAdd
{
  "data": {
    "description": "Internal Server Error",
    "exception": "DBusException('Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.',)",
    "traceback": [
      "Traceback (most recent call last):",
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 858, in _handle",
      "    route, args = self.router.match(environ)",
      "  File \"/usr/sbin/obmc-rest\", line 746, in custom_router_match",
      "    route.callback._setup(**args)",
      "  File \"/usr/sbin/obmc-rest\", line 86, in _setup",
      "    return self.setup(**kw)",
      "  File \"/usr/sbin/obmc-rest\", line 209, in setup",
      "    request.route_data['method'] = self.find(path, method)",
      "  File \"/usr/sbin/obmc-rest\", line 202, in find",
      "    m = self.find_method_on_bus(path, method, *items)",
      "  File \"/usr/sbin/obmc-rest\", line 238, in find_method_on_bus",
      "    data = iface.Introspect()",
      "  File \"/usr/lib/python2.7/site-packages/dbus/proxies.py\", line 145, in __call__",
      "    **keywords)",
      "  File \"/usr/lib/python2.7/site-packages/dbus/connection.py\", line 651, in call_blocking",
      "    message, timeout)",
      "DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
    ]
  },
  "message": "500 Internal Server Error",
  "status": "error"
**}rahulmah@rackspace:~$ date
Sat Sep  3 14:17:15 CDT 2016**
rahulmah@rackspace:~$

Above error response "DBusException: org.freedesktop.DBus.Error.NoReply" for useradd command needs to be figured out from dev.  For this I will open a separate issue in openbmc.

**Comment by rahulmah** [comment]
Code pushed for review. Increase timeout to always capture response in case of delay with REST.

**Comment by amboar** [comment]
Do we understand why adding a user takes 30 seconds?

**Comment by rahulmah** [comment]
@amboar : We should not be seeing 30 sec for REST command to reply back. But in case of user add it's happening which I believe is due to "DBusException: org.freedesktop.DBus.Error.NoReply" which we are seeing. I have opened issue for the same in openbmc.

**Comment by rahulmah** [comment]
I have opened below issue in openbmc to take care of delay part and error part in rest response. Code changes in test automation is not required. So closing the issue.

https://github.com/openbmc/openbmc/issues/543
