### ISSUE TITLE
Code Update Test Cases: Reboot BMC during code update

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc-test-automation#993]
- [ ] Stop BMC code update while in progress (Reboot BMC)
- [ ] Stop PNOR code update while in progress (Reboot BMC)

**Comment by gkeishin** [comment]
For any BAD path use cases and recoverable let's create a different suite by itself to do those stuff

extended/code_update/host_recoverable_update_errors_test.robot

Something like that.

**Comment by gkeishin** [comment]
- [x] Let me add some code to enable this one..

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/6860/

**Comment by charleshofer** [comment]
https://gerrit.openbmc-project.xyz/#/c/7037/ not tested yet
