### ISSUE TITLE
Code Update Test Cases: Check that error log and BMC dump persists across BMC code updates

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc-test-automation#994]
- [x] Check that error log persists across BMC code updates

**Comment by gkeishin** [comment]
- [x] Add BMC dump also. so that we check both in one go..

**Comment by charleshofer** [comment]
- [ ] Also want to check for settings like boot policy

**Comment by gkeishin** [comment]
Perfect..

**Comment by charleshofer** [comment]
https://gerrit.openbmc-project.xyz/#/c/7050/ not tested yet
